---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/aggregate-relocation-failures.html 
keywords: aggregate, relocation, failures, arl, stage 2, stage 3, stage 5 
summary: Risolvere i problemi di riposizionamento degli aggregati che potrebbero verificarsi quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Errori di trasferimento aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il trasferimento di aggregati (ARL) potrebbe non riuscire in diversi punti durante l'aggiornamento.



== Verificare la presenza di errori di trasferimento degli aggregati

Durante la procedura, l'ARL potrebbe non funzionare nella fase 2, 3 o 5.

.Fasi
. Immettere il seguente comando ed esaminare l'output:
+
`storage aggregate relocation show`

+
Il `storage aggregate relocation show` il comando mostra quali aggregati sono stati riallocati correttamente e quali no, insieme alle cause del guasto.

. Verificare la presenza di eventuali messaggi EMS nella console.
. Eseguire una delle seguenti operazioni:
+
** Intraprendere l'azione correttiva appropriata, a seconda dell'output di `storage aggregate relocation show` E l'output del messaggio EMS.
** Forzare il trasferimento dell'aggregato o degli aggregati utilizzando `override-vetoes` o il `override-destination-checks` opzione di `storage aggregate relocation start` comando.


+
Per informazioni dettagliate su `storage aggregate relocation start`, `override-vetoes`, e. `override-destination-checks` opzioni, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi ai comandi di _ONTAP 9: Manuale riferimento pagina_.





== Gli aggregati originalmente sul node1 sono di proprietà di node2 dopo il completamento dell'upgrade

Al termine della procedura di upgrade, node1 dovrebbe essere il nuovo nodo principale degli aggregati che in origine aveva node1 come nodo principale. È possibile trasferirli dopo l'aggiornamento.

.A proposito di questa attività
Gli aggregati potrebbero non riuscire a riallocare correttamente, ovvero hanno node2 come nodo principale invece di node1, nelle seguenti circostanze:

* Durante la fase 3, quando gli aggregati vengono ricollocati dal nodo 2 al nodo 1.
+
Alcuni degli aggregati che vengono ricollocati hanno node1 come nodo principale. Ad esempio, un tale aggregato potrebbe essere chiamato aggr_node_1. Se il trasferimento di aggr_node_1 non riesce durante la fase 3 e non è possibile forzare il trasferimento, l'aggregato viene lasciato indietro al nodo 2.

* Dopo la fase 4, quando il node2 viene sostituito con i nuovi moduli di sistema.
+
Quando node2 viene sostituito, aggr_node_1 verrà online con node1 come nodo home invece di node2.



È possibile risolvere il problema di proprietà errato dopo la fase 6, dopo aver attivato il failover dello storage, completando la seguente procedura:

.Fasi
. Ottieni un elenco di aggregati:
+
`storage aggregate show -nodes _node2_ -is-home true`

+
Per identificare gli aggregati che non sono stati correttamente ricollocati, fare riferimento all'elenco degli aggregati con il proprietario di casa del node1 ottenuto nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] e confrontarlo con l'output del comando precedente.

. Confrontare l'output del passaggio 1 con l'output acquisito per il nodo 1 nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] e annotare eventuali aggregati che non sono stati correttamente ricollocati.
. Spostare gli aggregati rimasti sul nodo 2:
+
`storage aggregate relocation start -node _node2_ -aggr _aggr_node_1_ -destination _node1_`

+
Non utilizzare il parametro -ndo-controller-upgrade durante questo trasferimento.

. Verificare che node1 sia ora il proprietario domestico degli aggregati:
+
`storage aggregate show -aggregate _aggr1,aggr2,aggr3..._ -fields home-name`

+
`_aggr1,aggr2,aggr3..._` è l'elenco degli aggregati che avevano il node1 come proprietario di casa originale.

+
Gli aggregati che non hanno node1 come proprietario di casa possono essere ricollocati in node1 utilizzando lo stesso comando di rilocazione nella fase 3.


