---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/complete-preparation-for-upgrade.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configurare e gestire Storage Encryption, gestire le chiavi di autenticazione e interrompere le relazioni SnapMirror quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Completare i preparativi per l'aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri le licenze ONTAP e la gestione della Storage Encryption tramite Onboard Key Manager (OKM). Facoltativamente, sospendi le relazioni SnapMirror.



[[learn-about-ontap-licensing]]
== Scopri le licenze ONTAP

Ogni nodo del cluster deve disporre di un proprio file di licenza NetApp (NLF).

Se non si dispone di un NLF, le funzionalità attualmente concesse in licenza nel cluster sono disponibili per il nuovo controller. Tuttavia, l'utilizzo di funzionalità senza licenza sul controller potrebbe non essere conforme al contratto di licenza, pertanto è necessario installare l'NLF per il nuovo controller al termine dell'aggiornamento.

Fare riferimento a link:other-references.html["Riferimenti"] per collegarsi al _NetApp Support Site_ dove è possibile ottenere il proprio NLF. I NLF sono disponibili nella sezione _My Support_ sotto _Software licenses_. Se il sito non dispone dei NLF necessari, contattare il proprio rappresentante commerciale NetApp.

Per informazioni dettagliate sulle licenze ONTAP, fare riferimento a link:other-references.html["Riferimenti"] per collegarsi al _System Administration Reference_.



[[manage-storage-encryption-using-the-onboard-key-manager]]
[[manage-storage-encryption-using-okm]]
== Gestire la crittografia dello storage utilizzando Onboard Key Manager

Utilizzate l'Onboard Key Manager (OKM) per gestire le chiavi di crittografia. Se avete configurato l'OKM, dovete annotare la passphrase e il materiale di backup prima di iniziare l'aggiornamento.

.Fasi
. Registrare la passphrase del cluster.
+
Si tratta della passphrase immessa quando l'OKM è stato configurato o aggiornato utilizzando l'API CLI o REST.

. Verifica la passphrase e il funzionamento del key-manager:
+
`security key-manager onboard sync`

+
Quando richiesto, inserisci la passphrase OKM a livello di cluster che hai registrato nel passaggio precedente.

. Verifica che cc-mode sia abilitato controllando l'output del seguente comando:
+
`security key-manager config show`

. Eseguire il backup delle informazioni del key-manager:
+
`security key-manager onboard show-backup`





[[optionally-quiesce-the-snapmirror-relationships]]
== Facoltativamente, mettere in quiescenza le relazioni SnapMirror

Prima di continuare con la procedura, è necessario confermare che tutte le relazioni di SnapMirror siano interrotti. Quando una relazione SnapMirror viene ritirata, rimane irreparata in caso di riavvii e failover.

.Fasi
. Verificare lo stato della relazione SnapMirror sul cluster di destinazione:
+
`snapmirror show`

+
[NOTE]
====
Se lo stato è "trasferimento", è necessario interrompere questi trasferimenti:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'interruzione non riesce se la relazione SnapMirror non si trova nello stato di "trasferimento".

. Interrompere tutte le relazioni tra il cluster:
+
`snapmirror quiesce -destination-vserver *`



.Quali sono le prossime novità?
Dopo aver preparato l'aggiornamento, link:relocate-non-root-aggr-and-nas-data-lifs-node1-node2.html["spostare gli aggregati non root e i LIF di dati NAS di proprietà del node1 al node2"].
