---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/confirm-new-controllers-are-set-up-correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: 'Verificare che la coppia ha sia attivata, verificare l"accesso allo storage node1 e node2 e LIF e confermare la proprietà aggregata dopo l"aggiornamento dei modelli di controller nello stesso chassis.' 
---
= Verificare che i nuovi controller siano impostati correttamente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per confermare la corretta configurazione, verificare che la coppia ha sia attivata. Inoltre, è possibile verificare che node1 e node2 possano accedere reciprocamente allo storage e che nessuno dei due possieda le LIF dei dati appartenenti ad altri nodi del cluster. Inoltre, è possibile verificare che tutti gli aggregati di dati si trovino sui nodi principali corretti e che i volumi di entrambi i nodi siano online. Se uno dei nuovi nodi dispone di un adattatore di destinazione unificato, è necessario ripristinare le configurazioni delle porte e modificare l'utilizzo dell'adattatore.

.Fasi
. Dopo i controlli post-node2, vengono attivate la coppia di ha cluster e failover dello storage per il cluster node2. Al termine dell'operazione, entrambi i nodi vengono visualizzati come completati e il sistema esegue alcune operazioni di pulizia.
. Verificare che il failover dello storage sia attivato:
+
`storage failover show`

+
L'esempio seguente mostra l'output del comando quando è attivato il failover dello storage:

+
[listing]
----
cluster::> storage failover show
                          Takeover
Node	    Partner       Possible      State Description
----------  -----------   ------------  ------------------
node1	    node2         true	        Connected to node2
node2	    node1         true	        Connected to node1
----
. Verificare che node1 e node2 appartengano allo stesso cluster utilizzando il seguente comando ed esaminando l'output:
+
`cluster show`

. Verificare che node1 e node2 possano accedere reciprocamente allo storage utilizzando il seguente comando ed esaminando l'output:
+
`storage failover show -fields local-missing-disks,partner-missing-disks`

. Verificare che né node1 né node2 detengano le LIF dei dati di proprietà di altri nodi del cluster utilizzando il seguente comando ed esaminando l'output:
+
`network interface show`

+
Se nessuno dei nodi 1 o node2 possiede le LIF dei dati di proprietà di altri nodi del cluster, ripristinare le LIF dei dati al proprietario di casa:

+
`network interface revert`

. Verificare che gli aggregati siano di proprietà dei rispettivi nodi principali.
+
`storage aggregate show -owner-name <node1>`

+
`storage aggregate show -owner-name <node2>`

. Determinare se i volumi sono offline:
+
`volume show -node <node1> -state offline`

+
`volume show -node <node2> -state offline`

. Se alcuni volumi sono offline, confrontali con l'elenco dei volumi offline che hai acquisito nella sezione link:prepare-nodes-for-upgrade.html["Preparare i nodi per l'aggiornamento"], e porta online qualsiasi volume offline, se necessario, utilizzando il seguente comando, una volta per ciascun volume:
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. Installare nuove licenze per i nuovi nodi utilizzando il seguente comando per ciascun nodo:
+
`system license add -license-code <license_code,license_code,license_code...>`

+
Il parametro License-code accetta un elenco di 28 chiavi alfabetiche maiuscole. È possibile aggiungere una licenza alla volta oppure più licenze contemporaneamente, separando ciascuna chiave di licenza con una virgola.

. Rimuovere tutte le vecchie licenze dai nodi originali utilizzando uno dei seguenti comandi:
+
`system license clean-up -unused -expired`

+
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
--
** Eliminare tutte le licenze scadute:
+
`system license clean-up -expired`

** Eliminare tutte le licenze inutilizzate:
+
`system license clean-up -unused`

** Eliminare una licenza specifica da un cluster utilizzando i seguenti comandi sui nodi:
+
`system license delete -serial-number <node1_serial_number> -package *`
`system license delete -serial-number <node2_serial_number> -package *`



--
+
Viene visualizzato il seguente output:

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
Invio `y` per rimuovere tutti i pacchetti.

. Verificare che le licenze siano installate correttamente utilizzando il seguente comando ed esaminandone l'output:
+
`system license show`

+
È possibile confrontare l'output con l'output che hai catturato nella sezione link:prepare-nodes-for-upgrade.html["Preparare i nodi per l'aggiornamento"].

. [[unset_maxwait]] Se nella configurazione vengono utilizzate unità auto-crittografanti e hai impostato la variabile  `kmip.init.maxwait` su  `off` (ad esempio, in _Boot node2 con i moduli di sistema sostitutivi_, link:boot-node2-with-a900-controller-and-nvs.html#boot_node2_step1["Fase 1"]), devi annullare l'impostazione della variabile:
+
`set diag; systemshell -node <node_name> -command sudo kenv -u -p kmip.init.maxwait`

. Configurare gli SP utilizzando il seguente comando su entrambi i nodi:
+
`system service-processor network modify -node <node_name>`

+
Fare riferimento a link:other-references.html["Riferimenti"] per collegarsi al _System Administration Reference_ per informazioni sugli SP e all'_ONTAP 9 Command reference_ per informazioni dettagliate sul comando di sistema  `service-processor network modify`.

. Se si desidera configurare un cluster senza switch sui nuovi nodi, fare riferimento a link:other-references.html["Riferimenti"] per collegarsi al _NetApp Support Site_ e seguire le istruzioni in _Transitioning to a two-node switchless cluster_.


.Al termine
Se la crittografia di archiviazione è abilitata su node1 e node2, completare la sezione link:set-up-storage-encryption-new-module.html["Impostare Storage Encryption sul nuovo modulo controller"]. Altrimenti, completare la sezione link:decommission-old-system.html["Decommissionare il vecchio sistema"].
