---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 'È possibile aggiornare l"hardware del controller convertendo un vecchio sistema in un sistema sostitutivo, mantenendo il vecchio chassis e i dischi del sistema.' 
---
= Scopri di più sulla procedura di aggiornamento ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esistono diversi metodi di rilocazione aggregata (ARL) per aggiornare l'hardware del controller. Questa procedura descrive come aggiornare i controller di storage in una coppia HA convertendo il sistema esistente nel sistema sostitutivo, mantenendo lo chassis e i dischi del sistema esistenti.

ARL sfrutta la configurazione ha e la comunicazione di interconnessione del cluster. In questo modo, è possibile spostare la proprietà di aggregati non root da un nodo a un altro, se condividono lo storage all'interno dello stesso cluster.

Durante la procedura, l'hardware del controller originale viene aggiornato con l'hardware del controller sostitutivo, riallocando la proprietà degli aggregati non root. Oltre a migrare gli aggregati non root tra i vecchi nodi di controller. Dopo l'installazione dei nodi di sostituzione, è possibile migrare gli aggregati non root dai vecchi nodi di controller ai nodi di sostituzione. I dati ospitati sui nodi che si sta aggiornando sono accessibili durante la procedura di aggiornamento. Inoltre, è possibile migrare i dati LIF tra i nodi del cluster durante la migrazione.

L'hardware del controller che si sostituisce dipende dal tipo di modello di sistema esistente:

[cols="30,70"]
|===
| Se il tuo sistema esistente è... | Quindi... 


| AFF A250, AFF C250 | Sostituire i due controller AFF A250 o AFF C250 con i nuovi controller e moduli i/O. 


| AFF A800, AFF C800 | Sostituire i due controller AFF A800 o AFF C800 con i nuovi controller e moduli i/O. 


| AFF A220, AFF A200, AFF C190, FAS2620 o FAS2720 | Scambiare il modulo controller su ciascun nodo del vecchio controller con il nuovo modulo. 


| AFF A700 o FAS9000 | Scambiare il controller e i moduli NVRAM su ciascun nodo del vecchio controller con i nuovi moduli. *Nota*: Non è necessario spostare, scollegare o ricollegare le schede i/o, i cavi dati, gli shelf di dischi e i dischi. 
|===

NOTE: I termini *node1* e *node2* sono utilizzati solo come riferimento ai nomi dei nodi in questo documento. Quando si segue la procedura, è necessario sostituire i nomi effettivi dei nodi.



== Requisiti e limitazioni

Prima di iniziare la procedura di aggiornamento, è necessario considerare fattori importanti.


NOTE: Prima di avviare la procedura di aggiornamento, è necessario leggere attentamente tutte le seguenti informazioni importanti.

* Questa procedura è complessa e presuppone che si disponga di competenze di amministrazione avanzate di ONTAP. Dovresti anche leggere e comprendere il link:guidelines_for_upgrading_controllers_with_arl.html["linee guida per l'aggiornamento dei controller"] E link:overview_of_the_arl_upgrade.html["Sequenza di aggiornamento ARL"] prima di iniziare l'aggiornamento.
* Questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato in un altro sistema. I passaggi necessari per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. È necessario contattare il supporto tecnico se l'hardware del controller sostitutivo è stato utilizzato in precedenza come parte di un altro cluster ONTAP o come sistema standalone a nodo singolo.
* È possibile utilizzare questa procedura per aggiornare l'hardware del controller nei cluster con più di due nodi; tuttavia, è necessario eseguire la procedura separatamente per ogni coppia ha nel cluster.
* Se si dispone di uno switch non supportato dalla versione di ONTAP e dal sistema sostitutivo a cui si sta eseguendo l'aggiornamento, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_.
* I sistemi AFF A250 e AFF C250 utilizzano porte 10/25 GbE integrate per l'interconnessione dei cluster. Per aggiornare i cluster switchless a due nodi di un sistema AFF A250 o AFF C250 a un sistema AFF A50, AFF A30, AFF C60 o AFF C30, è necessario utilizzare una scheda X60132A a 4 porte 10/25 GbE nello slot 1 su entrambi i nodi. Ciò fornisce l'interconnessione dei cluster per i LIF del cluster a una porta temporanea sulla piattaforma di destinazione.
* I sistemi AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70 e FAS90 condividono 100GbE porte di rete per le connessioni cluster e ha. Questi sistemi possono supportare connessioni cluster 10GbE o 25GbE a switch cluster legacy; tuttavia, NetApp consiglia di eseguire l'aggiornamento a velocità cluster 100GbE quando gli switch 10GbE e 25GbE non sono più necessari. Per ulteriori informazioni, vedere i seguenti articoli della Knowledge base:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Come configurare porte cluster 10G o 25g in una nuova configurazione cluster"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Come convertire le porte del cluster 10G o 25g esistenti in porte del cluster 40G o 100g"^]


--
+
Se non puoi collegare e0a o e0b porte cluster sul nodo esistente alle porte cluster sul nuovo nodo, consulta le seguenti per ulteriori informazioni:

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID bug online di NetApp CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["Bug online di NetApp ID 1127315"^]


* I sistemi ASA A900, AFF A900 e FAS9500 supportano solo l'alimentazione di linea alta (da 200V a 240V). Se il sistema AFF A700 o FAS9000 è alimentato a bassa tensione (da 100 V a 120 V), è necessario convertire l'alimentazione in ingresso del sistema AFF A700 o FAS9000 prima di utilizzare questa procedura.
* Se si sta eseguendo l'aggiornamento da un sistema esistente con tempi di inattività inclusi in <<supported-systems-in-chassis,matrice dei sistemi supportati>>, è possibile aggiornare l'hardware del controller spostando lo spazio di archiviazione o contattare il supporto tecnico. Fare riferimento al link:other_references.html["Riferimenti"] collegamento a _Upgrade spostando volumi o storage_.




== Automatizzare il processo di aggiornamento del controller

Questa procedura fornisce i passaggi per la procedura automatica, che utilizza l'assegnazione automatica del disco e i controlli di raggiungibilità delle porte di rete per semplificare l'esperienza di aggiornamento del controller.
