---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Installare i moduli di sistema sostitutivi sul nodo 2 durante un aggiornamento ARL dei modelli di controller nello stesso chassis. 
---
= Installare il modulo AFF A30, AFF A50, AFF C30 o AFF C60 su node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Installare il modulo controller sostitutivo ricevuto per l'aggiornamento su node2. Il Nodo 2 è il controller B, situato nella metà inferiore dello chassis se si guardano i controller dalla parte posteriore del sistema.

.Fasi
. Posizionare il sistema di stoccaggio sulle guide al centro del cabinet o del rack per telecomunicazioni, quindi sostenere il sistema di archiviazione dal basso e farlo scorrere in posizione.
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto di farlo più avanti nella procedura.

. Collegare le porte di gestione e console al modulo controller node2.
+

NOTE: Poiché lo chassis è già acceso, node2 avvia l'inizializzazione del BIOS seguita da AUTOBOOT non appena è completamente inserito.  Per interrompere l'avvio del nodo 2, prima di inserire completamente il modulo controller nello slot, si consiglia di collegare i cavi della console seriale e di gestione al modulo controller del nodo 2.

. Con la maniglia della camma in posizione aperta, spingere con decisione il modulo controller fino a quando non raggiunge la scheda intermedia e non è completamente inserito. Il dispositivo di chiusura si solleva quando il modulo controller è completamente inserito. Chiudere la maniglia della camma in posizione di blocco.
+

NOTE: Per evitare di danneggiare i connettori, non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio.

. Collegare la console seriale non appena il modulo è inserito e prepararsi a interrompere l'AUTOBOOT del nodo 2.
. Dopo aver interrotto L'AUTOBOOT, node2 si ferma al prompt DEL CARICATORE. Se non INTERROMPETE L'AUTOBOOT in tempo e node2 inizia l'avvio, attendete il prompt e premete Ctrl-C per entrare nel menu di avvio. Dopo che il nodo si è fermato al menu di avvio, utilizzare opzione `8` per riavviare il nodo e interrompere l'AUTOBOOT durante il riavvio.
. Al prompt LOADER> di node2, impostare le variabili di ambiente predefinite:
+
`set-defaults`

. Salvare le impostazioni predefinite delle variabili di ambiente:
+
`saveenv`

. Per configurazioni switchless a due nodi, verificare di avere una scheda X60132A a 4 porte 10/25 GbE nello slot 1 del nodo 2. La scheda X60132A è necessaria per l'interconnessione del cluster durante l'aggiornamento.

