---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/manage-authentication-using-kmip-servers.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configurare e gestire Storage Encryption, gestire le chiavi di autenticazione e interrompere le relazioni SnapMirror quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Gestire l'autenticazione utilizzando i server KMIP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.10.1, è possibile utilizzare i server KMIP (Key Management Interoperability Protocol) per gestire le chiavi di autenticazione.

.Fasi
. Aggiungere un nuovo controller:
+
`security key-manager external enable`

. Aggiungere il gestore delle chiavi:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Verificare che i server di gestione delle chiavi siano configurati e disponibili per tutti i nodi del cluster:
+
`security key-manager external show-status`

. Ripristinare le chiavi di autenticazione da tutti i server di gestione delle chiavi collegati al nuovo nodo:
+
`security key-manager external restore -node _new_controller_name_`



.Quali sono le prossime novità?
Dopo aver gestito l'autenticazione tramite server KMIP, link:confirm-new-controllers-are-set-up-correctly.html["confermare che i nuovi controller siano configurati correttamente"].
