---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verificare che le LIF dei dati NAS di node2 sul node1 vengano ricollocate dal node1 al node2 quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Riportare al nodo gli aggregati non root e le LIF dei dati NAS 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver verificato la configurazione di rete sul nodo 2, è necessario spostare i LIF dei dati NAS di proprietà del nodo 2 dal nodo 1 al nodo 2 e confermare che i LIF SAN siano presenti sul nodo 2.

.A proposito di questa attività
I LIF remoti gestiscono il traffico verso le LUN SAN durante la procedura di aggiornamento. Lo spostamento dei SAN LIF non è necessario per l'integrità del cluster o del servizio durante l'aggiornamento. I LIF SAN non vengono spostati a meno che non sia necessario mapparli su nuove porte.

Dopo aver portato online node2, è necessario verificare che i LIF siano integri e posizionati sulle porte corrette.

.Fasi
. Riprendere l'operazione di trasferimento:
+
[source, cli]
----
system controller replace resume
----
+
Il sistema esegue le seguenti operazioni:

+
--
** Verifica del quorum del cluster
** Verifica dell'ID di sistema
** Controllo della versione dell'immagine
** Verifica della piattaforma di destinazione
** Verifica della raggiungibilità della rete


--
+
Il sistema sospende l'operazione in questa fase del controllo di raggiungibilità della rete

. Riprendere l'operazione di trasferimento:
+
[source, cli]
----
system controller replace resume
----
+
Il sistema esegue i seguenti controlli:

+
--
** Controllo dello stato del cluster
** Controllo dello stato LIF del cluster


--
+
Dopo aver eseguito questi controlli, il sistema ricolloca gli aggregati non root e le LIF dei dati NAS in node2, che è ora in esecuzione sul controller sostitutivo.

+
L'operazione di sostituzione del controller viene interrotta al termine del trasferimento delle risorse.

. Controllare lo stato delle operazioni di trasferimento aggregato e LIF dei dati NAS:
+
[source, cli]
----
system controller replace show-details
----
+
Se la procedura di sostituzione del controller è in pausa, controllare e correggere l'errore, se presente, quindi il problema `resume` per continuare l'operazione.

. Se necessario, ripristinare e ripristinare i LIF spostati oppure migrare e modificare manualmente i LIF del nodo 2 che non sono riusciti a trasferirsi automaticamente sul nodo 2.
+
[role="tabbed-block"]
====
.Ripristinare e ripristinare i LIF spostati
--
.. Elencare eventuali LIF spostati:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. In caso di spostamento di LIF, ripristinare il nodo home al nodo node2:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrare e modificare manualmente i LIF
--
.. Migrare i LIF che non sono riusciti a trasferirsi automaticamente al nodo 2:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. Modificare il nodo home e la porta home per i LIF migrati:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. Riprendere l'operazione per richiedere al sistema di eseguire i controlli successivi richiesti:
+
[source, cli]
----
system controller replace resume
----
+
Il sistema esegue i seguenti post-controlli:

+
** Verifica del quorum del cluster
** Controllo dello stato del cluster
** Controllo della ricostruzione degli aggregati
** Controllo dello stato dell'aggregato
** Controllo dello stato del disco
** Controllo dello stato LIF del cluster
** Controllo del volume



