---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/retire-node2.html 
keywords: retire, node2, retiring, node 
summary: Chiudere il node2 e rimuoverlo dal rack o dallo chassis quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Andare in pensione node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per dismettere node2, è necessario arrestare node2 correttamente e quindi rimuoverlo dal rack o dallo chassis.

.Fasi
. Riprendere l'operazione:
+
`system controller replace resume`

+
Il nodo si arresta automaticamente.



.Quali sono le prossime novità?
Dopo aver disattivato il nodo2, scegliere una delle seguenti procedure di sostituzione del controller in base alla configurazione di upgrade:

* link:replace-node2-affa250-affc250.html["Sostituire il modulo controller node2 AFF A250 o AFF C250"]
* link:replace-node2-affa800-affc800.html["Sostituire il modulo controller node2 AFF A800 o AFF C800"]
* link:replace-node2-affa220-affa200-affc190-fas2620-fas2720.html["Sostituire il modulo controller node2 AFF A220, AFF A200, AFF C190, FAS2620 o FAS2720"]
* link:replace-node2-aff700-fas900.html["Sostituire i moduli controller e NVRAM AFF A700 o FAS9000 del nodo2"]

