---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sull'upgrade dei sistemi AFF e FAS
    url: "/index.html"
  - title: Scegliere la procedura di aggiornamento dell'hardware del controller
    url: "/choose_controller_upgrade_procedure.html"
  - section: upgrade-arl
  - section: upgrade
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
