---
permalink: upgrade/migrate-fas2820-aggregates-epsilon-lifs.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 'Migrare gli aggregati di dati, gli epsilon e le interfacce logiche (LIF) dal nodo 1 al nodo 4.' 
---
= Migrazione di aggregati di dati, epsilon e LIF dal nodo 1 al nodo 4 FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Migrare gli aggregati di dati, gli epsilon e le interfacce logiche (LIF) dal nodo 1 al nodo 4 FAS2820 .

.A proposito di questa attività
Eseguire i seguenti passaggi sul nodo 4.

.Fasi
. Al prompt LOADER per node4, impostare l'ID del sistema partner:
+
[source, cli]
----
setenv partner-sysid <system_ID_of_node1>
----
. Controllare l'ID del sistema partner:
+
[source, cli]
----
printenv partner-sysid
----
. Salva le modifiche:
+
[source, cli]
----
saveenv
----
. Avviare il nodo nel menu di boot:
+
[source, cli]
----
boot_ontap menu
----
. Nel menu di avvio, seleziona l'opzione `6 Update flash from backup config` per ripristinare il file system /var su node4.
+
Questa operazione sostituisce tutte le configurazioni basate su flash con l'ultimo backup su dischi.

. Invio `y` per continuare.
+
[NOTE]
====
Il nodo si riavvia automaticamente per caricare la nuova copia del file system /var.

Il nodo segnala un avviso di mancata corrispondenza dell'ID di sistema. Invio `y` Per eseguire l'override dell'ID di sistema.

====
. Migrare le LIF del cluster:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
+
[NOTE]
====
Se le porte del cluster di sistema non sono simili quando si aggiorna un FAS2820 a un controller sostitutivo, potrebbe essere necessario modificare temporaneamente le interfacce sul nodo 4 in porte del cluster:

[source, cli]
----
network port modify -node <node4> -port <port_name> -mtu 9000 -ipspace Cluster
----
====
+
[source, cli]
----
network interface migrate -vserver Cluster -lif <cluster_LIF>  -destination-node <node4> -destination-port <port_name>
----
. Attendi che il cluster raggiunga il quorum, quindi verifica che i nodi del cluster siano integri:
+
[source, cli]
----
– cluster show
----
+

NOTE: La coppia ha e il failover dello storage rimangono disattivati nello stato corrente.

. Spostare le LIF del cluster sulle porte del cluster TEMPORANEE 25G sul nodo 4:
+
[source, cli]
----
network interface modify -vserver Cluster -lif <cluster_LIF> -home-node <node4> -home-port <port_name>
----
. Completare questo passaggio solo se sul cluster FAS2820 che si sta aggiornando vengono utilizzati gruppi di interfaccia e VLAN dati. Altrimenti vai a<<migrate_node1_nod4,Fase 11>> .
+
I nomi delle porte di rete fisiche sul controller sostitutivo sono diversi da quelli sul FAS2820.  Ciò potrebbe causare lo spostamento delle VLAN e la configurazione errata dei gruppi di interfacce sul nodo 4.

+
.. Mostra le VLAN spostate:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans show
----
.. Ripristinare le VLAN spostate:
+
[source, cli]
----
cluster controller-replacement network displaced-vlans restore
----
.. Correggere i gruppi di interfacce configurati in modo errato.  I nomi delle porte tra FAS2820 e i controller che si stanno aggiornando potrebbero essere diversi.  Aggiornare i gruppi di interfaccia con le porte membro corrette:
+
[source, cli]
----
ifgrp remove-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----
+
[source, cli]
----
ifgrp add-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----




[[migrate_node1_nod4]]
. Migrare gli aggregati di dati dal nodo 1 al nodo 4:
+
[source, cli]
----
storage aggregate relocation start -aggregate-list <aggregate_list_name> -node <node1> -destination <node4> -ndo-controller-upgrade true -override-destination-checks true
----
. Mostra lo stato di aggregazione dei dati:
+
[source, cli]
----
storage aggregate show
----
. Migrare l'epsilon rimuovendolo dal nodo 1 e spostandolo nel nodo 4.
+
.. Rimuovere epsilon dal nodo 1:
+
[source, cli]
----
cluster modify -epsilon false -node <node1>
----
.. Sposta epsilon al nodo 4:
+
[source, cli]
----
cluster modify -epsilon true -node <node4>
----


. Mostra lo stato del cluster per verificare la modifica epsilon:
+
[source, cli]
----
cluster show
----
. Visualizza tutti i LIF della rete dati:
+
[source, cli]
----
network interface show -role data
----
. Migrare tutti i dati LIF al nodo 4:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node4> -destination-port <port_name>
----
. Visualizzare lo stato di tutti i dati LIF nel cluster:
+
[source, cli]
----
network interface show -role data
----
. Se qualche LIF è inattivo, imposta il suo stato amministrativo su `up` immettendo il seguente comando una volta per ogni LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Migrare la LIF di gestione del cluster:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node4> -destination-port <port_name>
----
. Visualizzare lo stato della LIF di gestione del cluster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Arrestare il nodo 1:
+
[source, cli]
----
halt -node <node1> -inhibit-takeover true -ignore-quorum-warnings true
----


.Quali sono le prossime novità?
link:convert-fas2820-node1-drive-shelf.html["Converti il node1 in uno shelf di dischi e connettiti al node3"]
