---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: 'Per completare l"aggiornamento, collegare FAS2820node3 a node4, quindi migrare le interfacce logiche dati (LIF) e gli aggregati dati da node4 a node3.' 
---
= Migrare LIF e aggregati di dati dal nodo 4 al nodo 3 FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per completare l'aggiornamento, collegare il nodo 3 FAS2820 al nodo 4, quindi migrare le interfacce logiche dati (LIF) e gli aggregati dati dal nodo 4 al nodo 3.

.A proposito di questa attività
Eseguire i seguenti passaggi sul nodo 3.

.Fasi
. Al prompt DEL CARICATORE per node3, avviare il nodo nel menu di boot:
+
[source, cli]
----
boot_ontap menu
----
. Selezionare l'opzione `6 Update flash from backup config` per ripristinare il file system /var su node3.
+
Questa operazione sostituisce tutte le configurazioni basate su flash con l'ultimo backup su dischi.

. Invio `y` per continuare.
. Consentire al nodo di avviarsi normalmente.
+
[NOTE]
====
Il nodo si riavvia automaticamente per caricare la nuova copia del file system /var.

Il nodo segnala una mancata corrispondenza dell'ID di sistema. Invio `y` Per eseguire l'override dell'ID di sistema.

====
. Verificare che le porte del cluster e HA siano connesse tra il nodo 3 e il nodo 4.
. Visualizza le porte cluster e HA su node3 e node4:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. Modificare il dominio di broadcast del cluster per includere le porte del cluster desiderate:
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: A partire da ONTAP 9.8, i nuovi spazi IP e uno o più domini di broadcast potrebbero essere designati per le porte fisiche esistenti destinate alla connettività del cluster.

. Modificare l'IPSpace del cluster per includere le porte del cluster desiderate e impostare l'unità di trasmissione massima su 9000, se non già impostata:
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. Visualizza tutte le LIF della rete del cluster:
+
[source, cli]
----
network interface show -role cluster
----
. Migrare tutti i LIF della rete cluster su entrambi i nodi alle rispettive porte home pianificate:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. Visualizza tutte le LIF della rete del cluster:
+
[source, cli]
----
network interface show -role cluster
----
. Configurare le porte home per i LIF della rete cluster:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. Migrare tutti i dati LIF destinati a node3 nuovamente su node3:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. Visualizza tutti i LIF della rete dati:
+
[source, cli]
----
network interface show -role data
----
. Configurare il nodo home e la porta home per tutti i LIF dati.  Se qualche LIF è inattivo, imposta il suo stato amministrativo su `up` immettendo il seguente comando una volta per ogni LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. Migrare la LIF di gestione del cluster:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. Visualizzare lo stato della LIF di gestione del cluster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Visualizzare lo stato di tutti gli aggregati di dati nel cluster:
+
[source, cli]
----
storage aggregate show
----
. Abilitare l'alta disponibilità del cluster nel cluster a due nodi:
+
[source, cli]
----
cluster ha modify -configured true
----
. Abilita e verifica il failover di archiviazione per node3 e node4:
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. Migrare gli aggregati di dati di proprietà di node4 che dovrebbero essere di proprietà di node3:
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. Visualizzare lo stato di tutti gli aggregati di dati nel cluster:
+
[source, cli]
----
storage aggregate show
----
. Abilitare il ripristino automatico delle LIF di rete tra i nodi:
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. Attiva giveback automatico per il failover dello storage:
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. Visualizzare lo stato del cluster:
+
[source, cli]
----
cluster show
----
. Visualizzare l'idoneità al failover:
+
[source, cli]
----
storage failover show
----
+

NOTE: Nell'output del report del cluster, un nodo potrebbe possedere erroneamente aggregati che appartengono a un altro nodo.  In tal caso, eseguire un'acquisizione e una restituzione da entrambe le parti del cluster.

. Visualizzare lo stato di tutti gli aggregati di dati nel cluster:
+
[source, cli]
----
storage aggregate show
----

