---
permalink: upgrade/reassign-node1-drives.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Dopo aver convertito AFF A150, AFF A220 o FAS2820 node1 in uno shelf di dischi e averlo collegato a node3, si riassegnano i dischi che in precedenza appartenevano a node1 a node3. 
---
= Riassegnare i dischi dal nodo 1 al nodo 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riassegna le unità che erano state precedentemente assegnate ad AFF A150, AFF A220 o FAS2820 node1 a node3.

.Fasi
Eseguire questi passaggi su node3.

. Al prompt DEL CARICATORE, fare il boot node3 in Maintenance Mode (modalità di manutenzione):
+
[source, cli]
----
boot_ontap maint
----
+
Viene visualizzato il prompt Modalità di manutenzione.

. Visualizza tutti i dischi collegati:
+
[source, cli]
----
disk show -v
----
. Registrare il valore dell'ID del sistema locale; questo è l'ID del sistema di node3.  Registrare anche gli ID di sistema di node1 e node4 dalla colonna "OWNER".
. Riassegnare tutti i dischi da node1 a node3:
+
[role="tabbed-block"]
====
.Se stai utilizzando dischi interi
--
Esegui il seguente comando:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID>
----
--
.Se stai utilizzando dischi partizionati
--
Esegui il seguente comando:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID> -p <node4_system_ID>
----
--
====
. Verificare che tutte le unità riassegnate siano visualizzabili con il nuovo ID di sistema:
+
[source, cli]
----
disk show -s <node3_system_ID>
----
+

CAUTION: Se le unità non sono visibili, *interrompere* e contattare l'assistenza tecnica per ricevere assistenza.

. Uscire dalla modalità di manutenzione:
+
[source, cli]
----
halt
----


.Quali sono le prossime novità?
link:migrate-node4-lifs-aggregates.html["Migrazione di LIF e aggregati di dati dal nodo 4 al node3"]
