---
permalink: upgrade/reassign-fas2820-node2-drives.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Dopo aver convertito il nodo 2 FAS2820 in uno scaffale di unità DS212C e aver effettuato la connessione al nodo 4, è possibile riassegnare le unità che in precedenza appartenevano al nodo 2 al nodo 4. 
---
= Riassegnare le unità dal nodo FAS2820 2 al nodo 4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riassegnare le unità che in precedenza appartenevano al nodo 2 di FAS2820 al nodo 4.

.Prima di iniziare
Verificare che il nodo 3 e il nodo 4 siano entrambi in standby al prompt DEL CARICATORE.

.A proposito di questa attività
Eseguire i seguenti passaggi sul nodo 4.

.Fasi
. Al prompt DEL CARICATORE, fare il boot node4 in Maintenance Mode (modalità di manutenzione):
+
[source, cli]
----
boot_ontap maint
----
+
Viene visualizzato il prompt Modalità di manutenzione.

. Visualizza tutti i dischi collegati:
+
[source, cli]
----
disk show -v
----
. Registrare il valore dell'ID del sistema locale; si tratta dell'ID del sistema di node4. Registrare anche gli ID di sistema di node1 e node2 dalla colonna "OWNER".
. Riassegnare tutte le unità dal nodo 2 al nodo 4.
+
[role="tabbed-block"]
====
.Se stai utilizzando dischi interi
--
Esegui il seguente comando:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID>
----
--
.Se stai utilizzando dischi partizionati
--
Esegui il seguente comando:

[source, cli]
----
disk reassign -s <node2_system_ID> -d <node4_system_ID> -p <node1_system_ID>
----
--
====
. Verificare che tutte le unità riassegnate siano visualizzabili con il nuovo ID di sistema:
+
[source, cli]
----
disk show -s <node4_System_ID>
----
+

CAUTION: Se le unità non sono visibili, *interrompere* e contattare l'assistenza tecnica per ricevere assistenza.

. Verificare che l'aggregato root di node2 sia riportato nell'output e che l'aggregato sia online:
+
[source, cli]
----
aggr status
----
. Uscire dalla modalità di manutenzione:
+
[source, cli]
----
halt
----


.Quali sono le prossime novità?
link:migrate-fas2820-aggregates-epsilon-lifs.html["Migrazione di aggregati di dati, epsilon e LIF dal nodo 1 al node4"]
