---
permalink: upgrade/upgrade-map-network-ports-ontap-9-8.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, correct, configure, setting, data, map network ports using ontap 9.8 
summary: 'Per consentire a node3 e node4 di comunicare tra loro nel cluster e con la rete dopo l"aggiornamento, è necessario confermare che le porte fisiche sono configurate correttamente con le impostazioni per l"uso previsto, come cluster, dati e così via.' 
---
= Mappare le porte di rete utilizzando ONTAP 9.8 o versione successiva
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per consentire a node3 e node4 di comunicare tra loro nel cluster e con la rete dopo l'aggiornamento, è necessario confermare che le porte fisiche sono configurate correttamente con le impostazioni per l'uso previsto, come cluster, dati e così via.

.Prima di iniziare
Questa procedura si applica ai sistemi che eseguono ONTAP 9.8 o versioni successive. Se si utilizza ONTAP 9.7 o versioni precedenti, è necessario seguire la procedura descritta in link:upgrade-map-network-ports-ontap-9-7-or-earlier.html["Mappare le porte di rete utilizzando ONTAP 9.7 o versioni precedenti"].

.A proposito di questa attività
È necessario eseguire questi passaggi su node3 e node4.


NOTE: I seguenti esempi di comandi si riferiscono a "node1" perché in questa fase della procedura i nodi di sostituzione "node3" e "node4" sono in realtà denominati "node1" e "node2".

.Fasi
. Se sul sistema è in esecuzione ONTAP 9.7 o versione precedente, *STOP*. È necessario utilizzare la procedura descritta in link:upgrade-map-network-ports-ontap-9-7-or-earlier.html["Mappare le porte di rete utilizzando ONTAP 9.7 o versioni precedenti"].
. Individuare le informazioni di configurazione di porta e LIF per node1 e node2 registrate in _Prepare for upgrade when moving storage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Fase 3"].
. Individuare le informazioni relative a porte, domini di trasmissione e IPspaces registrate in _preparazione per l'aggiornamento durante lo spostamento dello storage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Fase 3"].
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. Apportare le seguenti modifiche:
+
.. Avviare e accedere a node3 e node4 se non è già stato fatto.
.. Modificare le porte che faranno parte del dominio di broadcast del cluster:
+
`network port modify -node _node_name_ -port _port_name_ -mtu 9000 -ipspace Cluster`

+
Questo esempio aggiunge `Cluster` porta e1b su "node1":

+
`network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. Migrare le LIF del cluster alle nuove porte, una volta per ogni LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -source-node node1 -destination-node node1 -destination-port _port_name_`

+
Una volta migrate tutte le LIF del cluster e stabilita la comunicazione del cluster, il cluster deve entrare in quorum.

.. Modificare la porta home delle LIF del cluster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Rimuovere le vecchie porte da `Cluster` dominio di broadcast:
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports _node1:port_`

.. Visualizza lo stato di salute di node3 e node4:
+
`cluster show -node _node1_ -fields health`

.. In base alla versione di ONTAP in esecuzione sulla coppia ha sottoposta a upgrade, esegui una delle seguenti azioni:
+
[cols="30,70"]
|===
| Se la versione di ONTAP è... | Quindi... 


| da 9,8 a 9.11.1 | Verificare che le LIF del cluster siano in ascolto sulla porta 7700:

`::> network connections listening show -vserver Cluster` 


| 9.12.1 o versione successiva | Saltare questo passaggio e passare a. <<map_98_5,Fase 5>>. 
|===
+
La porta 7700 in ascolto sulle porte del cluster è il risultato previsto, come mostrato nell'esempio seguente per un cluster a due nodi:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. Per ogni cluster LIF che non è in ascolto sulla porta 7700, imposta lo stato amministrativo della LIF su `down` e poi `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Ripetere il passaggio secondario (g) per verificare che la LIF del cluster sia in ascolto sulla porta 7700.



. [[map_98_5]]modificare l'appartenenza dei domini di broadcast alle porte fisiche che ospitano LIF dati. È possibile eseguire questa operazione manualmente, come illustrato nella link:upgrade-map-network-ports-ontap-9-7-or-earlier.html#map_97_7["Mappare le porte di rete utilizzando ONTAP 9.7 o versioni precedenti, passaggio 7"]. NetApp consiglia di utilizzare la procedura di scansione e riparazione avanzata per la raggiungibilità della rete introdotta in ONTAP 9,8, come illustrato nella seguente fase 5, sottopagine da (a) a (g).
+
.. Elencare lo stato di raggiungibilità di tutte le porte:
+
`network port reachability show`

.. Riparare la raggiungibilità delle porte fisiche, seguita dalle porte VLAN, eseguendo il seguente comando su ciascuna porta, una alla volta:
+
`reachability repair -node _node_name_ -port _port_name_`

+
È previsto un avviso simile a quello riportato di seguito. Rivedere e accedere `y` oppure `n` a seconda dei casi:

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a
different broadcast domain, which can cause LIFs to be re-homed away
from the port. Are you sure you want to continue? {y|n}:
----
.. Per consentire a ONTAP di completare la riparazione, attendere circa un minuto dopo aver eseguito `reachability repair` sull'ultima porta.
.. Elencare tutti i domini di broadcast sul cluster:
+
`network port broadcast-domain show`

.. Quando viene eseguita la riparazione della raggiungibilità, ONTAP tenta di posizionare le porte nei domini di trasmissione corretti. Tuttavia, se non è possibile determinare la raggiungibilità di una porta e non corrisponde a nessuno dei domini di broadcast esistenti, ONTAP creerà nuovi domini di broadcast per queste porte. Se necessario, è possibile eliminare i domini di broadcast appena creati se tutte le porte membri diventeranno porte membri dei gruppi di interfacce. Elimina domini di broadcast:
+
`broadcast-domain delete -broadcast-domain _broadcast_domain_`

.. Esaminare la configurazione del gruppo di interfacce e, se necessario, aggiungere o eliminare le porte membro. Aggiungere porte membro alle porte del gruppo di interfacce:
+
`ifgrp add-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

+
Rimuovere le porte membro dalle porte del gruppo di interfacce:

+
`ifgrp remove-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

.. Eliminare e ricreare le porte VLAN in base alle necessità. Elimina porte VLAN:
+
`vlan delete -node _node_name_ -vlan-name _vlan_port_`

+
Creazione delle porte VLAN:

+
`vlan create -node _node_name_ -vlan-name _vlan_port_`

+

NOTE: A seconda della complessità della configurazione di rete del sistema da aggiornare, potrebbe essere necessario ripetere la fase 5, le fasi da (a) a (g) finché tutte le porte sono posizionate correttamente dove necessario.



. Se nel sistema non sono configurate VLAN, passare a. <<map_98_7,Fase 7>>. Se sono configurate VLAN, ripristinare le VLAN smontate precedentemente configurate su porte che non esistono più o che sono state configurate su porte spostate in un altro dominio di trasmissione.
+
.. Visualizzare le VLAN smontate:
+
`cluster controller-replacement network displaced-vlans show`

.. Ripristinare le VLAN spostate sulla porta di destinazione desiderata:
+
`displaced-vlans restore -node _node_name_ -port _port_name_ -destination-port _destination_port_`

.. Verificare che tutte le VLAN smontate siano state ripristinate:
+
`cluster controller-replacement network displaced-vlans show`

.. Le VLAN vengono automaticamente collocate nei domini di trasmissione appropriati circa un minuto dopo la loro creazione. Verificare che le VLAN ripristinate siano state collocate nei domini di trasmissione appropriati:
+
`network port reachability show`



. [[map_98_7]]a partire da ONTAP 9.8, ONTAP modificherà automaticamente le porte home dei file LIF se le porte vengono spostate tra domini di broadcast durante la procedura di riparazione della raggiungibilità delle porte di rete. Se la porta home di una LIF è stata spostata in un altro nodo o non è assegnata, tale LIF viene presentata come LIF spostato. Ripristinare le porte home dei file LIF spostati le cui porte home non esistono più o sono state spostate in un altro nodo.
+
.. Visualizzare le LIF le cui porte home potrebbero essere state spostate in un altro nodo o non esistere più:
+
`displaced-interface show`

.. Ripristinare la porta home di ciascun LIF:
+
`displaced-interface restore -vserver _vserver_name_ -lif-name _lif_name_`

.. Verificare che tutte le porte LIF home siano state ripristinate:
+
`displaced-interface show`

+
Quando tutte le porte sono configurate correttamente e aggiunte ai domini di trasmissione corretti, il comando di visualizzazione della raggiungibilità delle porte di rete dovrebbe riportare lo stato di raggiungibilità come ok per tutte le porte connesse e lo stato come non recuperabile per le porte senza connettività fisica. Se una delle porte riporta uno stato diverso da questi due, riparare la raggiungibilità come descritto in <<map_98_5,Fase 5>>.



. Verificare che tutte le LIF siano amministrativamente up sulle porte appartenenti ai domini di broadcast corretti.
+
.. Verificare la presenza di eventuali LIF amministrativamente non disponibili:
+
`network interface show -vserver _vserver_name_ -status-admin down`

.. Verificare la presenza di eventuali LIF non attivi dal punto di vista operativo: `network interface show -vserver _vserver_name_ -status-oper down`
.. Modificare le LIF che devono essere modificate in modo da avere una porta home diversa:
+
`network interface modify -vserver _vserver_name_ -lif _lif_ -home-port _home_port_`

+

NOTE: Per le LIF iSCSI, la modifica della porta home richiede che la LIF sia amministrativamente inattiva.

.. Ripristinare le LIF che non si trovano nelle rispettive porte home:
+
`network interface revert *`





.Al termine
Il mapping delle porte fisiche è stato completato. Per completare l'aggiornamento, visitare il sito Web all'indirizzo link:upgrade-final-upgrade-steps-in-ontap-9-8.html["Eseguire la procedura di aggiornamento finale in ONTAP 9.8 o versione successiva"].
