---
permalink: upgrade/upgrade-restore-root-volume-config.html 
sidebar: sidebar 
keywords: Controller Hardware Upgrade Express Guide 
summary: È necessario ripristinare le informazioni di configurazione dal volume root ai dispositivi di boot. 
---
= Ripristinare la configurazione del volume root
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario ripristinare le informazioni di configurazione dal volume root ai dispositivi di boot.


NOTE: Se si esegue un upgrade del controller in-place a un sistema che utilizza le porte "e0a" e "e0b" come porte di interconnessione ad alta disponibilità (ha), ad esempio FAS8300, AFF A400 o FAS8700, verificare di disporre di link:upgrade-prepare-when-moving-storage.html#assign_lifs["Riassegnato qualsiasi LIF di gestione o intercluster"] configurato sulle porte "e0a" e "e0b" del sistema originale prima di avviare la procedura di aggiornamento.

.A proposito di questa attività
Prima di passare alla fase successiva, è necessario eseguire questi passaggi su node3 e node4, completando ogni passaggio su un nodo e poi sull'altro.

.Fasi
. Accedere al menu di boot dal prompt DEL CARICATORE:
+
`boot_ontap menu`

. Dal menu di avvio, selezionare `(6) Update flash from backup config` e invio `y` quando viene richiesto di continuare. Scegliere una delle seguenti opzioni:
+
[listing]
----
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 6
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: y
----
+
Il processo di aggiornamento flash viene eseguito per alcuni minuti, quindi il sistema viene riavviato.

. Quando viene richiesto di confermare la mancata corrispondenza dell'ID di sistema, immettere `y`.
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id? {y|n} [n] y
----
+
La sequenza di avvio procede normalmente.



Se l'aggiornamento del controller non riesce e viene visualizzato un messaggio `rlib_port_ipspace_assign` Messaggio di errore, è necessario ripristinare l'aggiornamento ed eliminare le LIF sulle porte di rete del sistema originale utilizzate come porte ha sul sistema sostitutivo. Per ulteriori informazioni, vedere link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/PANIC_%3A_rlib_port_ipspace_assign%3A_port_e0a_could_not_be_moved_to_HA_ipspace["Questo articolo della Knowledge base"^].
