---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 'Questo contenuto descrive come aggiornare l"hardware del controller di un sistema AFF o FAS in un cluster spostando lo storage o i volumi.' 
---
= Decidere se eseguire l'upgrade spostando volumi o storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo contenuto descrive come aggiornare l'hardware del controller di un sistema AFF, FAS o ASA in un cluster trasferendo storage o volumi.

Utilizzare questa procedura se si desidera aggiornare l'hardware del controller nelle seguenti situazioni:


NOTE: Le procedure di aggiornamento dell'hardware sono state semplificate in ONTAP 9.8 con l'introduzione della funzione di posizionamento automatico delle porte.

* I nodi originali e nuovi sono compatibili e supportati.
* I nodi originali e nuovi eseguono ONTAP 9,0 o versioni successive. Quando possibile, NetApp consiglia di utilizzare la stessa versione di ONTAP sui nodi originale e sui nodi nuovi.
+
Se l'upgrade del controller include versioni miste di ONTAP, vedere https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["Cluster ONTAP a versione mista"^] per ulteriori informazioni.

* Si stanno riutilizzando gli indirizzi IP, le maschere di rete e i gateway dei nodi originali sui nuovi nodi.
* Si prevede di aggiornare l'hardware del controller spostando lo storage o spostando i volumi.
* Siete pronti a eseguire una procedura di interruzione se state eseguendo l'upgrade spostando lo storage.
+
L'aggiornamento mediante lo spostamento dei volumi non comporta interruzioni.

* Si prevede di convertire un nodo di un modello supportato in uno shelf di dischi, quindi di collegarlo ai nuovi nodi.


Se si sta aggiornando una configurazione MetroCluster, consultare la sezione https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Aggiornare, aggiornare o espandere la configurazione di MetroCluster"^].

.Informazioni correlate
* link:upgrade-considerations.html["Considerazioni per l'aggiornamento dell'hardware del controller"]
* link:../choose_controller_upgrade_procedure.html["Scegliere i metodi per aggiornare l'hardware del controller"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Dove trovare le procedure per le attività di manutenzione di MetroCluster"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

