---
permalink: upgrade/upgrade-reset-default-configuration-node3-and-node4.html 
sidebar: sidebar 
keywords: confirm, configuration, information, boot, media, interfere, controller, upgrade, reset, node3, node4, node, default, setting, reset default configuration on the new nodes 
summary: 'Per confermare che le informazioni di configurazione sul supporto di avvio non interferiscano con l"aggiornamento del controller, è necessario ripristinare le configurazioni di node3 e node4 alle impostazioni di configurazione predefinite.' 
---
= Ripristinare la configurazione predefinita sui nuovi nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per confermare che le informazioni di configurazione sul supporto di avvio non interferiscano con l'aggiornamento del controller, è necessario ripristinare le configurazioni di node3 e node4 alle impostazioni di configurazione predefinite.

.A proposito di questa attività
Eseguire i seguenti passaggi su node3 e node4. È possibile eseguire le operazioni su ciascun nodo in parallelo.

. Avviare il nodo nel menu di boot:
+
`boot_ontap menu`

. Al prompt del menu di boot, digita  `wipeconfig` e poi premi Invio.
+
Viene visualizzato il seguente output:

+
[listing]
----
Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  wipeconfig
----
. Invio `yes` quando viene visualizzato un prompt simile a quanto segue:
+
[listing]
----
This option deletes critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?: yes
Rebooting to finish wipeconfig request.
----
+
Il sistema avvia la `wipeconfig` procedura e si riavvia. Al termine della procedura, il sistema ritorna al menu di boot.

. Dal menu di boot, digita 8 per riavviare il nodo e digita Ctrl-C durante AUTOBOOT per arrestare il nodo al prompt LOADER.

