---
permalink: upgrade/upgrade_reassign_drives_node2_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Collegare fisicamente il nodo 2 al nodo 4 prima di riassegnare i dischi dal nodo 2 al nodo 4. 
---
= Riassegnare i dischi dal nodo 2 al nodo 4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver convertito il nodo AFF A250 2 in uno shelf di dischi NS224 e aver effettuato il collegamento al nodo AFF A400 4, è necessario riassegnare i dischi che in precedenza appartenevano al nodo 2 al nodo 4.

.Prima di iniziare
Verificare che sia il nodo 2 che il nodo 4 siano in standby al prompt DEL CARICATORE.

.A proposito di questa attività
Eseguire le seguenti operazioni al nodo 4.

.Fasi
. Al prompt DEL CARICATORE, fare il boot node4 in Maintenance Mode (modalità di manutenzione):
+
`boot_ontap maint`

. Mostrare lo stato delle interfacce 100GbE:
+
`storage port show`

. Impostare le interfacce 100GbE sulle porte di storage:
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. Verificare le modifiche di modalità alle interfacce 100GbE:
+
`storage port show`

+
Viene visualizzato un output simile al seguente:

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  online  30
----
. Visualizza tutti i dischi collegati:
+
`disk show -v`

. Registrare l'ID del sistema locale.
. Riassegnare tutti i dischi dal nodo 2 al nodo 4:
+
`disk reassign -s _node2_ -d _node4_ -p _node1_`

. Verificare che tutte le unità riassegnate siano visualizzabili con il nuovo ID di sistema:
+
`disk show -s _node4_System_ID_`

+

NOTE: Se i dischi non sono visualizzabili, *ARRESTARE* e contattare il supporto tecnico per assistenza.

. Uscire dalla modalità di manutenzione:
+
`halt`


