---
permalink: upgrade/upgrade-delete-san-lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lid, original, node, unjoin, original, delete san lifs from the original nodes 
summary: Se il cluster si trova in un ambiente SAN, è necessario eliminare tutti I LIF SAN dai nodi originali prima di poter disunire i nodi originali dal cluster. 
---
= Eliminare le LIF SAN non più richieste dai nodi originali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il cluster si trova in un ambiente SAN, è necessario eliminare i LIF SAN non più necessari dai nodi originali prima di poter disunire i nodi originali dal cluster.

.Fasi
. Se si dispone di iniziatori iSCSI, attenersi alla seguente procedura:
+
.. Visualizzare un elenco degli iniziatori attivi attualmente connessi a una SVM sui nodi originali, una volta per ciascuno dei vecchi LIF: +
`iscsi connection show -vserver _Vserver_name_ -lif _old_lif_`
+
L'esempio seguente mostra l'output del comando con un iniziatore attivo connesso a SVM vs1:

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. Se alcuni iniziatori sono ancora connessi a un nodo originale, disconnettersi dalle sessioni dal computer host.


. Visualizzare l'elenco dei set di porte per determinare se i LIF iSCSI o FC sui nodi originali appartengono a un set di porte:
+
`lun portset show`

+
L'esempio seguente mostra l'output di `lun portset show` comando:

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. Se gli iSCSI o i LIF FC su un nodo originale sono membri di un set di porte, rimuoverli dal set di porte:
+
`lun portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _lif_name_`

. Eliminare le LIF sui nodi originali:
+
`network interface delete -vserver _vserver_name_ -lif _lif_name_`


