---
permalink: upgrade/upgrade-remove-original-nodes.html 
sidebar: sidebar 
keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster 
summary: Dopo aver spostato i volumi nei nuovi nodi, è necessario rimuovere i nodi originali dal cluster. Quando si rimuove un nodo, la configurazione del nodo viene cancellata e tutti i dischi vengono inizializzati. 
---
= Rimuovere i nodi originali dal cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver spostato i volumi dai nodi originali ai nuovi nodi e aver spostato o eliminato i LIF dei dati, è possibile rimuovere i nodi originali dal cluster. Quando si rimuove un nodo, la configurazione del nodo viene cancellata e tutti i dischi vengono inizializzati.

.Fasi
. [[disable-ha]]Disabilita la configurazione ad alta disponibilità (HA) sui nodi originali:
+
[source, cli]
----
storage failover modify -node <original_node_name> -enabled false
----


. Cambia il livello di privilegio su avanzato:
+
[source, cli]
----
set -privilege advanced
----
. Identifica il nodo nel cluster che ha epsilon:
+
[source, cli]
----
cluster show
----
+
Nell'esempio seguente, "node0" attualmente contiene epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Se il nodo che stai rimuovendo detiene epsilon:
+
.. Sposta epsilon dal nodo che stai rimuovendo:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Sposta epsilon su un nodo che non stai rimuovendo:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identificare il nodo master corrente:
+
[source, cli]
----
cluster ring show
----
+
Il nodo master è il nodo che contiene processi come `mgmt`, `vldb`, `vifmgr`, `bcomd`, E `crs`.

. Se il nodo che stai rimuovendo è il nodo master corrente, abilita un altro nodo nel cluster affinché venga eletto come nodo master:
+
.. Rendere il nodo master corrente non idoneo a partecipare al cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
Il nodo viene contrassegnato come non funzionante finché non ne viene ripristinata l'idoneità. Quando il nodo master diventa non idoneo, uno dei nodi rimanenti viene eletto dal quorum del cluster come nuovo master.

+
[NOTE]
====
Se si esegue questo passaggio sul primo nodo di una coppia HA, è necessario contrassegnare solo quel nodo come non idoneo. Non modificare lo stato del partner HA.

Se il nodo partner viene selezionato come nuovo master, è necessario verificare se detiene epsilon prima di renderlo non idoneo. Se il nodo partner detiene epsilon, è necessario spostare epsilon su un nodo diverso che rimane nel cluster prima di renderlo non idoneo. Si esegue questa operazione quando si ripetono questi passaggi per rimuovere il nodo partner.

====
.. Rendere nuovamente idoneo il nodo master precedente a partecipare al cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Accedere al LIF di gestione del nodo remoto o al LIF di gestione del cluster su un nodo che non si sta rimuovendo dal cluster.
. Rimuovi i nodi dal cluster:
+
|===
| Per questa versione di ONTAP... | Utilizzare questo comando... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4 e versioni successive
 a| 
Con nome nodo:

[source, cli]
----
cluster remove-node -node <node_name>
----
Con IP del nodo:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Se si dispone di un cluster di versione mista e si sta rimuovendo l'ultimo nodo di versione inferiore, utilizzare `-skip-last-low-version-node-check` parametro con questi comandi.

+
Il sistema ti informa di quanto segue:

+
** È inoltre necessario rimuovere dal cluster il partner di failover del nodo.
** Dopo aver rimosso il nodo e prima che possa essere ricollegato a un cluster, è necessario utilizzare l'opzione del menu di avvio *(4) Pulisci configurazione e inizializza tutti i dischi* o l'opzione *(9) Configura partizionamento unità avanzato* per cancellare la configurazione del nodo e inizializzare tutti i dischi.
+
Se si verificano delle condizioni che è necessario risolvere prima di rimuovere il nodo, viene generato un messaggio di errore. Ad esempio, il messaggio potrebbe indicare che il nodo ha risorse condivise che è necessario rimuovere o che il nodo si trova in una configurazione HA del cluster o in una configurazione di failover dell'archiviazione che è necessario disabilitare.

+
Se il nodo è il quorum master, il cluster perderà brevemente il quorum e poi lo ripristinerà. Questa perdita del quorum è temporanea e non influisce su alcuna operazione sui dati.



. Se un messaggio di errore indica condizioni di errore, risolvere tali condizioni e rieseguire l'operazione `cluster remove-node` O `cluster unjoin` comando.
+
Il nodo si riavvia automaticamente dopo essere stato rimosso correttamente dal cluster.

. Se si sta riutilizzando il nodo, cancellare la configurazione del nodo e inizializzare tutti i dischi:
+
.. Durante il processo di avvio, premere Ctrl-C per visualizzare il menu di avvio quando richiesto.
.. Selezionare l'opzione del menu di avvio *(4) Pulisci la configurazione e inizializza tutti i dischi*.


. [[return-admin]]Torna al livello di privilegio admin:
+
[source, cli]
----
set -privilege admin
----


. Ripeti i passaggi <<disable-ha,1>> A <<return-admin,10>> per rimuovere il partner di failover dal cluster.
. Se il cluster ha solo due nodi rimanenti, configurare la disponibilità elevata per il cluster a due nodi:
+
[source, cli]
----
cluster ha modify -configured true
----


.Quali sono le prossime novità?
link:upgrade-complete-move-volumes.html["Completa l'aggiornamento dei volumi di spostamento"]
