---
permalink: upgrade/upgrade_considerations_move_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, lif, original, node, unjoin, original, move san lifs 
summary: È necessario spostare LE LIF SAN solo se si modifica il contenuto del cluster. 
---
= Considerazioni per lo spostamento di LIF SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario spostare le LIF SAN solo se si modificano i contenuti del cluster, ad esempio aggiungendo nodi al cluster o eliminando nodi dal cluster. Quando si sposta una LIF, non è necessario ridefinire la zona del fabric FC o creare nuove sessioni iSCSI tra gli host collegati del cluster e la nuova interfaccia di destinazione.

È possibile spostare UN LIF SAN utilizzando `network interface modify` comando. Per spostare UNA LIF SAN, devi portare la LIF offline, spostare la LIF su un nodo o una porta home diversa e quindi riportarla online nella nuova posizione. ALUA (Asymmetric Logical Unit Access) offre percorsi ridondanti e selezione automatica del percorso come parte di qualsiasi soluzione SAN ONTAP. Pertanto, quando il LIF viene portato offline per lo spostamento, non si verifica alcuna interruzione i/O. L'host semplicemente riprova e sposta i/o in un altro LIF.

Durante i movimenti LIF, è possibile eseguire senza interruzioni le seguenti attività:

* Sostituire una coppia ha di un cluster con una coppia ha aggiornata in modo trasparente per gli host che accedono ai dati LUN
* Aggiornare una scheda di interfaccia di destinazione
* Spostare le risorse di una macchina virtuale di storage (SVM) da un set di nodi in un cluster a un altro set di nodi nello stesso cluster
* Quando il server host è in linea, è possibile spostare un LUN SAN in una nuova coppia ha senza interrompere l'accesso del server host ai dati del LUN


Per ulteriori informazioni, consultare https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["Movimento LIF SAN"^] Procedura nella documentazione di _GESTIONE dello storage SAN_.
