---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 'Questo contenuto descrive come aggiornare l"hardware del controller di un sistema AFF o FAS in un cluster spostando lo storage o i volumi.' 
---
= Decidere se eseguire l'upgrade spostando volumi o storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo contenuto descrive come aggiornare l'hardware del controller di un sistema AFF, FAS o ASA in un cluster trasferendo storage o volumi.

Utilizzare questa procedura se si desidera aggiornare l'hardware del controller nelle seguenti situazioni:

[NOTE]
====
* Gli aggiornamenti ASA a un sistema sostitutivo ASA R2 non sono supportati. Per informazioni sulla migrazione dei dati da un sistema ASA a un sistema ASA R2, vedere link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Abilitare l'accesso ai dati dagli host SAN al sistema di storage ASA R2"^].
* Quando esegui l'upgrade a un sistema introdotto in ONTAP 9.15.1 o versioni successive, ONTAP converte l'efficienza dello storage dei volumi esistenti e applica le nuove funzioni di efficienza dello storage che sfruttano la funzionalità di offload dell'hardware. Si tratta di un processo in background automatico, senza alcun impatto visibile sulle prestazioni del sistema.
+
** Per AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 e AFF C80, ONTAP converte l'efficienza dello storage di tutti i volumi con thin provisioning esistenti, inclusi quelli che non utilizzano l'efficienza dello storage.
** Per un sistema FAS70 e FAS90, ONTAP converte solo l'efficienza dello storage dei volumi con thin provisioning esistenti che hanno ottenuto l'efficienza dello storage prima dell'upgrade.
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Scopri di più sull'efficienza dello storage"^].



* Le procedure di aggiornamento dell'hardware sono state semplificate in ONTAP 9.8 con l'introduzione della funzione di posizionamento automatico delle porte.


====
* I nodi originali e nuovi sono compatibili e supportati.
* I nodi originali e nuovi eseguono ONTAP 9,0 o versioni successive. Quando possibile, NetApp consiglia di utilizzare la stessa versione di ONTAP sui nodi originale e sui nodi nuovi.
+
Se l'upgrade del controller include versioni miste di ONTAP, vedere https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["Cluster ONTAP a versione mista"^] per ulteriori informazioni.

* Si stanno riutilizzando gli indirizzi IP, le maschere di rete e i gateway dei nodi originali sui nuovi nodi.
* Si prevede di aggiornare l'hardware del controller spostando lo storage o spostando i volumi.
* Siete pronti a eseguire una procedura di interruzione se state eseguendo l'upgrade spostando lo storage.
+
L'aggiornamento mediante lo spostamento dei volumi non comporta interruzioni.

* Si prevede di convertire un nodo di un modello supportato in uno shelf di dischi, quindi di collegarlo ai nuovi nodi.


Se si sta aggiornando una configurazione MetroCluster, consultare la sezione https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Aggiornare, aggiornare o espandere la configurazione di MetroCluster"^].

.Informazioni correlate
* link:upgrade_aff_a250_to_aff_a400_ndu_upgrade_workflow.html["Convertire AFF A250 in drive shelf e aggiornare ad AFF A400"](procedura non distruttiva)
* link:convert-fas2820-to-drive-shelf.html["Aggiornamento da FAS2820 convertendolo in un ripiano di unità"](procedura non distruttiva)
* link:upgrade-considerations.html["Considerazioni per l'aggiornamento dell'hardware del controller"]
* link:../choose_controller_upgrade_procedure.html["Scegliere i metodi per aggiornare l'hardware del controller"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Dove trovare le procedure per le attività di manutenzione di MetroCluster"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

