---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: È necessario riassegnare i dischi appartenenti a node1 e node2 rispettivamente a node3 e node4. 
---
= Collegare shelf di storage e riassegnare la proprietà del disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario riassegnare i dischi appartenenti a node1 e node2 rispettivamente a node3 e node4.

.A proposito di questa attività
Esegui i passaggi di questa sezione su node3 e node4. Completa ogni passaggio prima su node3 e poi su node4, prima di passare al passaggio successivo.

[[reassign-spare-disks-step1]]
.Fasi
. Collega i cavi degli shelf di storage dagli shelf che erano precedentemente collegati:
+
** Collega i cavi di node1 a node3
** Collega i cavi di node2 a node4.
+

CAUTION: Non collegare nuovi ripiani al nodo3 o al nodo4 durante questa procedura di aggiornamento. Puoi collegare nuovi ripiani al sistema senza interruzioni dopo aver completato l'aggiornamento del controller.



. Verificare l'alimentazione e la connettività fisica degli shelf.
. Dal prompt DEL CARICATORE node3, avviare in modalità manutenzione:
+
`boot_ontap maint`

. Visualizza l'ID di sistema del nodo 3:
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Registra l'ID di sistema del nodo3 da utilizzare in <<reassign-disks-and-aggregates,Fase 5>>.

. [[reassign-disks-and-aggregates]]Riassegna i dischi e gli aggregati di dati:
+
[role="tabbed-block"]
====
.Riassegna al nodo3
--
Riassegna al nodo 3 i dischi di riserva del nodo1, i dischi appartenenti all'aggregato root e tutti gli aggregati di dati:

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** Il parametro  `node1_sysid` è il valore che hai registrato in _Arresto dei nodi originali_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Fase 5"].
** Specifica il parametro  `-p <node2_sysid>` solo quando sono presenti dischi condivisi.


--
.Riassegna al nodo4
--
Riassegna al nodo 4 i dischi di riserva del nodo2, i dischi appartenenti all'aggregato root e tutti gli aggregati di dati:

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** Il parametro `node2_sysid` è il valore che hai registrato in _Arresto dei nodi originali_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Fase 5"].
** Specifica il parametro  `-p <node3_sysid>` solo quando sono presenti dischi condivisi.


--
====
+
Il sistema visualizza un messaggio simile al seguente:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Invio `y` per continuare.
+
Il sistema visualizza un messaggio simile al seguente:

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Invio `y` per continuare.
. Verificare che l'aggregato root di node1 sia impostato su `root` nel campo delle opzioni e che altri aggregati sono online:
+
`aggr status`

+
L'output dovrebbe essere simile a quanto segue:

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]Esci dalla modalità di manutenzione:
+
`halt`

. Ripeti <<reassign-spare-disks-step1,Fase 1>> su <<reassign-spare-disks-step9,Fase 9>> nodo4.


.Quali sono le prossime novità?
Dopo aver collegato i ripiani di archiviazione e riassegnato la proprietà del disco, link:upgrade-restore-root-volume-config.html["ripristina la configurazione del volume root"].
