---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configura e gestisci la crittografia dello storage, gestisci le chiavi di autenticazione e metti in pausa le relazioni SnapMirror durante l"aggiornamento ai controller introdotti in ONTAP 9.15.1 o versioni successive utilizzando il comando  `system controller replace`.' 
---
= Completare i preparativi per l'aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri le licenze ONTAP e la gestione della Storage Encryption tramite Onboard Key Manager (OKM). Facoltativamente, sospendi le relazioni SnapMirror.



[[learn-about-ontap-licensing]]
== Scopri le licenze ONTAP

Per informazioni dettagliate sulle licenze ONTAP, fare riferimento a https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gestione delle licenze"^].


NOTE: L'utilizzo di funzioni senza licenza sul controller potrebbe mettere fuori conformità con il contratto di licenza.



[[manage-storage-encryption-using-the-onboard-key-manager]]
[[manage_storage_encryption_using_okm]]
== Gestire la crittografia dello storage utilizzando Onboard Key Manager

Utilizzate l'Onboard Key Manager (OKM) per gestire le chiavi di crittografia. Se avete configurato l'OKM, dovete annotare la passphrase e il materiale di backup prima di iniziare l'aggiornamento.

.Fasi
. Registrare la passphrase del cluster.
+
Si tratta della passphrase immessa quando l'OKM è stato configurato o aggiornato utilizzando l'API CLI o REST.

. Verifica la passphrase e il funzionamento del key-manager:
+
`security key-manager onboard sync`

+
Quando richiesto, inserisci la passphrase OKM a livello di cluster che hai registrato nel passaggio precedente.

. Verifica che cc-mode sia abilitato controllando l'output del seguente comando:
+
`security key-manager config show`

. Eseguire il backup delle informazioni del key-manager:
+
`security key-manager onboard show-backup`





[[optionally-quiesce-the-snapmirror-relationships]]
== Facoltativamente, mettere in quiescenza le relazioni SnapMirror

Prima di continuare con la procedura, è necessario confermare che tutte le relazioni di SnapMirror siano interrotti. Quando una relazione SnapMirror viene ritirata, rimane irreparata in caso di riavvii e failover.

.Fasi
. Verificare lo stato della relazione SnapMirror sul cluster di destinazione:
+
`snapmirror show`

+
[NOTE]
====
Se lo stato è "trasferimento", è necessario interrompere questi trasferimenti:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'interruzione non riesce se la relazione SnapMirror non si trova nello stato di "trasferimento".

. Interrompere tutte le relazioni tra il cluster:
+
`snapmirror quiesce -destination-vserver *`



.Quali sono le prossime novità?
Dopo aver preparato l'aggiornamento, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["spostare gli aggregati non root e i LIF di dati NAS di proprietà del node1 al node2"].
