---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decidi se utilizzare ARL per aggiornare i controller che eseguono ONTAP 9.15.1 o versioni successive utilizzando `system controller replace` i comandi.' 
---
= Decidere se utilizzare questa procedura di ricollocazione aggregata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esistono diversi metodi di rilocazione aggregata (ARL) per l'aggiornamento dell'hardware dei controller. Questa procedura ARL descrive come aggiornare una coppia di controller HA nei sistemi di storage AFF e FAS introdotti in ONTAP 9.15.1 o versioni successive con nuovi controller, mantenendo i dati e i dischi esistenti. Si tratta di una procedura complessa che dovrebbe essere utilizzata solo da amministratori ONTAP esperti.

Per aiutarti a decidere se questa procedura ARL è adatta all'aggiornamento hardware del tuo controller, dovresti esaminare tutte le seguenti circostanze per gli aggiornamenti supportati e non supportati.



== Aggiornamenti supportati per questa procedura ARL

È possibile utilizzare questa procedura ARL per aggiornare una coppia di nodi nelle seguenti circostanze:

* Sul computer è in esecuzione ONTAP 9.15.1 o versione successiva.
* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando la procedura di spostamento del volume.
* Si è esperti nell'amministrazione di ONTAP e si è soddisfatti dei rischi di lavorare in modalità privilegi diagnostici.
* La combinazione di aggiornamento hardware è elencata in <<sys_commands_9151_supported_systems,matrice modello supportata>> .



NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).



== Aggiornamenti non supportati per questa procedura ARL

Non è possibile utilizzare questa procedura ARL per aggiornare una coppia di nodi nelle seguenti circostanze:

* Si sta eseguendo uno dei seguenti aggiornamenti:
+
|===
| Controller esistente | Controller sostitutivo 


| AFF A250 | AFF A50, AFF A30 


| AFF A800 | AFF A70, AFF A90 


| AFF C250 | AFF C30, AFF C60 


| AFF C800 | AFF C80 
|===
+
Per eseguire l'aggiornamento di un aggiornamento elencato nella tabella precedente, vedere il link:other_references.html["Riferimenti"]collegamento ai comandi _Use "System controller replace" (utilizza comandi di sostituzione del controller di sistema) per aggiornare i modelli di controller nello stesso chassis_.

* Si sta aggiornando una configurazione MetroCluster FC o IP. Per aggiornare una configurazione MetroCluster, consultare il link:other_references.html["Riferimenti"] collegamento alla _documentazione di aggiornamento ed espansione MetroCluster_.




== Combinazioni di aggiornamento del sistema supportate

La tabella seguente mostra le combinazioni di aggiornamento del controller supportate tramite ARL per i sistemi AFF e FAS introdotti in ONTAP 9.15.1 o versioni successive. Se la combinazione di aggiornamento del controller non è elencata, contattare l'assistenza tecnica.

|===
| Controller esistente | Controller sostitutivo | Supportato a partire da ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220, AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1P3 per FAS70, FAS90 9.16.1P2 per FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ per eseguire l'aggiornamento a AFF A20, è necessario prima convertire un AFF A150 o AFF A220 in uno shelf DS224C sostituendo il modulo controller con un modulo IOM12. Vedere link:../upgrade/upgrade-convert-node-to-shelf.html["Convertire un nodo originale in uno shelf di dischi"].

^2^ AFF A20, AFF A50, AFF A70 e AFF A90 sono sistemi integrati con due controller in una configurazione ha e dischi integrati in un unico chassis:

* Se si sta eseguendo l'aggiornamento a AFF A20, AFF A50, AFF A70 o AFF A90 con unità interne, è necessario rimuovere la proprietà di queste unità interne prima di eseguire l'aggiornamento. Dopo aver completato l'upgrade, puoi assegnare i dischi interni ai nodi AFF A20, AFF A50, AFF A70 o AFF A90 e utilizzarli per creare aggregati di dati. Non è necessario migrare aggregati root o di dati su dischi interni.
* Se si esegue l'aggiornamento a un AFF A20, AFF A50, AFF A70 o AFF A90 senza unità interne, non è necessario assegnare unità interne al termine dell'aggiornamento.




== Scegli una procedura di aggiornamento hardware diversa

* link:../upgrade-arl/index.html["Esaminare i metodi ARL alternativi disponibili per l'aggiornamento dell'hardware del controller"].
* Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.


.Informazioni correlate
Fare riferimento a link:other_references.html["Riferimenti"] per collegarsi alla _Documentazione ONTAP 9_.
