---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decidi se utilizzare ARL per aggiornare i controller che eseguono ONTAP 9.15.1 o versioni successive utilizzando `system controller replace` i comandi.' 
---
= Decidere se utilizzare la procedura di trasferimento degli aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa procedura descrive come aggiornare gli storage controller in una coppia ha con nuovi controller, mantenendo al contempo dati e dischi esistenti. Si tratta di una procedura complessa che deve essere utilizzata solo da amministratori esperti.



== Aggiornamenti supportati per ARL

È possibile aggiornare una coppia di nodi nelle seguenti circostanze:

* Sul computer è in esecuzione ONTAP 9.15.1 o versione successiva.
* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando la procedura di spostamento del volume.
* Si è esperti nell'amministrazione di ONTAP e si è soddisfatti dei rischi di lavorare in modalità privilegi diagnostici.



NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).

[[sys_command_9151_supported_Systems]]la tabella seguente mostra la matrice di modelli supportata per l'aggiornamento del controller.

|===
| Controller esistente | Controller sostitutivo | Supportato a partire da ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220, AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1P3 per FAS70, FAS90 9.16.1P2 per FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ per eseguire l'aggiornamento a AFF A20, è necessario prima convertire un AFF A150 o AFF A220 in uno shelf DS224C sostituendo il modulo controller con un modulo IOM12. Vedere link:../upgrade/upgrade-convert-node-to-shelf.html["Convertire un nodo originale in uno shelf di dischi"].

^2^ AFF A20, AFF A50, AFF A70 e AFF A90 sono sistemi integrati con due controller in una configurazione ha e dischi integrati in un unico chassis:

* Se si sta eseguendo l'aggiornamento a AFF A20, AFF A50, AFF A70 o AFF A90 con unità interne, è necessario rimuovere la proprietà di queste unità interne prima di eseguire l'aggiornamento. Dopo aver completato l'upgrade, puoi assegnare i dischi interni ai nodi AFF A20, AFF A50, AFF A70 o AFF A90 e utilizzarli per creare aggregati di dati. Non è necessario migrare aggregati root o di dati su dischi interni.
* Se si esegue l'aggiornamento a un AFF A20, AFF A50, AFF A70 o AFF A90 senza unità interne, non è necessario assegnare unità interne al termine dell'aggiornamento.


Se la combinazione di modelli di upgrade del controller non è riportata nella tabella precedente, contattare il supporto tecnico.



== Aggiornamenti non supportati per ARL

Non è possibile eseguire aggiornamenti utilizzando ARL nelle seguenti circostanze:

* Si sta eseguendo uno dei seguenti aggiornamenti:
+
|===
| Controller esistente | Controller sostitutivo 


| AFF A250 | AFF A50, AFF A30 


| AFF A800 | AFF A70, AFF A90 


| AFF C250 | AFF C30, AFF C60 


| AFF C800 | AFF C80 
|===
+
Per eseguire l'aggiornamento di un aggiornamento elencato nella tabella precedente, vedere il link:other_references.html["Riferimenti"]collegamento ai comandi _Use "System controller replace" (utilizza comandi di sostituzione del controller di sistema) per aggiornare i modelli di controller nello stesso chassis_.

* Si sta aggiornando un sistema V-Series o un sistema di storage di virtualizzazione FlexArray utilizzando un array esterno per lo storage backend. Contattare il supporto tecnico per opzioni di aggiornamento di un sistema V-series o FlexArray.
* Si sta aggiornando una configurazione MetroCluster FC o IP. Per aggiornare una configurazione MetroCluster, consultare il link:other_references.html["Riferimenti"] collegamento alla _documentazione di aggiornamento ed espansione MetroCluster_.


Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

.Informazioni correlate
Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento al _Centro documentazione di ONTAP 9_ da cui è possibile accedere alla documentazione del prodotto ONTAP 9.
