---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decidi se utilizzare ARL per aggiornare i controller che eseguono ONTAP 9.15.1 o versioni successive utilizzando `system controller replace` i comandi.' 
---
= Decidere se utilizzare la procedura di trasferimento degli aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa procedura descrive come aggiornare gli storage controller in una coppia ha con nuovi controller, mantenendo al contempo dati e dischi esistenti. Si tratta di una procedura complessa che deve essere utilizzata solo da amministratori esperti.

È possibile utilizzare questa procedura nelle seguenti circostanze:

* Si sta eseguendo ONTAP 9.15.1 o versione successiva.
* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando la procedura di spostamento dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è a proprio agio con i rischi di lavorare in modalità diagnostica con privilegi.



NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).

Non è possibile utilizzare questa procedura nelle seguenti circostanze:

* Si sta eseguendo l'aggiornamento di AFF A800 a AFF A70 o AFF A90. Per eseguire questo aggiornamento di AFF A800, vedere link:other_references.html["Riferimenti"] il collegamento ai comandi _Use "System controller replace" (utilizza comando di sostituzione del controller di sistema) per aggiornare i modelli di controller nello stesso chassis_.
* Si sta aggiornando un sistema V-Series o un sistema di storage di virtualizzazione FlexArray utilizzando un array esterno per lo storage backend. Contattare il supporto tecnico per opzioni di aggiornamento di un sistema V-series o FlexArray.
* Si sta aggiornando una configurazione MetroCluster FC o IP. Per aggiornare una configurazione MetroCluster, consultare il link:other_references.html["Riferimenti"] collegamento alla _documentazione di aggiornamento ed espansione MetroCluster_.


[[sys_command_9151_supported_Systems]]la tabella seguente mostra la matrice di modelli supportata per l'aggiornamento del controller.

|===
| Controller esistente | Controller sostitutivo | Supportato a partire da ONTAP... 


| FAS8200, FAS8300, FAS8700, FAS9000 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90, AFF A1K | 9.15.1 
|===
[NOTE]
====
AFF A70 e AFF A90 sono sistemi integrati con due dischi integrati e due controller in un singolo chassis.

* Se si sta eseguendo l'aggiornamento a un AFF A70 o a un AFF A90 con unità interne, è necessario rimuovere la proprietà di queste unità prima di eseguire l'aggiornamento. Dopo aver completato l'upgrade, puoi assegnare i dischi interni ai nodi AFF A70 o AFF A90 e utilizzarli per creare aggregati di dati. Non è obbligatorio migrare aggregati root o dati su dischi interni.
* Se si esegue l'aggiornamento a un AFF A70 o a un AFF A90 senza unità interne, non è necessario assegnare unità interne al termine dell'aggiornamento.


Se la combinazione di modelli di upgrade del controller non è riportata nella tabella precedente, contattare il supporto tecnico.

====
Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento al _Centro documentazione di ONTAP 9_ da cui è possibile accedere alla documentazione del prodotto ONTAP 9.
