---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Scopri se puoi eseguire l"aggiornamento ai controller introdotti in ONTAP 9.15.1 o versioni successive utilizzando i comandi  `system controller replace`.' 
---
= Linee guida per l'aggiornamento dei controller con ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per capire se puoi usare ARL per aggiornare a una coppia di controller introdotti in ONTAP 9.15.1 o versioni successive, dipende dalla piattaforma e dalla configurazione sia dei controller originali che di quelli sostitutivi.



[[supported-upgrades-for-arl]]
== Aggiornamenti supportati per ARL

Prima di aggiornare una coppia di nodi utilizzando questa procedura ARL, esaminare i seguenti requisiti per assicurarsi che la configurazione sia supportata:

* Verificare che l'ARL possa essere eseguito sulle unità di controllo originali e sostitutive.
* Verifica la dimensione di tutti gli aggregati definiti e il numero di dischi supportati dal sistema originale. Poi confronta la dimensione dell'aggregato e il numero di dischi supportati con la dimensione dell'aggregato e il numero di dischi supportati dal nuovo sistema. Consulta link:other-references.html["Riferimenti"] per il link a _Hardware Universe_ dove sono disponibili queste informazioni. La dimensione dell'aggregato e il numero di dischi supportati dal nuovo sistema devono essere uguali o superiori alla dimensione dell'aggregato e al numero di dischi supportati dal sistema originale.
* Verifica nelle regole di miscelazione del cluster se i nuovi nodi possono entrare a far parte del cluster con i nodi esistenti quando il controller originale viene sostituito. Per ulteriori informazioni sulle regole di miscelazione del cluster, consulta link:other-references.html["Riferimenti"] per il collegamento a _Hardware Universe_.
* Migra e sposta nuovamente le LIF del cluster in due porte del cluster per nodo, se disponi di un sistema, ad esempio AFF 700, con la seguente configurazione:
* Più di due porte cluster per nodo
* Una scheda di interconnessione in cluster in slot4 in modalità breakout per creare porte e4a, e4b, e4c e E4D, e porte E4E, e4f, e4g e e4h
+

NOTE: L'aggiornamento del controller con più di due porte del cluster per nodo potrebbe causare la mancanza di LIF del cluster sul nuovo controller in seguito all'upgrade.

+
Per ulteriori informazioni, vedere l'articolo della Knowledge base link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Come eliminare LIF del cluster indesiderate o non necessarie"^].



L'upgrade del controller tramite ARL è supportato sui sistemi configurati con volumi di conformità SnapLock Enterprise e SnapLock.



[[two-node-switchless-clusters]]
== Cluster senza switch a due nodi

Se si stanno aggiornando i nodi in un cluster senza switch a due nodi, è possibile lasciare i nodi nel cluster senza switch durante l'aggiornamento. Non è necessario convertirli in un cluster con switch.



[[upgrades-not-supported-for-arl]]
== Aggiornamenti non supportati per ARL

Non puoi aggiornare i controller sostitutivi che non supportano gli shelf di dischi collegati ai controller originali.

Fai riferimento a link:other-references.html["Riferimenti"] per collegarti a _Hardware Universe_ per informazioni sul supporto dei dischi.

Se vuoi aggiornare i controller di livello base con unità interne, fai riferimento a link:other-references.html["Riferimenti"] _Upgrade by moving volumes or storage_ e vai alla procedura _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_.



[[troubleshoot]]
== Risolvere i problemi

Se si verificano problemi durante l'aggiornamento dei controller, vederelink:aggregate_relocation_failures.html["Risolvere i problemi"] per maggiori informazioni e possibili soluzioni.

Se non si riesce a trovare una soluzione al problema riscontrato, contattare il supporto tecnico.

.Quali sono le prossime novità?
Dopo aver esaminato le linee guida per l'aggiornamento dei controller con ARL, link:overview_of_the_arl_upgrade.html["Scopri la sequenza di aggiornamento ARL"].
