---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/manage-authentication-using-kmip-servers.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configura e gestisci la crittografia dello storage, gestisci le chiavi di autenticazione e metti in pausa le relazioni SnapMirror durante l"aggiornamento ai controller introdotti in ONTAP 9.15.1 o versioni successive utilizzando il comando  `system controller replace`.' 
---
= Gestire l'autenticazione utilizzando i server KMIP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare i server KMIP (Key Management Interoperability Protocol) per gestire le chiavi di autenticazione.

.Fasi
. Aggiungere un nuovo controller:
+
`security key-manager external enable`

. Aggiungere il gestore delle chiavi:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Verificare che i server di gestione delle chiavi siano configurati e disponibili per tutti i nodi del cluster:
+
`security key-manager external show-status`

. Ripristinare le chiavi di autenticazione da tutti i server di gestione delle chiavi collegati al nuovo nodo:
+
`security key-manager external restore -node _new_controller_name_`



.Quali sono le prossime novità?
Dopo aver gestito l'autenticazione tramite server KMIP, link:ensure_new_controllers_are_set_up_correctly.html["confermare che i nuovi controller siano configurati correttamente"].
