---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 'Comprendere come funziona la procedura per aggiornare i controller su cui è in esecuzione ONTAP 9.15.1 o versioni successive utilizzando `system controller replace` i comandi.' 
---
= Panoramica dell'aggiornamento ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare i nodi utilizzando ARL, è necessario comprendere il funzionamento della procedura. In questo contenuto, la procedura viene suddivisa in diverse fasi.



== Aggiornare la coppia di nodi

Per aggiornare la coppia di nodi, è necessario preparare i nodi originali ed eseguire una serie di passaggi sia sul nodo originale che su quello nuovo. È quindi possibile decommissionare i nodi originali.



== Panoramica della sequenza di aggiornamento ARL

Durante la procedura, si aggiorna l'hardware del controller originale con l'hardware del controller sostitutivo, un controller alla volta, sfruttando la configurazione della coppia ha per trasferire la proprietà degli aggregati non root. Tutti gli aggregati non root devono essere sottoposti a due rilocazioni per raggiungere la destinazione finale, che è il nodo aggiornato corretto.

Ogni aggregato ha un proprietario di casa e un proprietario corrente. Il proprietario della casa è il proprietario effettivo dell'aggregato e il proprietario attuale è il proprietario temporaneo.

La seguente tabella descrive le attività di alto livello eseguite durante ciascuna fase e lo stato di proprietà aggregata alla fine della fase. Le fasi dettagliate vengono fornite più avanti nella procedura:

[cols="35,65"]
|===
| Fase | Descrizione 


| link:stage_1_index.html["Fase 1. Preparatevi per l'aggiornamento"]  a| 
Durante la fase 1, vengono eseguiti controlli preliminari e, se necessario, vengono corretti i diritti di proprietà degli aggregati. È necessario registrare alcune informazioni se si gestisce la crittografia dello storage utilizzando OKM e si può scegliere di interrompere le relazioni di SnapMirror.

Proprietà aggregata alla fine della fase 1:

* Node1 è il proprietario della casa e l'attuale proprietario degli aggregati node1.
* Node2 è il proprietario domestico e proprietario corrente degli aggregati node2.




| link:stage_2_index.html["Fase 2. Spostare e dismettere il node1"]  a| 
Durante la fase 2, è possibile spostare gli aggregati non root node1 e le LIF dei dati NAS in node2. Questo processo è in gran parte automatizzato; l'operazione viene interrotta per consentirti di controllarne lo stato. È necessario riprendere manualmente l'operazione. Se necessario, spostare gli aggregati non riusciti o vetoed. Prima di ritirare il node1, si registrano le informazioni node1 da utilizzare in seguito nella procedura. Puoi anche prepararti a netboot node3 e node4 più avanti nella procedura.

Proprietà aggregata alla fine della fase 2:

* Node2 è l'attuale proprietario degli aggregati node1.
* Node2 è il proprietario domestico e proprietario corrente degli aggregati node2.




| link:stage_3_index.html["Fase 3. Installazione e boot node3"]  a| 
Durante la fase 3, si installa e si avvia node3, si controlla che il cluster e le porte di gestione dei nodi da node1 siano online sul node3 e si verifica l'installazione node3. Se si utilizza NetApp Volume Encryption (NVE), viene ripristinata la configurazione del gestore delle chiavi. È inoltre possibile spostare le LIF dei dati NAS node1 e gli aggregati non root da node2 a node3 e verificare che le LIF SAN esistano sul node3.

Proprietà aggregata alla fine della fase 3:

* Node3 è il proprietario della casa e il proprietario corrente degli aggregati node1.
* Node2 è il proprietario domestico e proprietario corrente degli aggregati node2.




| link:stage_4_index.html["Fase 4. Spostare e dismettere il node2"]  a| 
Durante la fase 4, è possibile spostare aggregati non root e LIF dati NAS da node2 a node3. Inoltre, prima di ritirarlo, è possibile registrare le informazioni relative al nodo 2 da utilizzare in seguito nella procedura.

Proprietà aggregata alla fine della fase 4:

* Node3 è il proprietario della casa e l'attuale proprietario di aggregati che originariamente appartenevano al node1.
* Node2 è il proprietario domestico degli aggregati node2.
* Node3 è l'attuale proprietario degli aggregati node2.




| link:stage_5_index.html["Fase 5. Installazione e boot node4"]  a| 
Durante la fase 5, si installa e si avvia node4, si controlla che il cluster e le porte di gestione dei nodi da node2 siano online sul node4 e si verifica l'installazione node4. Se si utilizza NVE, si ripristina la configurazione del gestore delle chiavi. È inoltre possibile spostare le LIF dei dati NAS node2 e gli aggregati non root da node3 a node4 e verificare che le LIF SAN esistano sul node4.

Proprietà aggregata alla fine della fase 5:

* Node3 è il proprietario di casa e l'attuale proprietario degli aggregati che originariamente appartenevano al node1.
* Node4 è il proprietario della casa e l'attuale proprietario di aggregati che originariamente appartenevano al node2.




| link:stage_6_index.html["Fase 6. Completare l'aggiornamento"]  a| 
Durante la fase 6, si conferma che i nuovi nodi sono impostati correttamente e, se i nuovi nodi sono abilitati per la crittografia, si configura e imposta Storage Encryption o NVE. È inoltre necessario decommissionare i vecchi nodi e riprendere le operazioni di SnapMirror.

|===