---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: 'Fase 6 sequenza di processo per un aggiornamento ARL utilizzando i `system controller replace` comandi sui controller che eseguono ONTAP 9.15.1 o versione successiva.' 
---
= Panoramica della fase 6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 6, confermi che i nuovi nodi sono impostati correttamente e, se i nuovi nodi sono abilitati per la crittografia, configuri e configuri Storage Encryption o NetApp Volume Encryption. È inoltre necessario decommissionare i vecchi nodi e riprendere le operazioni di SnapMirror.

.Fasi
. link:manage-authentication-using-kmip-servers.html["Gestire l'autenticazione utilizzando i server KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Verificare che i nuovi controller siano impostati correttamente"]
. link:set_up_storage_encryption_new_module.html["Impostare Storage Encryption sul nuovo modulo controller"]
. link:set_up_netapp_volume_encryption_new_module.html["Impostare NetApp Volume o aggregate Encryption sul nuovo modulo controller"]
. link:decommission_old_system.html["Decommissionare il vecchio sistema"]
. link:resume_snapmirror_operations.html["Riprendere le operazioni di SnapMirror"]


[NOTE]
====
I sistemi AFF A70, AFF A90, AFF A1K, FAS70 e FAS90 condividono le porte di rete 100GbE per le connessioni cluster e ha. Questi sistemi possono supportare connessioni cluster 10GbE o 25GbE a switch cluster legacy; tuttavia, NetApp consiglia di eseguire l'aggiornamento a velocità cluster 100GbE quando gli switch 10GbE e 25GbE non sono più necessari. Per ulteriori informazioni, vedere i seguenti articoli della Knowledge base:

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Configurazione delle porte cluster 10G o 25g in un nuovo setup cluster su AFF/ASA A1K, A90, A70, FAS90, FAS70"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Come convertire un cluster esistente da 10G o 25g porte cluster a 40G o 100g porte cluster in un AFF/ASA A1K, FAS70, A70, FAS90, A90"^]


Se non è possibile collegare e0a o e0b porte cluster sul nodo esistente alle porte cluster sul nuovo nodo, vedere link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID bug online di NetApp CONTAP-166978"^].

====