---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Fase 5 sequenza di processo per un aggiornamento ARL utilizzando i `system controller replace` comandi sui controller che eseguono ONTAP 9.15.1 o versione successiva.' 
---
= Panoramica della fase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 5, si installa e si avvia node4, si controlla che il cluster e le porte di gestione dei nodi da node2 siano online sul node4 e si verifica l'installazione node4. Se si utilizza NVE, si ripristina la configurazione del gestore delle chiavi. È inoltre possibile spostare le LIF dei dati NAS node2 e gli aggregati non root da node3 a node4 e verificare che le LIF SAN esistano sul node4.

.Fasi
. link:install_boot_node4.html["Installazione e boot node4"]
. link:verify_node4_installation.html["Verificare l'installazione di node4"]
. link:restore_key-manager_config_node4.html["Ripristinare la configurazione del gestore delle chiavi sul nodo 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Spostare gli aggregati non root e le LIF di dati NAS di proprietà di node2 da node3 a node4"]

