---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: 'Fase 3 sequenza di processo per un aggiornamento ARL utilizzando i `system controller replace` comandi sui controller che eseguono ONTAP 9.15.1 o versione successiva.' 
---
= Panoramica della fase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 3, si installa e si avvia node3, si controlla che il cluster e le porte di gestione dei nodi da node1 siano online sul node3 e si verifica l'installazione node3. Se si utilizza NetApp Volume Encryption (NVE), viene ripristinata la configurazione del gestore delle chiavi. È inoltre possibile spostare le LIF dei dati NAS node1 e gli aggregati non root da node2 a node3 e verificare che le LIF SAN esistano sul node3.

.Fasi
. link:install_boot_node3.html["Installazione e boot node3"]
. link:verify_node3_installation.html["Verificare l'installazione di node3"]
. link:restore_key-manager_configuration_node3.html["Ripristinare la configurazione del gestore delle chiavi sul node3"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Spostare gli aggregati non root e le LIF di dati NAS di proprietà del node1 da node2 a node3"]

