---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 'Decidere se utilizzare ARL per aggiornare i controller che eseguono ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Decidere se utilizzare questa procedura di ricollocazione aggregata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esistono diversi metodi di ricollocazione aggregata (ARL) per aggiornare l'hardware del controller. Questa procedura descrive come aggiornare l'hardware del controller utilizzando ARL con "comandi di sostituzione del controller di sistema" su sistemi che eseguono ONTAP 9.7, 9.6 o 9.5. Questa complessa procedura dovrebbe essere utilizzata solo da amministratori ONTAP esperti.

Per aiutarti a decidere se questa procedura ARL è adatta all'aggiornamento hardware del tuo controller, dovresti esaminare tutte le seguenti circostanze per gli aggiornamenti supportati:

* Stai aggiornando i controller NetApp che eseguono ONTAP 9.5, 9.6 o 9.7. Questo documento non è applicabile agli aggiornamenti a ONTAP 9.8.
* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è a proprio agio con i rischi di lavorare in modalità diagnostica con privilegi.
* La combinazione di aggiornamento hardware è elencata in <<sys_commands_95_97_supported_systems,matrice modello supportata>> .
* Se si sta aggiornando una configurazione MetroCluster, si tratta di una configurazione FC a 4 nodi o superiore e tutti i nodi eseguono ONTAP 9.6 o 9.7.


[NOTE]
====
* Se si sta aggiornando un sistema scambiando i moduli del controller nello stesso chassis, come AFF A800 o AFF C800, NetApp consiglia vivamente di utilizzare la procedura di aggiornamento chelink:../upgrade-arl-auto-in-chassis/index.html["aggiorna i modelli di controller utilizzando ARL, mantenendo lo chassis e i dischi del sistema esistenti"] .  Questa procedura ARL include i passaggi che garantiscono che i dischi interni rimangano saldamente nello chassis quando si rimuovono e si installano i controller durante la procedura di aggiornamento.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Scopri le combinazioni di aggiornamento del sistema supportate utilizzando ARL, mantenendo lo chassis e i dischi del sistema esistenti"].

* Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).


====


== Combinazioni di aggiornamento del sistema supportate

Le tabelle seguenti mostrano la matrice dei modelli supportati per l'aggiornamento del controller utilizzando questa procedura ARL.

[cols="50,50"]
|===
| Vecchio controller | Controller sostitutivo 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700^1^, AFF A800^2^ 


| FAS8200 | FAS8700, FAS9000, FAS8300^4^^,^ ^5^ 


| AFF A300 | AFF A700^1^, AFF A800^2^^,^ ^3^, AFF A400^4^^,^ ^5^ 
|===

NOTE: Se la combinazione di modelli di upgrade del controller non è riportata nella tabella precedente, contattare il supporto tecnico.

^1^l'aggiornamento automatizzato ARL per il sistema AFF A700 è supportato da ONTAP 9.7P2.

^2^Se si esegue l'aggiornamento a un AFF A800 o a un sistema che supporta dischi interni ed esterni, è necessario seguire istruzioni specifiche per l'aggregazione root sui dischi NVMe interni.  Fare riferimento alink:reassign-node1-disks-to-node3.html#auto_check3_step9["Riassegnare node1 dischi a node3, passaggio 9"] Elink:reassign-node2-disks-to-node4.html#auto_check_4_step9["Riassegnare node2 dischi a node4, passaggio 9"] .

^3^l'aggiornamento automatizzato ARL da un sistema AFF A300 a un sistema AFF A800 è supportato da ONTAP 9.7P5.

^4^ONTAP 9.7P8 supporta l'aggiornamento automatizzato ARL da un sistema AFF A300 a un sistema AFF A400 e FAS8200 a un sistema FAS8300.

^5^se si esegue l'aggiornamento da un sistema AFF A300 a un sistema AFF A400 o FAS8200 a un sistema FAS8300 in una configurazione cluster senza switch a due nodi, è necessario scegliere le porte cluster temporanee per l'aggiornamento del controller. I sistemi AFF A400 e FAS8300 sono disponibili in due configurazioni, come bundle Ethernet in cui le porte della scheda mezzanine sono di tipo Ethernet e come bundle FC in cui le porte mezzanine sono di tipo FC.

* Per un sistema AFF A400 o FAS8300 con configurazione di tipo Ethernet, è possibile utilizzare una qualsiasi delle due porte mezzanine come porte cluster temporanee.
* Per un sistema AFF A400 o FAS8300 con configurazione di tipo FC, è necessario aggiungere una scheda di interfaccia di rete 10GbE a quattro porte (codice X1147A) per fornire porte cluster temporanee.
* Dopo aver completato un aggiornamento del controller utilizzando porte cluster temporanee, è possibile migrare senza interruzioni le LIF del cluster a e3a ed e3b, porte 100GbE su un sistema AFF A400 e porte e0c ed e0d, 100GbE su un sistema FAS8300.




== Scegli una procedura di aggiornamento hardware diversa

* link:../upgrade-arl/index.html["Esaminare i metodi ARL alternativi disponibili per l'aggiornamento dell'hardware del controller"].
* Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.


.Informazioni correlate
Fare riferimento a link:other_references.html["Riferimenti"] per collegarsi alla _Documentazione ONTAP 9_.
