---
sidebar: sidebar 
permalink: upgrade-arl-auto/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'È possibile aggiornare l"hardware del controller con ONTAP 9.5 a 9.7 utilizzando `system controller replace` , riallocando la proprietà di aggregati non root.' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa procedura descrive come aggiornare l'hardware del controller utilizzando ARL (aggregate relocation) per le seguenti configurazioni di sistema:

[cols="40,20,40"]
|===
| Metodo | Versione di ONTAP | Sistemi supportati 


| Utilizzo di `system controller replace` comandi | da 9.5 a 9.7 | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_95_97_supported_systems["Link alla matrice dei sistemi supportati"] 
|===
Durante la procedura, l'hardware del controller originale viene aggiornato con l'hardware del controller sostitutivo, riallocando la proprietà degli aggregati non root. La migrazione degli aggregati viene eseguita più volte da un nodo all'altro per confermare che almeno un nodo fornisce i dati degli aggregati durante l'intera procedura di aggiornamento. Inoltre, è possibile migrare le interfacce logiche dei dati (LIF) e assegnare le porte di rete sul nuovo controller ai gruppi di interfacce durante la procedura.

.Terminologia utilizzata in queste informazioni
In queste informazioni, i nodi originali sono chiamati "node1" e "node2", mentre i nuovi nodi sono chiamati "node3" e "node4". Durante la procedura descritta, "node1" viene sostituito da "node3" e "node2" da "node4".

I termini "node1", "node2", "node3" e "node4" vengono utilizzati solo per distinguere tra i nodi originali e quelli nuovi. Quando si segue la procedura, è necessario sostituire i nomi reali dei nodi originale e nuovo. Tuttavia, in realtà, i nomi dei nodi non cambiano: "Node3" ha lo stesso nome di "node1" e "node4" ha lo stesso nome di "node2" dopo l'aggiornamento dell'hardware del controller.

In queste informazioni, il termine "sistemi con software di virtualizzazione FlexArray" si riferisce ai sistemi che appartengono a queste nuove piattaforme. Il termine "sistema V-Series" si riferisce ai sistemi hardware separati che possono essere collegati agli array di storage.

.Informazioni importanti:
* Questa procedura è complessa e presuppone che si disponga di competenze di amministrazione avanzate di ONTAP. Devi anche leggere e comprendere link:guidelines_for_upgrading_controllers_with_arl.html["Linee guida per l'aggiornamento dei controller con ARL"] e a. link:overview_of_the_arl_upgrade.html["Panoramica dell'aggiornamento ARL"] prima di iniziare l'aggiornamento.
* Questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato. I passaggi necessari per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. Se in precedenza è stato utilizzato l'hardware del controller sostitutivo, è necessario contattare il supporto tecnico, in particolare se i controller eseguivano Data ONTAP in 7-Mode.
* È possibile utilizzare questa procedura per aggiornare l'hardware del controller nei cluster con più di due nodi; tuttavia, è necessario eseguire la procedura separatamente per ogni coppia ha nel cluster.
* Questa procedura si applica ai sistemi FAS, V-Series, AFF e ai sistemi con software di virtualizzazione FlexArray. I sistemi FAS rilasciati dopo ONTAP 9.5 possono essere collegati agli array di storage se viene installata la licenza richiesta. I sistemi V-Series esistenti sono supportati in ONTAP 9.5. Per ulteriori informazioni sui modelli di storage array e V-Series, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_ e accedere alla matrice di supporto V-Series.
* A partire da ONTAP 9.6, questa procedura si applica ai sistemi con configurazione MetroCluster a 4 nodi o superiore. Poiché i siti di configurazione MetroCluster possono trovarsi in due posizioni fisicamente diverse, l'aggiornamento automatizzato del controller deve essere eseguito singolarmente in ciascun sito MetroCluster per una coppia ha.
* Se si sta eseguendo l'aggiornamento da un sistema AFF A320, è possibile utilizzare i movimenti dei volumi per aggiornare l'hardware del controller o contattare il supporto tecnico. Se si desidera spostare il volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

