---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node3.html 
keywords: install, boot, node3 relocation, nodes, V-series, storage disks 
summary: 'Installare e avviare il node3 e installare il software ONTAP quando si aggiornano i controller con ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Installazione e boot node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È necessario installare node3 nel rack, trasferire le connessioni del node1 al node3, fare il boot node3 e installare ONTAP. È quindi necessario riassegnare uno qualsiasi dei dischi spare di node1, tutti i dischi appartenenti al volume root e qualsiasi aggregato non root che non sia stato trasferito in node2 precedentemente nel processo, come descritto in questa sezione.

.A proposito di questa attività
L'operazione di trasferimento viene messa in pausa all'inizio di questa fase. Questo processo è in gran parte automatizzato; l'operazione viene interrotta per consentirti di controllarne lo stato. È necessario riprendere manualmente l'operazione. Inoltre, è necessario verificare che le LIF SAN siano state spostate correttamente in node3.

È necessario eseguire il netboot node3 se non dispone della stessa versione di ONTAP 9 installata sul node1. Dopo aver installato node3, avviarlo dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avviamenti del sistema, seguendo le istruzioni riportate in link:prepare_for_netboot.html["Preparatevi per il netboot"].

.Importante:
* Se stai aggiornando un sistema V-Series connesso a storage array o un sistema con software di virtualizzazione FlexArray connesso a storage array, devi completare la procedura <<auto_install3_step1,Fase 1>> attraverso <<auto_install3_step21,Fase 21>>, quindi uscire da questa sezione e seguire le istruzioni in link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurare le porte FC sul nodo 3"] e. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Controllare e configurare le porte UTA/UTA2 sul nodo 3"] Sezioni secondo necessità, immissione dei comandi in modalità manutenzione. Quindi, tornare a questa sezione e riprendere con <<auto_install3_step23,Fase 23>>.
* Se si sta eseguendo l'aggiornamento di un sistema con dischi di storage, completare l'intera sezione e passare alla link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurare le porte FC sul nodo 3"] e. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Controllare e configurare le porte UTA/UTA2 sul nodo 3"] sezioni, immissione dei comandi al prompt del cluster.


.Fasi
. [[auto_install3_step1]]assicurarsi di disporre di spazio rack per node3.
+
Se node1 e node2 si trovano in uno chassis separato, è possibile inserire node3 nella stessa posizione rack del node1. Tuttavia, se il nodo 1 si trovava nello stesso chassis con il nodo 2, è necessario inserire il nodo 3 nel proprio spazio rack, preferibilmente vicino alla posizione del nodo 1.

. [[auto_install3_step2]]installare node3 nel rack, seguendo le _istruzioni di installazione e configurazione_ per il modello di nodo in uso.
+

NOTE: Se si esegue l'aggiornamento a un sistema con entrambi i nodi nello stesso chassis, installare node4 nello chassis e node3. In caso contrario, quando si avvia node3, il nodo si comporta come se fosse in una configurazione a doppio chassis e quando si avvia node4, l'interconnessione tra i nodi non si verificherà.

. [[auto_install3_step3]]cavo node3, spostamento delle connessioni da node1 a node3.
+
Collegare i seguenti collegamenti utilizzando le _istruzioni di installazione e configurazione_ o i _requisiti di installazione e riferimento per la virtualizzazione FlexArray_ per la piattaforma node3, il documento relativo allo shelf di dischi appropriato e _gestione coppia ha_.

+
Fare riferimento link:other_references.html["Riferimenti"]al collegamento ai _requisiti di installazione e di riferimento per la virtualizzazione FlexArray_ e _gestione coppia ha_.

+
** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI
+

NOTE: Potrebbe non essere necessario spostare la scheda di interconnessione o la connessione del cavo di interconnessione del cluster dal nodo 1 al nodo 3, poiché la maggior parte dei modelli di piattaforma dispone di un modello di scheda di interconnessione unico. Per la configurazione MetroCluster, è necessario spostare le connessioni del cavo FC-VI dal nodo 1 al nodo 3. Se il nuovo host non dispone di una scheda FC-VI, potrebbe essere necessario spostare la scheda FC-VI.



. [[auto_install3_step4]]accendere il computer in node3, quindi interrompere il processo di boot premendo Ctrl-C sul terminale della console per accedere al prompt dell'ambiente di boot.
+
Se si sta eseguendo l'aggiornamento a un sistema con entrambi i nodi nello stesso chassis, anche node4 viene riavviato. Tuttavia, è possibile ignorare il node4 boot fino a tardi.

+

NOTE: Quando si avvia node3, potrebbe essere visualizzato il seguente messaggio di avviso:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]se viene visualizzato il messaggio di avviso in <<auto_install3_step4,Fase 4>>, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio venga completato.
+

WARNING: *Attenzione: Non ignorare il ritardo; il mancato caricamento della batteria potrebbe causare la perdita di dati.*

+

NOTE: Fare riferimento a. link:prepare_for_netboot.html["Preparatevi per il netboot"].





. [[auto9597_istall3_step6]]configurare la connessione di netboot scegliendo una delle seguenti operazioni.
+

NOTE: È necessario utilizzare la porta di gestione e l'IP come connessione di netboot. Non utilizzare un IP LIF dei dati, altrimenti potrebbe verificarsi un'interruzione dei dati durante l'aggiornamento.

+
[cols="30,70"]
|===
| Se DHCP (Dynamic host Configuration Protocol) è... | Quindi... 


| In esecuzione | Configurare la connessione automaticamente immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -auto` 


| Non in esecuzione  a| 
Configurare manualmente la connessione immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` È l'indirizzo IP del sistema di storage (obbligatorio).
`_netmask_` è la maschera di rete del sistema di storage (obbligatoria).
`_gateway_` è il gateway per il sistema storage. (obbligatorio).
`_dns_addr_` È l'indirizzo IP di un name server sulla rete (opzionale).
`_dns_domain_` È il nome di dominio DNS (Domain Name Service). Se si utilizza questo parametro opzionale, non è necessario un nome di dominio completo nell'URL del server netboot; è necessario solo il nome host del server.


NOTE: Potrebbero essere necessari altri parametri per l'interfaccia. Invio `help ifconfig` al prompt del firmware per ulteriori informazioni.

|===
. [[step7]]Esegui netboot al nodo3:
+
[cols="30,70"]
|===
| Per... | Quindi... 


| Sistemi della serie FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Tutti gli altri sistemi | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
Il `<path_to_the_web-accessible_directory>` dovrebbe portare alla posizione in cui è stato scaricato `<ontap_version>_image.tgz` nella sezione link:prepare_for_netboot.html["Preparatevi per il netboot"].

+

NOTE: Non interrompere l'avvio.

. [[step8]]dal menu di boot, selezionare l'opzione `(7) Install new software first`.
+
Questa opzione di menu consente di scaricare e installare la nuova immagine ONTAP sul dispositivo di avvio.

+
Ignorare il seguente messaggio:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota si applica agli aggiornamenti senza interruzioni di ONTAP e non agli aggiornamenti dei controller.

+

NOTE: Utilizzare sempre netboot per aggiornare il nuovo nodo all'immagine desiderata. Se si utilizza un altro metodo per installare l'immagine sul nuovo controller, l'immagine potrebbe non essere corretta. Questo problema riguarda tutte le versioni di ONTAP. La procedura di netboot combinata con l'opzione `(7) Install new software` Consente di cancellare il supporto di avvio e di posizionare la stessa versione di ONTAP su entrambe le partizioni dell'immagine.

. [[step9]]se viene richiesto di continuare la procedura, immettere `y`E quando viene richiesto il pacchetto, immettere l'URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]]completare i seguenti passaggi secondari per riavviare il modulo controller:
+
.. Invio `n` per ignorare il ripristino del backup quando viene visualizzato il seguente prompt:
+
`Do you want to restore the backup configuration now? {y|n}`

.. Invio `y` per riavviare quando viene visualizzato il seguente prompt:
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
Il modulo controller si riavvia ma si arresta al menu di avvio perché il dispositivo di avvio è stato riformattato e i dati di configurazione devono essere ripristinati.



. [[step11]]selezionare la modalità di manutenzione `5` dal menu di boot e premere `y` quando viene richiesto di continuare con l'avvio.
. [[step12]]verificare che il controller e lo chassis siano configurati come ha:
+
`ha-config show`

+
L'esempio seguente mostra l'output di `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Il sistema registra in una PROM sia che si trovi in una coppia ha o in una configurazione standalone. Lo stato deve essere lo stesso su tutti i componenti all'interno del sistema standalone o della coppia ha.

. [[step13]]se il controller e lo chassis non sono configurati come ha, utilizzare i seguenti comandi per correggere la configurazione:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Se si dispone di una configurazione MetroCluster, utilizzare i seguenti comandi per modificare il controller e lo chassis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[step14]]Esci dalla modalità di manutenzione:
+
`halt`

+
Interrompere L'OPERAZIONE premendo Ctrl-C al prompt dell'ambiente di avvio.

. [[step15]]al nodo 2, controllare la data, l'ora e il fuso orario del sistema:
+
`date`

. [[step16]]al nodo 3, controllare la data utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show date`

. [[step17]]se necessario, impostare la data sul node3:
+
`set date _mm/dd/yyyy_`

. [[step18]]al nodo 3, controllare l'ora utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show time`

. [[step19]]se necessario, impostare l'ora su node3:
+
`set time _hh:mm:ss_`

. [[step20]]nel boot loader, impostare l'ID del sistema partner su node3:
+
`setenv partner-sysid _node2_sysid_`

+
Per il nodo 3, `partner-sysid` deve essere quello del node2.

+
.. Salvare le impostazioni:
+
`saveenv`



. [[auto_install3_step21]]verificare `partner-sysid` per il nodo 3:
+
`printenv partner-sysid`

. [[step22]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se il sistema... | Descrizione 


| Dispone di dischi e non di storage back-end | Passare a. <<auto_install3_step23,Fase 23>> 


| È un sistema V-Series o un sistema con software di virtualizzazione FlexArray collegato agli array di storage  a| 
.. Vai alla sezione link:set_fc_or_uta_uta2_config_on_node3.html["Impostazione della configurazione FC o UTA/UTA2 su node3"] e completare le sottosezioni di questa sezione.
.. Tornare a questa sezione e completare i passaggi rimanenti, iniziando da <<auto_install3_step23,Fase 23>>.



IMPORTANT: È necessario riconfigurare le porte FC onboard, le porte CNA onboard e le schede CNA prima di avviare ONTAP su V-Series o sul sistema con il software di virtualizzazione FlexArray.

|===
. [[auto_install3_step23]]aggiungere le porte FC Initiator del nuovo nodo alle zone di switch.
+
Se il sistema dispone di UNA SAN a nastro, è necessario eseguire lo zoning per gli iniziatori. Se necessario, modificare le porte integrate in Initiator facendo riferimento a. link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurazione delle porte FC sul nodo 3"]. Per ulteriori informazioni sullo zoning, consultare la documentazione relativa allo storage array e allo zoning.

. [[step24]]aggiungere le porte FC Initiator all'array di storage come nuovi host, mappando le LUN dell'array ai nuovi host.
+
Per istruzioni, consultare la documentazione relativa allo storage array e allo zoning.

. [[step25]]modificare i valori WWPN (Worldwide port name) nei gruppi di host o di volumi associati alle LUN degli array sullo storage array.
+
L'installazione di un nuovo modulo controller modifica i valori WWPN associati a ciascuna porta FC integrata.

. [[step26]]se la configurazione utilizza lo zoning basato su switch, regolare lo zoning in modo che rifletta i nuovi valori WWPN.


. Se si dispone di unità NetApp Storage Encryption (NSE) installate, attenersi alla seguente procedura.
+

NOTE: Se la procedura non è stata ancora eseguita, consultare l'articolo della Knowledge base https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Come verificare se un disco è certificato FIPS"^] per determinare il tipo di unità con crittografia automatica in uso.

+
.. Impostare `bootarg.storageencryption.support` a. `true` oppure `false`:
+
[cols="35,65"]
|===
| Se i seguenti dischi sono in uso… | Quindi… 


| Unità NSE conformi ai requisiti di crittografia automatica FIPS 140-2 livello 2 | `setenv bootarg.storageencryption.support *true*` 


| SED non FIPS di NetApp | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Non è possibile combinare dischi FIPS con altri tipi di dischi sullo stesso nodo o coppia ha. È possibile combinare SED con dischi non crittografanti sullo stesso nodo o coppia ha.

====
.. Contattare il supporto NetApp per assistenza nel ripristino delle informazioni di gestione delle chiavi integrate.


. Nodo di boot nel menu di boot:
+
`boot_ontap menu`

+
Se non si dispone di una configurazione FC o UTA/UTA2, eseguire la procedura link:set_fc_or_uta_uta2_config_node4.html#auto_check_4_step15["Controllare e configurare le porte UTA/UTA2 sul nodo 4, passaggio 15"] in modo che il node4 possa riconoscere i dischi del node2.

. [[auto9597_istall3_step29]]per una configurazione MetroCluster, sistemi V-Series e sistemi con software di virtualizzazione FlexArray collegati agli array di storage, visitare il sito link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["Controllare e configurare le porte UTA/UTA2 sul nodo 3, passaggio 15"].

