---
sidebar: sidebar 
permalink: upgrade-arl-auto/join_quorum_node_has_different_ports_stage3.html 
keywords: aggregate, relocation, quorum, network, ports 
summary: 'Durante la fase 3, verificare che il nuovo nodo si unisca al quorum quando si aggiornano i controller che eseguono ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Unirsi al quorum quando un nodo dispone di un set diverso di porte di rete
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il nodo con il nuovo controller si avvia e tenta di connettersi automaticamente al cluster; tuttavia, se il nuovo nodo dispone di un set diverso di porte di rete, è necessario eseguire i seguenti passaggi per confermare che il nodo si connette correttamente al quorum.

.A proposito di questa attività
È possibile utilizzare queste istruzioni per qualsiasi nodo pertinente. Node3 viene utilizzato per l'intero campione seguente.

.Fasi
. Verificare che le nuove porte del cluster si trovino nel dominio di trasmissione del cluster immettendo il seguente comando e verificandone l'output:
+
`network port show -node node -port port -fields broadcast-domain`

+
L'esempio seguente mostra che la porta "e1a" si trova nel dominio del cluster sul nodo 3:

+
[listing]
----
cluster::> network port show -node node3 -port e1a -fields broadcast-domain
node   port broadcast-domain
------ ---- ----------------
node3  e1a  Cluster
----
. Aggiungere le porte corrette al dominio di trasmissione del cluster immettendo il seguente comando e controllandone l'output:
+
`network port modify -node -port -ipspace Cluster -mtu 9000`

+
Questo esempio aggiunge la porta cluster "e1b" al nodo 3:

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
. Migrare le LIF del cluster alle nuove porte, una volta per ciascuna LIF, utilizzando il seguente comando:
+
`network interface migrate -vserver Cluster -lif _lif_name_ -source-node node3 - destination-node node3 -destination-port _port_name_`

. Modificare la porta home delle LIF del cluster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

. Se le porte del cluster non si trovano nel dominio di broadcast del cluster, aggiungerle utilizzando il seguente comando:
+
`network port broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster - ports node:port`

. Rimuovere le vecchie porte dal dominio di trasmissione del cluster. È possibile utilizzare per qualsiasi nodo rilevante. Il seguente comando rimuove la porta "e0d" sul nodo 3:
+
`network port broadcast-domain remove-ports network port broadcast-domain remove-ports ipspace Cluster -broadcast-domain Cluster ‑ports node3:e0d`

. Verificare che il nodo abbia raggiunto nuovamente il quorum:
+
`cluster show -node node3 -fields health`

. Regolare i domini di broadcast che ospitano le LIF del cluster e le LIF di gestione dei nodi/cluster. Verificare che ciascun dominio di trasmissione contenga le porte corrette. Una porta non può essere spostata tra domini di broadcast se è in hosting o è la sede di una LIF, quindi potrebbe essere necessario migrare e modificare le LIF come segue:
+
.. Visualizzare la porta home di una LIF:
+
`network interface show -fields home-node,home-port`

.. Visualizza il dominio di trasmissione contenente questa porta:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Aggiungere o rimuovere le porte dai domini di broadcast:
`network port broadcast-domain add-ports network port broadcast-domain remove-port`
.. Modificare una porta home di una LIF:
`network interface modify -vserver vserver -lif _lif_name_ –home-port _port_name_` Regolare i domini di broadcast dell'intercluster e migrare le LIF dell'intercluster, se necessario. Le LIF dei dati rimangono invariate.



