---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: 'Verificare che le porte fisiche sul nodo 1 siano mappate correttamente al nodo 3 quando si aggiornano i controller che eseguono ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Mappare le porte dal nodo 1 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È necessario verificare che le porte fisiche sul nodo 1 siano mappate correttamente alle porte fisiche sul nodo 3, consentendo al nodo 3 di comunicare con altri nodi del cluster e con la rete dopo l'aggiornamento.

.A proposito di questa attività
Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_ per acquisire informazioni sulle porte sui nuovi nodi. Le informazioni verranno utilizzate più avanti in questa sezione.

Le impostazioni delle porte possono variare a seconda del modello dei nodi. È necessario rendere la porta e la configurazione LIF sul nodo originale compatibili con l'utilizzo pianificato e la configurazione del nuovo nodo. Questo perché il nuovo nodo riproduce la stessa configurazione all'avvio, il che significa che quando si avvia node3, ONTAP tenterà di ospitare le LIF sulle stesse porte utilizzate sul node1.

Pertanto, se le porte fisiche sul nodo 1 non vengono mappate direttamente alle porte fisiche sul nodo 3, saranno necessarie modifiche alla configurazione del software per ripristinare la connettività di cluster, gestione e rete dopo l'avvio. Inoltre, se le porte del cluster sul nodo 1 non vengono mappate direttamente alle porte del cluster sul nodo 3, il nodo 3 potrebbe non ricongiungersi automaticamente al quorum quando viene riavviato fino a quando non si modifica la configurazione software per ospitare le LIF del cluster sulle porte fisiche corrette.

.Fasi
. Annotare nella tabella tutte le informazioni relative al cablaggio node1 per il nodo 1, le porte, i domini di trasmissione e gli IPspaces:
+
|===
| LIF | Node1 porte | Node1 IPspaces | Node1 domini di broadcast | Node3 porte | Node3 IPspaces | Node3 domini di broadcast 


| Cluster 1 |  |  |  |  |  |  


| Cluster 2 |  |  |  |  |  |  


| Cluster 3 |  |  |  |  |  |  


| Cluster 4 |  |  |  |  |  |  


| Gestione dei nodi |  |  |  |  |  |  


| Gestione del cluster |  |  |  |  |  |  


| Dati 1 |  |  |  |  |  |  


| Dati 2 |  |  |  |  |  |  


| Dati 3 |  |  |  |  |  |  


| Dati 4 |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| Porta intercluster |  |  |  |  |  |  
|===
. Annotare nella tabella tutte le informazioni relative al cablaggio per il nodo 3, le porte, i domini di trasmissione e gli IPspaces.
. Per verificare se il setup è un cluster senza switch a due nodi, procedere come segue:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`cluster::> set -privilege advanced`

.. Verificare se il setup è un cluster senza switch a due nodi:
+
`cluster::> network options switchless-cluster show`

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
Il valore dell'output di questo comando deve corrispondere allo stato fisico del sistema.

.. Tornare al livello di privilegi di amministrazione:
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. Seguire questi passaggi per inserire il node3 nel quorum:
+
.. Punto di avvio3. Vedere link:install_boot_node3.html["Installazione e boot node3"] per avviare il nodo, se non è già stato fatto.
.. Verificare che le nuove porte del cluster si trovino nel dominio di trasmissione del cluster:
+
`network port show -node _node_ -port _port_ -fields broadcast-domain`

+
L'esempio seguente mostra che la porta "e0a" si trova nel dominio del cluster sul nodo 3:

+
[listing]
----
 cluster::> network port show -node _node3_ -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. Se le porte del cluster non si trovano nel dominio di broadcast del cluster, aggiungerle con il seguente comando:
+
`broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports _node:port_`

+
Questo esempio aggiunge la porta cluster "e1b" al nodo 3:

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. Aggiungere le porte corrette al dominio di trasmissione del cluster:
+
`network port modify -node -port -ipspace Cluster -mtu 9000`

+
Questo esempio aggiunge la porta cluster "e1b" al nodo 4:

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. Migrare le LIF del cluster alle nuove porte, una volta per ogni LIF:
+
`network interface migrate -vserver Cluster -lif _lif_name_ -source-node _node3_ -destination-node _node3_ -destination-port _port_name_`

.. Modificare la porta home delle LIF del cluster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Rimuovere le vecchie porte dal dominio di trasmissione del cluster:
+
`network port broadcast-domain remove-ports`

+
Il seguente comando rimuove la porta "e0d" sul nodo 3:

+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports node3:e0d`

.. Verificare che node3 si sia riUnito al quorum:
+
`cluster show -node node3 -fields health`



. [[auto_map_3_step5]]regola i domini di broadcast che ospitano le LIF del cluster e le LIF di gestione dei nodi/gestione dei cluster. Verificare che ciascun dominio di trasmissione contenga le porte corrette. Una porta non può essere spostata tra domini di broadcast se è in hosting o è la sede di una LIF, quindi potrebbe essere necessario migrare e modificare le LIF come segue:
+
.. Visualizzare la porta home di una LIF:
+
`network interface show -fields home-node,home-port`

.. Visualizza il dominio di trasmissione contenente questa porta:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Aggiungere o rimuovere le porte dai domini di broadcast:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modificare la porta home di una LIF:
+
`network interface modify -vserver vserver -lif _lif_name_ –home-port _port_name_`



. Regolare l'appartenenza al dominio di broadcast delle porte di rete utilizzate per le LIF di intercluster utilizzando gli stessi comandi illustrati nella <<auto_map_3_step5,Fase 5>>.
. Regolare gli altri domini di broadcast e migrare i file LIF dei dati, se necessario, utilizzando gli stessi comandi illustrati nella <<auto_map_3_step5,Fase 5>>.
. Se sul nodo 1 sono presenti porte che non esistono più sul nodo 3, attenersi alla seguente procedura per eliminarle:
+
.. Accedere al livello di privilegio avanzato su uno dei nodi:
+
`set -privilege advanced`

.. Per eliminare le porte:
+
`network port delete -node _node_name_ -port _port_name_`

.. Tornare al livello di amministrazione:
+
`set -privilege admin`



. Regolare tutti i gruppi di failover LIF:
+
`network interface modify -failover-group _failover_group_ -failover-policy _failover_policy_`

+
Il seguente comando imposta il criterio di failover su `broadcast-domain-wide` E utilizza le porte del gruppo di failover "fg1" come destinazioni di failover per LIF "data1" sul node3:

+
`network interface modify -vserver node3 -lif data1 failover-policy broadcast-domainwide -failover-group fg1`

+
Fare riferimento a. link:other_references.html["Riferimenti"] Per ulteriori informazioni, fare riferimento a _Gestione di rete_ o ai comandi di _ONTAP 9: Manuale di riferimento pagina_.

. Verificare le modifiche al nodo 3:
+
`network port show -node node3`

. Ogni LIF del cluster deve essere in ascolto sulla porta 7700. Verificare che le LIF del cluster siano in ascolto sulla porta 7700:
+
`::> network connections listening show -vserver Cluster`

+
La porta 7700 in ascolto sulle porte del cluster è il risultato previsto, come mostrato nell'esempio seguente per un cluster a due nodi:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. Per ogni cluster LIF che non è in ascolto sulla porta 7700, imposta lo stato amministrativo della LIF su `down` e poi `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Ripetere il passaggio 11 per verificare che la LIF del cluster sia in ascolto sulla porta 7700.


