---
sidebar: sidebar 
permalink: upgrade-arl-auto/prepare_for_netboot.html 
keywords: prepare, netboot, node3, node4, boot, ONTAP image, media device 
summary: 'Preparare il nodo di netboot 3 e node4 quando si aggiornano i controller con ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Preparatevi per il netboot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver inserito fisicamente il nodo 3 e il nodo 4 più avanti nella procedura, potrebbe essere necessario eseguire il netboot. Il termine "netboot" indica che si sta eseguendo l'avvio da un'immagine ONTAP memorizzata su un server remoto. Durante la preparazione per il netboot, è necessario inserire una copia dell'immagine di boot di ONTAP 9 su un server Web a cui il sistema può accedere.

.Prima di iniziare
* Verificare che sia possibile accedere a un server HTTP con il sistema.
* Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_ e scaricare i file di sistema necessari per la piattaforma e la versione corretta di ONTAP.


.A proposito di questa attività
È necessario eseguire il netboot dei nuovi controller se non sono installati sulla stessa versione di ONTAP 9 installata sui controller originali. Dopo aver installato ciascun nuovo controller, avviare il sistema dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avvii del sistema.

Tuttavia, non è necessario eseguire il netboot dei controller se è installata la stessa versione di ONTAP 9 installata sui controller originali. In tal caso, saltare questa sezione e passare a. link:install_boot_node3.html["Fase 3 Installazione e boot node3"]

.Fasi
. Accedere al NetApp Support Site per scaricare i file utilizzati per eseguire l'avvio da rete del sistema.
. Scaricare il software ONTAP appropriato dalla sezione di download del software del sito di supporto NetApp e memorizzare il `<ontap_version>_image.tgz` file in una directory accessibile dal web.
. Passare alla directory accessibile dal Web e verificare che i file necessari siano disponibili.
+
[cols="30,70"]
|===
| Per... | Quindi... 


| Sistemi della serie FAS/AFF8000  a| 
Estrarre il contenuto di `<ontap_version>_image.tgz` file nella directory di destinazione:
`tar -zxvf <ontap_version>_image.tgz`


NOTE: Se si sta estraendo il contenuto su Windows, utilizzare 7-zip o WinRAR per estrarre l'immagine di netboot.

L'elenco delle directory deve contenere una cartella netboot con un file kernel:
`netboot/kernel`



| Tutti gli altri sistemi  a| 
L'elenco delle directory deve contenere il seguente file:
`<ontap_version>_image.tgz`


NOTE: Non è necessario estrarre il contenuto di `<ontap_version>_image.tgz` file.

|===
+
Verranno utilizzate le informazioni contenute nelle directory in link:install_boot_node3.html["Fase 3"].


