---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: 'Spostare gli aggregati non root e le LIF di dati NAS da node1 a node2 e spostare le risorse node1 in node3 quando si aggiornano i controller che eseguono ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Spostare gli aggregati non root e le LIF dei dati NAS di proprietà del node1 al node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di poter sostituire il node1 con il node3, è necessario spostare gli aggregati non root e le LIF dei dati NAS da node1 a node2 prima di spostare le risorse del node1 al node3.

.Prima di iniziare
L'operazione deve essere già in pausa quando si avvia l'operazione; è necessario ripristinarla manualmente.

.A proposito di questa attività
Le LIF remote gestiscono il traffico verso le LUN SAN durante la procedura di aggiornamento. Lo spostamento delle LIF SAN non è necessario per lo stato del cluster o del servizio durante l'aggiornamento. Dopo aver portato il nodo 3 online, è necessario verificare che i file LIF siano integri e posizionati su porte appropriate.


NOTE: Il proprietario domestico degli aggregati e dei LIF non viene modificato; viene modificato solo il proprietario corrente.

.Fasi
. Riprendere le operazioni di trasferimento aggregato e spostamento LIF dei dati NAS:
+
`system controller replace resume`

+
Tutti gli aggregati non root e le LIF dei dati NAS vengono migrati da node1 a node2.

+
L'operazione viene interrotta per consentire di verificare se tutti gli aggregati non root e le LIF di dati non SAN node1 sono stati migrati in node2.

. Controllare lo stato delle operazioni di trasferimento aggregato e LIF dei dati NAS:
+
`system controller replace show-details`

. Con l'operazione ancora in pausa, verificare che tutti gli aggregati non root siano in linea per il loro stato su node2:
+
`storage aggregate show -node _node2_ -state online -root false`

+
L'esempio seguente mostra che gli aggregati non root su node2 sono online:

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Se gli aggregati sono andati offline o diventano estranei sul node2, portarli online usando il seguente comando su node2, una volta per ogni aggregato:

+
`storage aggregate online -aggregate _aggr_name_`

. Verificare che tutti i volumi siano online sul nodo 2 utilizzando il seguente comando sul nodo 2 ed esaminandone l'output:
+
`volume show -node _node2_ -state offline`

+
Se alcuni volumi sono offline sul nodo 2, portarli online utilizzando il seguente comando sul nodo 2, una volta per ogni volume:

+
`volume online -vserver _vserver_name_ -volume _volume_name_`

+
Il `_vserver_name_` da utilizzare con questo comando si trova nell'output del precedente `volume show` comando.



. [[step5]]se le porte che attualmente ospitano i file LIF dei dati non esistono sul nuovo hardware, rimuoverle dal dominio di trasmissione:
+
`network port broadcast-domain remove-ports`

. Se le LIF non sono attive, impostare lo stato amministrativo delle LIF su `up` Immettendo il seguente comando, una volta per ogni LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_-home-node _nodename_ -status-admin up`

. Se sono stati configurati gruppi di interfacce o VLAN, completare i seguenti passaggi secondari:
+
.. Se non sono già state salvate, registrare le informazioni relative alla VLAN e al gruppo di interfacce in modo da poter ricreare le VLAN e i gruppi di interfacce sul nodo 3 dopo l'avvio del nodo 3.
.. Rimuovere le VLAN dai gruppi di interfacce:
+
`network port vlan delete -node _nodename_ -port _ifgrp_ -vlan-id _VLAN_ID_`

+

NOTE: Seguire l'azione correttiva per risolvere eventuali errori suggeriti dal comando di eliminazione della vlan.

.. Immettere il seguente comando ed esaminare il relativo output per verificare l'eventuale presenza di gruppi di interfacce configurati sul nodo:
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
Il sistema visualizza le informazioni sul gruppo di interfacce per il nodo, come illustrato nell'esempio seguente:

+
[listing]
----
cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                 Node: node1
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. Se nel nodo sono configurati gruppi di interfacce, registrare i nomi di tali gruppi e le porte ad essi assegnate, quindi eliminare le porte immettendo il seguente comando, una volta per ciascuna porta:
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




