---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: 'Configurare node3 porte FC onboard, porte UTA/UTA2 o scheda UTA/UTA2 quando si aggiornano i controller con ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Impostare la configurazione FC o UTA/UTA2 su node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se node3 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare la sezione <<Configurare le porte FC sul nodo 3>>, la sezione <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>, o entrambe le sezioni.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento alle porte e agli adattatori CNA (Converged Network Adapter). Tuttavia, la CLI utilizza il termine CNA.

Se node3 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 e si sta aggiornando un sistema con dischi di archiviazione, è possibile passare alla sezione link:reassign-node1-disks-to-node3.html["Riassegnare dischi da node1 TB a node3 TB"].



== Configurare le porte FC sul nodo 3

Se il nodo 3 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 1 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Confronta le impostazioni FC sul nodo 3 con le impostazioni acquisite in precedenza dal nodo 1.
. Eseguire una delle seguenti azioni per modificare le porte FC sul nodo 3, a seconda delle necessità:
+
In modalità di manutenzione (opzione 5 nel menu di avvio):

+
** Per programmare come porte di destinazione:
+
`ucadmin modify -m fc -t target <adapter>`

+
Per esempio: `ucadmin modify -m fc -t target 2a`

** Per programmare le porte initiator:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Per esempio: `ucadmin modify -m fc -t initator 2b`



. Verificare le nuove impostazioni utilizzando il seguente comando ed esaminando l'output:
+
`ucadmin show`

. Arrestare il nodo:
+
`halt`

. Avviare il sistema dal prompt del CARICATORE:
+
`boot_ontap menu`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Selezionare l'opzione `5` dal menu di avvio per la modalità di manutenzione.


. Eseguire una delle seguenti operazioni:
+
** Se node3 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate, passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.
** Se node3 non dispone di una scheda UTA/UTA2 o di porte onboard UTA/UTA2, ignorare <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>> e andare a link:reassign-node1-disks-to-node3.html["Riassegnare dischi da node1 TB a node3 TB"].






== Controllare e configurare le porte UTA/UTA2 sul nodo 3

Se node3 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, è necessario controllare la configurazione delle porte ed eventualmente riconfigurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Se si desidera utilizzare una porta UTA/UTA2 (Unified Target Adapter) per FC, è necessario prima verificare la configurazione della porta.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Puoi usare il `ucadmin show` comando per visualizzare o verificare la configurazione della porta corrente, come mostrato nel seguente output di esempio:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente la condivisione simultanea del traffico NIC e FCoE con la stessa interfaccia SFP+ 10 GbE e supporta le destinazioni FC.

Potresti trovare porte UTA/UTA2 su un adattatore aggiuntivo o sulla scheda madre del controller e avere le seguenti configurazioni, ma dovresti controllare la configurazione delle porte UTA/UTA2 sul nodo 3 e modificarla, se necessario:

* Le schede UTA/UTA2 ordinate al momento dell'ordine del controller vengono configurate prima della spedizione per avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
+

WARNING: Per configurare le porte UTA/UTA2 è necessario essere in modalità di manutenzione.  Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.



.Fasi
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Verificare le impostazioni della porta UTA/UTA2:
+
`ucadmin show`

+
Esaminare l'output e determinare se le porte UTA/UTA2 hanno la personalità desiderata.

+
L'output nell'esempio seguente mostra che il tipo di adattatore "1b" sta cambiando in iniziatore e che la modalità degli adattatori "2a" e "2b" sta cambiando in "cna".  La modalità CNA consente di utilizzare la scheda come adattatore di rete.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se le porte UTA/UTA2... | Quindi… 


| Non avere la personalità che si desidera | Vai a<<auto_check3_step4,Fase 4>> . 


| Avere la personalità che si desidera | Salta il passaggio 4 al passaggio 8 e vai a<<auto_check3_step9,Fase 9>> . 
|===
. [[auto_check3_step4]]Esegui una delle seguenti azioni:
+
[cols="30,70"]
|===
| Se si sta configurando... | Quindi… 


| Porte su una scheda UTA/UTA2 | Vai a<<auto_check3_step5,Fase 5>> 


| Porte UTA/UTA2 integrate | Salta il passaggio 5 e vai a<<auto_check3_step6,Fase 6>> . 
|===
. [[auto_check3_step5]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter <adapter_name>`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[auto_check3_step6]]Se la configurazione corrente non corrisponde all'uso desiderato, modificare la configurazione secondo necessità:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` è la modalità personality, `fc` oppure `cna`.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e le configurazioni MetroCluster .  Per i client SAN è necessario utilizzare la destinazione FC.



. Mettere online tutte le porte di destinazione immettendo il seguente comando una volta per ogni porta:
+
`storage enable adapter <adapter_name>`

. Collegare la porta.


[[auto_check3_step9]]
. Uscire dalla modalità di manutenzione:
+
`halt`

. Avviare il nodo nel menu di avvio eseguendo `boot_ontap menu` .


.Quali sono le prossime novità?
* Se stai effettuando l'aggiornamento a un sistema AFF A800 , vai alink:reassign-node1-disks-to-node3.html#auto_check3_step9["Riassegnare node1 dischi a node3, passaggio 9"] .
* Per tutti gli altri aggiornamenti di sistema, vai alink:reassign-node1-disks-to-node3.html["Riassegnare node1 dischi a node3, passaggio 1"] .

