---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'Configurare node4 porte FC integrate, porte UTA/UTA2 o scheda UTA/UTA2 quando si aggiornano i controller con ONTAP 9.5 a 9.7 utilizzando `system controller replace` comandi.' 
---
= Impostare la configurazione FC o UTA/UTA2 su node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se node4 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare il <<Configurare le porte FC sul nodo 4>> sezione, la <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>, o entrambe le sezioni.


NOTE: Se node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 e si sta eseguendo l'aggiornamento di un sistema con dischi di storage, passare alla sezione link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] sezione. Tuttavia, se si dispone di un sistema V-Series o di un software di virtualizzazione FlexArray e si è connessi agli array di storage e node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2, tornare alla sezione _Installazione e boot node4_ e riprendere da link:install_boot_node4.html#step22["Fase 22"]. Assicurarsi che il node4 disponga di spazio rack sufficiente. Se il nodo 4 si trova in uno chassis separato dal nodo 2, è possibile inserire il nodo 4 nella stessa posizione del nodo 3. Se node2 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

.Scelte
* <<Configurare le porte FC sul nodo 4>>
* <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>




== Configurare le porte FC sul nodo 4

Se node4 dispone di porte FC, integrate o su un adattatore FC, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, perché le porte non sono preconfigurate. Se le porte non sono configurate, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di un adattatore UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Se il sistema dispone di dischi di storage, è necessario immettere i comandi in questa sezione al prompt del cluster. Se si dispone di un sistema V-Series o di un sistema con software di virtualizzazione FlexArray collegato agli array di storage, immettere i comandi in questa sezione in modalità manutenzione.

.Fasi
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage | `system node hardware unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `ucadmin show` 
|===
+
Il sistema visualizza informazioni su tutti gli adattatori di rete FC e convergenti del sistema.

. Confrontare le impostazioni FC sul nodo 4 con quelle acquisite in precedenza dal nodo 1.
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage  a| 
Modificare le porte FC sul nodo 4 in base alle necessità:

** Per programmare le porte di destinazione:
+
`ucadmin modify -m fc -t target _adapter_`

** Per programmare le porte initiator:
+
`ucadmin modify -m fc -t initiator _adapter_`



`-t` È il tipo FC4: Destinazione o iniziatore.



| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage  a| 
Modificare le porte FC sul nodo 4 in base alle necessità:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` È il tipo, la destinazione o l'iniziatore FC4.


NOTE: Le porte FC devono essere programmate come iniziatori.

|===
. Uscire dalla modalità di manutenzione:
+
`halt`

. Avviare il sistema dal prompt del caricatore:
+
`boot_ontap menu`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Selezionare l'opzione `5` dal menu di avvio per la modalità di manutenzione.


. [[step8]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se il sistema che si sta aggiornando... | Quindi... 


| Dispone di dischi di storage  a| 
** Saltare questa sezione e andare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] Se node4 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate.




| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage  a| 
** Passare a. link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Controllare e configurare le porte UTA/UTA2 sul nodo 4"] Se node4 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate.
** Saltare la sezione _controllare e configurare le porte UTA/UTA2 su node4_ se node4 non dispone di una scheda UTA/UTA2 o di porte integrate UTA/UTA2, tornare alla sezione _Installazione e boot node4_ e riprendere da link:install_boot_node4.html#auto_install4_step23["Fase 23"].


|===




== Controllare e configurare le porte UTA/UTA2 sul nodo 4

Se node4 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2A, è necessario controllare la configurazione delle porte e configurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2A. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente al traffico simultaneo di NIC e FCoE di condividere la stessa interfaccia SFP+ 10 GbE e supporta la destinazione FC.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Le porte UTA/UTA2 potrebbero essere su un adattatore o sul controller con le seguenti configurazioni:

* Le schede UTA/UTA2 ordinate contemporaneamente al controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller sono configurate (prima della spedizione) in modo da avere la personalità richiesta.


Tuttavia, è necessario controllare la configurazione delle porte UTA/UTA2 sul nodo 4 e modificarla, se necessario.


WARNING: *Attenzione*: Se il sistema dispone di dischi di storage, immettere i comandi in questa sezione al prompt del cluster, a meno che non venga richiesto di accedere alla modalità di manutenzione. Se si dispone di un sistema MetroCluster FC, V-Series o un sistema con software di virtualizzazione FlexArray collegato agli array di storage, è necessario essere in modalità di manutenzione per configurare le porte UTA/UTA2.

.Fasi
. Verificare la configurazione delle porte utilizzando uno dei seguenti comandi sul nodo 4:
+
[cols="30,70"]
|===
| Se il sistema... | Quindi… 


| Dispone di dischi di storage | `system node hardware unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `ucadmin show` 
|===
+
Il sistema visualizza un output simile al seguente esempio:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Esaminare l'output di `ucadmin show` Controllare e determinare se le porte UTA/UTA2 hanno la personalità desiderata.
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se la porta CNA... | Quindi… 


| Non avere la personalità che si desidera | Passare a. <<auto_check_4_step5,Fase 5>>. 


| Avere la personalità che si desidera | Saltare i passaggi da 5 a 12 e passare a. <<auto_check_4_step13,Fase 13>>. 
|===
. [[auto_check_4_step5]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se si sta configurando... | Quindi… 


| Porte su una scheda UTA/UTA2 | Passare a. <<auto_check_4_step7,Fase 7>> 


| Porte UTA/UTA2 integrate | Saltare la fase 7 e passare a. <<auto_check_4_step8,Fase 8>>. 
|===
. Se l'adattatore è in modalità Initiator e la porta UTA/UTA2 è in linea, portare la porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[auto_check_4_step7]]se la configurazione corrente non corrisponde all'utilizzo desiderato, modificare la configurazione in base alle necessità:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` È la modalità Personality, FC o 10GbE UTA.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare FC Initiator per unità nastro, sistemi di virtualizzazione FlexArray e configurazioni MetroCluster. È necessario utilizzare la destinazione FC per i client SAN.



. [[auto_check_4_step8]]verificare le impostazioni utilizzando il seguente comando ed esaminandone l'output:
+
`ucadmin show`

. Verificare le impostazioni:
+
[cols="40,60"]
|===
| Se il sistema... | Quindi… 


| Dispone di dischi di storage | `ucadmin show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `ucadmin show` 
|===
+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Inserire le porte di destinazione in linea immettendo uno dei seguenti comandi, una volta per ciascuna porta:
+
[cols="30,70"]
|===
| Se il sistema... | Quindi… 


| Dispone di dischi di storage | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `fcp config _adapter_name_ up` 
|===
. Collegare la porta.


. [[step12]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage | Andare alla sezione link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"]. 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Tornare alla sezione _Installazione e boot node4_ e riprendere il lavoro dal link:install_boot_node4.html#auto_install4_step23["Fase 23"]. 
|===
. [[auto_check_4_step13]]Esci dalla modalità di manutenzione:
+
`halt`

. [[step14]]nodo di boot nel menu di boot:
+
`boot_ontap menu`

+
Se si sta eseguendo l'aggiornamento a un sistema A800, visitare il sito Web all'indirizzo <<auto_check_4_step23,Fase 23>>.

. [[auto_check_4_step15]]al nodo 4, andare al menu di boot e, utilizzando 22 ore su 24, 7 giorni su 7, selezionare l'opzione nascosta `boot_after_controller_replacement`. Al prompt, immettere node2 per riassegnare i dischi di node2 a node4, come nell'esempio seguente.
+
.Espandere l'esempio di output della console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
.
.
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----
====
. Se il sistema entra in un loop di riavvio con il messaggio `no disks found`, perché ha ripristinato le porte alla modalità di destinazione e quindi non è in grado di vedere alcun disco. Continuare con <<auto_check_4_step17,Fase 17>> attraverso <<auto_check_4_step22,Fase 22>> per risolvere questo problema.
. [[auto_check_4_step17]]premere `Ctrl-C` durante l'autoboot per arrestare il nodo su `LOADER>` prompt.
. Al prompt del caricatore, accedere alla modalità di manutenzione:
+
`boot_ontap maint`

. In modalità di manutenzione, visualizzare tutte le porte iniziatore precedentemente impostate che si trovano ora in modalità di destinazione:
+
`ucadmin show`

+
Riportare le porte in modalità initiator:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Verificare che le porte siano state modificate in modalità initiator:
+
`ucadmin show`

. Uscire dalla modalità di manutenzione:
+
`halt`

+
[NOTE]
====
Se si esegue l'aggiornamento da un sistema che supporta dischi esterni a un sistema che supporta anche dischi esterni, visitare il sito Web <<auto_check_4_step22,Fase 22>>.

Se si esegue l'aggiornamento da un sistema che utilizza dischi esterni a un sistema che supporta dischi interni ed esterni, ad esempio un sistema AFF A800, visitare il sito Web <<auto_check_4_step23,Fase 23>>.

====
. [[auto_check_4_step22]]al prompt del caricatore, avviare:
+
`boot_ontap menu`

+
Ora, all'avvio, il nodo è in grado di rilevare tutti i dischi ad esso assegnati in precedenza e di avviarsi come previsto.

+
Quando i nodi del cluster che si stanno sostituendo utilizzano la crittografia del volume root, il software ONTAP non è in grado di leggere le informazioni del volume dai dischi. Ripristinare le chiavi del volume root:

+
.. Tornare al menu di avvio speciale:
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Selezionare *(10) Imposta segreti di ripristino di Onboard Key Manager*
.. Invio `y` al seguente prompt:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. Quando richiesto, inserire la passphrase del gestore delle chiavi.
.. Inserire i dati di backup quando richiesto.
+

NOTE: È necessario aver ottenuto la passphrase e i dati di backup in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] sezione di questa procedura.

.. Dopo aver riavviato il sistema con lo speciale menu di boot, eseguire l'opzione *(1) Avvio normale*
+

NOTE: In questa fase potrebbe verificarsi un errore. Se si verifica un errore, ripetere i passaggi secondari in <<auto_check_4_step22,Fase 22>> fino a quando il sistema non si avvia normalmente.





. [[auto_check_4_step23]]se si esegue l'aggiornamento da un sistema con dischi esterni a un sistema che supporta dischi interni ed esterni (ad esempio, sistemi AFF A800), impostare l'aggregato node2 come aggregato root per confermare che node4 si avvia dall'aggregato root di node2. Per impostare l'aggregato root, accedere al menu di boot e selezionare l'opzione `5` per accedere alla modalità di manutenzione.
+

WARNING: *È necessario eseguire i seguenti passaggi secondari nell'ordine esatto indicato; in caso contrario, si potrebbe verificare un'interruzione o addirittura la perdita di dati.*

+
La seguente procedura imposta node4 per l'avvio dall'aggregato root di node2:

+
.. Accedere alla modalità di manutenzione:
+
`boot_ontap maint`

.. Controllare le informazioni su RAID, plex e checksum per l'aggregato node2:
+
`aggr status -r`

.. Controllare lo stato dell'aggregato node2:
+
`aggr status`

.. Se necessario, portare online l'aggregato node2:
+
`aggr_online root_aggr_from___node2__`

.. Impedire al node4 di avviarsi dal proprio aggregato root originale:
+
`aggr offline _root_aggr_on_node4_`

.. Impostare l'aggregato root node2 come nuovo aggregato root per node4:
+
`aggr options aggr_from___node2__ root`




