---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_2_index.html 
keywords: Prepare nodes for upgrade, storage encryption, KMS, key management server, stage 2 
summary: 'Fase 2 sequenza di processo per un aggiornamento ARL con `system controller replace` Comandi sui controller che eseguono ONTAP da 9.5 a 9.7.' 
---
= Panoramica della fase 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 2, è possibile spostare gli aggregati non root node1 e le LIF dei dati NAS in node2. Questo processo è in gran parte automatizzato; l'operazione viene interrotta per consentirti di controllarne lo stato. È necessario riprendere manualmente l'operazione. Se necessario, spostare gli aggregati non riusciti o vetoed. Inoltre, registrare le informazioni necessarie sul node1, dismettere il node1 e prepararsi al netboot node3 e node4 più avanti nella procedura.

.Fasi
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Spostare gli aggregati non root e le LIF dei dati NAS di proprietà del node1 al node2"]
. link:relocate_failed_or_vetoed_aggr.html["Spostare gli aggregati non riusciti o vetoed"]
. link:retire_node1.html["Ritirare il node1"]
. link:prepare_for_netboot.html["Preparatevi per il netboot"]

