= Passaggio 1: Configurare le porte FC sul nodo4
:allow-uri-read: 




[[step-1-configure-fc-ports-on-node4]]
[[configure-fc-ports-on-node4]]
== Passaggio 1: Configurare le porte FC sul nodo4

Se il nodo 4 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte come richiesto, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
Puoi saltare questa sezione se il tuo sistema non ha configurazioni FC. Se il tuo sistema ha porte UTA/UTA2 integrate o un adattatore UTA/UTA2, le configuri in <<check-config-uta-uta2-node4,Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti sul sistema:
+
`system node hardware unified-connect show`

. Confrontare le impostazioni FC sul nodo 4 con quelle acquisite in precedenza dal nodo 1.
. Modificare le porte FC sul nodo 4 in base alle necessità:
+
** Per programmare come porte di destinazione:
+
`ucadmin modify -m fc -t target _adapter_`

+
Per esempio: `ucadmin modify -m fc -t target 2a`

** Per programmare le porte initiator:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` È il tipo FC4: Destinazione o iniziatore.

+
Per esempio: `ucadmin modify -m fc -t initator 2b`



. Arrestare il nodo:
+
`halt`

. Avviare il sistema dal prompt del CARICATORE:
+
`boot_ontap menu`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Selezionare l'opzione `5` dal menu di avvio per la modalità di manutenzione.

