= Passaggio 1: Configurare le porte FC su node3
:allow-uri-read: 




[[step-1-configure-fc-ports-on-node3]]
[[configure-fc-ports-on-node3]]
== Passaggio 1: Configurare le porte FC su node3

Se il nodo 3 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 1 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
Puoi saltare questa sezione se il tuo sistema non ha configurazioni FC. Se il tuo sistema ha porte UTA/UTA2 integrate o una scheda UTA/UTA2, le configuri in <<check-config-uta-uta2-node3,Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Confronta le impostazioni FC sul nodo 3 con le impostazioni acquisite in precedenza dal nodo 1.
. Eseguire una delle seguenti azioni per modificare le porte FC sul nodo 3, a seconda delle necessità:
+
In modalità di manutenzione (opzione 5 nel menu di avvio):

+
** Per programmare come porte di destinazione:
+
`ucadmin modify -m fc -t target <adapter>`

+
Per esempio: `ucadmin modify -m fc -t target 2a`

** Per programmare le porte initiator:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Per esempio: `ucadmin modify -m fc -t initator 2b`



. Verificare le nuove impostazioni utilizzando il seguente comando ed esaminando l'output:
+
`ucadmin show`

. Arrestare il nodo:
+
`halt`

. Avviare il sistema dal prompt del CARICATORE:
+
`boot_ontap menu`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Selezionare l'opzione `5` dal menu di avvio per la modalità di manutenzione.

