= 
:allow-uri-read: 


È necessario eseguire il netboot node4 se non dispone della stessa versione di ONTAP 9 installata sul node2. Dopo aver installato node4, avviarlo dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avviamenti del sistema, seguendo le istruzioni riportate in link:prepare_for_netboot.html["Preparatevi per il netboot"].

[IMPORTANT]
====
* Per aggiornare il controller AFF A800 o AFF C800, è necessario assicurarsi che tutte le unità nello chassis siano saldamente posizionate sul midplane prima di rimuovere node2. Per ulteriori informazioni, vedere link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Sostituire i moduli controller AFF A800 o AFF C800"].
* Se si sta aggiornando un sistema con dischi di archiviazione, è necessario completare l'intera sezione e quindi procedere a link:set_fc_or_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"] , immettendo comandi al prompt del cluster.


====
.Fasi
. [[auto_install4_step1]]assicurarsi che node4 disponga di spazio rack sufficiente.
+
Se il nodo 4 si trova in uno chassis separato dal nodo 2, è possibile inserire il nodo 4 nella stessa posizione del nodo 3. Se node2 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

. Installare il nodo 4 nel rack seguendo le istruzioni contenute nelle _istruzioni di installazione e configurazione_ relative al modello di nodo.
. Nodo del cablo4, spostamento delle connessioni dal nodo 2 al nodo 4.
+
Cablare le seguenti connessioni, utilizzando le _Istruzioni di installazione e configurazione_ per la piattaforma node4, il documento appropriato sullo scaffale dei dischi e la documentazione sulla _gestione delle coppie HA_.

+
Fare riferimento alink:other_references.html["Riferimenti"] per collegarsi alla _gestione delle coppie HA_.

+
** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI
+

NOTE: Potrebbe non essere necessario spostare la connessione scheda di interconnessione/scheda FC-VI o cavo di interconnessione/FC-VI dal nodo 2 al nodo 4, poiché la maggior parte dei modelli di piattaforma dispone di modelli di schede di interconnessione univoci. Per la configurazione MetroCluster, è necessario spostare le connessioni del cavo FC-VI dal nodo 2 al nodo 4. Se il nuovo host non dispone di una scheda FC-VI, potrebbe essere necessario spostare la scheda FC-VI.



. Accendere il dispositivo al nodo 4, quindi interrompere il processo di avvio premendo Ctrl-C sul terminale della console per accedere al prompt dell'ambiente di avvio.
+

NOTE: Quando si avvia node4, potrebbe essere visualizzato il seguente messaggio di avviso:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Se viene visualizzato il messaggio di avviso nella fase 4, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio venga completato.
+

WARNING: *Non ignorare il ritardo; se non si lascia caricare la batteria, si potrebbe verificare una perdita di dati.*

+

NOTE: Fare riferimento a. link:prepare_for_netboot.html["Preparatevi per il netboot"].




