= Scopri le licenze ONTAP
:allow-uri-read: 




[[learn-about-ontap-licensing]]
== Scopri le licenze ONTAP

Alcune funzionalità richiedono licenze, emesse come _pacchetti_ che includono una o più funzionalità. Ogni nodo del cluster deve disporre di una propria chiave per poter utilizzare ciascuna funzionalità nel cluster.

Se non si dispone di nuove chiavi di licenza, le funzionalità attualmente concesse in licenza nel cluster sono disponibili per il nuovo controller. Tuttavia, l'utilizzo di funzionalità senza licenza sul controller potrebbe non essere conforme al contratto di licenza, pertanto è necessario installare la nuova chiave di licenza o le nuove chiavi per il nuovo controller al termine dell'aggiornamento.

Consulta link:other-references.html["Riferimenti"] per il collegamento al _NetApp Support Site_ dove puoi ottenere nuove chiavi di licenza di 28 caratteri per ONTAP. Le chiavi sono disponibili nella sezione _My Support_ alla voce _Software licenses_. Se il sito non dispone delle chiavi di licenza di cui hai bisogno, puoi contattare il tuo rappresentante commerciale NetApp.

Per informazioni dettagliate sulle licenze ONTAP, fare riferimento a link:other-references.html["Riferimenti"] per collegarsi al _System Administration Reference_.
