= Controllare e configurare le porte UTA/UTA2 sul nodo 4
:allow-uri-read: 




== Controllare e configurare le porte UTA/UTA2 sul nodo 4

Se node4 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2A, è necessario controllare la configurazione delle porte e configurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2A. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente al traffico simultaneo di NIC e FCoE di condividere la stessa interfaccia SFP+ 10 GbE e supporta la destinazione FC.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Le porte UTA/UTA2 potrebbero essere su un adattatore o sul controller con le seguenti configurazioni:

* Le schede UTA/UTA2 ordinate contemporaneamente al controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller sono configurate (prima della spedizione) in modo da avere la personalità richiesta.


Tuttavia, è necessario controllare la configurazione delle porte UTA/UTA2 sul nodo 4 e modificarla, se necessario.


WARNING: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Controlla come sono attualmente configurate le porte sul nodo 4:
+
`system node hardware unified-connect show`

+
Il sistema visualizza un output simile al seguente esempio:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Verificare le impostazioni:
+
`ucadmin show`

+
Esaminare l'output di `ucadmin show` Controllare e determinare se le porte UTA/UTA2 hanno la personalità desiderata.

+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se la porta CNA... | Quindi… 


| Non avere la personalità che si desidera | Passare a. <<auto_check_4_step5,Fase 5>>. 


| Avere la personalità che si desidera | Salta il passaggio 5 al passaggio 9 e vai a<<auto_check_4_step10,Fase 10>> . 
|===
. [[auto_check_4_step5]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se si sta configurando... | Quindi… 


| Porte su una scheda UTA/UTA2 | Vai a<<auto_check_4_step6,Fase 6>> 


| Porte UTA/UTA2 integrate | Salta il passaggio 6 e vai a<<auto_check_4_step7,Fase 7>> . 
|===
. [[auto_check_4_step6]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[auto_check_4_step7]]se la configurazione corrente non corrisponde all'utilizzo desiderato, modificare la configurazione in base alle necessità:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` È la modalità Personality, FC o 10GbE UTA.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e le configurazioni MetroCluster .  Per i client SAN è necessario utilizzare la destinazione FC.



. Mettere online tutte le porte di destinazione immettendo il seguente comando, una volta per ogni porta:
+
`storage enable adapter <adapter_name>`

. Collegare la porta.

