= Controllare e configurare le porte UTA/UTA2 sul nodo 3
:allow-uri-read: 




== Controllare e configurare le porte UTA/UTA2 sul nodo 3

Se node3 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, è necessario controllare la configurazione delle porte ed eventualmente riconfigurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Se si desidera utilizzare una porta UTA/UTA2 (Unified Target Adapter) per FC, è necessario prima verificare la configurazione della porta.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Puoi usare il `ucadmin show` comando per visualizzare o verificare la configurazione della porta corrente, come mostrato nel seguente output di esempio:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente la condivisione simultanea del traffico NIC e FCoE con la stessa interfaccia SFP+ 10 GbE e supporta le destinazioni FC.

Potresti trovare porte UTA/UTA2 su un adattatore aggiuntivo o sulla scheda madre del controller e avere le seguenti configurazioni, ma dovresti controllare la configurazione delle porte UTA/UTA2 sul nodo 3 e modificarla, se necessario:

* Le schede UTA/UTA2 ordinate al momento dell'ordine del controller vengono configurate prima della spedizione per avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
+

WARNING: Per configurare le porte UTA/UTA2 è necessario essere in modalità di manutenzione.  Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.



.Fasi
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Verificare le impostazioni della porta UTA/UTA2:
+
`ucadmin show`

+
Esaminare l'output e determinare se le porte UTA/UTA2 hanno la personalità desiderata.

+
L'output nell'esempio seguente mostra che il tipo di adattatore "1b" sta cambiando in iniziatore e che la modalità degli adattatori "2a" e "2b" sta cambiando in "cna".  La modalità CNA consente di utilizzare la scheda come adattatore di rete.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se le porte UTA/UTA2... | Quindi… 


| Non avere la personalità che si desidera | Vai a<<auto_check3_step4,Fase 4>> . 


| Avere la personalità che si desidera | Salta il passaggio 4 al passaggio 8 e vai a<<auto_check3_step9,Fase 9>> . 
|===
. [[auto_check3_step4]]Esegui una delle seguenti azioni:
+
[cols="30,70"]
|===
| Se si sta configurando... | Quindi… 


| Porte su una scheda UTA/UTA2 | Vai a<<auto_check3_step5,Fase 5>> 


| Porte UTA/UTA2 integrate | Salta il passaggio 5 e vai a<<auto_check3_step6,Fase 6>> . 
|===
. [[auto_check3_step5]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter <adapter_name>`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[auto_check3_step6]]Se la configurazione corrente non corrisponde all'uso desiderato, modificare la configurazione secondo necessità:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` è la modalità personality, `fc` oppure `cna`.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e le configurazioni MetroCluster .  Per i client SAN è necessario utilizzare la destinazione FC.



. Mettere online tutte le porte di destinazione immettendo il seguente comando una volta per ogni porta:
+
`storage enable adapter <adapter_name>`

. Collegare la porta.

