= Configurare le porte FC sul nodo 4
:allow-uri-read: 




== Configurare le porte FC sul nodo 4

Se node4 dispone di porte FC, integrate o su un adattatore FC, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, perché le porte non sono preconfigurate. Se le porte non sono configurate, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di un adattatore UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt del cluster.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti sul sistema:
+
`system node hardware unified-connect show`

. Confrontare le impostazioni FC sui nuovi nodi con quelle acquisite in precedenza dal nodo originale.
. Modificare le porte FC sul nodo 4 in base alle necessità:
+
** Per programmare le porte di destinazione:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Per programmare le porte initiator:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` È il tipo, la destinazione o l'iniziatore FC4.



. Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
+
`system node unified-connect show`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se le impostazioni FC predefinite sui nuovi nodi sono... | Quindi… 


| Le stesse di quelle acquisite sui nodi originali | Vai a<<man_config_4_Step9,Fase 9>> . 


| Diverso da quelli acquisiti sui nodi originali | Vai a<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Esci dalla modalità di manutenzione:
+
`halt`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Avviare node4 immettendo il seguente comando al prompt dell'ambiente di avvio:
+
`boot_ontap`

. [[man_config_4_Step9]]Esegui una delle seguenti azioni:
+
** Passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> Se node4 ha una scheda UTA/UTA2A o porte UTA/UTA2 integrate.
** Saltare la sezione e passare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] Se node4 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate.



