= 
:allow-uri-read: 


Prima di spegnere e dismettere il nodo 2, è necessario registrare le informazioni relative alla rete del cluster, alla gestione e alle porte FC, nonché l'ID del sistema NVRAM. Queste informazioni sono necessarie più avanti nella procedura quando si esegue il mapping del nodo 2 al nodo 4 e si riassegnano i dischi.

.Fasi
. Trova le porte di rete cluster, gestione nodi, intercluster e gestione cluster sul nodo 2:
+
`network interface show -curr-node _node_name_ -role cluster,intercluster,nodemgmt,cluster-mgmt`

+
Il sistema visualizza le LIF per quel nodo e per gli altri nodi nel cluster, come mostrato nell'esempio seguente:

+
[listing]
----
cluster::> network interface show -curr-node node2 -role
cluster,intercluster,node-mgmt,cluster-mgmt
         Logical     Status     Network            Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask       Node        Port    Home
-------- ----------  ---------- ------------------ ----------  ------- ----
node2
         intercluster up/up     192.168.1.202/24   node2       e0e     true
         clus1        up/up     169.254.xx.xx/24   node2       e0a     true
         clus2        up/up     169.254.xx.xx/24   node2       e0b     true
         mgmt1        up/up     192.168.0.xxx/24   node2       e0c     true
4 entries were displayed.
----
+

NOTE: Il sistema potrebbe non disporre di LIF intercluster. Si avrà una LIF di gestione del cluster solo su un nodo di una coppia di nodi. Una LIF di gestione cluster viene visualizzata nell'output di esempio di link:record_node1_information.html#step1["Fase 1"] In _Record node1 port information_.

. Acquisire le informazioni nell'output da utilizzare nella sezione link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"].
+
Le informazioni di output sono necessarie per mappare le nuove porte del controller alle vecchie porte del controller.

. Determinare le porte fisiche sul nodo 2:
+
`network port show -node _node_name_ -type physical` +

+
`_node_name_` è il nodo che viene migrato.

+
Il sistema visualizza le porte fisiche sul nodo 2, come mostrato nell'esempio seguente:

+
[listing]
----
cluster::> network port show -node node2 -type physical

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node2
       e0M       Default      IP_address       up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
5 entries were displayed.
----
. Registrare le porte e i relativi domini di trasmissione.
+
I domini di broadcast dovranno essere mappati alle porte sul nuovo controller più avanti nella procedura.

. Determinare le porte FC sul nodo 2:
+
`network fcp adapter show`

+
Il sistema visualizza le porte FC sul nodo 2, come mostrato nell'esempio seguente:

+
[listing]
----
cluster::> network fcp adapter show -node node2
                     Connection  Host
Node         Adapter Established Port Address
------------ ------- ----------- ------------
node2
             0a      ptp         11400
node2
             0c      ptp         11700
node2
             6a      loop        0
node2
             6b      loop        0
4 entries were displayed.
----
. Registrare le porte.
+
Le informazioni di output sono necessarie per mappare le nuove porte FC sul nuovo controller più avanti nella procedura.

. Se non è stato fatto in precedenza, controllare se ci sono gruppi di interfacce o VLAN configurati su node2:
+
`ifgrp show`

+
`vlan show`

+
Verranno utilizzate le informazioni contenute nella sezione link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"].

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se... | Quindi... 


| Numero ID sistema NVRAM registrato in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] | Passare a. link:retire_node2.html["Andare in pensione node2"]. 


| Il numero dell'ID del sistema NVRAM non è stato registrato in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] | Completo <<man_record_2_step9,Fase 9>> e. <<man_record_2_step10,Fase 10>> quindi passare alla sezione successiva, link:retire_node2.html["Andare in pensione node2"]. 
|===
. [[man_record_2_step9]]Visualizza gli attributi del node2:
+
`system node show -instance -node node2`

+
[listing]
----
cluster::> system node show -instance -node node2
                            ...
                 NVRAM System ID: system_ID
                           ...
----
. [[man_record_2_step10]]registrare l'ID del sistema NVRAM da utilizzare nella sezione link:install_boot_node4.html["Installazione e boot node4"].

