= 
:allow-uri-read: 


È necessario installare node3 nel rack, trasferire le connessioni del node1 al node3, fare il boot node3 e installare ONTAP. È inoltre necessario riassegnare i dischi spare di node1, i dischi appartenenti al volume root e gli aggregati non root non ricollocati in node2 in precedenza.

.A proposito di questa attività
È necessario eseguire l'avvio di rete del nodo 3 se non ha la stessa versione di ONTAP 9 installata sul nodo 1. Dopo aver installato node3, avviarlo dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avvii del sistema. Vedere link:prepare_for_netboot.html["Preparatevi per il netboot"].

Tuttavia, non è necessario eseguire l'avvio di rete di node3 se è installata la stessa versione o una versione successiva di ONTAP 9 su node1.

[IMPORTANT]
====
* Per un aggiornamento del controller AFF A800 o AFF C800 , è necessario assicurarsi che tutte le unità nello chassis siano saldamente posizionate contro il midplane prima di rimuovere node1. Per maggiori informazioni, vedere link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sostituire i moduli controller AFF A800 o AFF C800"].
* Se si sta aggiornando un sistema con dischi di archiviazione, è necessario completare l'intera sezione e quindi andare a link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurare le porte FC sul nodo 3"] E link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Controllare e configurare le porte UTA/UTA2 sul nodo 3"] , immettendo comandi al prompt del cluster.


====
.Fasi
. [[man_install3_step1]]assicurarsi di disporre di spazio rack per node3.
+
Se node1 e node2 si trovano in uno chassis separato, è possibile inserire node3 nella stessa posizione rack del node1. Tuttavia, se il nodo 1 si trovava nello stesso chassis con il nodo 2, è necessario inserire il nodo 3 nel proprio spazio rack, preferibilmente vicino alla posizione del nodo 1.

. [[fase 2]]installare il nodo 3 nel rack seguendo le _istruzioni di installazione e configurazione_ relative al modello di nodo in uso.
+

NOTE: Se si esegue l'aggiornamento a un sistema con entrambi i nodi nello stesso chassis, installare node4 nello chassis e node3. In caso contrario, quando si avvia node3, il nodo si comporta come se fosse in una configurazione a doppio chassis e quando si avvia node4, l'interconnessione tra i nodi non si verificherà.

. [[step3]]cavo node3, spostamento delle connessioni da node1 a node3.
+
I seguenti riferimenti consentono di stabilire i collegamenti dei cavi corretti. Passare a. link:other_references.html["Riferimenti"] per collegarli.

+
** _Istruzioni di installazione e configurazione_ per la piattaforma node3
** La procedura di shelf di dischi appropriata
** La documentazione _ha Pair Management_


+
Collegare i seguenti cavi:

+
** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI
+

NOTE: Potrebbe non essere necessario spostare la scheda di interconnessione o la connessione del cavo di interconnessione del cluster dal nodo 1 al nodo 3, poiché la maggior parte dei modelli di piattaforma dispone di un modello di scheda di interconnessione unico. Per la configurazione MetroCluster, è necessario spostare le connessioni del cavo FC-VI dal nodo 1 al nodo 3. Se il nuovo host non dispone di una scheda FC-VI, potrebbe essere necessario spostare la scheda FC-VI.



. [[man_install3_step4]]accendere il computer su node3, quindi interrompere il processo di boot premendo Ctrl-C sul terminale della console per accedere al prompt dell'ambiente di boot.
+
Se si sta eseguendo l'aggiornamento a un sistema con entrambi i nodi nello stesso chassis, anche node4 viene riavviato. Tuttavia, è possibile ignorare il node4 boot fino a tardi.

+

NOTE: Quando si avvia node3, potrebbe essere visualizzato il seguente messaggio di avviso:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]se viene visualizzato il messaggio di avviso in <<man_install3_step4,Fase 4>>, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio venga completato.
+

WARNING: *Non ignorare il ritardo; se non si lascia caricare la batteria, si potrebbe verificare una perdita di dati.*



. Al prompt della modalità di manutenzione, immettere il seguente comando:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema a cui si esegue l'aggiornamento si trova in una... | Quindi... 


| Configurazione a doppio chassis (con controller in chassis diversi) | Vai a<<man_install3_step8,Fase 8>> . 


| Configurazione a unico chassis (con controller nello stesso chassis)  a| 
.. Spostare il cavo della console dal nodo 3 al nodo 4.
.. Accendere il dispositivo al nodo 4, quindi interrompere il processo di avvio premendo Ctrl-C sul terminale della console per accedere al prompt dell'ambiente di avvio.
+
L'alimentazione dovrebbe essere già attiva se entrambi i controller si trovano nello stesso chassis.

+

NOTE: Lasciare node4 al prompt dell'ambiente di boot; si tornerà a node4 in link:install_boot_node4.html["Installazione e boot node4"].

.. Se viene visualizzato il messaggio di avviso nella <<man_install3_step4,Fase 4>>, seguire le istruzioni in <<man_install3_step5,Fase 5>>
.. Riportare il cavo della console dal nodo 4 al nodo 3.
.. Vai a<<man_install3_step8,Fase 8>> .


|===
. [[man_install3_step8]]Configura node3 per ONTAP:
+
`set-defaults`


