= Configurare le porte FC sul nodo 3
:allow-uri-read: 




== Configurare le porte FC sul nodo 3

Se il nodo 3 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC da node1 salvati in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt del cluster.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti presenti sul sistema.
+
`system node hardware unified-connect show`

. Confronta le impostazioni FC del nodo 3 con le impostazioni acquisite in precedenza dal nodo 1.
. [[man_config_3_step3]]Esegui una delle seguenti azioni:
+
[cols="35,65"]
|===
| Se le impostazioni FC predefinite sui nuovi nodi sono... | Quindi... 


| Le stesse di quelle che hai catturato sul node1 | Vai a<<man_config_3_step9,Fase 9>> . 


| Diverso da quelli che avete catturato sul node1 | Vai a<<man_config_3_step4,Fase 4>> . 
|===
. [[man_config_3_step4]]Modificare le porte FC sul nodo 3 secondo necessità immettendo uno dei seguenti comandi:
+
** Per programmare le porte di destinazione:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Per programmare le porte initiator:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` È il tipo FC4: Destinazione o iniziatore.



. Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
+
`system node hardware unified-connect show`

. Uscire dalla modalità di manutenzione:
+
`halt`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Avviare node3 al prompt dell'ambiente di avvio:
+
`boot_ontap`

. [[man_config_3_step9]]Esegui una delle seguenti azioni:
+
** Se node3 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate, passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.
** Se node3 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate, saltare <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>> e passare a. link:map_ports_node1_node3.html["Mappare le porte dal nodo 1 al nodo 3"].



