= 
:allow-uri-read: 


Se si stanno aggiornando i controller con dischi interni, è necessario completare diversi comandi ed esaminarne l'output per confermare che nessuno dei dischi interni contiene aggregati root o aggregati di dati.

.A proposito di questa attività
Se non si stanno aggiornando controller con aggregati su dischi interni, saltare questa sezione e passare alla sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.Fasi
. Inserisci il nodeshell, una volta per ciascuno dei nodi originali.
+
`system node run -node _node_name_`

. Visualizzare le unità interne:
+
`sysconfig -av`

+
Il sistema visualizza informazioni dettagliate sulla configurazione del nodo, incluso lo storage, come mostrato nell'output parziale mostrato nell'esempio seguente:

+
....

node> sysconfig -av
slot 0: SAS Host Adapter 0a (PMC-Sierra PM8001 rev. C, SAS, UP)
                Firmware rev: 01.11.06.00
                 Base WWN: 5:00a098:0008a3b:b0
                 Phy State: [0] Enabled, 6.0 Gb/s
                            [1] Enabled, 6.0 Gb/s
                            [2] Enabled, 6.0 Gb/s
                            [3] Enabled, 6.0 Gb/s
                ID Vendor Model FW Size
                00.0 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.1 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.2 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.3 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.4 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.5 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.6 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.7 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.8 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.9 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.10: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.11: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
...
....
. Esaminare l'output dello storage di `sysconfig -av` per identificare i dischi interni e registrare le informazioni.
+
I dischi interni hanno "00". All'inizio del proprio ID. Il "00." indica uno shelf di dischi interno e il numero dopo il punto decimale indica il singolo disco.

. [[man_aggr_step4]]immettere il seguente comando su entrambi i controller:
+
`aggr status -r`

+
Il sistema visualizza lo stato aggregato del nodo, come mostrato nell'output parziale nell'esempio seguente:

+
[listing]
----
node> aggr status -r
Aggregate aggr2 (online, raid_dp, parity uninit'd!) (block checksums)
Plex /aggr2/plex0 (online, normal, active)
RAID group /aggr2/plex0/rg0 (normal, block checksums)

RAID Disk Device    HA SHELF BAY CHAN Pool Type RPM  Used (MB/blks)     Phys (MB/blks)
--------- --------- -- ----- --- ---- ---- ---- ---- ------------------ ------------------
dparity   0a.00.1   0a   0    1  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
parity    0a.00.3   0a   0    3  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
data      0a.00.9   0a   0    9  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
...
----
+

NOTE: Il dispositivo utilizzato per creare l'aggregato potrebbe non essere un disco fisico ma una partizione.

. Esaminare l'output di `aggr status -r` per identificare gli aggregati utilizzando dischi interni e registrare le informazioni.
+
Nell'esempio del passaggio precedente, "aggr2" utilizza dischi interni, come indicato dall'ID dello shelf "0".

. Immettere il seguente comando su entrambi i controller:
+
`aggr status -y`

+
Il sistema visualizza le informazioni sui volumi sull'aggregato, come mostrato nell'output parziale nell'esempio seguente:

+
....
node> aggr status -v
...
 aggr2   online   raid_dp, aggr    nosnap=off, raidtype=raid_dp, raidsize=14,
                  64-bit           raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off, resyncsnaptime=60,
                                   fs_size_fixed=off, lost_write_protect=on,
                                   ha_policy=cfo, hybrid_enabled=off, percent_snapshot_space=0%,
                                   free_space_realloc=off, raid_cv=on, thorough_scrub=off
         Volumes: vol6, vol5, vol14
...
 aggr0   online   raid_dp, aggr    root, diskroot, nosnap=off, raidtype=raid_dp,
                  64-bit           raidsize=14, raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off,  resyncsnaptime=60, fs_size_fixed=off,
                                   lost_write_protect=on, ha_policy=cfo, hybrid_enabled=off,
                                   percent_snapshot_space=0%, free_space_realloc=off, raid_cv=on
         Volumes: vol0
....
+
In base all'output in <<man_aggr_step4,Fase 4>> Fase 6, aggr2 utilizza tre dischi interni, "0a.00.1", "0a.00.3" e "0a.00.9", mentre i volumi su "aggr2" sono "vol6", "vol5" e "vol14". Inoltre, nell'output della fase 6, la lettura per "aggr0" contiene la parola "root" all'inizio delle informazioni per l'aggregato. Che indica che contiene un volume root.

. Esaminare l'output di `aggr status -v` comando per identificare i volumi appartenenti a qualsiasi aggregato presente su un disco interno e se uno di questi volumi contiene un volume root.
. Uscire dal nodeshell immettendo il seguente comando su ciascun controller:
+
`exit`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se i controller | Quindi... 


| Non contenere aggregati sui dischi interni | Continuare con questa procedura. 


| Contengono aggregati ma non volumi sui dischi interni  a| 
Continuare con questa procedura.


NOTE: Prima di continuare, è necessario posizionare gli aggregati offline, quindi distruggere gli aggregati sui dischi interni. Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento alla gestione di _dischi e aggregati con il contenuto CLI_ per informazioni sulla gestione degli aggregati.



| Contenere volumi non root sui dischi interni  a| 
Continuare con questa procedura.


NOTE: Prima di continuare, è necessario spostare i volumi su uno shelf di dischi esterno, posizionare gli aggregati offline e distruggere gli aggregati sui dischi interni. Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento alla gestione di _dischi e aggregati con il contenuto CLI_ per informazioni sullo spostamento dei volumi.



| Contenere volumi root sui dischi interni | Non continuare con questa procedura. È possibile aggiornare i controller facendo riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_ e utilizzare la procedura _aggiornamento dell'hardware del controller su una coppia di nodi che eseguono Clustered Data ONTAP spostando i volumi_. 


| Contengono volumi non root sui dischi interni e non è possibile spostare i volumi su uno storage esterno | Non continuare con questa procedura. È possibile aggiornare i controller utilizzando la procedura _aggiornamento dell'hardware del controller su una coppia di nodi che eseguono Clustered Data ONTAP spostando i volumi_. Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_, dove è possibile accedere a questa procedura. 
|===

