= 
:allow-uri-read: 


. Se la versione di ONTAP installata sul nodo 4 è la stessa o successiva alla versione di ONTAP 9 installata sul nodo 2, immettere il seguente comando:
+
`boot_ontap menu`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi... 


| Non dispone della versione ONTAP corretta o corrente sul nodo 4 | Passare a. <<man_install4_Step20,Fase 20>>. 


| Ha la versione corretta o attuale di ONTAP al nodo 4 | Passare a. <<man_install4_Step25,Fase 25>>. 
|===
. [[man_install4_Step20]]configurare la connessione di netboot scegliendo una delle seguenti operazioni.
+

NOTE: Come connessione di netboot, è necessario utilizzare la porta di gestione e l'indirizzo IP. Non utilizzare un indirizzo IP LIF dei dati, altrimenti potrebbe verificarsi un'interruzione dei dati durante l'aggiornamento.

+
[cols="35,75"]
|===
| Se DHCP (Dynamic host Configuration Protocol) è... | Quindi... 


| In esecuzione  a| 
Configurare la connessione automaticamente immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -auto`



| Non in esecuzione  a| 
Configurare manualmente la connessione immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` È l'indirizzo IP del sistema di storage (obbligatorio).
`_netmask_` è la maschera di rete del sistema di storage (obbligatoria).
`_gateway_` è il gateway per il sistema storage (obbligatorio).
`_dns_addr_` È l'indirizzo IP di un name server sulla rete (opzionale).
`_dns_domain_` È il nome di dominio DNS (Domain Name Service). Se si utilizza questo parametro opzionale, non è necessario un nome di dominio completo nell'URL del server netboot; è necessario solo il nome host del server.


NOTE: Potrebbero essere necessari altri parametri per l'interfaccia. Invio `help ifconfig` al prompt del firmware per ulteriori informazioni.

|===
. Eseguire il netboot al nodo 4:
+
[cols="30,70"]
|===
| Per... | Quindi... 


| Sistemi della serie FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| Tutti gli altri sistemi | `netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
Il `<path_to_the_web-accessible_directory>` dovrebbe portare alla posizione in cui è stato scaricato
`<ontap_version>_image.tgz` poll link:prepare_for_netboot.html#man_netboot_Step1["Fase 1"] Nella sezione _Prepare for netboot_.

+

NOTE: Non interrompere l'avvio.

. Dal menu di avvio, selezionare `option (7) Install new software first`.
+
Questa opzione di menu consente di scaricare e installare la nuova immagine Data ONTAP sul dispositivo di avvio.

+
Ignorare il seguente messaggio:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota si applica agli aggiornamenti senza interruzioni di Data ONTAP e non agli aggiornamenti dei controller.

+

NOTE: Utilizzare sempre netboot per aggiornare il nuovo nodo all'immagine desiderata. Se si utilizza un altro metodo per installare l'immagine sul nuovo controller, l'immagine potrebbe non essere corretta. Questo problema riguarda tutte le versioni di ONTAP. La procedura di netboot combinata con l'opzione `(7) Install new software` Consente di cancellare il supporto di avvio e di posizionare la stessa versione di ONTAP su entrambe le partizioni dell'immagine.

. [[man_install4_step23]] se viene richiesto di continuare la procedura, inserire y e, quando richiesto, inserire l'URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. Completare i seguenti passaggi secondari:
+
.. Invio `n` per ignorare il ripristino del backup quando viene visualizzato il seguente prompt:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Riavviare immettendo `y` quando viene visualizzato il seguente prompt:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Il modulo controller si riavvia ma si arresta al menu di avvio perché il dispositivo di avvio è stato riformattato e i dati di configurazione devono essere ripristinati.



. [[man_install4_Step25]]selezionare la modalità di manutenzione `5` dal menu di boot e premere `y` quando viene richiesto di continuare con l'avvio.
. [[man_install4_Step26]]prima di continuare, visitare il sito link:set_fc_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"] Apportare le modifiche necessarie alle porte FC o UTA/UTA2 del nodo. Apportare le modifiche consigliate in queste sezioni, riavviare il nodo e passare alla modalità di manutenzione.
. Immettere il seguente comando ed esaminare l'output per trovare l'ID di sistema di node4:
+
`disk show -a`

+
Il sistema visualizza l'ID di sistema del nodo e le informazioni relative ai dischi, come mostrato nell'esempio seguente:

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. Riassegnare le parti di ricambio di node2, i dischi appartenenti alla root e gli aggregati non root che non sono stati ricollocati in node3 precedentemente nella sezione link:relocate_non_root_aggr_node2_node3.html["Spostare gli aggregati non root dal nodo 2 al nodo 3"]:
+

NOTE: Se nel sistema sono presenti dischi condivisi, aggregati ibridi o entrambi, è necessario utilizzare il corretto `disk reassign` dalla seguente tabella.

+
[cols="35,65"]
|===
| Tipo di disco... | Eseguire il comando... 


| Con dischi condivisi | `disk reassign -s`

`_node2_sysid_ -d _node4_sysid_ -p _node3_sysid_` 


| Senza condivisione | `disks disk reassign -s`

`_node2_sysid_ -d _node4_sysid_` 
|===
+
Per `<node2_sysid>` utilizzare le informazioni acquisite in link:record_node2_information.html#man_node2_info_step10["Fase 10"] Della sezione _Record node2 information_. Per `_node4_sysid_`, utilizzare le informazioni acquisite in <<man_install4_step23,Fase 23>>.

+

NOTE: Il `-p` l'opzione è richiesta solo in modalità di manutenzione quando sono presenti dischi condivisi.

+
Il `disk reassign` command riassegna solo i dischi per i quali `_node2_sysid_` è il proprietario corrente.

+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
Invio `n` quando viene richiesto di interrompere la riassegnazione del disco.

+
Quando viene richiesto di interrompere la riassegnazione del disco, è necessario rispondere a una serie di richieste come indicato di seguito:

+
.. Il sistema visualizza il seguente messaggio:
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. Invio `y` per continuare.
+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. Invio `y` per consentire l'aggiornamento della proprietà del disco.


. Se si esegue l'aggiornamento da un sistema con dischi esterni a un sistema che supporta dischi interni ed esterni (ad esempio, sistemi A800), impostare node4 come root per confermare che si avvia dall'aggregato root di node2.
+

WARNING: *Attenzione: È necessario eseguire le seguenti procedure secondarie nell'ordine esatto indicato; in caso contrario, si potrebbe verificare un'interruzione o persino la perdita di dati.*

+
La seguente procedura imposta node4 per l'avvio dall'aggregato root di node2:

+
.. Controllare le informazioni su RAID, plex e checksum per l'aggregato node2:
+
`aggr status -r`

.. Controllare lo stato generale dell'aggregato node2:
+
`aggr status`

.. Se necessario, portare online l'aggregato node2:
+
`aggr_online root_aggr_from___node2__`

.. Impedire al node4 di avviarsi dal proprio aggregato root originale:
+
`aggr offline _root_aggr_on_node4_`

.. Impostare l'aggregato root node2 come nuovo aggregato root per node4:
+
`aggr options aggr_from___node2__ root`



. Verificare che il controller e lo chassis siano configurati come `ha` immettendo il seguente comando e osservando l'output:
+
`ha-config show`

+
L'esempio seguente mostra l'output di `ha-config show` comando:

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
I sistemi registrano in una PROM se si trovano in una coppia ha o in una configurazione standalone. Lo stato deve essere lo stesso su tutti i componenti all'interno del sistema standalone o della coppia ha.

+
Se il controller e lo chassis non sono configurati come `ha`, utilizzare i seguenti comandi per correggere la configurazione:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`.

+
Se si dispone di una configurazione MetroCluster, utilizzare i seguenti comandi per correggere la configurazione:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`.

. Distruggere le caselle di posta sul node4:
+
`mailbox destroy local`

. Uscire dalla modalità di manutenzione:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. Al nodo 3, controllare la data, l'ora e il fuso orario del sistema:
+
`date`

. Al nodo 4, controllare la data al prompt dell'ambiente di boot:
+
`show date`

. Se necessario, impostare la data sul node4:
+
`set date _mm/dd/yyyy_`

. Al nodo 4, controllare l'ora al prompt dell'ambiente di boot:
+
`show time`

. Se necessario, impostare l'ora su node4:
+
`set time _hh:mm:ss_`

. Verificare che l'ID del sistema partner sia impostato correttamente, come indicato nella <<man_install4_Step26,Fase 26>> in opzione.
+
`printenv partner-sysid`

. Se necessario, impostare l'ID di sistema del partner su node4:
+
`setenv partner-sysid _node3_sysid_`

+
.. Salvare le impostazioni:
+
`saveenv`



. Al prompt dell'ambiente di boot, accedere al menu di boot:
+
`boot_ontap menu`

. Nel menu di avvio, selezionare l'opzione *(6) Aggiorna flash dalla configurazione di backup* immettendo `6` quando richiesto.
+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. Invio `y` quando richiesto.
+
L'avvio procede normalmente e il sistema richiede di confermare la mancata corrispondenza dell'ID di sistema.

+

NOTE: Il sistema potrebbe riavviarsi due volte prima di visualizzare l'avviso di mancata corrispondenza.

. Confermare la mancata corrispondenza. Il nodo potrebbe completare un ciclo di riavvio prima di avviarsi normalmente.
. Accedere a node4.

