= 
:allow-uri-read: 


Il presente documento si basa sui seguenti presupposti:

* L'hardware del controller sostitutivo è nuovo e non è stato utilizzato.
+

WARNING: *Attenzione*: Poiché questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato, le fasi necessarie per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. Se in precedenza è stato utilizzato l'hardware del controller sostitutivo, è necessario contattare il supporto tecnico, in particolare se i controller eseguivano Data ONTAP in 7-Mode.

* Hai letto e compreso le linee guida per l'aggiornamento della coppia di nodi.
+

WARNING: *Attenzione*: Non tentare di cancellare il contenuto della NVRAM. Se è necessario eliminare il contenuto della NVRAM, contattare il supporto tecnico di NetApp.

* Si sta eseguendo il comando appropriato prima e dopo `modify` e confrontando l'output di entrambi `show` comandi per verificare che il `modify` comando riuscito.
* Se si dispone di una configurazione SAN, si dispone di LIF locali e partner per ciascuna macchina virtuale di storage (SVM), sulla coppia ha. Se non si dispone di LIF locali e partner per ogni SVM, è necessario aggiungere LA LIF dei dati SAN sul nodo remoto e locale per tale SVM prima di iniziare l'aggiornamento.
* Se si dispone di set di porte in una configurazione SAN, è necessario verificare che ogni set di porte associato contenga almeno un LIF da ciascun nodo della coppia ha.


Questa procedura utilizza il termine _prompt dell'ambiente di boot_ per fare riferimento al prompt di un nodo da cui è possibile eseguire determinate attività, come il riavvio del nodo e la stampa o l'impostazione di variabili ambientali. Il prompt viene a volte chiamato in modo informale _prompt del boot loader_.

Il prompt dell'ambiente di boot viene mostrato nell'esempio seguente:

[listing]
----
LOADER>
----