= 
:allow-uri-read: 


Il presente documento si basa sui seguenti presupposti:

* L'hardware del controller sostitutivo è nuovo e non è stato utilizzato.
+

WARNING: Poiché questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato, i passaggi necessari per preparare i controller usati con il `wipeconfig` comando non sono inclusi in questa procedura.  È necessario contattare l'assistenza tecnica se l'hardware del controller sostitutivo è stato utilizzato in precedenza, soprattutto se i controller eseguivano Data ONTAP in modalità 7.

* Hai letto e compreso le linee guida per l'aggiornamento della coppia di nodi.
+

WARNING: Non tentare di cancellare il contenuto NVRAM .  Se è necessario cancellare il contenuto della NVRAM, contattare l'assistenza tecnica NetApp .

* Si sta eseguendo il comando appropriato prima e dopo `modify` e confrontando l'output di entrambi `show` comandi per verificare che il `modify` comando riuscito.
* Se si dispone di una configurazione SAN, si dispone di LIF locali e partner per ciascuna macchina virtuale di storage (SVM), sulla coppia ha. Se non si dispone di LIF locali e partner per ogni SVM, è necessario aggiungere LA LIF dei dati SAN sul nodo remoto e locale per tale SVM prima di iniziare l'aggiornamento.
* Se si dispone di set di porte in una configurazione SAN, è necessario verificare che ogni set di porte associato contenga almeno un LIF da ciascun nodo della coppia ha.


Questa procedura utilizza il termine _prompt dell'ambiente di boot_ per fare riferimento al prompt di un nodo da cui è possibile eseguire determinate attività, come il riavvio del nodo e la stampa o l'impostazione di variabili ambientali. Il prompt viene a volte chiamato in modo informale _prompt del boot loader_.

Il prompt dell'ambiente di boot viene mostrato nell'esempio seguente:

[listing]
----
LOADER>
----