= 
:allow-uri-read: 


. [[man_install3_step17]]] se la versione di ONTAP installata su node3 è uguale o successiva alla versione di ONTAP 9 installata su node1, elencare e riassegnare i dischi al nuovo node3:
+
`boot_ontap`

+

WARNING: Se questo nuovo nodo è stato utilizzato in qualsiasi altro cluster o coppia ha, è necessario eseguire `wipeconfig` prima di procedere. In caso contrario, potrebbero verificarsi interruzioni del servizio o perdita di dati. Contattare il supporto tecnico se il controller sostitutivo è stato utilizzato in precedenza, in particolare se i controller eseguivano ONTAP in 7-Mode.

. Premere CTRL-C per visualizzare il menu di avvio.
. [[man_install3_step19]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi... 


| _Non_ ha la versione ONTAP corretta o corrente sul nodo 3 | Vai a<<man_install3_step13,Fase 13>> . 


| Ha la versione corretta o attuale di ONTAP al nodo 3 | Vai a<<man_install3_step18,Fase 18>> . 
|===
. [[man_install3_step13]]Configurare la connessione netboot scegliendo una delle seguenti azioni.
+

NOTE: È necessario utilizzare la porta di gestione e l'IP come connessione di netboot. Non utilizzare un IP LIF dei dati, altrimenti potrebbe verificarsi un'interruzione dei dati durante l'aggiornamento.

+
[cols="35,65"]
|===
| Se DHCP (Dynamic host Configuration Protocol) è... | Quindi... 


| In esecuzione | Configurare la connessione automaticamente immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -auto` 


| Non in esecuzione  a| 
Configurare manualmente la connessione immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` È l'indirizzo IP del sistema di storage (obbligatorio).
`_netmask_` è la maschera di rete del sistema di storage (obbligatoria).
`_gateway_` è il gateway per il sistema storage (obbligatorio).
`_dns_addr_` È l'indirizzo IP di un name server sulla rete (opzionale).
`_dns_domain_` È il nome di dominio DNS (Domain Name Service). Se si utilizza questo parametro opzionale, non è necessario un nome di dominio completo nell'URL del server netboot; è necessario solo il nome host del server.


NOTE: Potrebbero essere necessari altri parametri per l'interfaccia. Invio `help ifconfig` al prompt del firmware per ulteriori informazioni.

|===
. Eseguire netboot sul nodo 3:
+
[cols="35,65"]
|===
| Per... | Quindi... 


| Sistemi della serie FAS/AFF8000 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| Tutti gli altri sistemi | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
Il `<path_to_the_web-accessible_directory>` consente di accedere alla posizione in cui è stato scaricato `<ontap_version>_image.tgz` poll link:prepare_for_netboot.html#man_netboot_Step1["Fase 1"] Nella sezione _Prepare for netboot_.

+

NOTE: Non interrompere l'avvio.

. Dal menu di avvio, seleziona prima l'opzione *(7) Installa nuovo software*.
+
Questa opzione di menu consente di scaricare e installare la nuova immagine ONTAP sul dispositivo di avvio.

+
Ignorare il seguente messaggio:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota si applica agli aggiornamenti senza interruzioni di ONTAP e non agli aggiornamenti dei controller.

+

NOTE: Utilizzare sempre netboot per aggiornare il nuovo nodo all'immagine desiderata. Se si utilizza un altro metodo per installare l'immagine sul nuovo controller, l'immagine potrebbe essere errata. Questo problema riguarda tutte le versioni di ONTAP. La procedura di netboot combinata con l'opzione `(7) Install new software` Consente di cancellare il supporto di avvio e di posizionare la stessa versione di ONTAP ONTAP su entrambe le partizioni dell'immagine.

. Se ti viene chiesto di continuare la procedura, inserisci `y` e quando ti viene richiesto il pacchetto, inserisci il seguente URL:
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. Completare i seguenti passaggi secondari:
+
.. Invio `n` per ignorare il ripristino del backup quando viene visualizzato il seguente prompt:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Riavviare immettendo `y` quando viene visualizzato il seguente prompt:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Il modulo controller si riavvia ma si arresta al menu di avvio perché il dispositivo di avvio è stato riformattato e i dati di configurazione devono essere ripristinati.



. [[man_install3_step18]]Seleziona *(5) Avvio in modalità di manutenzione* inserendo `5` , e poi inserisci `y` quando viene richiesto di continuare con l'avvio.
. [[man_install3_step26]]prima di continuare, visitare il sito link:set_fc_uta_uta2_config_node3.html["Impostare la configurazione FC o UTA/UTA2 su node3"] Apportare le modifiche necessarie alle porte FC o UTA/UTA2 del nodo.
+
Apportare le modifiche consigliate in queste sezioni, riavviare il nodo e passare alla modalità di manutenzione.

. Trova l'ID di sistema del nodo 3:
+
`disk show -a`

+
Il sistema visualizza l'ID di sistema del nodo e le informazioni relative ai dischi, come mostrato nell'esempio seguente:

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: Potrebbe essere visualizzato il messaggio `disk show: No disks match option -a.` dopo aver immesso il comando. Non si tratta di un messaggio di errore, pertanto è possibile continuare con la procedura.

. [[man_install3_step21]]Riassegnare i dischi di riserva del nodo 1, tutti i dischi appartenenti alla radice e tutti gli aggregati non radice che non sono stati trasferiti in precedenza al nodo 2 inlink:relocate_non_root_aggr_node1_node2.html["Spostare gli aggregati non root dal nodo 1 al nodo 2"] .
+
Inserire il modulo appropriato di `disk reassign` comando basato sulla presenza di dischi condivisi nel sistema:

+

NOTE: Se nel sistema sono presenti dischi condivisi, aggregati ibridi o entrambi, è necessario utilizzare il corretto `disk reassign` dalla seguente tabella.

+
[cols="35,65"]
|===
| Se il tipo di disco è... | Quindi eseguire il comando... 


| Con dischi condivisi | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| Senza dischi condivisi | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
Per `_node1_sysid_` utilizzare le informazioni acquisite in link:record_node1_information.html["Registrare le informazioni del nodo 1"]. Per ottenere il valore per `_node3_sysid_`, utilizzare `sysconfig` comando.

+

NOTE: Il `-p` l'opzione è richiesta solo in modalità di manutenzione quando sono presenti dischi condivisi.

+
Il `disk reassign` il comando riassegna solo i dischi per i quali `_node1_sysid_` è il proprietario corrente.

+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]]Invio `n`.
+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]]Invio `y`
+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]]Invio `y`.
. [[man_install3_step32]]se si esegue l'aggiornamento da un sistema con dischi esterni a un sistema che supporta dischi interni ed esterni (ad esempio, sistemi AFF A800), impostare l'aggregato node1 come root per confermare che node3 si avvia dall'aggregato root di node1.
+

WARNING: *Attenzione*: È necessario eseguire le seguenti fasi secondarie nell'ordine esatto indicato; in caso contrario, si potrebbe verificare un'interruzione o addirittura la perdita di dati.

+
La seguente procedura imposta node3 per l'avvio dall'aggregato root di node1:

+
.. Controllare le informazioni su RAID, plex e checksum per l'aggregato node1:
+
`aggr status -r`

.. Controllare lo stato dell'aggregato node1:
+
`aggr status`

.. Se necessario, portare online l'aggregato node1:
+
`aggr_online _root_aggr_from_node1_`

.. Impedire al node3 di avviarsi dal proprio aggregato root originale:
`aggr offline _root_aggr_on_node3_`
.. Impostare l'aggregato root node1 come nuovo aggregato root per node3:
+
`aggr options _aggr_from_node1_ root`

.. Verificare che l'aggregato root di node3 sia offline e che l'aggregato root per i dischi portati da node1 sia online e impostato su root:
+
`aggr status`

+

NOTE: La mancata esecuzione del passaggio secondario precedente potrebbe causare l'avvio di node3 dall'aggregato root interno, oppure il sistema potrebbe presumere l'esistenza di una nuova configurazione del cluster o richiedere di identificarne una.

+
Di seguito viene riportato un esempio dell'output del comando:



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]]verificare che il controller e lo chassis siano configurati come `ha`:
+
`ha-config show`

+
L'esempio seguente mostra l'output del comando ha-config show:

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
I sistemi registrano in una ROM programmabile (PROM) se si trovano in una configurazione a coppia ha o standalone. Lo stato deve essere lo stesso su tutti i componenti all'interno del sistema standalone o della coppia ha.

+
Se il controller e lo chassis non sono configurati come "ha", utilizzare i seguenti comandi per correggere la configurazione:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Se si dispone di una configurazione MetroCluster, utilizzare i seguenti comandi per modificare il controller e lo chassis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]]distruggere le caselle di posta sul node3:
+
`mailbox destroy local`

+
La console visualizza il seguente messaggio:

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]]Invio `y` quando viene richiesto di confermare che si desidera distruggere le caselle postali locali.
. [[man_install3_step36]]Esci dalla modalità di manutenzione:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. [[man_install3_step37]]al node2, controllare la data, l'ora e il fuso orario del sistema:
+
`date`

. [[man_install3_step38]]al node3, controllare la data al prompt dell'ambiente di boot:
+
`show date`

. [[man_install3_step39]]se necessario, impostare la data su node3:
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]]al node3, controllare l'ora al prompt dell'ambiente di boot:
+
`show time`

. [[man_install3_step41]]se necessario, impostare l'ora su node3:
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]Verificare che l'ID del sistema partner sia impostato correttamente come indicato in<<man_install3_step21,Fase 21>> con l'opzione -p:
+
`printenv partner-sysid`

. [[man_install3_step43]]se necessario, impostare l'ID di sistema del partner su node3:
+
`setenv partner-sysid _node2_sysid_`

+
Salvare le impostazioni:

+
`saveenv`

. [[man_install3_step44]]accedere al menu di boot al prompt dell'ambiente di boot:
+
`boot_ontap menu`

. [[man_install3_step45]]dal menu di avvio, selezionare l'opzione *(6) Aggiorna flash dalla configurazione di backup* immettendo `6` quando richiesto.
+
Il sistema visualizza il seguente messaggio:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]]Invio `y` quando richiesto.
+
L'avvio procede normalmente e il sistema chiede di confermare la mancata corrispondenza dell'ID di sistema.

+

NOTE: Il sistema potrebbe riavviarsi due volte prima di visualizzare l'avviso di mancata corrispondenza.

. [[man_install3_step47]]confermare la mancata corrispondenza come mostrato nell'esempio seguente:
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
Il nodo potrebbe essere sottoposto a un ciclo di riavvio prima dell'avvio normale.

. [[man_install3_step48]]Accedi a node3.

