= 
:allow-uri-read: 


È necessario installare node4 nel rack, trasferire node2 connessioni al node4 e fare il boot node4. È inoltre necessario riassegnare eventuali spare node2, dischi appartenenti a root e aggregati non root che non sono stati riallocati in precedenza in node3.

.A proposito di questa attività
È necessario netboot node4 se non dispone della stessa versione di ONTAP 9 installata sul node2. Dopo aver installato node4, avviarlo dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avviamenti del sistema seguendo le istruzioni riportate in link:prepare_for_netboot.html["Preparatevi per il netboot"]

Tuttavia, non è necessario eseguire il netboot node4 se sul nodo è installata la stessa versione o successiva di ONTAP 9.

*Informazioni importanti:*

* Se si sta aggiornando un sistema V-Series o un sistema con software di virtualizzazione FlexArray collegato agli array di storage, è necessario completare la procedura <<man_install4_Step1,Fase 1>> attraverso <<man_install4_Step7,Fase 7>>, lasciare questa sezione all'indirizzo <<man_install4_Step8,Fase 8>> e seguire le istruzioni in link:set_fc_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"] Se necessario, immettere i comandi in modalità manutenzione. Quindi, tornare a questa sezione e riprendere la procedura in <<man_install4_Step9,Fase 9>>.
* Tuttavia, se si sta aggiornando un sistema con dischi di storage, è necessario completare l'intera sezione e passare alla sezione link:set_fc_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"], immettendo i comandi al prompt del cluster.


.Fasi
. [[man_install4_Step1]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se node4 sarà in ... | Quindi... 


| Uno chassis separato dal node3 | Passare a. <<man_install4_Step2,Fase 2>>. 


| Lo stesso chassis con node3 | Saltare i passaggi 2 e 3 e passare a. <<man_install4_Step4,Fase 4>>. 
|===
. [[man_install4_Step2]] assicurarsi che node4 disponga di spazio rack sufficiente.
+
Se il nodo 4 si trova in uno chassis separato dal nodo 3, è possibile inserire il nodo 4 nella stessa posizione del nodo 2. Se node3 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

. Installare il nodo 4 nel rack seguendo le istruzioni contenute nelle _istruzioni di installazione e configurazione_ relative al modello di nodo.
. [[man_install4_Step4]]cavo node4, spostamento delle connessioni da node2 a node4.
+
I seguenti riferimenti consentono di stabilire i collegamenti dei cavi corretti. Passare a. link:other_references.html["Riferimenti"] per collegarli.

+
** _Istruzioni per l'installazione e la configurazione_ o _requisiti e riferimenti per l'installazione della virtualizzazione FlexArray_ per la piattaforma node4
** La procedura di shelf di dischi appropriata
** La documentazione _ha Pair Management_
+
Collegare i seguenti cavi:

** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI


+

NOTE: Non è necessario spostare la scheda di interconnessione/scheda FC_VI o la connessione del cavo Interconnect/FC_VI dal nodo 2 al nodo 4, poiché la maggior parte dei modelli di piattaforma dispone di modelli di schede di interconnessione univoci.

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il nodo 4 è in... | Quindi... 


| Lo stesso chassis del node3 | Passare a. <<man_install4_Step8,Fase 8>>. 


| Uno chassis separato dal node3 | Passare a. <<man_install4_Step6,Fase 6>>. 
|===
. [[man_install4_Step6]]accendere l'alimentazione a node4, quindi interrompere l'avvio premendo Ctrl-C per accedere al prompt dell'ambiente di avvio.
+

NOTE: Quando si avvia node4, potrebbe essere visualizzato il seguente messaggio:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]se viene visualizzato il messaggio di avviso nella fase 6, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio sia terminato.
+

WARNING: *Attenzione: Non ignorare il ritardo. Il mancato caricamento della batteria potrebbe causare la perdita di dati.*



. [[man_install4_Step8]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi e non di storage back-end | Saltare i passaggi da 9 a 14 e passare a. <<man_install4_Step15,Fase 15>>. 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage  a| 
.. Andare alla sezione _set the FC or UTA/UTA2 Configuration on node4_ e completare le sezioni link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Configurare le porte FC sul nodo 4"] e. link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Controllare e configurare le porte UTA/UTA2 sul nodo 4"], in base al sistema in uso.
.. Tornare a questa sezione e completare i passaggi rimanenti, iniziando da <<man_install4_Step9,Fase 9>>.



IMPORTANT: Prima di avviare ONTAP sul sistema V-Series, è necessario riconfigurare le porte integrate FC, le porte integrate UTA/UTA2 e le schede UTA/UTA2.

|===
. [[man_install4_Step9]]aggiungere le porte FC Initiator del nuovo nodo alle zone di switch.
+
Per istruzioni, consultare la documentazione relativa allo storage array e allo zoning.

. Aggiungere le porte FC Initiator all'array di storage come nuovi host, mappando le LUN dell'array ai nuovi host.
+
Per istruzioni, consultare la documentazione relativa allo storage array e allo zoning.

. Modificare i valori WWPN (World Wide Port Name) nei gruppi di host o volumi associati alle LUN degli array di storage.
+
L'installazione di un nuovo modulo controller modifica i valori WWPN associati a ciascuna porta FC integrata.

. Se la configurazione utilizza lo zoning basato su switch, regolare lo zoning in modo che rifletta i nuovi valori WWPN.
. Verificare che i LUN degli array siano ora visibili al nodo 4 immettendo il seguente comando ed esaminandone l'output:
+
`sysconfig -v`

+
Il sistema visualizza tutti i LUN degli array visibili a ciascuna porta FC Initiator. Se le LUN dell'array non sono visibili, non è possibile riassegnare i dischi da node2 a node4 più avanti in questa sezione.

. Premere Ctrl-C per visualizzare il menu di avvio e selezionare la modalità di manutenzione.
. [[man_install4_Step15]]al prompt della modalità di manutenzione, immettere il seguente comando:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. Configurare il nodo 4 per ONTAP:
+
`set-defaults`


