= 
:allow-uri-read: 


È necessario installare node4 nel rack, trasferire node2 connessioni al node4 e fare il boot node4. È inoltre necessario riassegnare eventuali spare node2, dischi appartenenti a root e aggregati non root che non sono stati riallocati in precedenza in node3.

.A proposito di questa attività
È necessario eseguire l'avvio di rete del nodo 4 se la versione ONTAP sul nodo 4 è diversa dalla versione ONTAP sul nodo 2. Dopo aver installato node4, avviarlo dall'immagine ONTAP 9 memorizzata sul server web. È quindi possibile scaricare i file corretti sul dispositivo di supporto di avvio per i successivi avvii del sistema seguendo le istruzioni in link:prepare_for_netboot.html["Preparatevi per il netboot"]

Tuttavia, non è necessario eseguire l'avvio di rete del nodo 4 se la versione ONTAP sul nodo 4 è uguale o successiva alla versione ONTAP sul nodo 2.

[IMPORTANT]
====
* Per un aggiornamento del controller AFF A800 o AFF C800 , è necessario assicurarsi che tutte le unità nello chassis siano saldamente posizionate contro il midplane prima di rimuovere node2. Per maggiori informazioni, vedere link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sostituire i moduli controller AFF A800 o AFF C800"].
* Se si sta aggiornando un sistema con dischi di archiviazione, è necessario completare l'intera sezione e quindi procedere alla sezione link:set_fc_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"] , immettendo comandi al prompt del cluster.


====
.Fasi
. [[man_install4_Step1]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se node4 sarà in ... | Quindi... 


| Uno chassis separato dal node3 | Passare a. <<man_install4_Step2,Fase 2>>. 


| Lo stesso chassis con node3 | Saltare i passaggi 2 e 3 e passare a. <<man_install4_Step4,Fase 4>>. 
|===
. [[man_install4_Step2]] assicurarsi che node4 disponga di spazio rack sufficiente.
+
Se il nodo 4 si trova in uno chassis separato dal nodo 3, è possibile inserire il nodo 4 nella stessa posizione del nodo 2. Se node3 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

. Installare il nodo 4 nel rack seguendo le istruzioni contenute nelle _istruzioni di installazione e configurazione_ relative al modello di nodo.
. [[man_install4_Step4]]cavo node4, spostamento delle connessioni da node2 a node4.
+
I seguenti riferimenti consentono di stabilire i collegamenti dei cavi corretti. Passare a. link:other_references.html["Riferimenti"] per collegarli.

+
** _Istruzioni di installazione e configurazione_ per la piattaforma node4
** La procedura di shelf di dischi appropriata
** La documentazione _ha Pair Management_
+
Collegare i seguenti cavi:

** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI


+

NOTE: Non è necessario spostare la scheda di interconnessione/scheda FC_VI o la connessione del cavo Interconnect/FC_VI dal nodo 2 al nodo 4, poiché la maggior parte dei modelli di piattaforma dispone di modelli di schede di interconnessione univoci.

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il nodo 4 è in... | Quindi... 


| Lo stesso chassis del node3 | Passare a. <<man_install4_Step8,Fase 8>>. 


| Uno chassis separato dal node3 | Passare a. <<man_install4_Step6,Fase 6>>. 
|===
. [[man_install4_Step6]]accendere l'alimentazione a node4, quindi interrompere l'avvio premendo Ctrl-C per accedere al prompt dell'ambiente di avvio.
+

NOTE: Quando si avvia node4, potrebbe essere visualizzato il seguente messaggio:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]se viene visualizzato il messaggio di avviso nella fase 6, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio sia terminato.
+

WARNING: *Non ignorare il ritardo.  Se la batteria non viene caricata, si potrebbe verificare una perdita di dati.*



. [[man_install4_Step8]]Al prompt della modalità di manutenzione, immettere il seguente comando:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. Configurare il nodo 4 per ONTAP:
+
`set-defaults`


