---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 'Utilizzare la procedura di aggiornamento ARL manuale per aggiornare l"hardware del controller con ONTAP 9.7 o versione precedente, riallocando la proprietà di aggregati non root.' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa procedura descrive come aggiornare l'hardware del controller utilizzando ARL (aggregate relocation) per le seguenti configurazioni di sistema:

[cols="20,20,60"]
|===
| Metodo | Versione di ONTAP | Sistemi supportati 


| Aggiornamento manuale con ARL | 9.7 o versioni precedenti  a| 
* Dal sistema FAS al sistema FAS
* Da un sistema FAS a un sistema con software di virtualizzazione FlexArray o V-Series
* Dal sistema AFF al sistema AFF
* Sistema con software di virtualizzazione FlexArray o sistema V-Series su un sistema FAS, a condizione che il sistema con software di virtualizzazione FlexArray o sistema V-Series non disponga di LUN array.
* Da un sistema V-Series a un sistema con software di virtualizzazione FlexArray o un sistema V-Series


|===
Durante la procedura, l'hardware del controller originale viene aggiornato con l'hardware del controller sostitutivo, riallocando la proprietà degli aggregati non root. La migrazione degli aggregati viene eseguita più volte da un nodo all'altro per confermare che almeno un nodo fornisce i dati degli aggregati durante l'intera procedura di aggiornamento. Inoltre, è possibile migrare le interfacce logiche dei dati (LIF) e assegnare le porte di rete sul nuovo controller ai gruppi di interfacce durante la procedura.


NOTE: In questo documento, i nodi originali sono denominati _node1_ e _node2_, mentre i nuovi nodi sono denominati _node3_ e _node4_. Durante la procedura descritta, il node1 viene sostituito dal node3, mentre il node2 viene sostituito dal node4. I termini _node1_, _node2_, _node3_ e _node4_ vengono utilizzati solo per distinguere tra i nodi originali e quelli nuovi. Quando si segue la procedura, è necessario sostituire i nomi reali dei nodi originale e nuovo. Tuttavia, in realtà, i nomi dei nodi non cambiano: Node3 ha il nome node1 e node4 ha il nome node2 dopo l'aggiornamento dell'hardware del controller. Questo documento utilizza il termine _sistemi con software di virtualizzazione FlexArray_ per fare riferimento ai sistemi che appartengono a queste nuove piattaforme. Utilizza il termine _sistema V-Series_ per fare riferimento ai sistemi hardware separati che possono essere collegati agli array di storage

.Informazioni importanti:
* Questa procedura è complessa e presuppone che si disponga di competenze di amministrazione avanzate di ONTAP. È inoltre necessario leggere e comprendere link:guidelines_upgrade_with_arl.html["Linee guida per l'aggiornamento dei controller con ARL"] e a. link:arl_upgrade_workflow.html["Workflow di upgrade ARL"] prima di iniziare l'aggiornamento.
* Questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato. I passaggi necessari per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. Se in precedenza è stato utilizzato l'hardware del controller sostitutivo, è necessario contattare il supporto tecnico, in particolare se i controller eseguivano Data ONTAP in 7-Mode.
* È possibile utilizzare questa procedura per aggiornare l'hardware del controller nei cluster con più di due nodi; tuttavia, è necessario eseguire la procedura separatamente per ogni coppia di ha (High Availability) nel cluster.
* Questa procedura si applica ai sistemi FAS, V-Series, AFF e ai sistemi con software di virtualizzazione FlexArray. I sistemi FAS rilasciati dopo ONTAP 9 possono essere collegati agli array di storage se viene installata la licenza richiesta. I sistemi V-Series esistenti sono supportati in ONTAP 9. Per informazioni sui modelli di storage array e V-Series, fare riferimento a. link:other_references.html["Riferimenti"] Per il collegamento a _Hardware Universe_ e consultare la _matrice di supporto V-Series_.


* Questa procedura si applica alle configurazioni MetroCluster a quattro e otto nodi che eseguono ONTAP 9.5 e versioni precedenti. Per le configurazioni MetroCluster con ONTAP 9.6 e versioni successive, visitare il sito Web all'indirizzo link:other_references.html["Riferimenti"] Per collegarsi a _utilizzando i comandi "sostituzione controller di sistema" per aggiornare l'hardware del controller che esegue ONTAP 9,5 a ONTAP 9,7_.

