---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: 'Utilizzare la procedura di aggiornamento ARL manuale per aggiornare l"hardware del controller con ONTAP 9.7 o versione precedente, riallocando la proprietà di aggregati non root.' 
---
= Scopri di più sulla procedura di aggiornamento ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa procedura descrive come aggiornare l'hardware del controller utilizzando la rilocazione manuale degli aggregati (ARL) sui sistemi che eseguono ONTAP 9.7 o versioni precedenti.

È possibile utilizzare questa procedura ARL se si sta eseguendo uno dei seguenti aggiornamenti:

* Dal sistema FAS al sistema FAS
* Dal sistema AFF al sistema AFF


Durante la procedura, l'hardware del controller originale viene aggiornato con l'hardware del controller sostitutivo, riallocando la proprietà degli aggregati non root. La migrazione degli aggregati viene eseguita più volte da un nodo all'altro per confermare che almeno un nodo fornisce i dati degli aggregati durante l'intera procedura di aggiornamento. Inoltre, è possibile migrare le interfacce logiche dei dati (LIF) e assegnare le porte di rete sul nuovo controller ai gruppi di interfacce durante la procedura.


NOTE: In questo documento, i nodi originali sono chiamati _node1_ e _node2_, mentre i nuovi nodi sono chiamati _node3_ e _node4_.  Durante la procedura descritta, il nodo 1 viene sostituito dal nodo 3 e il nodo 2 viene sostituito dal nodo 4.  I termini _node1_, _node2_, _node3_ e _node4_ vengono utilizzati solo per distinguere tra i nodi originali e quelli nuovi.  Quando si segue la procedura, è necessario sostituire i nomi reali dei nodi originali e nuovi.  Tuttavia, in realtà, i nomi dei nodi non cambiano: node3 ha il nome node1 e node4 ha il nome node2 dopo l'aggiornamento dell'hardware del controller.

.Informazioni importanti:
* Questa procedura è complessa e presuppone che si disponga di competenze di amministrazione avanzate di ONTAP. Devi anche leggere e comprendere il link:guidelines_upgrade_with_arl.html["linee guida per l'aggiornamento dei controller con ARL"] e il link:arl_upgrade_workflow.html["Workflow di upgrade ARL"] prima di iniziare l'aggiornamento.
* Questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato. I passaggi necessari per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. Se in precedenza è stato utilizzato l'hardware del controller sostitutivo, è necessario contattare il supporto tecnico, in particolare se i controller eseguivano Data ONTAP in 7-Mode.
* È possibile utilizzare questa procedura per aggiornare l'hardware del controller nei cluster con più di due nodi; tuttavia, è necessario eseguire la procedura separatamente per ogni coppia di ha (High Availability) nel cluster.


* Questa procedura si applica alle configurazioni MetroCluster a quattro e otto nodi che eseguono ONTAP 9.5 e versioni precedenti. Per le configurazioni MetroCluster con ONTAP 9.6 e versioni successive, visitare il sito Web all'indirizzo link:other_references.html["Riferimenti"] Per collegarsi a _utilizzando i comandi "sostituzione controller di sistema" per aggiornare l'hardware del controller che esegue ONTAP 9,5 a ONTAP 9,7_.

