---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: Verificare che le porte fisiche sul nodo 1 siano mappate correttamente sul nodo 3 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti. 
---
= Mappare le porte dal nodo 1 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario assicurarsi che le porte fisiche sul nodo 1 siano mappate correttamente alle porte fisiche sul nodo 3, che consentirà al nodo 3 di comunicare con gli altri nodi del cluster e con la rete dopo l'aggiornamento.

.Prima di iniziare
È necessario disporre già delle informazioni relative alle porte sui nuovi nodi di _Hardware Universe_. (Passare a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_). Le informazioni vengono utilizzate più avanti in questa sezione e in link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"].

La configurazione software del nodo 3 deve corrispondere alla connettività fisica del nodo 3 e la connettività IP deve essere ripristinata prima di continuare con l'aggiornamento.

.A proposito di questa attività
Le impostazioni delle porte possono variare a seconda del modello dei nodi.

È necessario rendere la porta e la configurazione LIF del nodo originale compatibili con la configurazione del nuovo nodo. Questo perché il nuovo nodo riproduce la stessa configurazione all'avvio, il che significa che quando si avvia node3, ONTAP tenterà di ospitare le LIF sulle stesse porte utilizzate sul node1.

Pertanto, se le porte fisiche sul nodo 1 non vengono mappate direttamente alle porte fisiche sul nodo 3, saranno necessarie modifiche alla configurazione del software per ripristinare la connettività di cluster, gestione e rete dopo l'avvio. Inoltre, se le porte del cluster sul nodo 1 non vengono mappate direttamente alle porte del cluster sul nodo 3, il nodo 3 potrebbe non ricongiungersi automaticamente al quorum quando viene riavviato fino a quando non viene apportata una modifica alla configurazione software per ospitare le LIF del cluster sulle porte fisiche corrette.

.Fasi
. [[step1]]Registra tutte le informazioni di cablaggio node1 per node1, le porte, i domini di trasmissione e gli spazi IPnella seguente tabella:
+
[cols=""35"]
|===
| LIF | Node1 porte | Node1 IPspaces | Dominio di broadcast node1 | Node3 porte | Node3 porte | Node3 domini di broadcast 


| Cluster 1 |  |  |  |  |  |  


| Cluster 2 |  |  |  |  |  |  


| Cluster 3 |  |  |  |  |  |  


| Cluster 4 |  |  |  |  |  |  


| Cluster 5 |  |  |  |  |  |  


| Cluster 6 |  |  |  |  |  |  


| Gestione dei nodi |  |  |  |  |  |  


| Gestione del cluster |  |  |  |  |  |  


| Dati 1 |  |  |  |  |  |  


| Dati 2 |  |  |  |  |  |  


| Dati 3 |  |  |  |  |  |  


| Dati 4 |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| Porta intercluster |  |  |  |  |  |  
|===
+
Fare riferimento a. link:record_node1_information.html["Registrare le informazioni del nodo 1"] per ottenere queste informazioni.

. [[step2]]registrare tutte le informazioni di cablaggio per node3, le porte, i domini di trasmissione e gli spazi IPnella tabella precedente utilizzando la stessa procedura descritta in link:record_node1_information.html["Registrare le informazioni del nodo 1"].
. [[fase 3]]seguire questi passaggi per verificare se l'installazione è un cluster senza switch a due nodi:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`cluster::> set -privilege advanced`

.. Verificare se il setup è un cluster senza switch a due nodi:
+
`network options switchless-cluster show`

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
Il valore di questo comando deve corrispondere allo stato fisico del sistema.

.. Tornare al livello di privilegi di amministrazione:
+
[listing]
----
 cluster::*> set -privilege admin
 cluster::>
----


. [[step4]]inserire il node3 nel quorum effettuando le seguenti operazioni:
+
.. Punto di avvio3. Vedere link:install_boot_node3.html["Installazione e boot node3"] per avviare il nodo, se non è già stato fatto.
.. Verificare che le nuove porte del cluster si trovino nel dominio di trasmissione del cluster:
+
`network port show -node _node-name_ -port _port-name_ -fields broadcast-domain`

+
L'esempio seguente mostra che la porta "e0a" si trova nel dominio "Cluster" sul nodo 3:

+
[listing]
----
 cluster::> network port show -node node3 -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e1a  Cluster
----
.. Aggiungere le porte corrette al dominio di trasmissione del cluster:
+
`network port modify -node _node-name_ -port _port-name_ -ipspace Cluster -mtu 9000`

+
Questo esempio aggiunge la porta cluster "e1b" al nodo 3:

+
[listing]
----
 network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
+

NOTE: Per una configurazione MetroCluster, potrebbe non essere possibile modificare il dominio di trasmissione di una porta perché è associata a una porta che ospita la LIF di una SVM di destinazione di sincronizzazione e visualizzare errori simili, ma non limitati al seguente messaggio`:

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
Immettere il seguente comando dalla SVM di origine di sincronizzazione corrispondente sul sito remoto per riallocare la LIF di destinazione di sincronizzazione su una porta appropriata:

+
`metrocluster vserver resync -vserver _Vserver-name_`

.. Migrare le LIF del cluster alle nuove porte, una volta per ogni LIF:
+
`network interface migrate -vserver Cluster -lif _LIF-name_ -source-node _node3_ -destination-node _node3_ -destination-port _port-name_`

.. Modificare la porta home delle LIF del cluster:
+
`network interface modify -vserver Cluster -lif _LIF-name_ –home-port _port-name_`

.. Se le porte del cluster non si trovano nel dominio di broadcast del cluster, aggiungerle:
+
`network port broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports _node:port_`

.. Rimuovere le vecchie porte dal dominio di trasmissione del cluster:
+
`network port broadcast-domain remove-ports`

+
Nell'esempio seguente viene rimossa la porta "e0d" sul nodo 3:

+
[listing]
----
network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports <node3:e0d>
----
.. Verificare che node3 si sia riUnito al quorum:
+
`cluster show -node _node3_ -fields health`



. [[man_map_1_step5]]regola i domini di broadcast che ospitano le LIF del cluster e le LIF di gestione dei nodi e/o del cluster. Verificare che ciascun dominio di trasmissione contenga le porte corrette. Una porta non può essere spostata tra domini di broadcast se è in hosting o è la sede di una LIF, quindi potrebbe essere necessario migrare e modificare le LIF come segue:
+
.. Visualizzare la porta home di una LIF:
+
`network interface show -fields _home-node,home-port_`

.. Visualizza il dominio di trasmissione contenente questa porta:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Aggiungere o rimuovere le porte dai domini di broadcast:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modificare la porta home di una LIF:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF-name_ –home-port _port-name_`



. [[man_map_1_step6]]regola i domini di trasmissione tra cluster e migra le LIF tra cluster, se necessario, utilizzando gli stessi comandi mostrati nella <<man_map_1_step5,Fase 5>>.
. [[step7]]regolare qualsiasi altro dominio di broadcast e migrare i dati LIF, se necessario, utilizzando gli stessi comandi illustrati nella <<man_map_1_step5,Fase 5>>.
. [[step8]]se vi sono porte sul node1 che non esistono più sul node3, attenersi alla seguente procedura per eliminarle:
+
.. Accedere al livello di privilegio avanzato su uno dei nodi:
+
`set -privilege advanced`

.. Eliminare le porte:
+
`network port delete -node _node-name_ -port _port-name_`

.. Tornare al livello di amministrazione:
+
`set -privilege admin`



. [[step9]]regola tutti i gruppi di failover LIF:
+
`network interface modify -failover-group _failover-group_ -failover-policy _failover-policy_`

+
Nell'esempio seguente viene impostato il criterio di failover su "broadcast-domain-wide" e vengono utilizzate le porte del gruppo di failover "fg1" come destinazioni di failover per LIF "data1" su "node3":

+
[listing]
----
network interface modify -vserver node3 -lif data1 failover-policy broadcast-domainwide -failover-group fg1
----
+
Passare a. link:other_references.html["Riferimenti"] Per ulteriori informazioni, fare riferimento a _Gestione di rete_ o ai comandi di _ONTAP 9: Manuale di riferimento pagina_.

. Verificare le modifiche al nodo 3:
+
`network port show -node node3`

. Ogni LIF del cluster deve essere in ascolto sulla porta 7700. Verificare che le LIF del cluster siano in ascolto sulla porta 7700:
+
`::> network connections listening show -vserver Cluster`

+
La porta 7700 in ascolto sulle porte del cluster è il risultato previsto, come mostrato nell'esempio seguente per un cluster a due nodi:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. Per ogni cluster LIF che non è in ascolto sulla porta 7700, imposta lo stato amministrativo della LIF su `down` e poi `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Ripetere il passaggio 11 per verificare che la LIF del cluster sia in ascolto sulla porta 7700.


