---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html 
keywords: move, nas, san, lif, ports, broadcast domain, node1, node2, node3 
summary: Spostare le LIF dei dati NAS node1 sul node2 da node2 a node3 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti. 
---
= Spostare le LIF dei dati NAS di proprietà del node1 da node2 a node3 e verificare le LIF SAN sul node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver verificato l'installazione di node3 e prima di spostare gli aggregati da node2 a node3, è necessario spostare i dati NAS LIF appartenenti a node1 che sono attualmente su node2 da node2 a node3. È inoltre necessario verificare le LIF SAN sul nodo 3.

.A proposito di questa attività
Le LIF remote gestiscono il traffico verso le LUN SAN durante la procedura di aggiornamento. Lo spostamento delle LIF SAN non è necessario per lo stato del cluster o del servizio durante l'aggiornamento. LE LIF SAN non vengono spostate a meno che non sia necessario mapparle su nuove porte. Dopo aver portato il nodo 3 online, verrete a verificare che i file LIF siano integri e posizionati sulle porte appropriate.

.Fasi
. [[step1]]Elenca tutte le LIF dati NAS non possedute da node2 immettendo il seguente comando su entrambi i nodi e catturando l'output:
+
`network interface show -role data -curr-node _node2_ -is-home false -home-node _node3_`

. [[worksheet_step2]]se il cluster è configurato per le LIF SAN, registrare le LIF SAN `adapter` e. `switch-port` informazioni di configurazione in questo link:worksheet_information_before_moving_san_lifs_node3.html["foglio di lavoro"] da utilizzare in seguito nella procedura.
+
.. Elencare le LIF SAN sul node2 ed esaminare l'output:
+
`network interface show -data-protocol fc*`

+
Il sistema restituisce un output simile al seguente esempio:

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. Elencare le configurazioni esistenti ed esaminare l'output:
+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Il sistema restituisce un output simile al seguente esempio:

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. [[step3]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se nodo1... | Quindi... 


| Ha configurato gruppi di interfacce o VLAN | Passare a. <<man_lif_verify_3_step3,Fase 4>>. 


| Non sono stati configurati gruppi di interfacce o VLAN | Saltare la fase 4 e passare a. <<man_lif_verify_3_step4,Fase 5>>. 
|===
. [[man_lif_verify_3_step3]]eseguire i seguenti passaggi secondari per migrare qualsiasi LIF di dati NAS ospitata su gruppi di interfacce e VLAN originariamente presenti sul nodo 1 da node2 a node3:
+
.. [[man_lif_verify_3_substepa]]Migrate qualsiasi LIF di dati ospitata su node2 che in precedenza apparteneva a node1 su un gruppo di interfacce a una porta sul node3 in grado di ospitare LIF sulla stessa rete immettendo il seguente comando, una volta per ogni LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Modificare la porta home e il nodo home di LIF in <<man_lif_verify_3_substepa,Sotto-fase A.>> Alla porta e al nodo che attualmente ospitano le LIF immettendo il seguente comando, una volta per ciascuna LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node3_ -home-port _netport|ifgrp_`

.. [[man_lif_verify_3_substepc]]Migrare tutti i dati LIF ospitati su node2 che in precedenza appartenevano a node1 su una porta VLAN a una porta su node3 in grado di ospitare LIF sulla stessa rete immettendo il seguente comando, una volta per ogni LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ –destination-port _netport|ifgrp_`

.. Modificare la porta home e il nodo home dei file LIF in <<man_lif_verify_3_substepc,Sotto-fase c>> Alla porta e al nodo che attualmente ospitano le LIF immettendo il seguente comando, una volta per ciascuna LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node3_ -home-port _netport|ifgrp_`



. [[man_lif_verify_3_step4]]eseguire una delle seguenti operazioni:
+
[cols="25,75"]
|===
| Se il cluster è configurato per... | Quindi... 


| NAS | Completo <<man_lif_verify_3_step5,Fase 6>> e. <<man_lif_verify_3_step6,Fase 7>>, Saltare il passaggio 8 e completare <<man_lif_verify_3_step8,Fase 9>> attraverso <<man_lif_verify_3_step11,Fase 12>>. 


| SAN | Disattivare tutte le LIF SAN sul nodo per disattivarle per l'aggiornamento:
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_lif_verify_3_step5]]se si dispone di porte dati non uguali sulle piattaforme, aggiungere le porte al dominio di trasmissione:
+
`network port broadcast-domain add-ports -ipspace _IPspace_name_ -broadcast-domain mgmt -ports _node:port_`

+
Nell'esempio seguente viene aggiunta la porta "e0a" sul nodo "6280-1" e la porta "e0i" sul nodo "8060-1" al dominio di trasmissione "mgmt" nell'IPSpace "Default":

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. [[man_lif_verify_3_step6]]Migrare ciascun LIF dati NAS in node3 immettendo il seguente comando, una volta per ogni LIF:
+
`network interface migrate -vserver _vserver_name_ -lif _LIF_name_ -destination-node _node3_ -destination-port _netport|ifgrp_`

. [[man_lif_verify_3_step7]]assicurarsi che la migrazione dei dati sia persistente:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_-home-port _netport|ifgrp_ -home-node _node3_`

. [[man_lif_verify_3_step8]]verificare che le LIF SAN si trovino sulle porte corrette sul nodo 3:
+
.. Immettere il seguente comando ed esaminarne l'output:
+
`network interface show -data-protocol iscsi|fcp -home-node _node3_`

+
Il sistema restituisce un output simile al seguente esempio:

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. Verificare che i nuovi e. `adapter` e. `switch-port` le configurazioni sono corrette confrontando l'output di `fcp adapter show` con le informazioni di configurazione registrate nel foglio di lavoro in <<worksheet_step2,Fase 2>>.
+
Elencare le nuove configurazioni LIF SAN al nodo 3:

+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Il sistema restituisce un output simile al seguente esempio:

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node        adapter fc-wwpn                 switch-port
----------- ------- ----------------------- -------------
cluster1-01 0a      50:0a:09:82:9c:13:38:00 ACME Switch:0
cluster1-01 0b      50:0a:09:82:9c:13:38:01 ACME Switch:1
cluster1-01 0c      50:0a:09:82:9c:13:38:02 ACME Switch:2
cluster1-01 0d      50:0a:09:82:9c:13:38:03 ACME Switch:3
cluster1-01 0e      50:0a:09:82:9c:13:38:04 ACME Switch:4
cluster1-01 0f      50:0a:09:82:9c:13:38:05 ACME Switch:5
cluster1-01 1a      50:0a:09:82:9c:13:38:06 ACME Switch:6
cluster1-01 1b      50:0a:09:82:9c:13:38:07 ACME Switch:7
cluster1-02 0a      50:0a:09:82:9c:6c:36:00 ACME Switch:0
cluster1-02 0b      50:0a:09:82:9c:6c:36:01 ACME Switch:1
cluster1-02 0c      50:0a:09:82:9c:6c:36:02 ACME Switch:2
cluster1-02 0d      50:0a:09:82:9c:6c:36:03 ACME Switch:3
cluster1-02 0e      50:0a:09:82:9c:6c:36:04 ACME Switch:4
cluster1-02 0f      50:0a:09:82:9c:6c:36:05 ACME Switch:5
cluster1-02 1a      50:0a:09:82:9c:6c:36:06 ACME Switch:6
cluster1-02 1b      50:0a:09:82:9c:6c:36:07 ACME Switch:7
16 entries were displayed
----
+

NOTE: Se un LIF SAN nella nuova configurazione non si trova su un adattatore ancora collegato allo stesso `switch-port`, potrebbe causare un'interruzione del sistema quando si riavvia il nodo.

.. Se node3 ha LIF SAN o gruppi DI LIF SAN che si trovano su una porta che non esisteva sul node1 o che devono essere mappati su una porta diversa, spostarli su una porta appropriata sul node3 completando i seguenti passaggi secondari:
+
... Impostare lo stato LIF su "DOWN" (giù):
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin down`

... Rimuovere la LIF dal set di porte:
+
`portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

... Immettere uno dei seguenti comandi:
+
**** Spostare una singola LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-port _new_home_port_`

**** Spostare tutte le LIF su una singola porta inesistente o errata su una nuova porta:
+
`network interface modify {-home-port _port_on_node1_ -home-node _node1_ -role data} -home-port _new_home_port_on_node3_`

**** Aggiungere nuovamente i file LIF al set di porte:
+
`portset add -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

+

NOTE: È necessario spostare I file LIF SAN su una porta con la stessa velocità di collegamento della porta originale.







. Modificare lo stato di tutte le LIF su "up" in modo che le LIF possano accettare e inviare traffico sul nodo:
+
`network interface modify -home-port _port_name_ -home-node _node3_ -lif data -status-admin up`

. Immettere il seguente comando su uno dei nodi ed esaminare l'output per verificare che le LIF siano state spostate nelle porte corrette e che le LIF abbiano lo stato di "up" immettendo il seguente comando su uno dei nodi ed esaminando l'output:
+
`network interface show -home-node _node3_ -role data`

. [[man_lif_verify_3_step11]] se le LIF non sono attive, impostare lo stato amministrativo delle LIF su "up" immettendo il seguente comando, una volta per ciascuna LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin up`

. Invia un messaggio AutoSupport post-upgrade a NetApp per il node1:
+
`system node autosupport invoke -node _node3_ -type all -message "node1 successfully upgraded from _platform_old_ to _platform_new_"`


