---
sidebar: sidebar 
permalink: upgrade-arl-manual/reboots_panics_power_cycles.html 
keywords: crash, reboot, node1, node2, node3, node4, upgrade 
summary: 'Il sistema potrebbe bloccarsi (riavvio, panico o ciclo di alimentazione) durante le diverse fasi di un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti.' 
---
= Riavvio, panic o cicli di alimentazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il sistema potrebbe bloccarsi (riavvio, panico o ciclo di alimentazione) durante diverse fasi dell'aggiornamento. La soluzione a questi problemi dipende da quando si verificano.



== Riavvio, panic o cicli di alimentazione durante la fase 2

Gli arresti anomali possono verificarsi prima, durante o subito dopo la fase 2, durante la quale si spostano gli aggregati da node1 a node2, si spostano le LIF dei dati e LE LIF SAN di proprietà di node1 in node2, si registrano le informazioni node1 e si ritirano node1.



=== Node1 o node2 si blocca prima della fase 2 con ha ancora attivato

Se node1 o node2 si bloccano prima della fase 2, nessun aggregato è stato ancora trasferito e la configurazione ha è ancora attivata.

.A proposito di questa attività
Il takeover e il giveback possono procedere normalmente.

.Fasi
. Verificare la presenza di messaggi EMS emessi dal sistema nella console ed eseguire l'azione correttiva consigliata.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node1 si blocca durante o subito dopo la fase 2 con ha ancora attivato

Alcuni o tutti gli aggregati sono stati spostati da node1 a node2 e HA è ancora abilitata. Node2 assume il controllo del volume root di node1 e di tutti gli aggregati non root che non sono stati spostati.

.A proposito di questa attività
La proprietà degli aggregati che sono stati ricollocati appare uguale alla proprietà degli aggregati non root che sono stati acquisiti perché il proprietario home non è cambiato. Quando node1 entra nel  `waiting for giveback state`, node2 restituisce tutti gli aggregati non root di node1.

.Fasi
. Completarelink:relocate_non_root_aggr_node1_node2.html#relocate-step1["Fase 1"] nella sezione _Spostare gli aggregati non radice dal nodo 1 al nodo 2_ di nuovo.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node1 si blocca dopo la fase 2 mentre ha è disattivato

Node2 non prende il controllo, ma sta ancora fornendo dati da tutti gli aggregati non root.

.Fasi
. Far salire il node1.
. Continuare con la procedura di aggiornamento della coppia di nodi.
+
È possibile che vengano visualizzate alcune modifiche nell'output di `storage failover show` comando, ma questo è tipico e non influisce sulla procedura. Consultare la sezione relativa alla risoluzione dei problemi link:issues_multiple_stages_of_procedure.html#storage-failover-command["Il failover dello storage non previsto mostra l'output del comando"].





=== Node2 non funziona durante o dopo la fase 2 con ha ancora attivato

Node1 ha trasferito alcuni o tutti i suoi aggregati al node2. HA è attivato.

.A proposito di questa attività
Node1 assume il controllo di tutti gli aggregati di Node2, nonché di tutti i propri aggregati che aveva trasferito a Node2. Quando Node2 entra nello  `Waiting for Giveback` stato, Node1 restituisce tutti gli aggregati di Node2.

.Fasi
. Completarelink:relocate_non_root_aggr_node1_node2.html#relocate-step1["Fase 1"] nella sezione _Spostare gli aggregati non radice dal nodo 1 al nodo 2_ di nuovo.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node2 si blocca dopo la fase 2 e dopo la disattivazione di ha

Node1 non prende il posto.

.Fasi
. Alzati il node2.
+
Si verifica un'interruzione del servizio per tutti gli aggregati durante l'avvio di node2.

. Continuare con il resto della procedura di aggiornamento della coppia di nodi.




== Riavvio, panic o cicli di alimentazione durante la fase 3

Gli errori possono verificarsi durante o subito dopo la fase 3, durante la quale si installa e si avvia node3, si mappano le porte da node1 a node3, si spostano le LIF dei dati e LE LIF SAN appartenenti a node1 e node2 in node3 e si spostano tutti gli aggregati da node2 a node3.



=== Node2 si blocca durante la fase 3 con ha disattivato e prima di spostare qualsiasi aggregato

Il nodo3 non subentra dopo un arresto anomalo del nodo2 poiché l'HA è già disabilitato.

.Fasi
. Alzati il node2.
+
Si verifica un'interruzione del servizio per tutti gli aggregati durante l'avvio di node2.

. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node2 si blocca durante la fase 3 dopo aver riallocato alcuni o tutti gli aggregati

Il nodo2 ha spostato alcuni o tutti i suoi aggregati su nodo3, che serve dati dagli aggregati che sono stati rilocati. HA è disabilitato.

.A proposito di questa attività
Si è verificato un disservizio per gli aggregati che non sono stati ricollocati.

.Fasi
. Alzati il node2.
. Riposizionare gli aggregati rimanenti completandolink:relocate_non_root_aggr_node2_node3.html#verify-partner-sys-id["Fase 1"] Attraversolink:relocate_non_root_aggr_node2_node3.html#relocate-step5["Fase 5"] nella sezione _Spostare gli aggregati non radice dal nodo 2 al nodo 3_.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node3 si blocca durante la fase 3 e prima che node2 abbia riallocato gli aggregati

Node2 non prende il controllo, ma sta ancora fornendo dati da tutti gli aggregati non root.

.Fasi
. Alzati il node3.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node3 si blocca durante la fase 3 durante il trasferimento dell'aggregato

Se il nodo3 si arresta in modo anomalo mentre il nodo2 sta spostando gli aggregati sul nodo3, il nodo2 interrompe lo spostamento di tutti gli aggregati rimanenti.

.A proposito di questa attività
Node2 continua a servire gli aggregati rimanenti, ma gli aggregati che erano già stati ricollocati in node3 incontrano un'interruzione del client durante l'avvio di node3.

.Fasi
. Alzati il node3.
. Completarelink:relocate_non_root_aggr_node2_node3.html#relocate-step5["Fase 5"] di nuovo nella sezione _Spostare gli aggregati non radice dal nodo 2 al nodo 3_.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node3 non riesce ad avviarsi dopo il blocco nella fase 3

A causa di un guasto catastrofico, il node3 non può essere avviato in seguito a un crash durante la fase 3.

.Fase
. Contattare il supporto tecnico.




=== Node2 si blocca dopo la fase 3 ma prima della fase 5

Node3 continua a fornire dati per tutti gli aggregati. La coppia ha è disattivata.

.Fasi
. Alzati il node2.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node3 si blocca dopo la fase 3 ma prima della fase 5

Node3 si blocca dopo la fase 3 ma prima della fase 5. La coppia ha è disattivata.

.Fasi
. Alzati il node3.
+
Si è verificato un'interruzione del servizio client per tutti gli aggregati.

. Continuare con la procedura di aggiornamento della coppia di nodi.




== Riavvio, panic o cicli di alimentazione durante la fase 5

I crash possono verificarsi durante la fase 5, in cui si installa e si avvia node4, si mappano le porte da node2 a node4, si spostano le LIF dei dati e LE LIF SAN appartenenti a node2 da node3 a node4 e si spostano tutti gli aggregati di node2 da node3 a node4.



=== Node3 si blocca durante la fase 5

Node3 ha trasferito alcuni o tutti gli aggregati del node2 al node4. Node4 non prende il controllo, ma continua a servire aggregati non root che node3 ha già trasferito. La coppia ha è disattivata.

.A proposito di questa attività
Si verifica un'interruzione per il resto degli aggregati fino a quando il node3 non viene riavviato.

.Fasi
. Alzati il node3.
. Riallocare gli aggregati rimanenti che appartenevano al node2 ripetendo link:relocate_node2_non_root_aggr_node3_node4.html#man_relocate_3_4_Step1["Fase 1"] attraverso link:relocate_node2_non_root_aggr_node3_node4.html#step3["Fase 3"] Nella sezione _spostare gli aggregati non root di node2 da node3 a node4_.
. Continuare con la procedura di aggiornamento della coppia di nodi.




=== Node4 si blocca durante la fase 5

Node3 ha trasferito alcuni o tutti gli aggregati del node2 al node4. Node3 non prende il controllo, ma continua a servire aggregati non root che node3 possiede e quelli che non sono stati ricollocati. HA disattivato.

.A proposito di questa attività
Esiste un'interruzione per gli aggregati non root che sono stati già ricollocati fino al riavvio di node4.

.Fasi
. Far salire il node4.
. Riposizionare gli aggregati rimanenti che appartenevano al nodo 2 completando nuovamentelink:relocate_node2_non_root_aggr_node3_node4.html#man_relocate_3_4_Step1["Fase 1"] Attraversolink:relocate_node2_non_root_aggr_node3_node4.html#step3["Fase 3"] in _Sposta gli aggregati non radice del nodo2 dal nodo3 al nodo4_.
. Continuare con la procedura di aggiornamento della coppia di nodi.

