---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: Inviare un messaggio AutoSupport per node2 e spostare gli aggregati non root di node2 in node3 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti. 
---
= Spostare gli aggregati non root dal nodo 2 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di sostituire node2 con node4, è necessario inviare un messaggio AutoSupport per node2 e spostare gli aggregati non root di proprietà di node2 a node3.

[[sysconfig-a-command]]
.Fasi
. Verificare che l'ID del sistema partner sia impostato correttamente su node2 e node3:
+
** `system node run -node _node2_ -command sysconfig -a`
** `system node run -node _node3_ -command sysconfig -a`
+
Il sistema visualizza un output simile al seguente esempio:

+
[listing, subs="+quotes"]
----
NetApp Release 9.16.1: Mon Feb 10 07:55:45 EST 2025
System ID: _system-ID_; *partner ID: _partner-system-ID_*
System Serial Number: _system-serial-number_
System Rev: A0
System Storage Configuration: Mixed-Path HA
----
+
Se "ID partner" non è corretto per node2 o node3:

+
... Riavviare il nodo con il valore errato.
... Eseguire nuovamente i comandi in <<sysconfig-a-command,Fase 1>>e verificare che l'"ID partner" sia stato modificato nel valore corretto.




. Manda un messaggio a "AutoSupport" a "NetApp for node2:
+
`system node autosupport invoke -node _node2_ -type all -message "Upgrading _node2_ from _platform_old_ to _platform_new_"`

. Verificare che il messaggio AutoSupport sia stato inviato:
+
`system node autosupport show -node _node2_ -instance`

+
I campi "ultimo oggetto inviato:" e "ultimo invio:" contengono il titolo dell'ultimo messaggio inviato e l'ora in cui il messaggio è stato inviato.

. Spostare gli aggregati non root:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Elencare gli aggregati di proprietà di node2:
+
`storage aggregate show -owner-name _node2_`

.. Avviare il trasferimento degli aggregati:
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: Il comando individua solo gli aggregati non root.

.. Quando richiesto, immettere `y`.
+
Il trasferimento avviene in background. La riposizionamento di un aggregato può richiedere da pochi secondi a un paio di minuti. Il tempo include sia le parti di fuori servizio del client che quelle di non fuori servizio. Il comando non sposta aggregati non in linea o con restrizioni.

.. Tornare al livello di privilegio admin:
+
`set -privilege admin`



. Verificare lo stato di trasferimento del nodo 2:
+
`storage aggregate relocation show -node _node2_`

+
L'output visualizza "Done" (eseguito) per un aggregato dopo che è stato spostato.

+

NOTE: Prima di passare alla fase successiva, è necessario attendere che tutti gli aggregati di proprietà di node2 siano stati ricollocati in node3.

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| In caso di trasferimento di... | Quindi... 


| Tutti gli aggregati hanno avuto successo | Andare a <<man_relocate_2_3_step7,Fase 7>>. 


| Qualsiasi aggregato ha avuto esito negativo o è stato vetoato  a| 
.. Visualizzare un messaggio di stato dettagliato:
+
`storage aggregate show -instance`

+
È inoltre possibile controllare i registri EMS per visualizzare l'azione correttiva necessaria.

+

NOTE: Il `event log show` command elenca gli errori che si sono verificati.

.. Eseguire l'azione correttiva.
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Spostare eventuali aggregati guasti o vetoed:
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controllerupgrade true`

.. Quando richiesto, immettere `y`.
.. Tornare al livello di privilegio admin:
+
`set -privilege admin`



Se necessario, è possibile forzare il trasferimento utilizzando uno dei seguenti metodi:

** Sovrascrivendo i veto check:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Sovrascrivendo i controlli di destinazione:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Per ulteriori informazioni sui comandi di trasferimento degli aggregati di storage, visitare il sito Web all'indirizzo link:other_references.html["Riferimenti"] Per collegarsi alla gestione di _dischi e aggregati con i comandi CLI_ e _ONTAP 9: Manuale riferimento pagina_.

|===
. [[man_relocate_2_3_step7]]verificare che tutti gli aggregati non root siano online su node3:
+
`storage aggregate show -node _node3_ -state offline -root false`

+
Se alcuni aggregati sono andati offline o sono diventati estranei, è necessario portarli online una volta per ciascun aggregato:

+
`storage aggregate online -aggregate _aggr_name_`

. Verificare che tutti i volumi siano online al nodo3:
+
`volume show -node _node3_ -state offline`

+
Se alcuni volumi sono offline sul node3, è necessario portarli online, una volta per ciascun volume:

+
`volume online -vserver _Vserver-name_ -volume _volume-name_`

. Verificare che node2 non disponga di aggregati non root online:
+
`storage aggregate show -owner-name _node2_ -ha-policy sfo -state online`

+
L'output del comando non dovrebbe visualizzare gli aggregati online non root perché tutti gli aggregati online non root sono già stati riallocati in node3.


