---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: Inviare un messaggio AutoSupport per node2 e spostare gli aggregati non root di node2 in node3 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti. 
---
= Spostare gli aggregati non root dal nodo 2 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di sostituire node2 con node4, è necessario inviare un messaggio AutoSupport per node2 e spostare gli aggregati non root di proprietà di node2 a node3.


CAUTION: Durante questa procedura, non spostare gli aggregati da node3 a node2. In questo modo, gli aggregati vengono portati offline e si verifica una mancanza di servizio dei dati per gli aggregati che vengono ricollocati.

[[verify-partner-sys-id]]
.Fasi
. Verificare che l'ID del sistema partner sia impostato correttamente sul nodo 3:
+
.. Immettere il livello di privilegio avanzato:
+
`set -privilege advanced`

.. Mostra l'ID del sistema del partner su node3:
+
`ha interconnect config show -node <node3-node1>`

+
Il sistema visualizza un output simile al seguente esempio:

+
.Mostra esempio
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. Se "ID sistema partner" non è corretto per node3:
+
.. Arresto node3:
+
`halt`

.. Al prompt di Loader, impostare il valore corretto "partner-sysid".
+
Il node3 "partner-sysid" è l'ID di sistema di node2, che è possibile trovare nell' `ha interconnect config show`output in <<verify-partner-sys-id,Fase 1>>.

.. Salvare le impostazioni:
+
`saveenv`

.. Al prompt di Loader, avviare node3 nel menu di avvio:
+
`boot_ontap menu`

.. Accedere a node3.


. Manda un messaggio a "AutoSupport" a "NetApp for node2:
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. Verificare che il messaggio AutoSupport sia stato inviato:
+
`system node autosupport show -node <node2> -instance`

+
I campi "ultimo oggetto inviato:" e "ultimo invio:" contengono il titolo dell'ultimo messaggio inviato e l'ora in cui il messaggio è stato inviato.

. [[relocate-step5]]Riposiziona gli aggregati non radice:
+
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Elencare gli aggregati di proprietà di node2:
+
`storage aggregate show -owner-name <node2>`

.. Avviare il trasferimento degli aggregati:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: Il comando individua solo gli aggregati non root.

.. Quando richiesto, immettere `y`.
+
Il trasferimento avviene in background. La riposizionamento di un aggregato può richiedere da pochi secondi a un paio di minuti. Il tempo include sia le parti di fuori servizio del client che quelle di non fuori servizio. Il comando non sposta aggregati non in linea o con restrizioni.

.. Tornare al livello di privilegio admin:
+
`set -privilege admin`



. Verificare lo stato di trasferimento del nodo 2:
+
`storage aggregate relocation show -node <node2>`

+
L'output visualizza "Done" (eseguito) per un aggregato dopo che è stato spostato.

+

NOTE: Prima di passare alla fase successiva, è necessario attendere che tutti gli aggregati di proprietà di node2 siano stati ricollocati in node3.

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| In caso di trasferimento di... | Quindi... 


| Tutti gli aggregati hanno avuto successo | Andare a <<man_relocate_2_3_step8,Fase 8>>. 


| Qualsiasi aggregato ha avuto esito negativo o è stato vetoato  a| 
.. Visualizzare un messaggio di stato dettagliato:
+
`storage aggregate show -instance`

+
È inoltre possibile controllare i registri EMS per visualizzare l'azione correttiva necessaria.

+

NOTE: Il `event log show` command elenca gli errori che si sono verificati.

.. Eseguire l'azione correttiva.
.. Impostare il livello di privilegio su Advanced (avanzato):
+
`set -privilege advanced`

.. Spostare eventuali aggregati guasti o vetoed:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. Quando richiesto, immettere `y`.
.. Tornare al livello di privilegio admin:
+
`set -privilege admin`



Se necessario, è possibile forzare il trasferimento utilizzando uno dei seguenti metodi:

** Sovrascrivendo i veto check:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Sovrascrivendo i controlli di destinazione:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Per ulteriori informazioni sui comandi di trasferimento degli aggregati di storage, visitare il sito Web all'indirizzo link:other_references.html["Riferimenti"] Per collegarsi alla gestione di _dischi e aggregati con i comandi CLI_ e _ONTAP 9: Manuale riferimento pagina_.

|===
. [[man_relocate_2_3_step8]]verificare che tutti gli aggregati non root siano online su node3:
+
`storage aggregate show -node <node3> -state offline -root false`

+
Se alcuni aggregati sono andati offline o sono diventati estranei, è necessario portarli online una volta per ciascun aggregato:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verificare che tutti i volumi siano online al nodo3:
+
`volume show -node <node3> -state offline`

+
Se alcuni volumi sono offline sul node3, è necessario portarli online, una volta per ciascun volume:

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. Verificare che node2 non disponga di aggregati non root online:
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
L'output del comando non dovrebbe visualizzare gli aggregati online non root perché tutti gli aggregati online non root sono già stati riallocati in node3.


