---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: Configurare node3 porte FC integrate, porte UTA/UTA2 o scheda UTA/UTA2 durante un aggiornamento ARL manuale sui controller con ONTAP 9.7 o versione precedente. 
---
= Impostare la configurazione FC o UTA/UTA2 su node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se node3 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare<<Configurare le porte FC sul nodo 3>> O<<Controllare e configurare le porte UTA/UTA2 sul nodo 3>> o entrambe le sezioni.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine "UTA2" per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine "CNA".

* Se node3 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 e si sta aggiornando un sistema con dischi di archiviazione, è possibile passare alink:map_ports_node1_node3.html["Mappare le porte dal nodo 1 al nodo 3"] .
* Tuttavia, se si dispone di un sistema V-Series o di un sistema con software di virtualizzazione FlexArray con array di storage e node3 non dispone di porte FC integrate, porte UTA/UTA integrate o una scheda UTA/UTA2, tornare a _Installazione e fare il boot node3_ e riprendere a link:install_boot_node3.html#man_install3_step22["Fase 22"].




== Configurare le porte FC sul nodo 3

Se il nodo 3 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC da node1 salvati in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt del cluster.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti presenti sul sistema.
+
`system node hardware unified-connect show`

. Confronta le impostazioni FC del nodo 3 con le impostazioni acquisite in precedenza dal nodo 1.
. [[man_config_3_step3]]Esegui una delle seguenti azioni:
+
[cols="35,65"]
|===
| Se le impostazioni FC predefinite sui nuovi nodi sono... | Quindi... 


| Le stesse di quelle che hai catturato sul node1 | Vai a<<man_config_3_step9,Fase 9>> . 


| Diverso da quelli che avete catturato sul node1 | Vai a<<man_config_3_step4,Fase 4>> . 
|===
. [[man_config_3_step4]]Modificare le porte FC sul nodo 3 secondo necessità immettendo uno dei seguenti comandi:
+
** Per programmare le porte di destinazione:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Per programmare le porte initiator:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` È il tipo FC4: Destinazione o iniziatore.



. Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
+
`system node hardware unified-connect show`

. Uscire dalla modalità di manutenzione:
+
`halt`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Avviare node3 al prompt dell'ambiente di avvio:
+
`boot_ontap`

. [[man_config_3_step9]]Esegui una delle seguenti azioni:
+
** Se node3 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate, passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>>.
** Se node3 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate, saltare <<Controllare e configurare le porte UTA/UTA2 sul nodo 3>> e passare a. link:map_ports_node1_node3.html["Mappare le porte dal nodo 1 al nodo 3"].






== Controllare e configurare le porte UTA/UTA2 sul nodo 3

Se node3 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2, è necessario controllare la configurazione delle porte ed eventualmente riconfigurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Se si desidera utilizzare una porta UTA/UTA2 (Unified Target Adapter) per FC, è necessario prima verificare la configurazione della porta.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

È possibile utilizzare `ucadmin show` comando per verificare la configurazione corrente della porta:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente la condivisione simultanea del traffico NIC e FCoE con la stessa interfaccia SFP+ 10 GbE e supporta le destinazioni FC.

Le porte UTA/UTA2 potrebbero essere presenti su un adattatore o sul controller e presentano le seguenti configurazioni, ma è necessario controllare la configurazione delle porte UTA/UTA2 sul nodo 3 e modificarla, se necessario:

* Le schede UTA/UTA2 ordinate al momento dell'ordine del controller vengono configurate prima della spedizione per avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
+

NOTE: Immettere i comandi in questa sezione al prompt del cluster, a meno che non venga richiesto di entrare in modalità Manutenzione.



.Fasi
. Verificare la configurazione attuale della porta immettendo il seguente comando sul nodo 3:
+
`system node hardware unified-connect show`

+
Il sistema visualizza un output simile al seguente esempio:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[fase 2]]se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. [[step3]]esaminare l'output di `system node hardware unified-connect show` oppure `ucadmin show` Per determinare se le porte UTA/UTA2 hanno la personalità desiderata.
. [[step4]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se le porte UTA/UTA2... | Quindi... 


| Non avere la personalità che si desidera | Passare a. <<man_check_3_step5,Fase 5>>. 


| Avere la personalità che si desidera | Salta il passaggio 5 al passaggio 13 e vai a<<man_check_3_step14,Fase 14>> . 
|===
. [[man_check_3_step5]]Se il sistema dispone di dischi di archiviazione ed esegue Data ONTAP 8.3 in cluster, avviare node3 ed entrare in modalità di manutenzione:
+
`boot_ontap maint`

. Verificare le impostazioni:
+
`ucadmin show`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se si sta configurando... | Quindi... 


| Porte su una scheda UTA/UTA2 | Vai a<<man_check_3_step8,Fase 8>> . 


| Porte UTA/UTA2 integrate | Salta il passaggio 8 e vai a<<man_check_3_step9,Fase 9>> . 
|===
. [[man_check_3_step8]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[man_check_3_step9]]Se la configurazione corrente non corrisponde all'uso desiderato, modificare la configurazione secondo necessità:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` è la modalità personality, `fc` oppure `cna`.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e le configurazioni MetroCluster .  Per i client SAN è necessario utilizzare la destinazione FC.



. Arrestare il sistema:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

. Immettere il seguente comando:
+
`boot_ontap`

. [[step11]]verificare le impostazioni:
+
`system node hardware unified-connect show`

+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]Metti online tutte le porte di destinazione immettendo il seguente comando, una volta per ogni porta:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step14]]Cablare la porta.

