---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_6_index.html 
keywords: stage 6, complete, upgrade, set up, setup, controller, storage encryption, netapp encryption, decommission, resume snapmirror 
summary: Fase 6 sequenza di processo per un aggiornamento ARL manuale su controller con ONTAP 9.7 o versioni precedenti. 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 6, confermi che i nuovi nodi sono impostati correttamente e, se i nuovi nodi sono abilitati per la crittografia, configuri e configuri Storage Encryption o NetApp Volume Encryption. È inoltre necessario decommissionare i vecchi nodi e riprendere le operazioni di SnapMirror.

. link:manage_authentication_kmip.html["Gestire l'autenticazione utilizzando i server KMIP"]
. link:ensure_controllers_set_up_correctly.html["Verificare che i nuovi controller siano impostati correttamente"]
. link:set_up_storage_encryption_new_controller.html["Impostare Storage Encryption sul nuovo modulo controller"]
. link:set_up_netapp_encryption_on_new_controller.html["Impostare NetApp Volume o aggregate Encryption sul nuovo modulo controller"]
. link:decommission_old_system.html["Decommissionare il vecchio sistema"]
. link:resume_snapmirror_ops.html["Riprendere le operazioni di SnapMirror"]

