---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_5_index.html 
keywords: stage 5, install, boot, node3, node4, relocate, aggregates 
summary: Fase 5 sequenza di processo per un aggiornamento ARL manuale su controller con ONTAP 9.7 o versioni precedenti. 
---
= Panoramica della fase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 5, si installa e si avvia node4, si mappano le porte di gestione del cluster e dei nodi da node2 a node4, si verifica l'installazione node4 e si spostano le LIF dei dati e LE LIF SAN appartenenti al node2 da node3 a node4. È inoltre possibile spostare gli aggregati node2 da node3 a node4.

.Fasi
. link:install_boot_node4.html["Installazione e boot node4"]
. link:set_fc_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"]
. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"]
. link:verify_node4_installation.html["Verificare l'installazione di node4"]
. link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["Spostare le LIF dei dati NAS di proprietà di node2 da node3 a node4 e verificare le LIF SAN sul node4"]
. link:relocate_node2_non_root_aggr_node3_node4.html["Spostare gli aggregati non root node2 da node3 a node4"]

