---
sidebar: sidebar 
permalink: upgrade-arl-manual/troubleshoot_index.html 
keywords: troubleshoot, troubleshooting, problem, error, failure 
summary: Risolvere i problemi che potrebbero verificarsi durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.7 o versioni precedenti. 
---
= Risolvere i problemi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si potrebbe riscontrare un errore durante l'aggiornamento della coppia di nodi. Il nodo potrebbe bloccarsi, gli aggregati potrebbero non spostarsi o i LIF potrebbero non migrare. La causa dell'errore e la relativa soluzione dipendono dal momento in cui si è verificato l'errore durante la procedura di aggiornamento.

Fare riferimento alla tabella che descrive le diverse fasi della procedura nella sezione link:arl_upgrade_workflow.html["Workflow di upgrade ARL"]. Le informazioni sugli errori che possono verificarsi vengono elencate in base alla fase della procedura.

* link:aggregate_relocation_failures.html["Errori di trasferimento aggregati"]
* link:reboots_panics_power_cycles.html["Riavvio, panic o cicli di alimentazione"]
* link:issues_multiple_stages_of_procedure.html["Problemi che possono verificarsi in più fasi della procedura"]
* link:lif_migration_failure.html["Errore di migrazione LIF"]
* link:lifs_invalid_ports_after_upgrade.html["Le LIF si trovano su porte non valide dopo l'aggiornamento"]

