---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decidere se utilizzare ARL per aggiornare i controller con ONTAP 9.8 o versioni successive utilizzando `system controller replace` comandi.' 
---
= Decidere se utilizzare questa procedura di ricollocazione aggregata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esistono diversi metodi di ricollocazione aggregata (ARL) per aggiornare l'hardware del controller. Questa procedura descrive come aggiornare l'hardware del controller utilizzando la ricollocazione aggregata (ARL) con "comandi di sostituzione del controller di sistema" su sistemi che eseguono ONTAP 9.8 o versioni successive. Questa complessa procedura dovrebbe essere utilizzata solo da amministratori ONTAP esperti.

Per aiutarti a decidere se questa procedura ARL è adatta all'aggiornamento hardware del tuo controller, dovresti esaminare tutte le seguenti circostanze per gli aggiornamenti supportati:

* Sul computer è in esecuzione ONTAP 9,8 o versione successiva.
* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è soddisfatti dei rischi di lavorare in modalità privilegi diagnostici.
* Durante l'upgrade di una configurazione MetroCluster, si tratta di una configurazione FC a quattro nodi o superiore che utilizza ONTAP 9,8 o versioni successive.
+
Per aggiornare le configurazioni IP di MetroCluster, fare riferimento al link:other_references.html["Riferimenti"]collegamento _aggiornamento ed espansione MetroCluster_.



[NOTE]
====
* Se si sta aggiornando un sistema scambiando i moduli del controller nello stesso chassis, come AFF A800 o AFF C800, NetApp consiglia vivamente di utilizzare la procedura di aggiornamento chelink:../upgrade-arl-auto-in-chassis/index.html["aggiorna i modelli di controller utilizzando ARL, mantenendo lo chassis e i dischi del sistema esistenti"] .  Questa procedura ARL include i passaggi che garantiscono che i dischi interni rimangano saldamente nello chassis quando si rimuovono e si installano i controller durante la procedura di aggiornamento.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Scopri le combinazioni di aggiornamento del sistema supportate utilizzando ARL, mantenendo lo chassis e i dischi del sistema esistenti"].

* Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).


====


== Combinazioni di aggiornamento del sistema supportate

Nella tabella seguente viene mostrata la matrice dei sistemi supportati per eseguire un aggiornamento del controller utilizzando questa procedura ARL.

|===
| Vecchio controller | Controller sostitutivo 


| FAS8020^3^, FAS8040^3^, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| FAS8060^4^, FAS8080^4^ | FAS9500 


| AFF8020^3^, AFF8040^3^, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800^1^ 


| AFF8060^4^, AFF8080^4^ | AFF A900 


| FAS8200 | FAS8300^2^, FAS8700, FAS9000, FAS9500 


| FAS8300, FAS8700, FAS9000 | FAS9500 


| AFF A300 | AFF A400^2^, AFF A700, AFF A800^1^, AFF A900 


| AFF A320^4^ | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===

NOTE: Se la combinazione del modello di aggiornamento del controller non è riportata nella tabella precedente, contattare il supporto tecnico.

^1^per i passaggi aggiuntivi necessari per i sistemi AFF A800, andare al passo che fa riferimento a A800 nella sezione link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Riassegnare node1 dischi a node3, passaggio 9"], o link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["Riassegnare node2 dischi a node4, passaggio 9"].

^2^se stai eseguendo l'aggiornamento da un AFF A300 a un AFF A400 o da un FAS8200 a un sistema FAS8300 in una configurazione cluster senza switch a due nodi, devi scegliere le porte cluster temporanee per l'aggiornamento del controller. I sistemi AFF A400 e FAS8300 sono disponibili in due configurazioni, come bundle Ethernet in cui le porte della scheda mezzanine sono di tipo Ethernet e come bundle FC in cui le porte mezzanine sono di tipo FC.

* Per un sistema AFF A400 o FAS8300 con configurazione di tipo Ethernet, è possibile utilizzare una qualsiasi delle due porte mezzanine come porte cluster temporanee.
* Per un sistema AFF A400 o FAS8300 con configurazione di tipo FC, è necessario aggiungere una scheda di interfaccia di rete 10GbE a quattro porte (codice X1147A) per fornire porte cluster temporanee.
* Dopo aver completato un aggiornamento del controller utilizzando porte cluster temporanee, è possibile migrare senza interruzioni le LIF del cluster a e3a ed e3b, porte 100GbE su un sistema AFF A400 e porte e0c ed e0d, 100GbE su un sistema FAS8300.


^3^per gli aggiornamenti dei sistemi FAS8020, FAS8040, AFF8020 e AFF8040 ai controller sostitutivi di destinazione elencati nella tabella precedente, i controller sostitutivi devono eseguire la stessa versione ONTAP del vecchio controller. I sistemi FAS8020, FAS8040, AFF8020 e AFF8040 non supportano le versioni di ONTAP successive a ONTAP 9.8.

^4^la tabella seguente mostra le versioni minime e successive di ONTAP supportate per queste combinazioni di upgrade del controller.

[cols="20,30,20,30"]
|===
2+| Vecchio controller 2+| Controller sostitutivo 


| Sistema | Versione di ONTAP | Sistema | Versione di ONTAP 


| AFF A320 | 9.9.1 o versione successiva | AFF A400 | 9.9.1 o versione successiva 


| AFF8060 | 9.8P13 o patch successive | AFF A900 | da 9.10.1 a 9.12.1 


| AFF8080 | 9.8P10 o patch successive | AFF A900 | da 9.10.1 a 9.12.1 


| FAS8060 | 9.8P13 o patch successive | FAS9500 | Da 9.10.1P3 a 9.12.1 


| FAS8080 | 9.8P12 o patch successive | FAS9500 | Da 9.10.1P3 a 9.12.1 
|===
[NOTE]
====
Per le combinazioni di upgrade illustrate nella tabella precedente:

* Non è necessario utilizzare la stessa versione di ONTAP sui controller esistenti e sostitutivi. L'aggiornamento del software ONTAP viene eseguito con l'aggiornamento del controller.
* Durante l'aggiornamento, è necessario installare un controller sostitutivo con una versione di ONTAP e un livello di patch supportati.
* Non è possibile annullare o annullare un aggiornamento del controller dopo aver avviato la procedura e aver aggiornato il primo nodo.


====


== Scegli una procedura di aggiornamento hardware diversa

* link:../upgrade-arl/index.html["Esaminare i metodi ARL alternativi disponibili per l'aggiornamento dell'hardware del controller"].
* Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.


.Informazioni correlate
Fare riferimento a link:other_references.html["Riferimenti"] per collegarsi alla _Documentazione ONTAP 9_.
