---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Capire se è possibile aggiornare i controller con ONTAP 9.8 o versione successiva utilizzando `system controller replace` comandi.' 
---
= Linee guida per l'aggiornamento dei controller con ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per capire se è possibile utilizzare ARL per aggiornare una coppia di controller che eseguono ONTAP 9.8 o versioni successive, è necessario disporre della piattaforma e della configurazione dei controller originali e sostitutivi.



== Aggiornamenti supportati per ARL

Quando si aggiorna una coppia di nodi utilizzando questa procedura ARL per ONTAP 9.8 o versioni successive, è necessario verificare che ARL possa essere eseguito sui controller originali e su quelli sostitutivi.

È necessario controllare le dimensioni di tutti gli aggregati definiti e il numero di dischi supportati dal sistema originale. È quindi necessario confrontare le dimensioni e il numero di dischi aggregati supportati con le dimensioni e il numero di dischi aggregati supportati dal nuovo sistema. Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _Hardware Universe_ dove queste informazioni sono disponibili. La dimensione aggregata e il numero di dischi supportati dal nuovo sistema devono essere uguali o superiori alla dimensione aggregata e al numero di dischi supportati dal sistema originale.

È necessario verificare nelle regole di combinazione del cluster se i nuovi nodi possono diventare parte del cluster con i nodi esistenti quando il controller originale viene sostituito. Per ulteriori informazioni sulle regole di combinazione dei cluster, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_.


NOTE: Se si sta aggiornando un sistema che supporta dischi interni (ad esempio, un sistema FAS2700 o AFF A250) ma NON dispone di dischi interni, fare riferimento a. link:other_references.html["Riferimenti"] E utilizzare la procedura descritta nella sezione _aggregate Relocation to Manually Upgrade Controller hardware_ content (trasferimento aggregato per aggiornare manualmente l'hardware del controller) corretta per la versione di ONTAP in uso.

Se si dispone di un sistema con più di due porte cluster per nodo, ad esempio un sistema FAS8080 o AFF8080, prima di avviare l'aggiornamento, è necessario migrare e riassegnare le LIF del cluster a due porte cluster per nodo. Se si esegue l'aggiornamento del controller con più di due porte cluster per nodo, le LIF del cluster potrebbero non essere presenti sul nuovo controller dopo l'aggiornamento.

L'upgrade del controller tramite ARL è supportato sui sistemi configurati con volumi di conformità SnapLock Enterprise e SnapLock.



== Cluster senza switch a due nodi

Se si stanno aggiornando i nodi in un cluster senza switch a due nodi, è possibile lasciare i nodi nel cluster senza switch durante l'aggiornamento. Non è necessario convertirli in un cluster con switch.



== Aggiornamenti non supportati per ARL

Non è possibile eseguire i seguenti aggiornamenti:

* Ai controller sostitutivi che non supportano gli shelf di dischi collegati ai controller originali
+
Fare riferimento a. link:other_references.html["Riferimenti"] Per il collegamento a _Hardware Universe_ per informazioni sul supporto dei dischi.

* Ai controller entry-level con dischi interni, ad esempio FAS 2500.
+
Se si desidera aggiornare i controller entry-level con dischi interni, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_ e passare alla procedura _aggiornamento di una coppia di nodi che eseguono Clustered Data ONTAP spostando volumi_.





== Configurazione MetroCluster FC

In una configurazione FC MetroCluster, è necessario sostituire i nodi del sito di disaster recovery/failover il prima possibile. La mancata corrispondenza nei modelli di controller all'interno di un MetroCluster non è supportata perché la mancata corrispondenza del modello di controller può causare la offline del mirroring del disaster recovery. Utilizzare il `-skip-metrocluster-check true` comando per ignorare i controlli MetroCluster quando si sostituiscono i nodi del secondo sito.



== Risolvere i problemi

Si potrebbe riscontrare un errore durante l'aggiornamento della coppia di nodi. Il nodo potrebbe bloccarsi, gli aggregati potrebbero non spostarsi o i LIF potrebbero non migrare. La causa dell'errore e la relativa soluzione dipendono dal momento in cui si è verificato l'errore durante la procedura di aggiornamento.

In caso di problemi, fare riferimento al link:aggregate_relocation_failures.html["Risolvere i problemi"] sezione alla fine della procedura per ulteriori informazioni e possibili soluzioni. Le informazioni sui guasti che possono verificarsi sono elencate in base alla fase della procedura nella link:overview_of_the_arl_upgrade.html["Sequenza di aggiornamento ARL"] .

Se non si riesce a trovare una soluzione al problema riscontrato, contattare il supporto tecnico.
