---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: 'Installare e avviare il node4 e installare il software ONTAP quando si aggiornano i controller con ONTAP 9.8 o versione successiva utilizzando `system controller replace` comandi.' 
---
= Installazione e boot node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È necessario installare node4 nel rack, trasferire le connessioni node2 al node4, fare il boot node4 e installare ONTAP. È quindi necessario riassegnare uno qualsiasi dei dischi spare di node2, i dischi appartenenti al volume root e gli aggregati non root che non sono stati riallocati in node3 prima del processo, come descritto in questa sezione.

.A proposito di questa attività
L'operazione di trasferimento viene messa in pausa all'inizio di questa fase. Questo processo è per lo più automatizzato; l'operazione viene interrotta per consentirti di controllarne lo stato. È necessario riprendere manualmente l'operazione.

È necessario eseguire l'avvio di rete del nodo 4 se la versione ONTAP sul nodo 4 è diversa dalla versione ONTAP sul nodo 2. Dopo aver installato node4, avviarlo dall'immagine ONTAP 9 memorizzata sul server web. È quindi possibile scaricare i file corretti sul dispositivo di supporto di avvio per i successivi avvii del sistema seguendo le istruzioni in link:prepare_for_netboot.html["Preparatevi per il netboot"].

[IMPORTANT]
====
* Per un aggiornamento del controller AFF A800 o AFF C800 , è necessario assicurarsi che tutte le unità nello chassis siano saldamente posizionate contro il midplane prima di rimuovere node2. Per maggiori informazioni, vedere link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sostituire i moduli controller AFF A800 o AFF C800"].
* Se si sta aggiornando un sistema con dischi di archiviazione, è necessario completare l'intera sezione e quindi procedere a link:set_fc_or_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"] , immettendo comandi al prompt del cluster.


====
.Fasi
. [[auto_install4_step1]]assicurarsi che node4 disponga di spazio rack sufficiente.
+
Se il nodo 4 si trova in uno chassis separato dal nodo 2, è possibile inserire il nodo 4 nella stessa posizione del nodo 3. Se node2 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

. Installare il nodo 4 nel rack seguendo le istruzioni contenute nelle _istruzioni di installazione e configurazione_ relative al modello di nodo.
. Nodo del cablo4, spostamento delle connessioni dal nodo 2 al nodo 4.
+
Cablare le seguenti connessioni, utilizzando le _Istruzioni di installazione e configurazione_ per la piattaforma node4, il documento appropriato sullo scaffale dei dischi e la documentazione sulla _gestione delle coppie HA_.

+
Fare riferimento alink:other_references.html["Riferimenti"] per collegarsi alla _gestione delle coppie HA_.

+
** Console (porta di gestione remota)
** Porte del cluster
** Porte dati
** Porte di gestione di cluster e nodi
** Storage
** Configurazioni SAN: Porte switch FC e Ethernet iSCSI
+

NOTE: Potrebbe non essere necessario spostare la connessione scheda di interconnessione/scheda FC-VI o cavo di interconnessione/FC-VI dal nodo 2 al nodo 4, poiché la maggior parte dei modelli di piattaforma dispone di modelli di schede di interconnessione univoci. Per la configurazione MetroCluster, è necessario spostare le connessioni del cavo FC-VI dal nodo 2 al nodo 4. Se il nuovo host non dispone di una scheda FC-VI, potrebbe essere necessario spostare la scheda FC-VI.



. Accendere il dispositivo al nodo 4, quindi interrompere il processo di avvio premendo Ctrl-C sul terminale della console per accedere al prompt dell'ambiente di avvio.
+

NOTE: Quando si avvia node4, potrebbe essere visualizzato il seguente messaggio di avviso:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Se viene visualizzato il messaggio di avviso nella fase 4, eseguire le seguenti operazioni:
+
.. Verificare la presenza di eventuali messaggi della console che potrebbero indicare un problema diverso da una batteria NVRAM in esaurimento e, se necessario, intraprendere le azioni correttive necessarie.
.. Attendere che la batteria si ricarichi e che il processo di avvio venga completato.
+

WARNING: *Non ignorare il ritardo; se non si lascia caricare la batteria, si potrebbe verificare una perdita di dati.*

+

NOTE: Fare riferimento a. link:prepare_for_netboot.html["Preparatevi per il netboot"].





. [[step6]]configurare la connessione netboot scegliendo una delle seguenti operazioni.
+

NOTE: È necessario utilizzare la porta di gestione e l'IP come connessione di netboot. Non utilizzare un IP della LIF dati o potrebbe verificarsi una mancanza di disponibilità dei dati durante l'aggiornamento.

+
[cols="30,70"]
|===
| Se DHCP (Dynamic host Configuration Protocol) è... | Quindi... 


| In esecuzione | Configurare la connessione automaticamente utilizzando il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -auto` 


| Non in esecuzione  a| 
Configurare manualmente la connessione immettendo il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` È l'indirizzo IP del sistema di storage (obbligatorio).
`_netmask_` è la maschera di rete del sistema di storage (obbligatoria).
`_gateway_` è il gateway per il sistema storage (obbligatorio).
`_dns_addr_` È l'indirizzo IP di un name server sulla rete (opzionale).
`_dns_domain_` È il nome di dominio DNS (opzionale).


NOTE: Potrebbero essere necessari altri parametri per l'interfaccia. Invio `help ifconfig` al prompt del firmware per ulteriori informazioni.

|===
. Eseguire il netboot al nodo 4:
+
[cols="30,70"]
|===
| Per... | Quindi... 


| Sistemi della serie FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Tutti gli altri sistemi | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
Il `<path_to_the_web-accessible_directory>` dovrebbe portare alla posizione in cui è stato scaricato `<ontap_version>_image.tgz` Nella fase 1 della sezione link:prepare_for_netboot.html["Preparatevi per il netboot"].

+

NOTE: Non interrompere l'avvio.

. Dal menu di avvio, selezionare opzione `(7) Install new software first`.
+
Questa opzione di menu consente di scaricare e installare la nuova immagine ONTAP sul dispositivo di avvio.

+
Ignorare il seguente messaggio:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota si applica agli aggiornamenti senza interruzioni di ONTAP e non agli aggiornamenti dei controller.

+

NOTE: Utilizzare sempre netboot per aggiornare il nuovo nodo all'immagine desiderata. Se si utilizza un altro metodo per installare l'immagine sul nuovo controller, l'immagine potrebbe non essere corretta. Questo problema riguarda tutte le versioni di ONTAP. La procedura di netboot combinata con l'opzione `(7) Install new software` Consente di cancellare il supporto di avvio e di posizionare la stessa versione di ONTAP su entrambe le partizioni dell'immagine.

. Se viene richiesto di continuare la procedura, immettere `y`E quando viene richiesto il pacchetto, immettere l'URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. Completare i seguenti passaggi secondari per riavviare il modulo controller:
+
.. Invio `n` per ignorare il ripristino del backup quando viene visualizzato il seguente prompt:
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. Riavviare immettendo `y` quando viene visualizzato il seguente prompt:
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
Il modulo controller si riavvia ma si arresta al menu di avvio perché il dispositivo di avvio è stato riformattato e i dati di configurazione devono essere ripristinati.



. Selezionare la modalità di manutenzione `5` dal menu di boot e premere `y` quando viene richiesto di continuare con l'avvio.
. Verificare che il controller e lo chassis siano configurati come ha:
+
`ha-config show`

+
L'esempio seguente mostra l'output di `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Il sistema registra in una PROM sia che si trovi in una coppia ha o in una configurazione standalone. Lo stato deve essere lo stesso su tutti i componenti all'interno del sistema standalone o della coppia ha.

. Se il controller e lo chassis non sono configurati come ha, utilizzare i seguenti comandi per correggere la configurazione:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Se si dispone di una configurazione MetroCluster, utilizzare i seguenti comandi per modificare il controller e lo chassis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. Uscire dalla modalità di manutenzione:
+
`halt`

+
Interrompere L'OPERAZIONE premendo Ctrl-C al prompt dell'ambiente di avvio.

. [[auto_install4_step15]]al node3, controllare la data, l'ora e il fuso orario del sistema:
+
`date`

. Al nodo 4, controllare la data utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show date`

. Se necessario, impostare la data sul node4:
+
`set date _mm/dd/yyyy_`

. In node4, controllare l'ora utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show time`

. Se necessario, impostare l'ora su node4:
+
`set time _hh:mm:ss_`

. Nel boot loader, impostare l'ID del sistema partner su node4:
+
`setenv partner-sysid _node3_sysid_`

+
Per il nodo 4, `partner-sysid` deve essere quello del node3.

+
Salvare le impostazioni:

+
`saveenv`

. [[auto_install4_step21]] verificare `partner-sysid` per il nodo 4:
+
`printenv partner-sysid`



. [[auto_install4_step22]]Se sono installate unità NetApp Storage Encryption (NSE), procedere come segue:
+

NOTE: Se la procedura non è stata ancora eseguita, consultare l'articolo della Knowledge base https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Come verificare se un disco è certificato FIPS"^] per determinare il tipo di unità con crittografia automatica in uso.

+
.. Impostare `bootarg.storageencryption.support` a. `true` oppure `false`:
+
[cols="35,65"]
|===
| Se i seguenti dischi sono in uso… | Quindi… 


| Unità NSE conformi ai requisiti di crittografia automatica FIPS 140-2 livello 2 | `setenv bootarg.storageencryption.support *true*` 


| SED non FIPS di NetApp | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Non è possibile combinare dischi FIPS con altri tipi di dischi sullo stesso nodo o coppia ha. È possibile combinare SED con dischi non crittografanti sullo stesso nodo o coppia ha.

====
.. Accedere al menu di avvio speciale e selezionare l'opzione `(10) Set Onboard Key Manager recovery secrets`.
+
Inserire la passphrase e le informazioni di backup registrate in precedenza. Vedere link:manage_storage_encryption_using_okm.html["Gestire la crittografia dello storage utilizzando Onboard Key Manager"].



. Avviare il nodo nel menu di avvio:
+
`boot_ontap menu`

+
.Quali sono le prossime novità?
** Se si dispone di una configurazione FC o UTA/UTA2,link:set_fc_or_uta_uta2_config_node4.html["imposta e configura le porte FC o UTA/UTA2 sul nodo 4"] .
** Se non si dispone di una configurazione FC o UTA/UTA2,link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step1["riassegnare i dischi del nodo 2 al nodo 4, passaggio 1"] in modo che node4 possa riconoscere i dischi di node2.
** Se si dispone di una configurazione MetroCluster ,link:set_fc_or_uta_uta2_config_node4.html["imposta e configura le porte FC o UTA/UTA2 sul nodo 4"] per rilevare i dischi collegati al nodo.



