---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/restore_key-manager_config_node4.html 
keywords: restore key-manager, configuration, node4, nve, arl, volume, encryption 
summary: 'Se necessario, ripristinare la configurazione del gestore delle chiavi sul nodo 4 quando si aggiornano i controller con ONTAP 9.8 o versione successiva utilizzando `system controller replace` comandi.' 
---
= Ripristinare la configurazione del gestore delle chiavi sul nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se si utilizza NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE) per crittografare i volumi sul sistema che si sta aggiornando, la configurazione della crittografia deve essere sincronizzata con i nuovi nodi. Se non si sincronizza il gestore delle chiavi, quando si riposizionano gli aggregati node2 da node3 a node4 utilizzando ARL, potrebbero verificarsi errori perché node4 non dispone delle chiavi di crittografia necessarie per portare online volumi e aggregati crittografati.

.A proposito di questa attività
Sincronizzare la configurazione della crittografia con i nuovi nodi seguendo questa procedura:

.Fasi
. Eseguire il seguente comando da node4:
+
`security key-manager onboard sync`

. Prima di spostare gli aggregati di dati, verificare che la chiave SVM-KEK sia ripristinata su "true" in node4:
+
[listing]
----
::> security key-manager key query -node node4 -fields restored -key-type SVM-KEK
----
+
.Esempio
[listing]
----
::> security key-manager key query -node node4 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node4    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

