---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'Configurare node4 porte FC onboard, porte UTA/UTA2 o scheda UTA/UTA2 quando si aggiornano controller con ONTAP 9.8 o versioni successive utilizzando `system controller replace` comandi.' 
---
= Impostare la configurazione FC o UTA/UTA2 su node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se node4 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare<<Configurare le porte FC sul nodo 4>> O<<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> o entrambe le sezioni.

[NOTE]
====
Se node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 (ad esempio, sistemi AFF e FAS introdotti a partire da ONTAP 9.15.1) e si sta aggiornando un sistema con dischi di archiviazione, è possibile passare alink:reassign-node2-disks-to-node4.html["Riassegnare dischi da node2 TB a node4 TB"] .

Assicurarsi che il node4 disponga di spazio rack sufficiente. Se il nodo 4 si trova in uno chassis separato dal nodo 2, è possibile inserire il nodo 4 nella stessa posizione del nodo 3. Se node2 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

====


== Configurare le porte FC sul nodo 4

Se il nodo 4 dispone di porte FC, integrate o su un adattatore FC aggiuntivo, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, poiché le porte non sono preconfigurate al momento della spedizione dei sistemi.  Se non si configurano le porte come richiesto, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di un adattatore UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti sul sistema:
+
`system node hardware unified-connect show`

. Confrontare le impostazioni FC sul nodo 4 con quelle acquisite in precedenza dal nodo 1.
. Modificare le porte FC sul nodo 4 in base alle necessità:
+
** Per programmare come porte di destinazione:
+
`ucadmin modify -m fc -t target _adapter_`

+
Per esempio: `ucadmin modify -m fc -t target 2a`

** Per programmare le porte initiator:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` È il tipo FC4: Destinazione o iniziatore.

+
Per esempio: `ucadmin modify -m fc -t initator 2b`



. Arrestare il nodo:
+
`halt`

. Avviare il sistema dal prompt del CARICATORE:
+
`boot_ontap menu`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Selezionare l'opzione `5` dal menu di avvio per la modalità di manutenzione.


. [[step8]]eseguire una delle seguenti operazioni:
+
** Passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> Se node4 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate.
** Se node4 non ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate, saltare _Controllare e configurare le porte UTA/UTA2 su node4_ e andare alink:reassign-node2-disks-to-node4.html["Riassegnare dischi da node2 TB a node4 TB"] .






== Controllare e configurare le porte UTA/UTA2 sul nodo 4

Se node4 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2A, è necessario controllare la configurazione delle porte e configurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2A. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente al traffico simultaneo di NIC e FCoE di condividere la stessa interfaccia SFP+ 10 GbE e supporta la destinazione FC.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Le porte UTA/UTA2 potrebbero essere su un adattatore o sul controller con le seguenti configurazioni:

* Le schede UTA/UTA2 ordinate contemporaneamente al controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller sono configurate (prima della spedizione) in modo da avere la personalità richiesta.


Tuttavia, è necessario controllare la configurazione delle porte UTA/UTA2 sul nodo 4 e modificarla, se necessario.


WARNING: Immettere i comandi in questa sezione al prompt della shell in modalità Manutenzione.

.Fasi
. Controlla come sono attualmente configurate le porte sul nodo 4:
+
`system node hardware unified-connect show`

+
Il sistema visualizza un output simile al seguente esempio:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Verificare le impostazioni:
+
`ucadmin show`

+
Esaminare l'output di `ucadmin show` Controllare e determinare se le porte UTA/UTA2 hanno la personalità desiderata.

+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se la porta CNA... | Quindi… 


| Non avere la personalità che si desidera | Passare a. <<auto_check_4_step5,Fase 5>>. 


| Avere la personalità che si desidera | Salta il passaggio 5 al passaggio 9 e vai a<<auto_check_4_step10,Fase 10>> . 
|===
. [[auto_check_4_step5]]eseguire una delle seguenti operazioni:
+
[cols="30,70"]
|===
| Se si sta configurando... | Quindi… 


| Porte su una scheda UTA/UTA2 | Vai a<<auto_check_4_step6,Fase 6>> 


| Porte UTA/UTA2 integrate | Salta il passaggio 6 e vai a<<auto_check_4_step7,Fase 7>> . 
|===
. [[auto_check_4_step6]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[auto_check_4_step7]]se la configurazione corrente non corrisponde all'utilizzo desiderato, modificare la configurazione in base alle necessità:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` È la modalità Personality, FC o 10GbE UTA.
** `-t` È di tipo FC4, `target` oppure `initiator`.
+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e le configurazioni MetroCluster .  Per i client SAN è necessario utilizzare la destinazione FC.



. Mettere online tutte le porte di destinazione immettendo il seguente comando, una volta per ogni porta:
+
`storage enable adapter <adapter_name>`

. Collegare la porta.


. [[auto_check_4_step10]]Esci dalla modalità di manutenzione:
+
`halt`

. [[step14]]avviare il nodo nel menu di avvio:
+
`boot_ontap menu`



.Quali sono le prossime novità?
* Se si sta eseguendo l'aggiornamento a un sistema AFF A800, visitare il sito link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["Riassegnare i dischi del nodo 2 al nodo 4, fase 9"].
* Per tutti gli altri aggiornamenti di sistema, vai alink:reassign-node2-disks-to-node4.html["Riassegnare node2 dischi a node4, passaggio 1"] .

