---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Fase 5 sequenza di processo per un aggiornamento ARL con `system controller replace` Comandi sui controller che eseguono ONTAP 9.8 o versioni successive.' 
---
= Panoramica della fase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 5, si installa e si avvia node4, si controlla che il cluster e le porte di gestione dei nodi di node2 siano online su node4, si riassegnano i dischi da node2 a node4 e si verifica l'installazione di node4. Se si utilizza NVE, si ripristina la configurazione del gestore delle chiavi. Se necessario, impostare la configurazione FC o UTA/UTA2 su node4. È inoltre possibile spostare le LIF dei dati NAS node2 e gli aggregati non root da node3 a node4 e verificare che le LIF SAN esistano sul node4.

.Fasi
. link:install_boot_node4.html["Installazione e boot node4"]
. link:set_fc_or_uta_uta2_config_node4.html["Impostare la configurazione FC o UTA/UTA2 su node4"]
. link:reassign-node2-disks-to-node4.html["Riassegnare dischi da node2 TB a node4 TB"]
. link:verify_node4_installation.html["Verificare l'installazione di node4"]
. link:restore_key-manager_config_node4.html["Ripristinare la configurazione del gestore delle chiavi sul nodo 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Spostare gli aggregati non root e le LIF di dati NAS di proprietà di node2 da node3 a node4"]

