---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_2_index.html 
keywords: relocating, retiring, node1, lif, stage 2 
summary: 'Fase 2 sequenza di processo per un aggiornamento ARL con `system controller replace` Comandi sui controller che eseguono ONTAP 9.8 o versioni successive.' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 2, è possibile spostare gli aggregati non root node1 e le LIF dei dati NAS in node2. Questo processo è in gran parte automatizzato; l'operazione viene interrotta per consentirti di controllarne lo stato. È necessario riprendere manualmente l'operazione. Se necessario, spostare gli aggregati non riusciti o vetoed. È necessario registrare le informazioni necessarie per il node1 e poi dismettere il node1. Puoi anche prepararti a netboot node3 e node4 più avanti nella procedura.

.Fasi
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Spostare gli aggregati non root e le LIF dei dati NAS di proprietà del node1 al node2"]
. link:relocate_failed_or_vetoed_aggr.html["Spostare gli aggregati non riusciti o vetoed"]
. link:retire_node1.html["Ritirare il node1"]
. link:prepare_for_netboot.html["Preparatevi per il netboot"]

