---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_health_of_metrocluster_config.html 
keywords: verifying, health, metrocluster, configuration, fabric, mcc 
summary: 'Verificare lo stato della configurazione di MetroCluster e il corretto funzionamento durante l"aggiornamento dei controller con ONTAP 9.8 o versione successiva utilizzando `system controller replace` comandi.' 
---
= Verificare lo stato della configurazione MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di avviare un aggiornamento su una configurazione Fabric MetroCluster, è necessario verificare lo stato della configurazione MetroCluster per verificarne il corretto funzionamento.

.Fasi
. Verificare che i componenti di MetroCluster siano integri:
+
`metrocluster check run`

+
....
metrocluster_siteA::*> metrocluster check run
....
+
L'operazione viene eseguita in background.

. Dopo il `metrocluster check run` operazione completata, visualizzare i risultati:
+
`metrocluster check show`

+
Dopo circa cinque minuti, vengono visualizzati i seguenti risultati:

+
[listing]
----
metrocluster_siteA::*> metrocluster check show
Last Checked On: 4/7/2019 21:15:05
Component            Result
---------------      -------
nodes                ok
lifs                 ok
config-replication   ok
aggregates           warning
clusters             ok
connections          not-applicable
volumes              ok
7 entries were displayed.
----
. Controllare lo stato dell'operazione di controllo MetroCluster in esecuzione:
+
`metrocluster operation history show -job-id 38`

. Verificare che non siano presenti avvisi sullo stato di salute:
+
`system health alert show`


