---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/boot_node1_with_a900_controller_and_nvs.html 
keywords: boot, NVRAM, controller, module, node1, replacement 
summary: Fare il boot node1 con i moduli controller sostitutivi quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Fare il boot node1 con i moduli di sistema sostitutivi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Node1 con i moduli sostitutivi è ora pronto per l'avvio. Questa sezione fornisce i passaggi necessari per eseguire l'avvio del nodo 1 con i moduli sostitutivi per le seguenti configurazioni di aggiornamento:

[cols="35,65"]
|===
| Controller node1 esistente | Moduli di sistema node1 sostitutivi 


| AFF A800 | AFF A90 o AFF A70 ^1^ 


| AFF A220 configurato come ASA | Modulo controller AFF A150 ^1^ 


| AFF A220
AFF A200
AFF C190 | Modulo controller AFF A150 ^1^ 


| FAS2620
FAS2720 | Modulo controller FAS2820 ^1^ 


| AFF A700 configurato come ASA | Controller ASA A900 e moduli NVRAM ^2^ 


| AFF A700 | Controller AFF A900 e moduli NVRAM ^2^ 


| FAS9000 | Controller FAS9500 e moduli NVRAM ^2^ 
|===
^1^ quando si sostituiscono i moduli controller, si spostano tutte le connessioni dal vecchio al modulo controller sostitutivo.

^2^ quando si sostituiscono il controller e i moduli NVRAM, vengono spostate solo le connessioni della console e di gestione.

.Fasi
. (Solo aggiornamento AFF A800) al prompt del CARICATORE, accedere alla modalità di manutenzione:
+
`boot_ontap maint`

+
.. Rispondere `yes` al prompt di conferma.
.. Mostrare lo stato delle interfacce 100GbE:
+
`storage port show`.

+
Tutte le porte 100GbE collegate agli shelf NS224 o agli switch di storage devono riportare il rapporto come `storage` porte, come mostrato nell'output di esempio riportato di seguito.

+
[listing]
----
*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e8a  ENET storage 100 Gb/s    enabled  online  30
e8b  ENET storage 100 Gb/s    enabled  online  30
e11a ENET storage 100 Gb/s    enabled  online  30
e11b ENET storage 100 Gb/s    enabled  online  30
----
.. Uscire dalla modalità di manutenzione:
+
`halt`



. [[A900_boot_node1]]se sono installate unità di crittografia storage NetApp (NSE), procedere come segue.
+

NOTE: Se la procedura non è stata ancora eseguita, consultare l'articolo della Knowledge base https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Come verificare se un disco è certificato FIPS"^] per determinare il tipo di unità con crittografia automatica in uso.

+
.. Impostare `bootarg.storageencryption.support` a. `true` oppure `false`:
+
[cols="35,65"]
|===
| Se i seguenti dischi sono in uso… | Quindi… 


| Unità NSE conformi ai requisiti di crittografia automatica FIPS 140-2 livello 2 | `setenv bootarg.storageencryption.support *true*` 


| SED non FIPS di NetApp | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Non è possibile combinare dischi FIPS con altri tipi di dischi sullo stesso nodo o coppia ha. È possibile combinare SED con dischi non crittografanti sullo stesso nodo o coppia ha.

====
.. Accedere al menu di avvio speciale e selezionare l'opzione `(10) Set Onboard Key Manager recovery secrets`.
+
Inserire la passphrase e le informazioni di backup registrate in precedenza. Vedere link:manage_storage_encryption_using_okm.html["Gestire la crittografia dello storage utilizzando Onboard Key Manager"].



. Avviare il nodo nel menu di boot:
+
`boot_ontap menu`

. Riassegnare i vecchi dischi node1 al nodo sostituzione1 immettendo "22/7" e selezionando l'opzione nascosta `boot_after_controller_replacement` quando il nodo si arresta nel menu di boot.
+
Dopo un breve intervallo di tempo, viene richiesto di inserire il nome del nodo da sostituire. Se sono presenti dischi condivisi (chiamati anche Advanced Disk Partitioning (ADP) o dischi partizionati), viene richiesto di inserire il nome del nodo del partner ha.

+
Questi prompt potrebbero essere interrati nei messaggi della console. Se non si immette un nome di nodo o non si immette un nome corretto, viene richiesto di inserire nuovamente il nome.

+
[NOTE]
====
Se `[localhost:disk.encryptNoSupport:ALERT]: Detected FIPS-certified encrypting drive` e, oppure `[localhost:diskown.errorDuringIO:error]: error 3 (disk failed) on disk` in caso di errori, attenersi alla seguente procedura:

.. Arrestare il nodo al prompt DEL CARICATORE.
.. Controllare e ripristinare i bootargs di codifica di archiviazione menzionati in <<A900_boot_node1,Fase 2>>.
.. Al prompt del CARICATORE, avviare:
+
`boot_ontap`



====
+
È possibile utilizzare il seguente esempio come riferimento:

+
.Espandere l'esempio di output della console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7

(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.



The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement

This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes

.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>

System rebooting...

.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+
[NOTE]
====
Gli ID di sistema mostrati nell'esempio precedente sono ID di esempio. Gli ID di sistema effettivi dei nodi che si stanno aggiornando saranno diversi.

Tra l'immissione dei nomi dei nodi al prompt e il prompt di accesso, il nodo viene riavviato alcune volte per ripristinare le variabili di ambiente, aggiornare il firmware sulle schede del sistema e per altri aggiornamenti del ONTAP.

====

