---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: 'Connettere il cluster, l"ha, lo storage e le connessioni dati che erano state precedentemente connesse a AFF A800 node1 al AFF A90 o AFF A70 node1 appena installato' 
---
= Cavo node1 per cluster-ha e storage condivisi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se stai eseguendo uno dei seguenti upgrade, devi connettere il cluster, l'ha, lo storage, i dati e le connessioni di gestione che erano stati precedentemente connessi al node1 sul sistema esistente al node1 appena installato sul sistema sostitutivo.

[cols="35,65"]
|===
| Sistema esistente | Sistema sostitutivo 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | C80 
|===


== Collegare le porte e0M e BMC

Se il sistema esistente dispone di una porta di gestione (e0M) e di una porta BMC, le porte e0M e BMC sono combinate e accessibili attraverso la porta "chiave inglese" sul sistema sostitutivo. Prima di eseguire la connessione al sistema sostitutivo, è necessario assicurarsi che le porte e0M e BMC siano connesse allo stesso switch e alla stessa subnet del sistema esistente.

[cols="35,65"]
|===
| Se... | Quindi... 


| Gli indirizzi IP e0M e BMC si trovano sulla stessa subnet IP | Collegare la porta e0M o BMC del sistema esistente alla porta "chiave" del sistema sostitutivo. 


| Gli indirizzi IP e0M e BMC si trovano su sottoreti diverse  a| 
. Unire gli indirizzi IP e0M e BMC in un'unica subnet IP.
. Collegare la porta e0M o BMC del sistema esistente alla porta "chiave" del sistema sostitutivo.


|===


== Connettersi a un cluster senza switch a due nodi

Le tabelle seguenti mostrano l'utilizzo delle porte dello switch per le configurazioni cluster senza switch a due nodi.

|===
| Porta | AFF A800, AFF C800 | AFF A90 | AFF A70, AFF C80 


| Cluster | e0a | e1a | e1a 


| Cluster | e1a | e7a (utilizzare e1b se non è presente e7a) | e1b 


| HA | e0b | Non collegare | Non collegare 


| HA | e1b | Non collegare | Non collegare 


| Porte di storage SAS (se presenti e utilizzate) | Qualsiasi porta disponibile | Qualsiasi porta disponibile | Qualsiasi porta disponibile 


| Porte di storage Ethernet per NS224 shelf | Qualsiasi porta disponibile | Fare riferimento alla mappatura della connettività dello storage Ethernet | Fare riferimento alla mappatura della connettività dello storage Ethernet 
|===
|===
| Porta | AFF A250, AFF C250 | AFF A30, AFF C30, AFF C60 | AFF A50 


| Cluster e ha | e0c | e4a | e4a 


| Cluster e ha | e0d | e2a (utilizzare e4b se non è presente e2a) | e2a (utilizzare e4b se non è presente e2a) 


| Porte di storage Ethernet | Qualsiasi porta disponibile | e3a, e3b | e3a, e3b 


| Porte di storage SAS | Qualsiasi porta disponibile | 3a, 3b | 3a, 3b 
|===


== Connettersi a un cluster collegato allo switch

Per un cluster con collegamento a switch, verificare di soddisfare i seguenti requisiti per il nodo (sostitutivo) AFF A30, AFF A50, AFF A70, AFF A90, AFF C30, AFF C60 o AFF C80:

* Le porte cluster identiche sul nodo di sostituzione si trovano sullo stesso switch. Ad esempio, al termine dell'upgrade, collegare E1a su node1 e E1a su node2 a uno switch del cluster. Analogamente, la seconda porta cluster di entrambi i nodi deve essere collegata al secondo switch cluster. La connessione incrociata tra porte ha e cluster condivisi, in cui E1a di node1 è connesso allo switch e E1a di node2 è connesso allo switch, causa errori di comunicazione ha.
* Il nodo sostitutivo utilizza porte Ethernet ha-cluster condivise. Verificare che gli switch del cluster siano installati con un file di configurazione di riferimento (RCF) che supporti le porte condivise cluster-ha.

