---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decidere se utilizzare la procedura ARL che aggiorna i modelli di controller nello stesso chassis. 
---
= Decidere se utilizzare questa procedura di ricollocazione aggregata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esistono diversi metodi di rilocazione aggregata (ARL) per aggiornare l'hardware del controller. Questo articolo descrive come aggiornare i controller di storage in una coppia HA convertendo il sistema esistente nel sistema sostitutivo, mantenendo lo chassis e i dischi del sistema esistente. Questa complessa procedura dovrebbe essere utilizzata solo da amministratori ONTAP esperti.

Per aiutarti a decidere se questa procedura ARL è adatta all'aggiornamento hardware del tuo controller, dovresti esaminare tutte le seguenti circostanze per gli aggiornamenti supportati e non supportati.



== Supportato per questo aggiornamento ARL

È possibile utilizzare questa procedura ARL nelle seguenti circostanze:

* L'aggiornamento del controller è elencato in <<supported-systems,matrice dei sistemi supportati>> .
* Con il rappresentante di vendita NetApp hai verificato di aver ricevuto l'hardware necessario per l'aggiornamento del controller:
+
** Due controller AFF A90, AFF A70 o AFF C80 e tutti i moduli di i/O. Le lunghezze richieste di cavi 100GbE.
** Due controller AFF A50, AFF A30, AFF C30 o AFF C60 e moduli i/o e i cavi richiesti
** Controller ASA A150, AFF A150 o FAS2820
** Moduli e parti ASA A900, AFF A900 o FAS9500 controller e NVRAM


* È in esecuzione la versione ONTAP minima per l'aggiornamento. Per ulteriori informazioni, fare riferimento alla <<supported-systems,combinazioni di aggiornamento del sistema supportate>>.
* Si è esperti nell'amministrazione di ONTAP e si è soddisfatti dei rischi di lavorare in modalità privilegi diagnostici.
* I sistemi eseguono ONTAP 9.15.1 o versione successiva e utilizzano switch Ethernet per la connessione allo storage Ethernet.



NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).



== Non supportato per questo aggiornamento ARL

Non è possibile utilizzare questa procedura ARL nelle seguenti circostanze:

* Vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si sta utilizzando il software di virtualizzazione FlexArray sul sistema esistente che viene aggiornato.
* Si sta aggiornando una configurazione IP di MetroCluster.
+
Per aggiornare una configurazione IP di MetroCluster, consultare link:other_references.html["Riferimenti"]il collegamento al contenuto _MetroCluster Upgrade and Expansion_.





== Combinazioni di aggiornamento del sistema supportate

Nella tabella seguente viene mostrata la matrice dei sistemi supportati per eseguire un aggiornamento del controller convertendo il sistema esistente nel sistema sostitutivo, mantenendo lo chassis e i dischi del sistema esistente.


CAUTION: Questa procedura si applica rigorosamente alle seguenti configurazioni di aggiornamento. Non utilizzare questa procedura per eseguire un aggiornamento tra qualsiasi altra combinazione di sistema. Per tutti gli altri modelli di controller, fare riferimento al link:other_references.html["Riferimenti"]collegamento ai comandi _utilizzo dei comandi "sostituzione dei controller di sistema" per aggiornare l'hardware dei controller che eseguono ONTAP 9,8 o versioni successive_ e _utilizzo del trasferimento degli aggregati per aggiornare manualmente l'hardware dei controller che esegue ONTAP 9,8 o versioni successive_.

[cols="20,20,40"]
|===
| Sistema esistente | Sistema sostitutivo | Versioni di ONTAP supportate 


| AFF C250 ^1^ | AFF C30, AFF C60 | 9.16.1 


| AFF A250 ^1^ | AFF A30, AFF A50 | 9.16.1 


| AFF C800 ^1^ | AFF C80 | 9.16.1 


| AFF A800 ^1^ | AFF A90 o AFF A70 | 9.15.1 e versioni successive 


| AFF A220 configurato come ASA (All SAN Array) | ASA A150 | 9.13.1P1 e successivi 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e versioni successive 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 e successivi ^2^



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e versioni successive 


| FAS2620 | FAS2820  a| 
9.11.1P7 o versioni successive delle patch (FAS2620) ^2^

9.13.1 e versioni successive (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 e versioni successive 


| AFF A700 configurato come ASA | ASA A900 | 9.13.1P1 e successivi 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 e versioni successive 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 e versioni successive 
|===
^1^ quando si esegue l'upgrade a un sistema introdotto in ONTAP 9.15.1 o versione successiva, ONTAP converte l'efficienza dello storage di tutti i volumi con thin provisioning, inclusi quelli che non utilizzano l'efficienza dello storage, e applica le nuove funzioni di efficienza dello storage che sfruttano la funzionalità di offload dell'hardware. Si tratta di un processo in background automatico, senza alcun impatto visibile sulle prestazioni del sistema. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Scopri di più"^]

^2^ I sistemi AFF A200 e FAS2620 non supportano le versioni ONTAP successive alla 9.11.1.

[NOTE]
====
NetApp consiglia vivamente, quando possibile, di disporre della stessa versione di ONTAP sui sistemi vecchi e sostitutivi.

Le versioni minime di ONTAP riportate nella tabella precedente sono obbligatorie. Queste versioni di ONTAP dispongono della versione del firmware del processore di servizio o del BMC (Baseboard Management Controller) necessaria per supportare la combinazione di tipi di controller all'interno di uno chassis durante un aggiornamento.

====


== Scegli una procedura di aggiornamento hardware diversa

* link:../upgrade-arl/index.html["Esaminare i metodi ARL alternativi disponibili per l'aggiornamento dell'hardware del controller"].
* Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.


.Informazioni correlate
Fare riferimento a link:other_references.html["Riferimenti"] per collegarsi alla _Documentazione ONTAP 9_.
