---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decidere se utilizzare la procedura ARL che aggiorna i modelli di controller nello stesso chassis. 
---
= Decidere se utilizzare la procedura di trasferimento degli aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questo contenuto descrive come aggiornare i controller di storage in una coppia ha mantenendo tutti i dati e i dischi esistenti. Si tratta di una procedura complessa che deve essere utilizzata solo da amministratori esperti.

Seguire questa procedura nei seguenti casi:

* Si sta eseguendo uno dei seguenti aggiornamenti del controller:
+
[cols="50,50"]
|===
| Vecchio controller | Controller sostitutivo 


| AFF A220 configurato come ASA | ASA A150 


| AFF A220, AFF A200 o AFF C190 | AFF A150 


| FAS2620 o FAS2720 | FAS2820 


| AFF A700 configurato come ASA | ASA A900 


| AFF A700 | AFF A900 


| FAS9000 | FAS9500 
|===
* Hai verificato con il tuo commerciale NetApp di aver ricevuto l'hardware per l'upgrade del controller:
+
** Controller ASA A150, AFF A150 o FAS2820
** Controller ASA A900, AFF A900 o FAS9500 e moduli NVRAM e le parti necessarie per l'upgrade


* Si sta utilizzando la versione minima di ONTAP per l'aggiornamento. Per ulteriori informazioni, vedere link:index.html["Panoramica"].
* Non si desidera aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è a proprio agio con i rischi di lavorare in modalità diagnostica con privilegi.


Non utilizzare questa procedura nei seguenti casi:

* Si utilizza il software di virtualizzazione FlexArray sui sistemi AFF A700 o FAS9000.
* Si sta utilizzando uno switch condiviso per l'interconnessione cluster e lo storage collegato Ethernet.


Per l'aggiornamento delle configurazioni Fabric MetroCluster o MetroCluster IP sui sistemi AFF A700 o FAS9000, vedere link:other_references.html["Riferimenti"] Per collegarsi al contenuto _aggiornamento ed espansione MetroCluster_.


NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).

Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento al _Centro documentazione di ONTAP 9_ da cui è possibile accedere alla documentazione del prodotto ONTAP 9.
