---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decidere se utilizzare la procedura ARL che aggiorna i modelli di controller nello stesso chassis. 
---
= Decidere se utilizzare la procedura di trasferimento degli aggregati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo contenuto descrive come aggiornare i controller di storage in una coppia ha mantenendo tutti i dati e i dischi esistenti. Si tratta di una procedura complessa che deve essere utilizzata solo da amministratori esperti.



== Supportato per gli aggiornamenti ARL

È possibile utilizzare questa procedura nelle seguenti circostanze:

* L'aggiornamento del controller è elencato nella link:index.html#supported-systems,["matrice dei sistemi supportati"].
* Con il rappresentante di vendita NetApp hai verificato di aver ricevuto l'hardware necessario per l'aggiornamento del controller:
+
** Due controller AFF A90, AFF A70 o AFF C80 e tutti i moduli di i/O. La lunghezza richiesta di 100GbE cavi.
** Due controller e moduli di i/o AFF A50, AFF A30, AFF C30 o AFF C60. I cavi necessari.
** Controller ASA A150, AFF A150 o FAS2820
** Moduli ASA A900, AFF A900 o FAS9500 controller e NVRAM e le parti


* Si sta utilizzando la versione minima di ONTAP per l'aggiornamento. Per ulteriori informazioni, vedere link:index.html["Panoramica"].
* Non si desidera aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è a proprio agio con i rischi di lavorare in modalità diagnostica con privilegi.
* I sistemi eseguono ONTAP 9.15.1 o versione successiva e utilizzano switch Ethernet per la connessione allo storage Ethernet.




== Non supportato per gli aggiornamenti ARL

Non è possibile utilizzare questa procedura nelle seguenti circostanze:

* Si sta utilizzando il software di virtualizzazione FlexArray sul sistema esistente che viene aggiornato.
* Si sta aggiornando una configurazione IP di MetroCluster.
+
Per aggiornare una configurazione IP di MetroCluster, consultare link:other_references.html["Riferimenti"]il collegamento al contenuto _MetroCluster Upgrade and Expansion_.




NOTE: Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).

Se si preferisce un metodo diverso per aggiornare l'hardware del controller e si desidera eseguire spostamenti di volume, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

Fare riferimento a. link:other_references.html["Riferimenti"] Collegamento al _Centro documentazione di ONTAP 9_ da cui è possibile accedere alla documentazione del prodotto ONTAP 9.
