---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/ensure_new_controllers_are_set_up_correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: 'Verificare che la coppia ha sia attivata, verificare l"accesso allo storage node1 e node2 e LIF e confermare la proprietà aggregata dopo l"aggiornamento dei modelli di controller nello stesso chassis.' 
---
= Verificare che i nuovi controller siano impostati correttamente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per confermare la corretta configurazione, è necessario verificare che la coppia ha sia attivata. È inoltre necessario verificare che node1 e node2 possano accedere reciprocamente allo storage e che nessuno dei due possieda le LIF dei dati appartenenti ad altri nodi del cluster. Inoltre, è necessario verificare che tutti gli aggregati di dati si trovino sui nodi principali corretti e che i volumi di entrambi i nodi siano online. Se uno dei nuovi nodi dispone di un adattatore di destinazione unificato, è necessario ripristinare le configurazioni delle porte e modificare l'utilizzo dell'adattatore.

.Fasi
. Dopo i controlli post-node2, vengono attivate la coppia di ha cluster e failover dello storage per il cluster node2. Al termine dell'operazione, entrambi i nodi vengono visualizzati come completati e il sistema esegue alcune operazioni di pulizia.
. Verificare che il failover dello storage sia attivato:
+
`storage failover show`

+
L'esempio seguente mostra l'output del comando quando è attivato il failover dello storage:

+
[listing]
----
cluster::> storage failover show
                          Takeover
Node	    Partner       Possible      State Description
----------  -----------   ------------  ------------------
node1	    node2         true	        Connected to node2
node2	    node1         true	        Connected to node1
----
. Verificare che node1 e node2 appartengano allo stesso cluster utilizzando il seguente comando ed esaminando l'output:
+
`cluster show`

. Verificare che node1 e node2 possano accedere reciprocamente allo storage utilizzando il seguente comando ed esaminando l'output:
+
`storage failover show -fields local-missing-disks,partner-missing-disks`

. Verificare che né node1 né node2 detengano le LIF dei dati di proprietà di altri nodi del cluster utilizzando il seguente comando ed esaminando l'output:
+
`network interface show`

+
Se nessuno dei nodi 1 o node2 possiede le LIF dei dati di proprietà di altri nodi del cluster, ripristinare le LIF dei dati al proprietario di casa:

+
`network interface revert`

. Verificare che gli aggregati siano di proprietà dei rispettivi nodi principali.
+
`storage aggregate show -owner-name _node1_`

+
`storage aggregate show -owner-name _node2_`

. Determinare se i volumi sono offline:
+
`volume show -node _node1_ -state offline`

+
`volume show -node _node2_ -state offline`

. Se alcuni volumi non sono in linea, confrontarli con l'elenco dei volumi non in linea acquisito nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"]e portare online uno qualsiasi dei volumi offline, come richiesto, utilizzando il seguente comando, una volta per ciascun volume:
+
`volume online -vserver _vserver_name_ -volume _volume_name_`

. Installare nuove licenze per i nuovi nodi utilizzando il seguente comando per ciascun nodo:
+
`system license add -license-code _license_code,license_code,license_code..._`

+
Il parametro License-code accetta un elenco di 28 chiavi alfabetiche maiuscole. È possibile aggiungere una licenza alla volta oppure più licenze contemporaneamente, separando ciascuna chiave di licenza con una virgola.

. Rimuovere tutte le vecchie licenze dai nodi originali utilizzando uno dei seguenti comandi:
+
`system license clean-up -unused -expired`

+
`system license delete -serial-number _node_serial_number_ -package _licensable_package_`

+
--
** Eliminare tutte le licenze scadute:
+
`system license clean-up -expired`

** Eliminare tutte le licenze inutilizzate:
+
`system license clean-up -unused`

** Eliminare una licenza specifica da un cluster utilizzando i seguenti comandi sui nodi:
+
`system license delete -serial-number _node1_serial_number_ -package *`
`system license delete -serial-number _node2_serial_number_ -package *`



--
+
Viene visualizzato il seguente output:

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
Invio `y` per rimuovere tutti i pacchetti.

. Verificare che le licenze siano installate correttamente utilizzando il seguente comando ed esaminandone l'output:
+
`system license show`

+
È possibile confrontare l'output con quello acquisito in link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"] sezione.

. [[unset_maxwait]] se nella configurazione vengono utilizzate unità con crittografia automatica ed è stato impostato `kmip.init.maxwait` variabile a. `off` (Ad esempio, in _Boot node2 with the replacement system modules_, link:boot_node2_with_a900_controller_and_nvs.html#boot_node2_step1["Fase 1"]), è necessario annullare l'impostazione della variabile:
+
`set diag; systemshell -node _node_name_ -command sudo kenv -u -p kmip.init.maxwait`

. Configurare gli SP utilizzando il seguente comando su entrambi i nodi:
+
`system service-processor network modify -node _node_name_`

+
Fare riferimento a. link:other_references.html["Riferimenti"] Per informazioni dettagliate sul sistema, consultare il documento _riferimento amministrazione sistema_ e i comandi di _ONTAP 9: Riferimento pagina manuale_ `service-processor network modify` comando.

. Se si desidera configurare un cluster senza switch sui nuovi nodi, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_ e seguire le istruzioni in _passaggio a un cluster senza switch a due nodi_.


.Al termine
Se Storage Encryption è attivato su node1 e node2, completare la sezione link:set_up_storage_encryption_new_module.html["Impostare Storage Encryption sul nuovo modulo controller"]. In caso contrario, completare la sezione link:decommission_old_system.html["Decommissionare il vecchio sistema"].
