---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: Capire se è possibile utilizzare ARL, mantenendo i vecchi dischi e chassis del sistema, per la configurazione di aggiornamento. 
---
= Linee guida per l'aggiornamento dei controller
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per capire se è possibile utilizzare il trasferimento aggregato (ARL), mantenendo il vecchio chassis e i dischi del sistema, dipende dalla configurazione di aggiornamento del sistema e dalla versione di ONTAP.



== Aggiornamenti supportati per ARL

Gli aggiornamenti dei controller sono supportati per alcune configurazioni di sistema. Fare riferimento al link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems["combinazioni di aggiornamento del sistema supportate"] per un elenco dei sistemi supportati e la versione minima di ONTAP.

Se è stato ricevuto un nuovo sistema AFF A30, AFF A50, AFF A70, AFF A90, AFF A150, AFF A900, AFF C30, AFF C60, AFF C80, FAS2820 o FAS9500 come sistema completo, incluso un nuovo chassis, fare riferimento al link:other_references.html["Riferimenti"]collegamento per i comandi _use "system controller replace" (utilizza sostituzione controller di sistema) per aggiornare l'hardware del controller che esegue ONTAP 9,8 o versioni successive.

L'upgrade del controller tramite ARL è supportato sui sistemi configurati con volumi di conformità SnapLock Enterprise e SnapLock.



== Cluster senza switch a due nodi

Se si stanno aggiornando i nodi in un cluster senza switch a due nodi, è possibile lasciare i nodi nel cluster senza switch durante l'aggiornamento. Non è necessario convertirli in un cluster con switch.



== Switch Attached Clusters

Se si stanno aggiornando i nodi in un cluster collegato a uno switch del cluster, è necessario verificare che la marca, il modello, la versione del firmware, l'RCF e la versione di ONTAP in esecuzione sullo switch siano uguali a quelle in esecuzione sul controller sostitutivo dopo l'aggiornamento. Se necessario, è necessario eseguire l'aggiornamento dello switch prima di aggiornare i controller utilizzando ARL.

Per ulteriori informazioni, vedere link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Connettersi a un cluster collegato allo switch"].



== Risolvere i problemi

Si potrebbe riscontrare un errore durante l'aggiornamento della coppia di nodi. Il nodo potrebbe bloccarsi, gli aggregati potrebbero non spostarsi o i LIF potrebbero non migrare. La causa dell'errore e la relativa soluzione dipendono dal momento in cui si è verificato l'errore durante la procedura di aggiornamento.

In caso di problemi, fare riferimento al link:aggregate_relocation_failures.html["Risolvere i problemi"] sezione alla fine della procedura per ulteriori informazioni e possibili soluzioni. Le informazioni sui guasti che possono verificarsi sono elencate in base alla fase della procedura nella link:overview_of_the_arl_upgrade.html["Sequenza di aggiornamento ARL"] .

Se non trovi una soluzione al problema riscontrato, contatta l'assistenza tecnica.
