---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: Capire se è possibile utilizzare ARL, mantenendo i vecchi dischi e chassis del sistema, per la configurazione di aggiornamento. 
---
= Linee guida per l'aggiornamento dei controller
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per capire se è possibile utilizzare il trasferimento aggregato (ARL), mantenendo il vecchio chassis e i dischi del sistema, dipende dalla configurazione di aggiornamento del sistema e dalla versione di ONTAP.



== Aggiornamenti supportati per ARL

Gli aggiornamenti dei controller sono supportati per alcune configurazioni di sistema. Per visualizzare l'elenco dei sistemi supportati e le versioni minime di ONTAP, vedere link:index.html["Panoramica"].

Se hai ricevuto un nuovo AFF A150, FAS2820, AFF A900 o FAS9500 come sistema completo, incluso un nuovo chassis, fai riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _utilizzare i comandi "system controller replace" per aggiornare l'hardware del controller con contenuto ONTAP 9.8 o successivo.

L'upgrade del controller tramite ARL è supportato sui sistemi configurati con volumi di conformità SnapLock Enterprise e SnapLock.



== Cluster senza switch a due nodi

Se si stanno aggiornando i nodi in un cluster senza switch a due nodi, è possibile lasciare i nodi nel cluster senza switch durante l'aggiornamento. Non è necessario convertirli in un cluster con switch.



== Switch Attached Clusters

Se si stanno aggiornando i nodi in un cluster collegato a uno switch del cluster, è necessario verificare che la marca, il modello, la versione del firmware, l'RCF e la versione di ONTAP in esecuzione sullo switch siano uguali a quelle in esecuzione sul controller sostitutivo dopo l'aggiornamento. Se necessario, è necessario eseguire l'aggiornamento dello switch prima di aggiornare i controller utilizzando la procedura ARL descritta in questa documentazione.



== Risolvere i problemi

Se si verificano problemi durante l'aggiornamento dei controller, consultare link:troubleshoot_index.html["Risolvere i problemi"] sezione alla fine della procedura per ulteriori informazioni e possibili soluzioni.

Se non si riesce a trovare una soluzione al problema riscontrato, contattare il supporto tecnico.
