---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900 
summary: 'È possibile aggiornare l"hardware del controller su un AFF A700 a un AFF A900 sostituendo il modulo controller e NVS.' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa procedura descrive come aggiornare l'hardware del controller utilizzando ARL (aggregate relocation) per le seguenti configurazioni di sistema:

[cols="30,20,20,30"]
|===
| Metodo | Versione di ONTAP | Sistemi supportati | Descrizione 


| Utilizzo di `system controller replace` comandi | 9.10.1P10, 9.11.1P6 o versioni successive | Da AFF A700 a AFF A900 | Converte un sistema AFF A700 in un sistema AFF A900, mantenendo lo chassis A700 


| Utilizzo di `system controller replace` comandi | 9.10.1P10, 9.11.1P6 o versioni successive | Da FAS9000 a FAS9500 | Converte un sistema FAS9000 in un sistema FAS9500, mantenendo lo chassis FAS9000. 
|===
È possibile aggiornare senza interruzioni l'hardware del controller su una coppia ad alta disponibilità (ha) scambiando il controller e i moduli NVRAM. Innanzitutto, si esegue la migrazione degli aggregati non root tra i vecchi nodi controller. Dopo l'installazione, si esegue la migrazione degli aggregati non root dai vecchi nodi controller ai nodi controller sostitutivi. I dati ospitati sui nodi che si sta aggiornando sono accessibili durante la procedura di aggiornamento.

.A proposito di questa attività
Durante questa procedura di aggiornamento del controller, è possibile sostituire solo le due FRU (Field Replaceable Unit) su ciascun nodo del sistema AFF A700 o FAS9000 con le nuove FRU.


NOTE: Non è necessario spostare, scollegare o ricollegare le schede i/o, i cavi dati, gli shelf di dischi e i dischi.

Questa procedura utilizza un metodo chiamato ARL (aggregate relocation), che sfrutta la configurazione ha per consentire di spostare la proprietà di aggregati non root da un nodo a un altro se condividono lo storage all'interno dello stesso cluster.

Durante la procedura, l'hardware del controller originale viene aggiornato con l'hardware del controller sostitutivo, riallocando la proprietà degli aggregati non root. La migrazione degli aggregati viene eseguita più volte da un nodo all'altro per confermare che almeno un nodo fornisce i dati degli aggregati durante l'intera procedura di aggiornamento. Inoltre, è possibile migrare i dati LIF tra i nodi del cluster durante la migrazione.


NOTE: I termini *node1* e *node2* sono utilizzati solo come riferimento ai nomi dei nodi in questo documento. Quando si segue la procedura, è necessario sostituire i nomi reali dei nodi.

.Informazioni importanti
* Questa procedura è complessa e presuppone che si disponga di competenze di amministrazione avanzate di ONTAP. È inoltre necessario leggere e comprendere link:guidelines_for_upgrading_controllers_with_arl.html["Linee guida per l'aggiornamento dei controller"] e a. link:overview_of_the_arl_upgrade.html["Panoramica dell'aggiornamento ARL"] prima di iniziare l'aggiornamento.
* Questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato in un altro sistema. I passaggi necessari per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. È necessario contattare il supporto tecnico se l'hardware del controller sostitutivo è stato utilizzato in precedenza come parte di un altro cluster ONTAP o come sistema standalone a nodo singolo.
* È possibile utilizzare questa procedura per aggiornare l'hardware del controller nei cluster con più di due nodi; tuttavia, è necessario eseguire la procedura separatamente per ogni coppia ha nel cluster.
* Questa procedura si applica solo ai sistemi AFF A700 e FAS9000. Per tutti gli altri modelli di controller che richiedono l'aggiornamento a un sistema AFF A900 o FAS9500, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi ai comandi di _sostituzione del controller di sistema" per aggiornare l'hardware del controller che esegue ONTAP 9.8 o versione successiva_ e al contenuto di _utilizzo del trasferimento aggregato per aggiornare manualmente l'hardware del controller che esegue ONTAP 9.8 o versione successiva_.
* I sistemi AFF A900 e FAS9500 supportano solo l'alimentazione high-line (da 200 V a 240 V). Se il sistema AFF A700 o FAS9000 è alimentato a bassa tensione (da 100 V a 120 V), è necessario convertire l'alimentazione in ingresso del sistema AFF A700 o FAS9000 prima di utilizzare questa procedura.
* Se si esegue l'aggiornamento da un sistema AFF A700 o FAS9000 con downtime, è possibile aggiornare l'hardware del controller spostando lo storage o contattare il supporto tecnico. Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_.

