---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verificare che i dati LIF NAS node1 sul node2 vengano ricollocati da node2 a node1 quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Sposta node1 aggregati non root e LIF dati NAS da node2 TB a node1 aggiornato
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver verificato la configurazione di rete su node1 e prima di spostare gli aggregati da node2 a node1, verificare che i dati NAS LIF appartenenti a node1 che sono attualmente su node2 vengano ricollocati da node2 a node1. È inoltre necessario verificare che le LIF SAN esistano nel node1.

.A proposito di questa attività
Le LIF remote gestiscono il traffico verso le LUN SAN durante la procedura di aggiornamento. Lo spostamento delle LIF SAN non è necessario per lo stato del cluster o del servizio durante l'aggiornamento. LE LIF SAN non vengono spostate a meno che non sia necessario mapparle su nuove porte. Dopo aver portato il node1 online, è necessario verificare che i LIF siano integri e posizionati sulle porte appropriate.

.Fasi
. Riprendere l'operazione di trasferimento:
+
`system controller replace resume`

+
Il sistema esegue le seguenti operazioni:

+
--
** Verifica del quorum del cluster
** Verifica dell'ID di sistema
** Controllo della versione dell'immagine
** Verifica della piattaforma di destinazione
** Verifica della raggiungibilità della rete


--
+
L'operazione viene interrotta in questa fase del controllo della raggiungibilità della rete.

. Eseguire un controllo della raggiungibilità della rete:
+
`network port reachability show -node node1`

+
Verificare che tutte le porte connesse, inclusi il gruppo di interfacce e le porte VLAN, mostrino il loro stato come `OK`.

. Per i seguenti upgrade, è necessario riassegnare le LIF SAN FCP.
+
[cols="35,65"]
|===
| Sistema esistente | Sistema sostitutivo 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | AFF C80 
|===
+
Per tutti gli altri aggiornamenti del sistema, passare alla <<resume_relocation_step4,Fase 4>>.

+
.. Riassegna le LIF SAN FCP utilizzate per l'accesso ai dati FCP o FC-NVMe alle porte home corrette:
+
`network interface show -vserver <vserver_hosting_fcp_lifs>`

.. Per le LIF con il nodo corrente come node1 aggiornato e la porta corrente riporta "status oper" come "-" (poiché la porta esisteva sul nodo AFF A800 ma non esiste sul nodo AFF A90), modificare la porta corrente prima di poterla portare online.
+
Verificare che la connettività fisica sia stabilita alla porta di destinazione FC in cui è necessario spostare la LIF FC:

+
--
... Impostare lo stato LIF su "DOWN" (giù):
+
`network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down`

... Modifica la porta home della LIF:
+
`network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>`

... Impostare lo stato della LIF su "UP":
+
`network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up`



--
+
Ripetere i passaggi secondari a e b per ogni LIF FC SAN che viene home su node1.



. [[resume_relocation_step4]]riprendere l'operazione di rilocazione:
+
`system controller replace resume`

+
Il sistema esegue i seguenti controlli:

+
--
** Controllo dello stato del cluster
** Controllo dello stato LIF del cluster


--
+
Dopo aver eseguito questi controlli, il sistema ricolloca gli aggregati non root e le LIF dei dati NAS di proprietà di node1 nel nuovo node1.

+
L'operazione di sostituzione del controller viene interrotta al termine del trasferimento delle risorse.

. Controllare lo stato delle operazioni di trasferimento aggregato e LIF dei dati NAS:
+
`system controller replace show-details`

+
Se la procedura di sostituzione del controller è in pausa, controllare e correggere l'errore, se presente, quindi il problema `resume` per continuare l'operazione.

. Se necessario, ripristinare e ripristinare eventuali LIF spostate. Elencare eventuali LIF spostate:
+
`cluster controller-replacement network displaced-interface show`

+
In caso di spostamento di LIF, ripristinare il nodo home al nodo node1:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Riprendere l'operazione per richiedere al sistema di eseguire i controlli successivi richiesti:
+
`system controller replace resume`

+
Il sistema esegue i seguenti post-controlli:

+
** Verifica del quorum del cluster
** Controllo dello stato del cluster
** Controllo della ricostruzione degli aggregati
** Controllo dello stato dell'aggregato
** Controllo dello stato del disco
** Controllo dello stato LIF del cluster
** Controllo del volume



