---
sidebar: sidebar 
permalink: /upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Verificare che le LIF dei dati NAS di node2 sul node1 vengano ricollocate dal node1 al node2 quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis. 
---
= Riportare al nodo gli aggregati non root e le LIF dei dati NAS 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver verificato la configurazione di rete sul nodo 2 e prima di spostare gli aggregati dal nodo 1 al nodo 2, verificare che i dati NAS LIF appartenenti al nodo 2 che sono attualmente sul nodo 1 vengano ricollocati dal nodo 1 al nodo 2. È inoltre necessario verificare che le LIF SAN esistano sul nodo 2.

.A proposito di questa attività
Le LIF remote gestiscono il traffico verso le LUN SAN durante la procedura di aggiornamento. Lo spostamento delle LIF SAN non è necessario per lo stato del cluster o del servizio durante l'aggiornamento. LE LIF SAN non vengono spostate a meno che non sia necessario mapparle su nuove porte. Dopo aver portato il nodo 2 online, è necessario verificare che i LIF siano integri e posizionati sulle porte appropriate.

.Fasi
. Riprendere l'operazione di trasferimento:
+
`system controller replace resume`

+
Il sistema esegue le seguenti operazioni:

+
--
** Verifica del quorum del cluster
** Verifica dell'ID di sistema
** Controllo della versione dell'immagine
** Verifica della piattaforma di destinazione
** Verifica della raggiungibilità della rete


--
+
L'operazione viene interrotta in questa fase del controllo della raggiungibilità della rete.

. Riprendere l'operazione di trasferimento:
+
`system controller replace resume`

+
Il sistema esegue i seguenti controlli:

+
--
** Controllo dello stato del cluster
** Controllo dello stato LIF del cluster


--
+
Dopo aver eseguito questi controlli, il sistema ricolloca gli aggregati non root e le LIF dei dati NAS in node2, che è ora in esecuzione sul controller sostitutivo.

+
L'operazione di sostituzione del controller viene interrotta al termine del trasferimento delle risorse.

. Controllare lo stato delle operazioni di trasferimento aggregato e LIF dei dati NAS:
+
`system controller replace show-details`

+
Se la procedura di sostituzione del controller è in pausa, controllare e correggere l'errore, se presente, quindi il problema `resume` per continuare l'operazione.

. Se necessario, ripristinare e ripristinare eventuali LIF spostate. Elencare eventuali LIF spostate:
+
`cluster controller-replacement network displaced-interface show`

+
In caso di spostamento di LIF, ripristinare il nodo home al nodo node2:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Riprendere l'operazione per richiedere al sistema di eseguire i controlli successivi richiesti:
+
`system controller replace resume`

+
Il sistema esegue i seguenti post-controlli:

+
** Verifica del quorum del cluster
** Controllo dello stato del cluster
** Controllo della ricostruzione degli aggregati
** Controllo dello stato dell'aggregato
** Controllo dello stato del disco
** Controllo dello stato LIF del cluster
** Controllo del volume



