---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/netboot_node1.html 
keywords: preparing, prepare, netboot, ontap, node1 
summary: Quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis, è necessario eseguire il netboot node1 dopo aver sostituito il modulo di sistema sostitutivo corrispondente. 
---
= Node1 NetBoot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver scambiato i moduli di sistema sostitutivi corrispondenti, è necessario eseguire il netboot node1. Il termine netboot significa che si sta eseguendo l'avvio da un'immagine ONTAP memorizzata su un server remoto. Quando ci si prepara per il netboot, si aggiunge una copia dell'immagine di boot di ONTAP 9 su un server web a cui il sistema può accedere.

Non è possibile controllare la versione di ONTAP installata sul supporto di avvio del modulo controller sostitutivo, a meno che non sia installata in uno chassis e accesa. La versione di ONTAP sul supporto di avvio del sistema sostitutivo deve essere la stessa della versione di ONTAP in esecuzione sul vecchio sistema che si sta aggiornando e le immagini di avvio primaria e di backup devono corrispondere. Per verificare la versione minima supportata di ONTAP per l'aggiornamento, vedere link:index.html["Panoramica"].

È possibile configurare le immagini eseguendo un netboot seguito da `wipeconfig` dal menu di boot. Se il modulo controller è stato utilizzato in precedenza in un altro cluster, il `wipeconfig` il comando cancella qualsiasi configurazione residua sul supporto di avvio.

Per eseguire l'avvio da rete, è possibile utilizzare anche l'opzione di avvio USB. Consultare l'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["Come utilizzare il comando boot_recovery LOADER per installare ONTAP per la configurazione iniziale di un sistema"^].

.Prima di iniziare
* Verificare che sia possibile accedere a un server HTTP con il sistema.
* Scaricare i file di sistema necessari per il sistema e la versione corretta di ONTAP dal _sito di supporto NetApp_. Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_.


.A proposito di questa attività
È necessario eseguire il netboot dei nuovi controller se non sono installati sulla stessa versione di ONTAP 9 installata sui controller originali. Dopo aver installato ciascun nuovo controller, avviare il sistema dall'immagine di ONTAP 9 memorizzata sul server Web. È quindi possibile scaricare i file corretti sul dispositivo di avvio per i successivi avvii del sistema.

.Fasi
. Fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al _sito di supporto NetApp_ e scaricare i file utilizzati per eseguire il netboot del sistema.
. [[netboot_node1_step2]]Scarica il software ONTAP appropriato dalla sezione di download del software del _sito di supporto NetApp_ e memorizza il `<ontap_version>_image.tgz` file in una directory accessibile dal web.
. Passare alla directory accessibile dal Web e verificare che i file necessari siano disponibili.
. L'elenco delle directory deve contenere `<ontap_version>_image.tgz`.
. Configurare la connessione di netboot scegliendo una delle seguenti operazioni.
+

NOTE: È necessario utilizzare la porta di gestione e l'IP come connessione di netboot. Non utilizzare un IP LIF dei dati, altrimenti potrebbe verificarsi un'interruzione dei dati durante l'aggiornamento.

+
[cols="35,65"]
|===
| Se DHCP (Dynamic host Configuration Protocol) è... | Quindi... 


| In esecuzione | Configurare la connessione automaticamente utilizzando il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -auto` 


| Non in esecuzione  a| 
Configurare manualmente la connessione utilizzando il seguente comando al prompt dell'ambiente di boot:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` È l'indirizzo IP del sistema di storage (obbligatorio).
`_netmask_` è la maschera di rete del sistema di storage (obbligatoria).
`_gateway_` è il gateway per il sistema storage (obbligatorio).
`_dns_addr_` È l'indirizzo IP di un name server sulla rete (opzionale).
`_dns_domain_` È il nome di dominio DNS (Domain Name Service) (facoltativo).


NOTE: Potrebbero essere necessari altri parametri per l'interfaccia. Invio `help ifconfig` al prompt del firmware per ulteriori informazioni.

|===
. Eseguire il netboot al nodo 1:
+
`netboot \http://<web_server_ip/path_to_web_accessible_directory>/netboot/kernel`

+

NOTE: Non interrompere l'avvio.

. Attendere l'avvio del node1 sul modulo controller AFF A900 o FAS9500 e visualizzare le opzioni del menu di avvio come mostrato di seguito:
+
[listing]
----
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)?
----
. Dal menu di avvio, selezionare opzione `(7) Install new software first`.
+
Questa opzione di menu consente di scaricare e installare la nuova immagine ONTAP sul dispositivo di avvio.

+
Ignorare il seguente messaggio:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Questa nota si applica agli aggiornamenti software ONTAP senza interruzioni e non agli aggiornamenti del controller.

+

NOTE: Utilizzare sempre netboot per aggiornare il nuovo nodo all'immagine desiderata. Se si utilizza un altro metodo per installare l'immagine sul nuovo controller, l'immagine potrebbe non essere corretta. Questo problema riguarda tutte le versioni di ONTAP. La procedura di netboot combinata con l'opzione `(7) Install new software` Consente di cancellare il supporto di avvio e di posizionare la stessa versione di ONTAP su entrambe le partizioni dell'immagine.

. Se viene richiesto di continuare la procedura, immettere `y`E quando viene richiesto il pacchetto, immettere l'URL:
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`
+
Il `<path_to_the_web-accessible_directory>` dovrebbe portare alla posizione in cui è stato scaricato `<ontap_version>_image.tgz` poll <<netboot_node1_step2,Fase 2>>.

. Completare i seguenti passaggi secondari per riavviare il modulo controller:
+
.. Invio `n` per ignorare il ripristino del backup quando viene visualizzato il seguente prompt:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Invio `y` per riavviare quando viene visualizzato il seguente prompt:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Il modulo controller si riavvia ma si arresta al menu di avvio perché il dispositivo di avvio è stato riformattato e i dati di configurazione devono essere ripristinati.



. Quando richiesto, eseguire `wipeconfig` comando per cancellare qualsiasi configurazione precedente sul supporto di avvio:
+
.. Quando viene visualizzato il messaggio riportato di seguito, rispondere `yes`:
+
[listing]
----
This will delete critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?:
----
.. Il nodo viene riavviato per terminare `wipeconfig` e poi si ferma al menu di boot.


. Selezionare l'opzione `5` per passare alla modalità di manutenzione dal menu di avvio. Risposta `yes` al prompt finché il nodo non si arresta in modalità di manutenzione e al prompt dei comandi `*>`.
. Verificare che il controller e lo chassis siano configurati come `ha`:
+
`ha-config show`

+
L'esempio seguente mostra l'output di `ha-config show` comando:

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. Se il controller e lo chassis non sono configurati come `ha`, utilizzare i seguenti comandi per correggere la configurazione:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

. Verificare `ha-config` impostazioni:
+
`ha-config show`

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. Arrestare il nodo 1:
+
`halt`

+
Node1 dovrebbe arrestarsi al prompt DEL CARICATORE.

. Al nodo 2, controllare la data, l'ora e il fuso orario del sistema:
+
`date`

. Al nodo 1, controllare la data utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show date`

. Se necessario, impostare la data sul node1:
+
`set date _mm/dd/yyyy_`

+

NOTE: Impostare la data UTC corrispondente al nodo 1.

. In node1, controllare l'ora utilizzando il seguente comando al prompt dell'ambiente di boot:
+
`show time`

. Se necessario, impostare l'ora su node1:
+
`set time _hh:mm:ss_`

+

NOTE: Impostare l'ora UTC corrispondente su node1.

. Impostare l'ID del sistema partner su node1:
+
`setenv partner-sysid _node2_sysid_`

+
Per il node1, il `partner-sysid` deve essere quello del node2. È possibile ottenere l'ID di sistema node2 da `node show -node _node2_` output del comando su node2.

+
.. Salvare le impostazioni:
+
`saveenv`



. Al nodo 1, al prompt DEL CARICATORE, verificare `partner-sysid` per il nodo 1:
+
`printenv partner-sysid`


