---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1. aff, a900, NVRAM, controller 
summary: Spostare gli aggregati non root del node2 al node1 durante un aggiornamento da AFF A700 a AFF A900. 
---
= Spostare aggregati non root e LIF dati NAS da node2 a node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di poter sostituire il nodo 2 con il modulo controller AFF A900 o FAS9500 e il modulo NVRAM, è necessario prima spostare gli aggregati non root di proprietà di node2 in node1.

.Prima di iniziare
Una volta completati i controlli successivi alla fase precedente, la release di risorse per node2 si avvia automaticamente. Gli aggregati non root e le LIF di dati non SAN vengono migrati da node2 al nuovo node1.

.A proposito di questa attività
Una volta migrati gli aggregati e i LIF, l'operazione viene sospesa per scopi di verifica. In questa fase, è necessario verificare che tutti gli aggregati non root e le LIF di dati non SAN vengano migrati nel nuovo node1.

Il proprietario dell'abitazione per gli aggregati e le LIF non viene modificato; solo il proprietario corrente viene modificato.

.Fasi
. Verificare che tutti gli aggregati non root siano online e che il loro stato sia su node1:
+
`storage aggregate show -node node1 -state online -root false`

+
L'esempio seguente mostra che gli aggregati non root sul nodo 1 sono online:

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	 #Vols	 Nodes	  RAID	   Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB      744.8GB	 0%	 online	  5	 node1	  raid_dp  normal
aggr_2	      825.0GB	    825.0GB	 0%	 online	  1	 node1	  raid_dp  normal
2 entries were displayed.
----
+
Se gli aggregati sono andati offline o diventano estranei sul node1, portarli online utilizzando il seguente comando sul nuovo node1, una volta per ogni aggregato:

+
`storage aggregate online -aggregate _aggr_name_`

. Verificare che tutti i volumi siano online sul nodo 1 utilizzando il seguente comando sul nodo 1 ed esaminandone l'output:
+
`volume show -node node1 -state offline`

+
Se alcuni volumi sono offline sul nodo 1, portarli online utilizzando il seguente comando sul nodo 1, una volta per ogni volume:

+
`volume online -vserver _vserver-name_ -volume _volume-name_`

+
Il `_vserver-name_` da utilizzare con questo comando si trova nell'output del precedente `volume show` comando.

. Verificare che le LIF siano state spostate nelle porte corrette e che lo stato sia `up`. Se le LIF non sono attive, impostare lo stato amministrativo delle LIF su UP immettendo il seguente comando, una volta per ciascuna LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ - status-admin up`

. Verificare che non vi siano dati LIF rimasti sul nodo 2 utilizzando il seguente comando ed esaminando l'output:
+
`network interface show -curr-node _node2_ -role data`


