---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_7_index.html 
keywords: upgrade, authentication, storage, volume, aggregate, encryption, overview, stage 7 
summary: 'Fase 7 sequenza di processo per un aggiornamento ARL con `system controller replace` comandi per aggiornare i modelli di controller nello stesso chassis.' 
---
= Panoramica della fase 7
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 7, confermi che i nuovi nodi sono impostati correttamente e, se i nuovi nodi sono abilitati per la crittografia, configuri e configuri Storage Encryption o NetApp Volume Encryption. È inoltre necessario decommissionare i vecchi nodi e riprendere le operazioni di SnapMirror.

.Fasi
. link:manage-authentication-using-kmip-servers.html["Gestire l'autenticazione utilizzando i server KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Verificare che i nuovi controller siano impostati correttamente"]
. link:set_up_storage_encryption_new_module.html["Impostare Storage Encryption sul nuovo modulo controller"]
. link:set_up_netapp_volume_encryption_new_module.html["Impostare NetApp Volume o aggregate Encryption sul nuovo modulo controller"]
. link:decommission_old_system.html["Decommissionare il vecchio sistema"]
. link:resume_snapmirror_operations.html["Riprendere le operazioni di SnapMirror"]

