---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_7_index.html 
keywords: upgrade, authentication, storage, volume, aggregate, encryption, overview, stage 7 
summary: 'Fase 7 sequenza di processo per un aggiornamento ARL con `system controller replace` comandi per aggiornare i modelli di controller nello stesso chassis.' 
---
= Panoramica della fase 7
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 7, confermi che i nuovi nodi sono impostati correttamente e, se i nuovi nodi sono abilitati per la crittografia, configuri e configuri Storage Encryption o NetApp Volume Encryption. È inoltre necessario decommissionare i vecchi nodi e riprendere le operazioni di SnapMirror.

.Fasi
. link:manage-authentication-using-kmip-servers.html["Gestire l'autenticazione utilizzando i server KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Verificare che i nuovi controller siano impostati correttamente"]
. link:set_up_storage_encryption_new_module.html["Impostare Storage Encryption sul nuovo modulo controller"]
. link:set_up_netapp_volume_encryption_new_module.html["Impostare NetApp Volume o aggregate Encryption sul nuovo modulo controller"]
. link:decommission_old_system.html["Decommissionare il vecchio sistema"]
. link:resume_snapmirror_operations.html["Riprendere le operazioni di SnapMirror"]


[NOTE]
====
I sistemi AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70 e FAS90 condividono 100GbE porte di rete per le connessioni cluster e ha. Questi sistemi possono supportare connessioni cluster 10GbE o 25GbE a switch cluster legacy; tuttavia, NetApp consiglia di eseguire l'aggiornamento a velocità cluster 100GbE quando gli switch 10GbE e 25GbE non sono più necessari. Per ulteriori informazioni, vedere i seguenti articoli della Knowledge base:

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Come configurare porte cluster 10G o 25g in una nuova configurazione cluster"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Come convertire le porte del cluster 10G o 25g esistenti in porte del cluster 40G o 100g"^]


Se non è possibile collegare e0a o e0b porte cluster sul nodo esistente alle porte cluster sul nuovo nodo, vedere link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID bug online di NetApp CONTAP-166978"^].

====