---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_3_index.html 
keywords: upgrade, boot, node1, verify, restore, overview, stage 3 
summary: 'Fase 3 sequenza di processo per un aggiornamento ARL con `system controller replace` comandi per aggiornare i modelli di controller nello stesso chassis.' 
---
= Panoramica della fase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 3, colleghi il cluster condiviso-ha e le connessioni storage per gli shelf esterni, se presenti, avvii node1 con i moduli di sistema aggiornati, e verifica dell'installazione node1 aggiornata. Se si utilizza NetApp Volume Encryption (NVE), viene ripristinata la configurazione del gestore delle chiavi. È inoltre possibile spostare gli aggregati non root node1 e le LIF dei dati NAS da node2 al node1 aggiornato e verificare che le LIF SAN esistano sul node1.

.Fasi
. link:cable-node1-for-shared-cluster-HA-storage.html["Cavo node1 per storage ha-cluster condiviso (solo upgrade a AFF A800)"]
. link:boot_node1_with_a900_controller_and_nvs.html["Fare il boot node1 con i moduli di sistema sostitutivi"]
. link:verify_node1_installation.html["Verificare l'installazione di node1"]
. link:restore_key_manager_config_upgraded_node1.html["Ripristinare la configurazione del gestore delle chiavi sul nodo aggiornato 1"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html["Spostare gli aggregati non root e le LIF di dati NAS di proprietà del node1 dal node2 al node1 aggiornato"]

