---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_3_index.html 
keywords: upgrade, preparing, preparation, prepare, overview, stage 1 
summary: 'Fase 1 sequenza di processo per un aggiornamento ARL con `system controller replace` Comandi sui controller che eseguono ONTAP 9.8 o versioni successive.' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 3, si avvia node1 con controller e moduli NVRAM aggiornati e si verifica l'installazione node1 aggiornata. Se si utilizza NetApp Volume Encryption (NVE), viene ripristinata la configurazione del gestore delle chiavi. È inoltre possibile spostare gli aggregati non root node1 e le LIF dei dati NAS da node2 al node1 aggiornato e verificare che le LIF SAN esistano sul node1.

.Fasi
. link:boot_node1_with_a900_controller_and_nvs.html["Punto di avvio1 con il controller AFF A900 o FAS9500 e i moduli NVRAM"]
. link:verify_node1_installation.html["Verificare l'installazione di node1"]
. link:restore_key_manager_config_upgraded_node1.html["Ripristinare la configurazione del gestore delle chiavi sul nodo aggiornato 1"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html["Spostare gli aggregati non root e le LIF di dati NAS di proprietà del node1 dal node2 al node1 aggiornato"]

