---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: 'Prima di iniziare l"aggiornamento, verificare di disporre dell"hardware corretto per aggiornare i modelli di controller nello stesso chassis.' 
---
= Verificare l'hardware di aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di avviare l'aggiornamento, verificare di disporre dei moduli corretti per il sistema sostitutivo. In caso di componenti mancanti, contattare il supporto tecnico o il rappresentante commerciale NetApp per assistenza.

[cols="50,50"]
|===
| Se stai effettuando l'aggiornamento da ... | Il sistema di sostituzione deve avere ... 


| AFF A250, AFF C250  a| 
* Due moduli controller e nuovi moduli io
* Una scheda X60132A a 4 porte 10/25GbE per configurazioni di aggiornamento senza switch a due nodi




| AFF A800, AFF C800 | Due moduli controller, due NVRAM e nuovi moduli io 


 a| 
* AFF A220 configurato come ASA
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720

 a| 
Due moduli controller

Se stai convertendo il sistema esistente in uno shelf di archiviazione in modo da poterlo collegare a un altro sistema, il sistema sostitutivo deve avere anche due moduli io.



 a| 
* AFF A700 configurato come ASA
* AFF A700
* FAS9000

| Due controller e due moduli NVRAM 
|===