---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify-rcf-configuration.html 
keywords: aggregate, relocation, cluster, switch, rcf, shared 
summary: Verificare che lo switch RCF del cluster supporti le porte cluster/HA condivise per i nuovi controller per gli aggiornamenti dei cluster collegati allo switch. 
---
= Verificare la configurazione RCF sugli switch del cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questa fase della procedura di aggiornamento, tutti gli aggregati di dati dovrebbero trovarsi sul nodo 1.  Se si sta aggiornando una configurazione con cluster collegati allo switch, è necessario verificare che il file di configurazione di riferimento dello switch del cluster (RCF) supporti le porte cluster/HA condivise per i nuovi controller.

Se si sta eseguendo l'aggiornamento a una configurazione cluster switchless a due nodi, è possibile saltare questa sezione e passare alink:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Riportare al nodo gli aggregati non root e le LIF dei dati NAS 2"] .

.Fasi
. Passare alla modalità avanzata dei privilegi:
+
`set advanced`

. Controllare lo stato di "IC RDMA":
+
`ha interconnect status show`

+
Nell'output, la "Connessione IC RDMA" dovrebbe avere lo stato `Up` .

+
[cols="50,50"]
|===
| Se lo stato "IC RDMA Connection" è ... | Quindi… 


| `Up` | Vai alink:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Riportare al nodo gli aggregati non root e le LIF dei dati NAS 2"] . 


| `Down` | Vai a<<verify-rcf-step3,Fase 3>> . 
|===
. Controllare le porte del cluster e commutare RCF.
+
Per ulteriori informazioni, vedere link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Connettersi a un cluster collegato allo switch"].

. Verificare che lo stato "IC RDMA Connection" sia cambiato in `Up` :
+
`ha interconnect status show`



.Cosa c'è dopo?
link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["Riportare al nodo gli aggregati non root e le LIF dei dati NAS 2"]
