---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: 'Prima di iniziare l"aggiornamento, verificare di disporre dell"hardware corretto per aggiornare i modelli di controller nello stesso chassis.' 
---
= Verificare l'hardware di aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di iniziare l'aggiornamento, verificare di disporre dell'hardware corretto per l'aggiornamento. In base all'upgrade, per ogni coppia ha che stai aggiornando, devi avere due moduli controller o due moduli controller e due moduli NVRAM per il sistema sostitutivo. In caso di componenti mancanti, contattare il supporto tecnico o il rappresentante commerciale NetApp per assistenza.

[cols="50,50"]
|===
| Se si sta eseguendo l'aggiornamento... | Il sistema di sostituzione deve avere ... 


| AFF A800 | Due moduli controller, due NVRAM e nuovi moduli io 


| AFF A220 configurato come ASA per ASA A150 | Due moduli controller 


| Da AFF A220, AFF A200 o AFF C190 a AFF A150 | Due moduli controller 


| FAS2620 o da FAS2720 a FAS2820 | Due moduli controller 


| AFF A700 configurato come ASA per ASA A900 | Due controller e due moduli NVRAM 


| Da AFF A700 a AFF A900 | Due controller e due moduli NVRAM 


| Da FAS9000 a FAS9500 | Due controller e due moduli NVRAM 
|===