---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, NVRAM, controller, module, modules 
summary: 'Verificare l"installazione del nodo 1 con i moduli sostitutivi quando si utilizza ARL per aggiornare i modelli di controller nello stesso chassis.' 
---
= Verificare l'installazione di node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver avviato node1 con il modulo controller sostitutivo, verificare che sia installato correttamente.

Solo per gli upgrade di AFF A250, AFF C250, AFF A800 o AFF C800, eseguire la mappatura delle porte fisiche dal sistema node1 esistente al sistema node1 sostitutivo, in quanto le porte fisiche stanno cambiando tra i controller esistenti e quelli sostitutivi. Le porte fisiche non cambiano per gli altri sistemi supportati da questa procedura di aggiornamento.

.A proposito di questa attività
È necessario attendere che il nodo 1 si unisca al quorum, quindi riprendere l'operazione di sostituzione del controller.

A questo punto della procedura, l'operazione di aggiornamento del controller dovrebbe essere stata sospesa poiché node1 tenta di unirsi automaticamente al quorum.

.Fasi
. Verificare che node1 si sia Unito al quorum:
+
`cluster show -node node1 -fields health`

+
L'output di `health` il campo deve essere `true`.

. Questo passaggio si applica alle seguenti configurazioni di aggiornamento. Per tutti gli altri aggiornamenti di sistema, saltare questo passaggio e andare a <<verify-node1-step3,Fase 3>> :
+
** Cluster switchless a due nodi
** Passare dai sistemi AFF A250 o AFF C250 collegati a un sistema AFF A50, AFF A30, AFF C30 o AFF C60


+
--
Se node1 non si unisce automaticamente al quorum:

.. Controllare lo spazio IP delle porte e1a ed e1b:
+
`network port show`

.. Se lo spazio IP non è "Cluster", modifica lo spazio IP in "Cluster" su e1a ed e1b:
+
`network port modify -node <node_name> -port <port> -ipspace Cluster`

.. Verificare che lo spazio IP delle porte e1a ed e1b sia "Cluster":
+
`network port show`

.. Migrare i LIF del cluster node1 a e1a ed e1b:
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node1_name> -destination-port <port_name>`



--
. [[verify-node1-step3]]Verifica che node1 e node2 facciano parte dello stesso cluster e che il cluster sia integro:
+
`cluster show`

+
[NOTE]
====
Se node1 non è entrato a far parte del quorum dopo l'avvio, attendere cinque minuti e controllare di nuovo. A seconda della connessione al cluster, la scansione della raggiungibilità delle porte potrebbe richiedere del tempo e spostare le LIF nelle rispettive porte home.

Se node1 non è ancora al quorum dopo cinque minuti, modificare la porta del cluster del nuovo nodo collocandola in "Cluster ipspace" utilizzando il comando di privilegio diagnostico `network port modify <port_name> -ipspace Cluster`.

====
. Passare alla modalità avanzata dei privilegi:
+
`set advanced`

. Controllare lo stato dell'operazione di sostituzione del controller e verificare che sia in stato di pausa e nello stesso stato in cui si trovava prima dell'arresto del node1 per eseguire le attività fisiche di installazione di nuovi controller e cavi in movimento:
+
`system controller replace show`

+
`system controller replace show-details`

. Riprendere l'operazione di sostituzione del controller:
+
`system controller replace resume`

. L'operazione di sostituzione del controller viene interrotta per l'intervento con il seguente messaggio:
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: In questa procedura, la sezione _creazione di VLAN, ifgrps e domini di trasmissione_ è stata rinominata _Ripristino configurazione di rete su node1_.

. Con la sostituzione del controller in stato di pausa, passare a. <<Ripristinare la configurazione di rete sul nodo 1>>.




== Ripristinare la configurazione di rete sul nodo 1

Dopo aver confermato che node1 è in quorum e può comunicare con node2, verificare che le VLAN, i gruppi di interfacce e i domini di broadcast di node1 siano visibili sul node1. Inoltre, verificare che tutte le porte di rete node1 siano configurate nei domini di trasmissione corretti.

.A proposito di questa attività
Per ulteriori informazioni sulla creazione e la ricreazione di VLAN, gruppi di interfacce e domini di trasmissione, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi al contenuto di _Network Management_.

.Fasi
. Elencare tutte le porte fisiche sul nodo aggiorno1:
+
`network port show -node node1`

+
Vengono visualizzate tutte le porte di rete fisiche, le porte VLAN e le porte del gruppo di interfacce sul nodo. Da questo output, è possibile visualizzare le porte fisiche spostate in `Cluster` Dominio di broadcast di ONTAP. È possibile utilizzare questo output per agevolare la scelta delle porte da utilizzare come porte membro del gruppo di interfacce, porte di base VLAN o porte fisiche standalone per l'hosting di LIF.

. Elencare i domini di broadcast sul cluster:
+
`network port broadcast-domain show`

. Elencare la raggiungibilità delle porte di rete di tutte le porte sul nodo 1:
+
`network port reachability show -node node1`

+
L'output dovrebbe essere simile al seguente esempio:

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
Negli esempi precedenti, node1 si è avviato dopo la sostituzione del controller. Le porte che visualizzano la "non raggiungibilità" non hanno connettività fisica. È necessario riparare tutte le porte con uno stato di raggiungibilità diverso da `ok`.

+

NOTE: Durante l'aggiornamento, le porte di rete e la relativa connettività non devono cambiare. Tutte le porte devono risiedere nei domini di trasmissione corretti e la raggiungibilità delle porte di rete non deve cambiare. Tuttavia, prima di spostare i file LIF da node2 a node1, è necessario verificare la raggiungibilità e lo stato di salute delle porte di rete.

. [[restore_node1_step4]]riparare la raggiungibilità per ciascuna porta sul node1 con uno stato di raggiungibilità diverso da `ok` utilizzando il seguente comando, nel seguente ordine:
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. Porte fisiche
.. Porte VLAN


--
+
L'output dovrebbe essere simile al seguente esempio:

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e1b
----
+
[listing]
----
Warning: Repairing port "node1:e1b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
Un messaggio di avviso, come mostrato nell'esempio precedente, è previsto per le porte con uno stato di raggiungibilità che potrebbe essere diverso dallo stato di raggiungibilità del dominio di broadcast in cui si trova attualmente. Esaminare la connettività della porta e rispondere `y` oppure `n` a seconda dei casi.

+
Verificare che tutte le porte fisiche abbiano la raggiungibilità prevista:

+
`network port reachability show`

+
Quando viene eseguita la riparazione della raggiungibilità, ONTAP tenta di posizionare le porte nei domini di trasmissione corretti. Tuttavia, se non è possibile determinare la raggiungibilità di una porta e non appartiene a nessuno dei domini di broadcast esistenti, ONTAP creerà nuovi domini di broadcast per queste porte.

. Verificare la raggiungibilità delle porte:
+
`network port reachability show`

+
Quando tutte le porte sono configurate correttamente e aggiunte ai domini di trasmissione corretti, il `network port reachability show` il comando deve riportare lo stato di raggiungibilità come `ok` per tutte le porte connesse e lo stato come `no-reachability` per porte senza connettività fisica. Se una delle porte riporta uno stato diverso da questi due, eseguire la riparazione della raggiungibilità e aggiungere o rimuovere le porte dai propri domini di trasmissione come indicato nella <<restore_node1_step4,Fase 4>>.

. Verificare che tutte le porte siano state inserite nei domini di broadcast:
+
`network port show`

. Verificare che tutte le porte nei domini di trasmissione abbiano configurato la MTU (Maximum Transmission Unit) corretta:
+
`network port broadcast-domain show`

. Ripristinare le porte LIF home, specificando le porte Vserver e LIF home, se presenti, che devono essere ripristinate seguendo questa procedura:
+
.. Elencare eventuali LIF spostati:
+
`displaced-interface show`

.. Ripristinare i nodi home LIF e le porte home:
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. Verificare che tutte le LIF dispongano di una porta home e siano amministrativamente up:
+
`network interface show -fields home-port,status-admin`


