---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: Decidere se utilizzare la procedura ARL manuale per aggiornare i controller di storage in una coppia HA con nuovi controller che eseguono ONTAP 9.8 o versione successiva. 
---
= Decidere se utilizzare questa procedura di ricollocazione aggregata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa procedura descrive come aggiornare l'hardware del controller utilizzando la rilocazione manuale degli aggregati (ARL) su sistemi che eseguono ONTAP 9.8 o versioni successive. Questa complessa procedura dovrebbe essere utilizzata solo da amministratori ONTAP esperti.

Utilizzare questo contenuto nelle seguenti circostanze:

* Non vuoi aggiungere i nuovi controller come nuova coppia ha al cluster e migrare i dati utilizzando gli spostamenti dei volumi.
* Si è esperti nell'amministrazione di ONTAP e si è a proprio agio con i rischi di lavorare in modalità diagnostica con privilegi.
* I controller eseguono ONTAP 9.8 o versione successiva.
* Si dispone di un sistema che utilizza le configurazioni Fabric MetroCluster a 4 e 8 nodi con ONTAP 9.8 o versione successiva.
* Nel sistema sono presenti aggregati ibridi.


[NOTE]
====
* Se si sta aggiornando un sistema sostituendo i moduli controller nello stesso chassis, come AFF A800 o AFF C800, NetApp consiglia vivamente di utilizzare la procedura di aggiornamento che link:../upgrade-arl-auto-in-chassis/index.html["aggiorna i modelli di controller utilizzando ARL, mantenendo lo chassis di sistema esistente, i dischi e i dati"]. Questa procedura ARL include i passaggi che garantiscono che i dischi interni rimangano saldamente nello chassis quando si rimuovono e si installano i controller durante la procedura di aggiornamento.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Scopri le combinazioni di aggiornamento del sistema supportate utilizzando ARL, mantenendo lo chassis, i dischi e i dati del sistema esistenti"].

* Con questa procedura è possibile utilizzare NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) e NetApp aggregate Encryption (NAE).


====
Se preferisci un metodo diverso per aggiornare l'hardware del controller e sei disposto a spostare i volumi, fai riferimento a link:other-references.html["Riferimenti"]_Aggiornamento tramite spostamento di volumi o storage_.

Consulta link:other-references.html["Riferimenti"] per collegarti al _ONTAP 9 Documentation Center_ dove puoi accedere alla documentazione del prodotto ONTAP 9.



[[choose-a-different-hardware-upgrade-procedure]]
== Scegli una procedura di aggiornamento hardware diversa

* link:../upgrade-arl/index.html["Esaminare i metodi ARL alternativi disponibili per l'aggiornamento dell'hardware del controller"].
* Se preferisci un metodo diverso per aggiornare l'hardware del controller e sei disposto a spostare i volumi, fai riferimento a link:other-references.html["Riferimenti"]_Aggiornamento tramite spostamento di volumi o storage_.


.Informazioni correlate
Consultare link:other-references.html["Riferimenti"] per collegarsi alla _ONTAP 9 Documentation_.

.Quali sono le prossime novità?
Dopo aver deciso se utilizzare questa procedura ARL, link:arl_upgrade_workflow.html["esaminare il flusso di lavoro di aggiornamento ARL"].
