---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade 
summary: Capire se è possibile utilizzare la procedura di aggiornamento ARL manuale per una coppia di controller che eseguono ONTAP 9.8 o versioni successive. 
---
= Linee guida per l'aggiornamento dei controller con ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per capire se è possibile utilizzare il trasferimento aggregato (ARL) per aggiornare una coppia di controller che eseguono ONTAP 9.8, dipende dalla piattaforma e dalla configurazione dei controller originali e di quelli sostitutivi.



== Aggiornamenti supportati per ARL

È possibile aggiornare una coppia di nodi utilizzando ARL nei seguenti casi:

* Prima dell'aggiornamento, sia i controller originali che quelli sostitutivi devono eseguire la stessa versione di ONTAP 9.8.
* I controller sostitutivi devono avere una capacità uguale o superiore a quella dei controller originali. Capacità uguale o superiore si riferisce agli attributi, ad esempio le dimensioni della NVRAM, il volume, il LUN o i limiti del numero di aggregati; si riferisce anche alle dimensioni massime del volume o dell'aggregato dei nuovi nodi.
* È possibile aggiornare i seguenti tipi di sistemi:
+
** Da un sistema FAS a un sistema FAS.
** Da un sistema FAS a un sistema con software di virtualizzazione FlexArray o un sistema V-Series.
** Da un sistema AFF a un sistema AFF.
** Un sistema con software di virtualizzazione FlexArray o un sistema V-Series su un sistema FAS, a condizione che il sistema con software di virtualizzazione FlexArray o il sistema V-Series non disponga di LUN array.
** Da un sistema V-Series a un sistema con software di virtualizzazione FlexArray o un sistema V-Series.


* Per alcuni aggiornamenti del controller ARL è possibile utilizzare porte cluster temporanee sul controller sostitutivo per l'aggiornamento. Ad esempio, se si esegue l'aggiornamento da un sistema AFF A300 a un sistema AFF A400, a seconda della configurazione di AFF A400, è possibile utilizzare una delle due porte mezzanine o aggiungere una scheda di interfaccia di rete 10GbE a quattro porte per fornire porte cluster temporanee. Dopo aver completato un aggiornamento del controller utilizzando porte del cluster temporanee, è possibile migrare senza interruzioni i cluster alle porte 100 GbE del controller sostitutivo.
* L'upgrade del controller tramite ARL è supportato sui sistemi configurati con volumi di conformità SnapLock Enterprise e SnapLock.


È necessario verificare se l'ARL può essere eseguito sui controller originali e sostitutivi. È necessario controllare le dimensioni di tutti gli aggregati definiti e il numero di dischi supportati dal sistema originale. Quindi confrontarli con la dimensione aggregata e il numero di dischi supportati dal nuovo sistema. Per accedere a queste informazioni, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_. La dimensione aggregata e il numero di dischi supportati dal nuovo sistema devono essere uguali o superiori alla dimensione aggregata e al numero di dischi supportati dal sistema originale.

È necessario verificare nelle regole di combinazione del cluster se i nuovi nodi possono diventare parte del cluster con i nodi esistenti quando il controller originale viene sostituito. Per ulteriori informazioni sulle regole di combinazione dei cluster, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_.


NOTE: Entrambi i sistemi sono ad alta disponibilità (ha) o non ha. Entrambi i nodi devono avere la personalità abilitata o disabilitata; non è possibile combinare un nodo con la personalità ottimizzata per All Flash abilitata con un nodo che non ha la personalità abilitata nella stessa coppia ha. Se le personalità sono diverse, contattare il supporto tecnico.


NOTE: Se il nuovo sistema dispone di meno slot rispetto al sistema originale o se dispone di un numero inferiore o di porte diverse, potrebbe essere necessario aggiungere un adattatore al nuovo sistema. Fare riferimento a. link:other_references.html["Riferimenti"] Per informazioni dettagliate su piattaforme specifiche, consultare il sito Web del supporto NetApp _Hardware Universe_.

Se si dispone di un sistema con più di due porte cluster per nodo, ad esempio un sistema FAS8080 o AFF8080, prima di avviare l'aggiornamento, è necessario migrare e riassegnare le LIF del cluster a due porte cluster per nodo. Se si esegue l'aggiornamento del controller con più di due porte cluster per nodo, le LIF del cluster potrebbero non essere presenti sul nuovo controller dopo l'aggiornamento.



== Aggiornamenti non supportati per ARL

Non è possibile eseguire i seguenti aggiornamenti:

* Da o verso i controller che non possono eseguire ONTAP 9.8 o versioni successive.
* Ai controller sostitutivi che non supportano gli shelf di dischi collegati ai controller originali.
+
Per informazioni sul supporto dei dischi, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Hardware Universe_.

* Da controller con aggregati root o aggregati di dati su dischi interni.
+
Se si desidera aggiornare i controller con aggregati root o aggregati di dati su dischi interni, fare riferimento a. link:other_references.html["Riferimenti"] Per collegarsi a _Upgrade spostando volumi o storage_ e passare alla procedura _aggiornamento di una coppia di nodi che eseguono Clustered Data ONTAP spostando volumi_.

+

NOTE: Se si desidera aggiornare ONTAP sui nodi di un cluster, fare riferimento a. link:other_references.html["Riferimenti"] Collegamento a _Upgrade ONTAP_.





== Presupposti e terminologia

Il presente documento si basa sui seguenti presupposti:

* L'hardware del controller sostitutivo è nuovo e non è stato utilizzato.
+

WARNING: *Attenzione*: Poiché questa procedura presuppone che l'hardware del controller sostitutivo sia nuovo e non sia stato utilizzato, le fasi necessarie per preparare i controller usati con `wipeconfig` i comandi non sono inclusi in questa procedura. Se in precedenza è stato utilizzato l'hardware del controller sostitutivo, è necessario contattare il supporto tecnico, in particolare se i controller eseguivano Data ONTAP in 7-Mode.

* Hai letto e compreso le linee guida per l'aggiornamento della coppia di nodi.
+

WARNING: *Attenzione*: Non tentare di cancellare il contenuto della NVRAM. Se è necessario eliminare il contenuto della NVRAM, contattare il supporto tecnico di NetApp.

* Si sta eseguendo il comando appropriato prima e dopo `modify` e confrontando l'output di entrambi `show` comandi per verificare che il `modify` comando riuscito.
* Se si dispone di una configurazione SAN, si dispone di LIF locali e partner per ciascuna macchina virtuale di storage (SVM), sulla coppia ha. Se non si dispone di LIF locali e partner per ogni SVM, è necessario aggiungere LA LIF dei dati SAN sul nodo remoto e locale per tale SVM prima di iniziare l'aggiornamento.
* Se si dispone di set di porte in una configurazione SAN, è necessario verificare che ogni set di porte associato contenga almeno un LIF da ciascun nodo della coppia ha.


Questa procedura utilizza il termine _prompt dell'ambiente di boot_ per fare riferimento al prompt di un nodo da cui è possibile eseguire determinate attività, come il riavvio del nodo e la stampa o l'impostazione di variabili ambientali. Il prompt viene a volte chiamato in modo informale _prompt del boot loader_.

Il prompt dell'ambiente di boot viene mostrato nell'esempio seguente:

[listing]
----
LOADER>
----


== Licensing in ONTAP 9.8 o versioni successive

Alcune funzionalità richiedono licenze, emesse come _pacchetti_ che includono una o più funzionalità. Ogni nodo del cluster deve disporre di una propria chiave per poter utilizzare ciascuna funzionalità nel cluster.

Se non si dispone di nuove chiavi di licenza, le funzionalità attualmente concesse in licenza nel cluster sono disponibili per il nuovo controller e continueranno a funzionare. Tuttavia, l'utilizzo di funzionalità senza licenza sul controller potrebbe non essere conforme al contratto di licenza, pertanto è necessario installare la nuova chiave di licenza o le nuove chiavi per il nuovo controller al termine dell'aggiornamento.

Tutte le chiavi di licenza sono composte da 28 caratteri alfabetici maiuscoli. Fare riferimento a. link:other_references.html["Riferimenti"] Per accedere al _sito di supporto NetApp_, dove è possibile ottenere nuove chiavi di licenza di 28 caratteri per ONTAP 9.8. o versioni successive. Le chiavi sono disponibili nella sezione _My Support_ sotto _licenze software_. Se il sito non dispone delle chiavi di licenza necessarie, contattare il rappresentante commerciale NetApp.

Per informazioni dettagliate sulle licenze, visitare il sito Web all'indirizzo link:other_references.html["Riferimenti"] Per collegarsi al _System Administration Reference_.



== Crittografia dello storage

I nodi originali o i nuovi nodi potrebbero essere abilitati per Storage Encryption. In tal caso, è necessario eseguire ulteriori operazioni in questa procedura per verificare che Storage Encryption sia impostato correttamente.

Se si desidera utilizzare Storage Encryption, tutti i dischi associati ai nodi devono disporre di dischi con crittografia automatica.



== Cluster senza switch a due nodi

Se si stanno aggiornando i nodi in un cluster senza switch a due nodi, è possibile lasciare i nodi nel cluster senza switch durante l'aggiornamento. Non è necessario convertirli in un cluster con switch



== Risolvere i problemi

Si potrebbe riscontrare un errore durante l'aggiornamento della coppia di nodi. Il nodo potrebbe bloccarsi, gli aggregati potrebbero non spostarsi o i LIF potrebbero non migrare. La causa dell'errore e la relativa soluzione dipendono dal momento in cui si è verificato l'errore durante la procedura di aggiornamento.

Se si verificano problemi durante l'aggiornamento dei controller, fare riferimento a link:aggregate_relocation_failures.html["Risolvere i problemi"] sezione. Le informazioni sui guasti che possono verificarsi sono elencate in base alla fase della procedura nella link:arl_upgrade_workflow.html["Sequenza di aggiornamento ARL"] .

Se non si riesce a trovare una soluzione al problema riscontrato, contattare il supporto tecnico.
