---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: Se necessario, configurare il nuovo modulo controller per NVE o NAE durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.8 o versioni successive. 
---
= Configurare NetApp Volume o Aggregte Encryption sul nuovo modulo controller
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se il controller sostituito o il partner ad alta disponibilità (ha) del nuovo controller utilizza NetApp Volume Encryption (NVE) o NetApp aggregate Encryption (NAE), è necessario configurare il nuovo modulo controller per NVE o NAE.

.A proposito di questa attività
Questa procedura include i passaggi che vengono eseguiti sul nuovo modulo controller. Immettere il comando sul nodo corretto.

.Fasi
. Verificare che i server di gestione delle chiavi siano ancora disponibili, che il loro stato e le relative informazioni sulla chiave di autenticazione:
+
`security key-manager key query -node node`

. Aggiungere i server di gestione delle chiavi elencati nel passaggio precedente all'elenco dei server di gestione delle chiavi nel nuovo controller:
+
.. Aggiungere il server di gestione delle chiavi utilizzando il seguente comando:
+
`security key-manager -add _key_management_server_ip_address_`

.. Ripetere il passaggio precedente per ciascun server di gestione delle chiavi elencato. È possibile collegare fino a quattro server di gestione delle chiavi.
.. Verificare che i server di gestione delle chiavi siano stati aggiunti correttamente utilizzando il seguente comando:
+
`security key-manager show`



. Sul nuovo modulo controller, eseguire la configurazione guidata della gestione delle chiavi per configurare e installare i server di gestione delle chiavi.
+
È necessario installare gli stessi server di gestione delle chiavi installati sul modulo controller esistente.

+
.. Avviare la configurazione guidata del server di gestione delle chiavi sul nuovo nodo utilizzando il seguente comando:
+
`security key-manager setup -node _new_controller_name_`

.. Completare la procedura guidata per configurare i server di gestione delle chiavi.


. Ripristinare le chiavi di autenticazione da tutti i server di gestione delle chiavi collegati al nuovo nodo:
+
[cols="35,65"]
|===
| Per... | Utilizzare questo comando... 


| Gestore delle chiavi esterno | `security key-manager external restore`Questo comando richiede la passphrase OKM 


| Onboard Key Manager (OKM) | `security key-manager onboard sync` 
|===
+
Per ulteriori informazioni, consultare l'articolo della Knowledge base https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["Come ripristinare la configurazione del server di gestione delle chiavi esterne dal menu di avvio di ONTAP"^].



.Al termine
Controllare se i volumi sono stati portati offline perché le chiavi di autenticazione non erano disponibili o non è stato possibile raggiungere i server di gestione delle chiavi esterne. Riportare online quei volumi utilizzando  `volume online` comando.
