---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: Configurare node4 porte FC integrate, porte UTA/UTA2 o scheda UTA/UTA2 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.8 o versioni successive. 
---
= Impostare la configurazione FC o UTA/UTA2 su node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se node4 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare<<Configurare le porte FC sul nodo 4>> O<<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> o entrambe le sezioni.

Se node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 (ad esempio, sistemi AFF e FAS introdotti a partire da ONTAP 9.15.1) e si sta aggiornando un sistema con dischi di archiviazione, è possibile passare alink:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] .



== Configurare le porte FC sul nodo 4

Se node4 dispone di porte FC, integrate o su un adattatore FC, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, perché le porte non sono preconfigurate. Se le porte non sono configurate, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di un adattatore UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Immettere i comandi in questa sezione al prompt del cluster.

.Fasi
. Visualizza informazioni su tutti gli adattatori di rete FC e convergenti sul sistema:
+
`system node hardware unified-connect show`

. Confrontare le impostazioni FC sui nuovi nodi con quelle acquisite in precedenza dal nodo originale.
. Modificare le porte FC sul nodo 4 in base alle necessità:
+
** Per programmare le porte di destinazione:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Per programmare le porte initiator:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` È il tipo, la destinazione o l'iniziatore FC4.



. Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
+
`system node unified-connect show`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se le impostazioni FC predefinite sui nuovi nodi sono... | Quindi… 


| Le stesse di quelle acquisite sui nodi originali | Vai a<<man_config_4_Step9,Fase 9>> . 


| Diverso da quelli acquisiti sui nodi originali | Vai a<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Esci dalla modalità di manutenzione:
+
`halt`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Avviare node4 immettendo il seguente comando al prompt dell'ambiente di avvio:
+
`boot_ontap`

. [[man_config_4_Step9]]Esegui una delle seguenti azioni:
+
** Passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> Se node4 ha una scheda UTA/UTA2A o porte UTA/UTA2 integrate.
** Saltare la sezione e passare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] Se node4 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate.






== Controllare e configurare le porte UTA/UTA2 sul nodo 4

Se node4 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2A, è necessario controllare la configurazione delle porte e configurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2A. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente al traffico simultaneo di NIC e FCoE di condividere la stessa interfaccia SFP+ 10 GbE e supporta la destinazione FC.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Le porte UTA/UTA2 potrebbero essere su un adattatore o sul controller con le seguenti configurazioni:

* Le schede UTA/UTA2 ordinate contemporaneamente al controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller sono configurate (prima della spedizione) in modo da avere la personalità richiesta.


Tuttavia, è possibile controllare la configurazione delle porte UTA/UTA2 sul nodo 4 e modificarla, se necessario.


WARNING: Immettere i comandi in questa sezione al prompt del cluster, a meno che non venga richiesto di entrare in modalità Manutenzione.  Se si dispone di un sistema MetroCluster FC, è necessario essere in modalità di manutenzione per configurare le porte UTA/UTA2.

.Fasi
. Controlla come sono attualmente configurate le porte sul nodo 4:
+
`system node hardware unified-connect show`

. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Esaminare l'output di `system node hardware unified-connect show` oppure `ucadmin show` Controllare e determinare se le porte UTA/UTA2 hanno la personalità desiderata.
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se la porta CNA... | Quindi... 


| Non avere la personalità che si desidera | Passare a. <<man_check_4_Step5,Fase 5>>. 


| Avere la personalità che si desidera | Saltare i passaggi da 5 a 12 e passare a. <<man_check_4_Step13,Fase 13>>. 
|===
. [[man_check_4_Step5]]Se il sistema dispone di dischi di archiviazione ed esegue Data ONTAP 8.3, avviare node4 ed entrare in modalità di manutenzione:
+
`boot_ontap maint`

. Verificare le impostazioni immettendo il seguente comando ed esaminandone l'output:
+
`ucadmin show`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se si sta configurando... | Quindi... 


| Porte su una scheda UTA/UTA2A | Vai a<<man_check_4_Step8,Fase 8>> . 


| Porte UTA/UTA2 integrate | Salta il passaggio 8 e vai a<<man_check_4_Step9,Fase 9>> . 
|===
. [[man_check_4_Step8]]Se l'adattatore è in modalità iniziatore e la porta UTA/UTA2 è online, metti offline la porta UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[man_check_4_Step9]]Se la configurazione corrente non corrisponde all'uso desiderato, immettere il seguente comando per modificare la configurazione in base alle esigenze:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` È la modalità Personality: FC o 10GbE UTA.
** `-t` È il tipo FC4: Destinazione o iniziatore.


+

NOTE: È necessario utilizzare l'iniziatore FC per le unità nastro e la destinazione FC per i client SAN.

. Se il sistema dispone di dischi di archiviazione, immettere il seguente comando:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

+
.. Immettere il seguente comando:
+
`boot_ontap`



. Se il sistema dispone di dischi di archiviazione, immettere il seguente comando:
+
`system node hardware unified-connect show`

+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. Inserire le porte di destinazione in linea immettendo uno dei seguenti comandi, una volta per ciascuna porta:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[MAN_check_4_STEP13]]collegare la porta via cavo.

