---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: Configurare node4 porte FC integrate, porte UTA/UTA2 o scheda UTA/UTA2 durante un aggiornamento ARL manuale sui controller che eseguono ONTAP 9.8 o versioni successive. 
---
= Impostare la configurazione FC o UTA/UTA2 su node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se node4 dispone di porte FC integrate, porte UTA/UTA2 (onboard Unified target adapter) o una scheda UTA/UTA2, è necessario configurare le impostazioni prima di completare il resto della procedura.

.A proposito di questa attività
Potrebbe essere necessario completare l'operazione <<Configurare le porte FC sul nodo 4>>, il <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>, o entrambe le sezioni.

Se node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2 e si sta eseguendo l'aggiornamento di un sistema con dischi di storage, è possibile passare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"].

Tuttavia, se si dispone di un sistema V-Series o di un software di virtualizzazione FlexArray e si è connessi agli array di storage e node4 non dispone di porte FC integrate, porte UTA/UTA2 integrate o una scheda UTA/UTA2, tornare alla sezione _Installazione e boot node4_ e riprendere a link:install_boot_node4.html#man_install4_Step9["Fase 9"]. Assicurarsi che il node4 disponga di spazio rack sufficiente. Se il nodo 4 si trova in uno chassis separato dal nodo 2, è possibile inserire il nodo 4 nella stessa posizione del nodo 3. Se node2 e node4 si trovano nello stesso chassis, node4 si trova già nella posizione rack appropriata.

.Scelte
* <<Configurare le porte FC sul nodo 4>>
* <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>




== Configurare le porte FC sul nodo 4

Se node4 dispone di porte FC, integrate o su un adattatore FC, è necessario impostare le configurazioni delle porte sul nodo prima di metterlo in servizio, perché le porte non sono preconfigurate. Se le porte non sono configurate, si potrebbe verificare un'interruzione del servizio.

.Prima di iniziare
È necessario disporre dei valori delle impostazioni della porta FC del nodo 2 salvati nella sezione link:prepare_nodes_for_upgrade.html["Preparare i nodi per l'aggiornamento"].

.A proposito di questa attività
È possibile saltare questa sezione se il sistema non dispone di configurazioni FC. Se il sistema dispone di porte UTA/UTA2 integrate o di un adattatore UTA/UTA2, configurarle in <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>>.


IMPORTANT: Se il sistema dispone di dischi di storage, è necessario immettere i comandi in questa sezione al prompt del cluster. Se si dispone di un sistema V-Series o di un sistema con software di virtualizzazione FlexArray collegato agli array di storage, immettere i comandi in questa sezione in modalità manutenzione.

.Fasi
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage | Passare a. <<man_config_4_Step5,Fase 5>>. 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Passare a. <<man_config_4_Step2,Fase 2>>. 
|===
. [[MAN_config_4_Step2]]accesso alla modalità di manutenzione:
+
`boot_ontap maint`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage | `system node hardware unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `ucadmin show` 
|===
+
Il sistema visualizza informazioni su tutti gli adattatori di rete FC e convergenti del sistema.

. Confrontare le impostazioni FC sui nuovi nodi con quelle acquisite in precedenza dal nodo originale.
. [[man_config_4_Step5]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage  a| 
Modificare le porte FC sul nodo 4 in base alle necessità:

** Per programmare le porte di destinazione:


`system node hardware unified-connect modify -type | -t target -adapter _port_name_`

** Per programmare le porte initiator:


`system node unified-connect modify type | -t initiator -adapter _port_name_`

`-type` È il tipo, la destinazione o l'iniziatore FC4.



| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage  a| 
Modificare le porte FC sul nodo 4 in base alle necessità:

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` È il tipo, la destinazione o l'iniziatore FC4.


NOTE: Le porte FC devono essere programmate come iniziatori.

|===
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage | Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
`system node unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Verificare le nuove impostazioni immettendo il seguente comando ed esaminando l'output:
`ucadmin show` 
|===
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se le impostazioni FC predefinite sui nuovi nodi sono... | Quindi… 


| Le stesse di quelle acquisite sui nodi originali | Passare a. <<man_config_4_Step11,Fase 11>>. 


| Diverso da quelli acquisiti sui nodi originali | Passare a. <<man_config_4_Step8,Punto 8>>. 
|===
. [[MAN_config_4_Step8]]Esci dalla modalità di manutenzione:
+
`halt`

. Dopo aver immesso il comando, attendere che il sistema si arresti al prompt dell'ambiente di avvio.
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| È un sistema V-Series o dispone di un software di virtualizzazione FlexArray con Data ONTAP 8.3.0 o versione successiva | Accedere alla modalità di manutenzione immettendo il seguente comando al prompt dell'ambiente di avvio:
`boot_ontap maint` 


| Non è un sistema V-Series e non dispone del software di virtualizzazione FlexArray | Fare il boot node4 immettendo il seguente comando al prompt dell'ambiente di boot:
`boot_ontap` 
|===
. [[man_config_4_step11]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema che si sta aggiornando... | Quindi… 


| Dispone di dischi di storage  a| 
** Passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> Se node4 ha una scheda UTA/UTA2A o porte UTA/UTA2 integrate.
** Saltare la sezione e passare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"] Se node4 non dispone di una scheda UTA/UTA2 o di porte UTA/UTA2 integrate.




| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage  a| 
** Passare a. <<Controllare e configurare le porte UTA/UTA2 sul nodo 4>> Se node4 ha una scheda UTA/UTA2 o porte UTA/UTA2 integrate.
** Saltare la sezione _controllare e configurare le porte UTA/UTA2 su node4_ se node4 non dispone di una scheda UTA/UTA2 o di porte integrate UTA/UTA2, tornare alla sezione _Installazione e boot node4_ e riprendere la sezione su link:install_boot_node4.html#man_install4_Step9["Fase 9"].


|===




== Controllare e configurare le porte UTA/UTA2 sul nodo 4

Se node4 dispone di porte UTA/UTA2 integrate o di una scheda UTA/UTA2A, è necessario controllare la configurazione delle porte e configurarle, a seconda di come si desidera utilizzare il sistema aggiornato.

.Prima di iniziare
È necessario disporre dei moduli SFP+ corretti per le porte UTA/UTA2.

.A proposito di questa attività
Le porte UTA/UTA2 possono essere configurate in modalità FC nativa o UTA/UTA2A. La modalità FC supporta l'iniziatore FC e la destinazione FC; la modalità UTA/UTA2 consente al traffico simultaneo di NIC e FCoE di condividere la stessa interfaccia SFP+ 10 GbE e supporta la destinazione FC.


NOTE: I materiali di marketing NetApp potrebbero utilizzare il termine UTA2 per fare riferimento agli adattatori e alle porte CNA. Tuttavia, la CLI utilizza il termine CNA.

Le porte UTA/UTA2 potrebbero essere su un adattatore o sul controller con le seguenti configurazioni:

* Le schede UTA/UTA2 ordinate contemporaneamente al controller vengono configurate prima della spedizione in modo da avere la personalità richiesta.
* Le schede UTA/UTA2 ordinate separatamente dal controller vengono fornite con il linguaggio di destinazione FC predefinito.
* Le porte UTA/UTA2 integrate sui nuovi controller sono configurate (prima della spedizione) in modo da avere la personalità richiesta.


Tuttavia, è possibile controllare la configurazione delle porte UTA/UTA2 sul nodo 4 e modificarla, se necessario.

*Attenzione*: Se il sistema dispone di dischi di storage, immettere i comandi in questa sezione al prompt del cluster, a meno che non venga richiesto di accedere alla modalità di manutenzione. Se si dispone di un sistema MetroCluster FC, V-Series o un sistema con software di virtualizzazione FlexArray collegato agli array di storage, è necessario essere in modalità di manutenzione per configurare le porte UTA/UTA2.

.Fasi
. Verificare la configurazione delle porte utilizzando uno dei seguenti comandi sul nodo 4:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi… 


| Dispone di dischi di storage | `system node hardware unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `ucadmin show` 
|===
+
Il sistema visualizza un output simile al seguente esempio:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Se il modulo SFP+ corrente non corrisponde all'utilizzo desiderato, sostituirlo con il modulo SFP+ corretto.
+
Contattare il rappresentante NetApp per ottenere il modulo SFP+ corretto.

. Esaminare l'output di `system node hardware unified-connect show` oppure `ucadmin show` Controllare e determinare se le porte UTA/UTA2 hanno la personalità desiderata.
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se la porta CNA... | Quindi... 


| Non avere la personalità che si desidera | Passare a. <<man_check_4_Step5,Fase 5>>. 


| Avere la personalità che si desidera | Saltare i passaggi da 5 a 12 e passare a. <<man_check_4_Step13,Fase 13>>. 
|===
. [[MAN_check_4_Step5]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage e utilizza Data ONTAP 8.3 | Fare il boot node4 e accedere alla modalità di manutenzione:
`boot_ontap maint` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Passare a. <<man_check_4_Step6,Fase 6>>. La modalità di manutenzione dovrebbe essere già attiva. 
|===
. [[MAN_check_4_Step6]]eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se si sta configurando... | Quindi... 


| Porte su una scheda UTA/UTA2A | Passare a. <<man_check_4_Step7,Fase 7>>. 


| Porte UTA/UTA2 integrate | Saltare la fase 7 e passare a. <<man_check_4_Step8,Fase 8>>. 
|===
. [[MAN_check_4_Step7]]se la scheda di rete è in modalità Initiator e la porta UTA/UTA2 è in linea, portare la porta UTA/UTA2 offline:
+
`storage disable adapter _adapter_name_`

+
Gli adattatori in modalità di destinazione sono automaticamente offline in modalità di manutenzione.

. [[MAN_check_4_Step8]]se la configurazione corrente non corrisponde all'utilizzo desiderato, immettere il seguente comando per modificare la configurazione in base alle necessità:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` È la modalità Personality: FC o 10GbE UTA.
** `-t` È il tipo FC4: Destinazione o iniziatore.


+

NOTE: È necessario utilizzare FC Initiator per le unità nastro e i sistemi di virtualizzazione FlexArray. È necessario utilizzare la destinazione FC per i client SAN.

. Verificare le impostazioni immettendo il seguente comando ed esaminandone l'output:
+
`ucadmin show`

. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage  a| 
.. Immettere il seguente comando:
+
`halt`

+
Il sistema si arresta al prompt dell'ambiente di avvio.

.. Immettere il seguente comando:
+
`boot_ontap`





| È un sistema V-Series o dispone di software di virtualizzazione FlexArray, è collegato agli array di storage e utilizza Data ONTAP 8.3 | Riavvio in modalità di manutenzione:
`boot_ontap maint` 
|===
. Verificare le impostazioni:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage | Immettere il seguente comando:
`system node hardware unified-connect show` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Immettere il seguente comando:
`ucadmin show` 
|===
+
L'output degli esempi seguenti mostra che il tipo di adattatore FC4 "1b" sta cambiando in `initiator` e che la modalità degli adattatori "2a" e "2b" stia cambiando in `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. Inserire le porte di destinazione in linea immettendo uno dei seguenti comandi, una volta per ciascuna porta:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | `fcp config _adapter_name_ up` 
|===
. [[MAN_check_4_STEP13]]collegare la porta via cavo.
. Eseguire una delle seguenti operazioni:
+
[cols="35,65"]
|===
| Se il sistema... | Quindi... 


| Dispone di dischi di storage | Passare a. link:map_ports_node2_node4.html["Mappare le porte dal nodo 2 al nodo 4"]. 


| È un sistema V-Series o dispone di software di virtualizzazione FlexArray ed è collegato agli array di storage | Tornare alla sezione _Installazione e boot node4_ e riprendere la sezione all'indirizzo link:install_boot_node4.html#man_install4_Step9["Fase 9"]. 
|===

