---
sidebar: sidebar 
permalink: upgrade-arl/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: 'Utilizzare il trasferimento di aggregati per aggiornare l"hardware del controller' 
---
= Inizia da qui: Scegli la tua procedura di aggiornamento ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puoi aggiornare l'hardware dei controller senza interruzioni utilizzando il trasferimento degli aggregati (ARL). Per altri metodi per aggiornare l'hardware del controller, vedere link:../upgrade/upgrade-decide-to-use-this-guide.html["Eseguire l'upgrade spostando volumi o storage"].

Con ARL, potrai eseguire l'upgrade dell'hardware del controller senza interruzioni su una coppia di nodi con ONTAP e migrando gli aggregati non root dai nodi originali ai nuovi nodi dello stesso cluster. I dati ospitati sui nodi che vengono aggiornati sono accessibili durante l'aggiornamento.

ARL sfrutta la configurazione ha per consentirti di spostare la proprietà degli aggregati non root da un nodo a un altro, se condividono lo storage all'interno dello stesso cluster.

Esistono diversi metodi ARL per aggiornare l'hardware del controller. Per selezionare la procedura appropriata, consultare le seguenti informazioni sui sistemi e sulle versioni ONTAP supportate per ciascuna opzione di aggiornamento ARL.



== Utilizzare i comandi "sostituzione controller di sistema" con ONTAP 9.15,1 o versione successiva

Se lo scenario di aggiornamento è elencato nella seguente tabella dei sistemi supportati, andare a link:../upgrade-arl-auto-app-9151/index.html["Utilizzare i comandi "sostituzione controller di sistema" per aggiornare l'hardware del controller introdotto in ONTAP 9.15.1 e versioni successive"] per avviare la procedura di aggiornamento.

.Mostra i sistemi supportati
[%collapsible]
====
|===
| Controller esistente | Controller sostitutivo | Supportato a partire da ONTAP... 


| AFF A400 | AFF A50 | 9.16.1 


| AFF A300 | AFF A50 | 9.16.1 


| AFF A220, AFF A150 | AFF A20 | 9.16.1 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1P3 per FAS70, FAS90 9.16.1P2 per FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90, AFF A1K | 9.15.1 
|===
====


== Aggiornare i modelli di controller nello stesso chassis

Se lo scenario di aggiornamento è elencato nella seguente matrice dei sistemi supportati, andare alink:../upgrade-arl-auto-in-chassis/index.html["Utilizzare i comandi "System controller replace" per aggiornare i modelli di controller nello stesso chassis"] per avviare la procedura di aggiornamento.

.Mostra i sistemi supportati
[%collapsible]
====
[cols="20,20,40"]
|===
| Vecchio sistema | Sistema sostitutivo | Versioni di ONTAP supportate 


| AFF C250 | AFF C30, AFF C60 | 9.16.1 e versioni successive 


| AFF A250 | AFF A50, AFF A30 | 9.16.1 e versioni successive 


| AFF C800 | AFF C80 | 9.16.1 e versioni successive 


| AFF A800 | AFF A70 o AFF A90 | 9.15.1 e versioni successive 


| AFF A220 configurato come ASA (All SAN Array) | ASA A150 | 9.13.1P1 e successivi 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e versioni successive 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 e successivi

*Nota*: AFF A200 non supporta le versioni ONTAP successive alla 9.11.1.



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 e versioni successive 


| FAS2620 | FAS2820  a| 
9.11.1P7 o versioni successive delle patch (FAS2620)

*Nota*: FAS2620 non supporta le versioni ONTAP successive alla 9.11.1.

9.13.1 e versioni successive (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 e versioni successive 


| AFF A700 configurato come ASA | ASA A900 | 9.13.1P1 e successivi 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 e versioni successive 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 e versioni successive 
|===
====


== Utilizzare i comandi "System controller REPLACE" con ONTAP 9.8 o versioni successive

Se lo scenario di aggiornamento è elencato nella seguente tabella dei sistemi supportati, andare a link:../upgrade-arl-auto-app/index.html["Utilizzare i comandi "System controller replace" per aggiornare l'hardware del controller con ONTAP 9.8 o versione successiva"] per avviare la procedura di aggiornamento.

.Mostra i sistemi supportati
[%collapsible]
====
|===
| Vecchio controller | Controller sostitutivo 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| FAS8060, FAS8080 | FAS9500 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| AFF8060, AFF8080 | AFF A900 


| FAS8200 | FAS8300, FAS8700, FAS9000, FAS9500 


| FAS8300, FAS8700, FAS9000 | FAS9500 


| AFF A300 | AFF A400, AFF A700, AFF A800, AFF A900 


| AFF A320 | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===
====


== Utilizzare i comandi "System controller REPLACE" con ONTAP 9 9,7

Se lo scenario di aggiornamento è elencato nella seguente tabella dei sistemi supportati, andare a link:../upgrade-arl-auto/index.html["Utilizzare i comandi "System controller replace" per aggiornare l'hardware del controller che esegue ONTAP 9.5 a 9.7"] per avviare la procedura di aggiornamento.

.Mostra i sistemi supportati
[%collapsible]
====
[cols="50,50"]
|===
| Vecchio controller | Controller sostitutivo 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| FAS8200 | FAS8700, FAS9000, FAS8300 


| AFF A300 | AFF A700, AFF A800, AFF A400 
|===
====


== Utilizzare i comandi ARL manuali

Se lo scenario di aggiornamento non è supportato utilizzando "comandi di sistema", è possibile eseguire un aggiornamento ARL utilizzando i comandi manuali.

.Mostra i sistemi supportati
[%collapsible]
====
[role="tabbed-block"]
=====
.ONTAP 9.8 o successivo
--
Gli aggiornamenti manuali ARL sono supportati per i seguenti sistemi che eseguono ONTAP 9.8 e versioni successive:

* Dal sistema FAS al sistema FAS
* Dal sistema AFF al sistema AFF
+
È possibile eseguire l'aggiornamento a un sistema sostitutivo della stessa serie:

+
** Dal sistema AFF A-Series al sistema AFF A-Series
** Da sistema AFF C-Series a sistema AFF C-Series


* Dal sistema ASA al sistema ASA
+

NOTE: Gli aggiornamenti ASA a un sistema sostitutivo ASA R2 non sono supportati. Per informazioni sulla migrazione dei dati da ASA a ASA R2, vedere link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Abilitare l'accesso ai dati dagli host SAN al sistema di storage ASA R2"^].

+
È possibile eseguire l'aggiornamento a un sistema sostitutivo della stessa serie:

+
** Dal sistema ASA A-Series al sistema ASA A-Series
** Da sistema ASA C-Series a sistema ASA C-Series




link:../upgrade-arl-manual-app/index.html["Aggiornare manualmente l'hardware del controller con ONTAP 9.8 o versione successiva"]

--
.ONTAP 9.7 o precedente
--
Gli aggiornamenti manuali ARL sono supportati per i seguenti sistemi che eseguono ONTAP 9.7 e versioni precedenti:

* Dal sistema FAS al sistema FAS
* Dal sistema AFF al sistema AFF


link:../upgrade-arl-manual/index.html["Aggiornare manualmente l'hardware del controller con ONTAP 9.7 o versione precedente"]

--
=====
====